// admin/src/routes/dashboard/fees/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import {
    Percent, ArrowUpDown, Save, RotateCcw, Loader2,
    AlertCircle, CheckCircle2, TrendingUp, TrendingDown,
    Coins, ShieldCheck, User, BadgeCheck, CircleDot
  } from 'lucide-svelte';
  import { authGet, authPut } from '$lib/api/client';
  import type { FeeSchedule } from '$lib/api/types';
  import PageHeader from '$lib/components/PageHeader.svelte';
  import ErrorAlert from '$lib/components/ErrorAlert.svelte';
  import { toast } from '$lib/stores/toast';
  import { formatPercent } from '$lib/utils/helpers';

  // ─── Label Maps ─────────────────────────────────────────────
  const userTypeLabels: Record<string, string> = {
    USER: 'مستخدم عادي',
    VERIFIED_USER: 'مستخدم موثّق'
  };

  const userTypeConfig: Record<string, { icon: any; color: string; bg: string }> = {
    USER: { icon: User, color: '#3b82f6', bg: 'rgba(59,130,246,0.12)' },
    VERIFIED_USER: { icon: BadgeCheck, color: '#22d3a4', bg: 'rgba(34,211,164,0.12)' }
  };

  const orderTypeLabels: Record<string, string> = {
    MARKET: 'سوقي',
    LIMIT: 'محدد',
    STOP_LIMIT: 'وقف محدد',
    TAKE_PROFIT: 'جني الأرباح'
  };

  // ─── State ──────────────────────────────────────────────────
  let fees = $state<FeeSchedule[]>([]);
  let loading = $state(true);
  let error = $state('');
  let saving = $state<number | null>(null);
  let refreshing = $state(false);

  // Track edited fields: key = `${feeId}-${field}`, value = true
  let dirtyFields = $state<Record<string, boolean>>({});
  // Track original values for reset
  let originalFees = $state<FeeSchedule[]>([]);
  // Track current edit values: key = feeId, value = partial fields
  let editValues = $state<Record<number, { maker_fee?: number; taker_fee?: number; min_fee?: number }>>({});

  // ─── Computed ───────────────────────────────────────────────
  let groupedFees = $derived(() => {
    const groups: Record<string, FeeSchedule[]> = {};
    for (const fee of fees) {
      if (!groups[fee.user_type]) groups[fee.user_type] = [];
      groups[fee.user_type].push(fee);
    }
    return groups;
  });

  let summaryStats = $derived(() => {
    const result: Record<string, { avgMaker: number; avgTaker: number }> = {};
    for (const [type, group] of Object.entries(groupedFees())) {
      const avgMaker = group.reduce((s, f) => s + f.maker_fee, 0) / (group.length || 1);
      const avgTaker = group.reduce((s, f) => s + f.taker_fee, 0) / (group.length || 1);
      result[type] = { avgMaker, avgTaker };
    }
    return result;
  });

  // ─── Helpers ────────────────────────────────────────────────
  function getFieldValue(fee: FeeSchedule, field: 'maker_fee' | 'taker_fee' | 'min_fee'): number {
    return editValues[fee.id]?.[field] ?? fee[field];
  }

  function setFieldValue(fee: FeeSchedule, field: 'maker_fee' | 'taker_fee' | 'min_fee', value: number) {
    if (!editValues[fee.id]) editValues[fee.id] = {};
    editValues[fee.id][field] = value;
    const key = `${fee.id}-${field}`;
    const original = originalFees.find(f => f.id === fee.id);
    if (original && original[field] !== value) {
      dirtyFields[key] = true;
    } else {
      delete dirtyFields[key];
    }
    // Trigger reactivity
    editValues = { ...editValues };
    dirtyFields = { ...dirtyFields };
  }

  function isFieldDirty(feeId: number, field: string): boolean {
    return !!dirtyFields[`${feeId}-${field}`];
  }

  function isFeeDirty(feeId: number): boolean {
    return Object.keys(dirtyFields).some(k => k.startsWith(`${feeId}-`));
  }

  // ─── API ────────────────────────────────────────────────────
  async function fetchFees() {
    try {
      error = '';
      const res = await authGet('/api/v1/admin/fees');
      if (!res.ok) throw new Error('فشل تحميل جداول الرسوم');
      const json = await res.json();
      if (json.success) {
        fees = json.data;
        originalFees = json.data.map((f: FeeSchedule) => ({ ...f }));
        editValues = {};
        dirtyFields = {};
      }
    } catch (e: any) {
      error = e.message;
    } finally {
      loading = false;
      refreshing = false;
    }
  }

  async function handleSave(feeId: number) {
    const edits = editValues[feeId];
    if (!edits) return;

    saving = feeId;
    try {
      const res = await authPut(`/api/v1/admin/fees/${feeId}`, edits);
      if (!res.ok) throw new Error('فشل حفظ التعديلات');
      const json = await res.json();
      if (json.success) {
        fees = fees.map(f => f.id === feeId ? json.data : f);
        originalFees = originalFees.map(f => f.id === feeId ? { ...json.data } : f);
        // Clear dirty state for this fee
        for (const key of Object.keys(dirtyFields)) {
          if (key.startsWith(`${feeId}-`)) delete dirtyFields[key];
        }
        delete editValues[feeId];
        dirtyFields = { ...dirtyFields };
        editValues = { ...editValues };
        toast.success('تم حفظ الرسوم بنجاح');
      }
    } catch (e: any) {
      toast.error(e.message);
    } finally {
      saving = null;
    }
  }

  function handleReset(feeId: number) {
    const original = originalFees.find(f => f.id === feeId);
    if (!original) return;

    editValues[feeId] = {
      maker_fee: original.maker_fee,
      taker_fee: original.taker_fee,
      min_fee: original.min_fee
    };

    for (const key of Object.keys(dirtyFields)) {
      if (key.startsWith(`${feeId}-`)) delete dirtyFields[key];
    }

    dirtyFields = { ...dirtyFields };
    editValues = { ...editValues };
    toast.info('تم إعادة القيم الأصلية');
  }

  async function handleRefresh() {
    refreshing = true;
    await fetchFees();
    toast.success('تم تحديث البيانات');
  }

  // ─── Lifecycle ──────────────────────────────────────────────
  onMount(() => {
    fetchFees();
  });
</script>

<div class="space-y-6">
  <!-- Header -->
  <PageHeader title="إدارة الرسوم" subtitle="تعديل جداول الرسوم حسب نوع المستخدم ونوع الأمر">
    <button class="btn-ghost text-sm flex items-center gap-2" onclick={handleRefresh} disabled={refreshing}>
      {#if refreshing}
        <Loader2 size={16} class="animate-spin" />
      {:else}
        <RotateCcw size={16} />
      {/if}
      تحديث
    </button>
  </PageHeader>

  <!-- Error -->
  {#if error}
    <ErrorAlert message={error} onclose={() => (error = '')} />
  {/if}

  <!-- Summary Cards -->
  {#if !loading && fees.length > 0}
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5">
      {#each Object.entries(summaryStats()) as [type, stats] (type)}
        {@const cfg = userTypeConfig[type]}
        {@const Icon = cfg?.icon || User}
        <div class="stat-card group">
          <div class="flex items-start justify-between">
            <div class="flex-1 min-w-0">
              <p class="text-[11px] font-semibold tracking-wider uppercase" style="color: var(--text-quaternary);">{userTypeLabels[type] || type}</p>
              <div class="mt-2 space-y-1">
                <div class="flex items-center gap-2">
                  <TrendingUp size={13} style="color: #22d3a4;" />
                  <span class="text-xs" style="color: var(--text-tertiary);">صانع:</span>
                  <span class="text-sm font-bold tabular-nums" style="color: #22d3a4;">{formatPercent(stats.avgMaker)}</span>
                </div>
                <div class="flex items-center gap-2">
                  <TrendingDown size={13} style="color: #f43f7a;" />
                  <span class="text-xs" style="color: var(--text-tertiary);">آخذ:</span>
                  <span class="text-sm font-bold tabular-nums" style="color: #f43f7a;">{formatPercent(stats.avgTaker)}</span>
                </div>
              </div>
            </div>
            <div class="flex items-center justify-center w-11 h-11 rounded-xl shrink-0" style="background: {cfg?.bg || 'rgba(59,130,246,0.12)'}; box-shadow: 0 0 20px {cfg?.bg || 'rgba(59,130,246,0.12)'};">
              <Icon size={20} style="color: {cfg?.color || '#3b82f6'};" />
            </div>
          </div>
        </div>
      {/each}
    </div>
  {/if}

  <!-- Fee Tables -->
  {#if loading}
    <div class="space-y-8">
      {#each Array(2) as _}
        <div class="panel p-6 space-y-4">
          <div class="animate-shimmer h-6 w-40 rounded" style="background: rgba(255,255,255,0.05);"></div>
          {#each Array(4) as _}
            <div class="flex items-center gap-4">
              <div class="animate-shimmer h-4 w-24 rounded" style="background: rgba(255,255,255,0.04);"></div>
              <div class="animate-shimmer h-10 flex-1 rounded-lg" style="background: rgba(255,255,255,0.03);"></div>
              <div class="animate-shimmer h-10 flex-1 rounded-lg" style="background: rgba(255,255,255,0.03);"></div>
              <div class="animate-shimmer h-10 flex-1 rounded-lg" style="background: rgba(255,255,255,0.03);"></div>
            </div>
          {/each}
        </div>
      {/each}
    </div>
  {:else if fees.length > 0}
    <div class="space-y-8">
      {#each Object.entries(groupedFees()) as [userType, group] (userType)}
        {@const cfg = userTypeConfig[userType]}
        {@const Icon = cfg?.icon || User}

        <div class="panel overflow-hidden">
          <!-- Group Header -->
          <div class="flex items-center gap-3 p-5 border-b" style="border-color: rgba(255,255,255,0.06);">
            <div class="flex items-center justify-center w-10 h-10 rounded-xl" style="background: {cfg?.bg};">
              <Icon size={20} style="color: {cfg?.color};" />
            </div>
            <div>
              <h2 class="font-bold text-lg" style="color: var(--text-primary);">{userTypeLabels[userType] || userType}</h2>
              <p class="text-xs" style="color: var(--text-quaternary);">{group.length} نوع أوامر</p>
            </div>
            <div class="mr-auto flex items-center gap-1.5">
              <Coins size={14} style="color: var(--text-quaternary);" />
              <span class="text-xs" style="color: var(--text-quaternary);">جدول الرسوم</span>
            </div>
          </div>

          <!-- Table -->
          <div class="overflow-x-auto">
            <table class="data-table w-full">
              <thead>
                <tr>
                  <th style="min-width: 140px;">نوع الأمر</th>
                  <th style="min-width: 140px;">رسوم الصانع</th>
                  <th style="min-width: 140px;">رسوم الآخذ</th>
                  <th style="min-width: 140px;">الحد الأدنى</th>
                  <th style="min-width: 160px;">إجراءات</th>
                </tr>
              </thead>
              <tbody>
                {#each group as fee (fee.id)}
                  <tr>
                    <!-- Order Type -->
                    <td>
                      <div class="flex items-center gap-2">
                        <ArrowUpDown size={14} style="color: var(--text-quaternary);" />
                        <span class="font-medium text-sm">{orderTypeLabels[fee.order_type] || fee.order_type}</span>
                      </div>
                    </td>

                    <!-- Maker Fee -->
                    <td>
                      <div class="relative">
                        <input
                          type="number"
                          step="0.01"
                          class="input-field w-full tabular-nums text-left"
                          value={getFieldValue(fee, 'maker_fee')}
                          oninput={(e) => setFieldValue(fee, 'maker_fee', parseFloat((e.target as HTMLInputElement).value) || 0)}
                          style={isFieldDirty(fee.id, 'maker_fee') ? 'border-color: rgba(245,181,68,0.5); box-shadow: 0 0 0 1px rgba(245,181,68,0.2);' : ''}
                        />
                        {#if isFieldDirty(fee.id, 'maker_fee')}
                          <CircleDot size={12} class="absolute left-2 top-1/2 -translate-y-1/2" style="color: #f5b544;" />
                        {/if}
                      </div>
                    </td>

                    <!-- Taker Fee -->
                    <td>
                      <div class="relative">
                        <input
                          type="number"
                          step="0.01"
                          class="input-field w-full tabular-nums text-left"
                          value={getFieldValue(fee, 'taker_fee')}
                          oninput={(e) => setFieldValue(fee, 'taker_fee', parseFloat((e.target as HTMLInputElement).value) || 0)}
                          style={isFieldDirty(fee.id, 'taker_fee') ? 'border-color: rgba(245,181,68,0.5); box-shadow: 0 0 0 1px rgba(245,181,68,0.2);' : ''}
                        />
                        {#if isFieldDirty(fee.id, 'taker_fee')}
                          <CircleDot size={12} class="absolute left-2 top-1/2 -translate-y-1/2" style="color: #f5b544;" />
                        {/if}
                      </div>
                    </td>

                    <!-- Min Fee -->
                    <td>
                      <div class="relative">
                        <input
                          type="number"
                          step="0.01"
                          class="input-field w-full tabular-nums text-left"
                          value={getFieldValue(fee, 'min_fee')}
                          oninput={(e) => setFieldValue(fee, 'min_fee', parseFloat((e.target as HTMLInputElement).value) || 0)}
                          style={isFieldDirty(fee.id, 'min_fee') ? 'border-color: rgba(245,181,68,0.5); box-shadow: 0 0 0 1px rgba(245,181,68,0.2);' : ''}
                        />
                        {#if isFieldDirty(fee.id, 'min_fee')}
                          <CircleDot size={12} class="absolute left-2 top-1/2 -translate-y-1/2" style="color: #f5b544;" />
                        {/if}
                      </div>
                    </td>

                    <!-- Actions -->
                    <td>
                      <div class="flex items-center gap-2">
                        <button
                          class="btn-primary text-xs flex items-center gap-1.5"
                          onclick={() => handleSave(fee.id)}
                          disabled={saving === fee.id || !isFeeDirty(fee.id)}
                        >
                          {#if saving === fee.id}
                            <Loader2 size={13} class="animate-spin" />
                          {:else}
                            <Save size={13} />
                          {/if}
                          حفظ
                        </button>
                        <button
                          class="btn-ghost text-xs flex items-center gap-1.5"
                          onclick={() => handleReset(fee.id)}
                          disabled={!isFeeDirty(fee.id)}
                        >
                          <RotateCcw size={13} />
                          إعادة
                        </button>
                      </div>
                    </td>
                  </tr>
                {/each}
              </tbody>
            </table>
          </div>
        </div>
      {/each}
    </div>
  {:else}
    <div class="panel p-8 flex flex-col items-center text-center">
      <Percent size={32} style="color: var(--text-quaternary);" />
      <p class="text-sm mt-2" style="color: var(--text-quaternary);">لا توجد جداول رسوم</p>
    </div>
  {/if}
</div>

// frontend/src/app/dashboard/admin/fees/page.tsx
"use client";

import { useEffect, useState } from "react";
import toast from "react-hot-toast";
import {
  Coins,
  Loader2,
  Save,
  Percent,
  User,
  TrendingUp,
  RefreshCw,
  AlertTriangle,
} from "lucide-react";
import { authGet, authPut } from "@/lib/api";

interface FeeSchedule {
  id?: number;
  user_type: string;
  order_type: string;
  maker_fee: string;
  taker_fee: string;
}

const USER_TYPES = [
  { value: "REGULAR", label: "مستخدم عادي" },
  { value: "VIP", label: "VIP مستخدم" },
  { value: "MARKET_MAKER", label: "صانع سوق" },
];

const ORDER_TYPES = [
  { value: "MARKET", label: "أمر سوقي" },
  { value: "LIMIT", label: "أمر محدد" },
  { value: "STOP_LIMIT", label: "أمر وقف خسارة" },
  { value: "TAKE_PROFIT", label: "أمر جني أرباح" },
];

export default function AdminFeesPage() {
  const [fees, setFees] = useState<FeeSchedule[]>([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [editingFees, setEditingFees] = useState<FeeSchedule[]>([]);
  const [hasChanges, setHasChanges] = useState(false);

  useEffect(() => {
    fetchFees();
  }, []);

  const fetchFees = async () => {
    setLoading(true);
    try {
      const res = await authGet("/api/v1/admin/fees");
      if (res.ok) {
        const data = await res.json();
        const feeData = Array.isArray(data.data) ? data.data : [];
        setFees(feeData);
        setEditingFees(feeData.map((f: FeeSchedule) => ({ ...f })));
        setHasChanges(false);
      } else {
        toast.error("فشل تحميل جداول الرسوم");
      }
    } catch {
      toast.error("حدث خطأ في الاتصال");
    } finally {
      setLoading(false);
    }
  };

  const handleFeeChange = (index: number, field: "maker_fee" | "taker_fee", value: string) => {
    const updated = [...editingFees];
    updated[index] = { ...updated[index], [field]: value };
    setEditingFees(updated);
    setHasChanges(true);
  };

  const handleSave = async () => {
    setSaving(true);
    try {
      const res = await authPut("/api/v1/admin/fees", { fees: editingFees });
      const data = await res.json();
      if (!res.ok) {
        toast.error(data.error || "فشل حفظ الرسوم");
        return;
      }
      toast.success(data.message || "تم حفظ الرسوم بنجاح");
      setFees(editingFees.map(f => ({ ...f })));
      setHasChanges(false);
    } catch {
      toast.error("حدث خطأ في الاتصال");
    } finally {
      setSaving(false);
    }
  };

  const getUserTypeLabel = (type: string) => {
    const option = USER_TYPES.find(o => o.value === type);
    return option?.label || type;
  };

  const getOrderTypeLabel = (type: string) => {
    const option = ORDER_TYPES.find(o => o.value === type);
    return option?.label || type;
  };

  // Group fees by user type for better display
  const groupedFees = editingFees.reduce((acc, fee) => {
    if (!acc[fee.user_type]) acc[fee.user_type] = [];
    acc[fee.user_type].push(fee);
    return acc;
  }, {} as Record<string, FeeSchedule[]>);

  return (
    <div className="space-y-6">
      {/* ── Header ── */}
      <div className="flex items-center justify-between animate-slide-in-up">
        <div className="flex items-center gap-3">
          <div className="h-11 w-11 rounded-xl bg-gradient-to-br from-emerald-500 to-teal-600 flex items-center justify-center shadow-lg shadow-emerald-500/20">
            <Coins className="h-6 w-6 text-white" />
          </div>
          <div>
            <h1 className="text-2xl sm:text-3xl font-bold">إدارة الرسوم</h1>
            <p className="text-muted-foreground text-sm mt-0.5">تعديل جداول رسوم التداول حسب نوع المستخدم والأمر</p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={fetchFees}
            disabled={loading}
            className="btn-ghost gap-2 text-sm"
          >
            <RefreshCw className={`h-4 w-4 ${loading ? "animate-spin" : ""}`} />
            تحديث
          </button>
          {hasChanges && (
            <button
              onClick={handleSave}
              disabled={saving}
              className="btn-primary gap-2 text-sm"
            >
              {saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}
              حفظ التغييرات
            </button>
          )}
        </div>
      </div>

      {/* ── Info Banner ── */}
      <div className="p-4 rounded-2xl bg-yellow-500/5 border border-yellow-500/15 animate-slide-in-up" style={{ animationDelay: "50ms" }}>
        <div className="flex items-start gap-3">
          <AlertTriangle className="h-5 w-5 text-yellow-400 shrink-0 mt-0.5" />
          <div className="text-sm text-muted-foreground leading-relaxed">
            <p><span className="font-semibold text-foreground">تنبيه: </span>تعديل الرسوم يؤثر على جميع المستخدمين. تأكد من القيم قبل الحفظ. الرسوم تُحسب كنسبة مئوية (مثلاً 0.1 = 0.1%).</p>
          </div>
        </div>
      </div>

      {/* ── Fee Schedules ── */}
      {loading ? (
        <div className="flex flex-col items-center justify-center py-20 gap-3">
          <div className="h-16 w-16 rounded-2xl bg-emerald-500/10 flex items-center justify-center">
            <Loader2 className="h-8 w-8 animate-spin text-emerald-500" />
          </div>
          <p className="text-sm text-muted-foreground">جاري تحميل جداول الرسوم...</p>
        </div>
      ) : editingFees.length === 0 ? (
        <div className="glass-panel rounded-2xl p-10 text-center animate-fade-in">
          <Coins className="h-12 w-12 text-muted-foreground/30 mx-auto mb-4" />
          <h3 className="text-lg font-bold mb-2">لا توجد جداول رسوم</h3>
          <p className="text-sm text-muted-foreground">لم يتم العثور على جداول رسوم. قم بإنشائها من لوحة التحكم.</p>
        </div>
      ) : (
        <div className="space-y-6">
          {Object.entries(groupedFees).map(([userType, userFees], gi) => (
            <div
              key={userType}
              className="glass-panel rounded-2xl p-6 animate-slide-in-up"
              style={{ animationDelay: `${(gi + 1) * 100}ms` }}
            >
              {/* User Type Header */}
              <div className="flex items-center gap-3 mb-5">
                <div className="h-10 w-10 rounded-xl bg-gradient-to-br from-emerald-500/20 to-teal-500/10 flex items-center justify-center border border-emerald-500/10">
                  <User className="h-5 w-5 text-emerald-500" />
                </div>
                <div>
                  <h3 className="font-bold text-base">{getUserTypeLabel(userType)}</h3>
                  <p className="text-xs text-muted-foreground">
                    {userFees.length} نوع أوامر
                  </p>
                </div>
              </div>

              {/* Fee Table */}
              <div className="overflow-x-auto">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="border-b border-border/40 bg-muted/10">
                      <th className="text-right p-3 text-muted-foreground font-medium">
                        <div className="flex items-center gap-1.5"><TrendingUp className="h-3.5 w-3.5" /> نوع الأمر</div>
                      </th>
                      <th className="text-center p-3 text-muted-foreground font-medium">
                        <div className="flex items-center justify-center gap-1.5"><Percent className="h-3.5 w-3.5" /> رسوم صانع السوق (Maker)</div>
                      </th>
                      <th className="text-center p-3 text-muted-foreground font-medium">
                        <div className="flex items-center justify-center gap-1.5"><Percent className="h-3.5 w-3.5" /> رسوم آخذ السوق (Taker)</div>
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    {userFees.map((fee, fi) => {
                      const editingIndex = editingFees.findIndex(
                        ef => ef.user_type === fee.user_type && ef.order_type === fee.order_type
                      );
                      return (
                        <tr key={fi} className="border-b border-border/10 hover:bg-muted/5 transition-colors">
                          <td className="p-3 font-medium text-sm">
                            {getOrderTypeLabel(fee.order_type)}
                          </td>
                          <td className="p-3">
                            <div className="flex items-center justify-center gap-1">
                              <input
                                type="number"
                                step="0.001"
                                min="0"
                                className="input-field w-28 text-center tabular-nums"
                                value={editingFees[editingIndex]?.maker_fee ?? fee.maker_fee}
                                onChange={(e) => handleFeeChange(editingIndex, "maker_fee", e.target.value)}
                              />
                              <span className="text-xs text-muted-foreground">%</span>
                            </div>
                          </td>
                          <td className="p-3">
                            <div className="flex items-center justify-center gap-1">
                              <input
                                type="number"
                                step="0.001"
                                min="0"
                                className="input-field w-28 text-center tabular-nums"
                                value={editingFees[editingIndex]?.taker_fee ?? fee.taker_fee}
                                onChange={(e) => handleFeeChange(editingIndex, "taker_fee", e.target.value)}
                              />
                              <span className="text-xs text-muted-foreground">%</span>
                            </div>
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* ── Save Button (bottom) ── */}
      {hasChanges && (
        <div className="sticky bottom-4 z-20 animate-slide-in-up">
          <div className="glass-panel-strong rounded-2xl p-4 flex items-center justify-between">
            <p className="text-sm text-muted-foreground">
              <span className="text-yellow-400 font-semibold">⚠</span> لديك تغييرات غير محفوظة
            </p>
            <div className="flex items-center gap-2">
              <button onClick={() => { setEditingFees(fees.map(f => ({ ...f }))); setHasChanges(false); }} className="btn-ghost text-sm">
                تراجع
              </button>
              <button onClick={handleSave} disabled={saving} className="btn-primary gap-2 text-sm">
                {saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}
                حفظ التغييرات
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
