// admin/src/routes/dashboard/kyc/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import {
    ShieldCheck,
    Search,
    Filter,
    Eye,
    CheckCircle2,
    XCircle,
    Clock,
    FileText,
    ChevronRight,
    ChevronLeft,
    AlertCircle,
    Loader2,
    X,
    Send,
    BellRing,
    Image,
    BadgeCheck
  } from 'lucide-svelte';
  import { authGet, authPut, API, getToken } from '$lib/api/client';
  import type { KYCRequest } from '$lib/api/types';
  import { createAdminStream } from '$lib/api/types';

  // ─── Types ───
  interface KYCPageResponse {
    success: boolean;
    data: KYCRequest[];
    pagination: {
      page: number;
      limit: number;
      total: number;
      totalPages: number;
    };
  }

  interface KYCStats {
    pending: number;
    approved: number;
    rejected: number;
  }

  // ─── State ───
  let kycRequests = $state<KYCRequest[]>([]);
  let loading = $state(true);
  let error = $state<string | null>(null);
  let page = $state(1);
  let totalPages = $state(1);
  let totalItems = $state(0);
  const limit = 20;

  let searchQuery = $state('');
  let statusFilter = $state<string>('');
  let stats = $state<KYCStats>({ pending: 0, approved: 0, rejected: 0 });

  // ─── Document preview modal ───
  let previewOpen = $state(false);
  let previewUrl = $state('');
  let previewType = $state<'image' | 'pdf'>('image');
  let previewName = $state('');

  // ─── Reject dialog ───
  let rejectDialogOpen = $state(false);
  let rejectTargetId = $state<number | null>(null);
  let rejectReason = $state('');
  let rejectLoading = $state(false);

  // ─── SSE live indicator ───
  let sseConnected = $state(false);
  let newKycCount = $state(0);
  let newKycFlash = $state(false);

  // ─── Action loading per card ───
  let actionLoadingId = $state<number | null>(null);

  // ─── Document type labels (Arabic) ───
  const docTypeLabels: Record<string, string> = {
    PASSPORT: 'جواز سفر',
    NATIONAL_ID: 'بطاقة وطنية',
    DRIVERS_LICENSE: 'رخصة قيادة',
    UTILITY_BILL: 'فاتورة مرافق',
    BANK_STATEMENT: 'كشف حساب بنكي',
    SELFIE: 'صورة شخصية'
  };

  // ─── Status config ───
  const statusConfig: Record<string, { label: string; pillClass: string; icon: typeof Clock; color: string }> = {
    PENDING: { label: 'قيد المراجعة', pillClass: 'pill-gold', icon: Clock, color: '#f5b544' },
    APPROVED: { label: 'مقبول', pillClass: 'pill-mint', icon: CheckCircle2, color: '#22d3a4' },
    REJECTED: { label: 'مرفوض', pillClass: 'pill-rose', icon: XCircle, color: '#f43f7a' }
  };

  // ─── Helpers ───
  function formatDate(iso: string): string {
    const d = new Date(iso);
    return d.toLocaleDateString('ar-EG', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  }

  function getDocTypeLabel(type: string): string {
    return docTypeLabels[type] || type;
  }

  function detectDocType(url: string): 'image' | 'pdf' {
    const lower = url.toLowerCase();
    if (lower.endsWith('.pdf') || lower.includes('.pdf?')) return 'pdf';
    return 'image';
  }

  function maskDocNumber(num: string): string {
    if (!num || num.length <= 4) return num;
    return num.slice(0, -4).replace(/./g, '•') + num.slice(-4);
  }

  function getStatusConfig(status: string) {
    return statusConfig[status] || statusConfig.PENDING;
  }

  // ─── Fetch KYC requests ───
  async function fetchKYC() {
    loading = true;
    error = null;
    try {
      const params = new URLSearchParams({ page: String(page), limit: String(limit) });
      if (statusFilter) params.set('status', statusFilter);
      if (searchQuery.trim()) params.set('search', searchQuery.trim());

      const res = await authGet(`/api/v1/admin/kyc?${params.toString()}`);
      if (!res.ok) throw new Error('فشل تحميل طباتات KYC');
      const json: KYCPageResponse = await res.json();

      if (json.success) {
        kycRequests = json.data;
        totalPages = json.pagination.totalPages;
        totalItems = json.pagination.total;
      }
    } catch (e: any) {
      error = e.message;
    } finally {
      loading = false;
    }
  }

  // ─── Fetch stats ───
  async function fetchStats() {
    try {
      const res = await authGet('/api/v1/admin/kyc/stats');
      if (!res.ok) return;
      const json = await res.json();
      if (json.success) {
        stats = json.data;
      }
    } catch {
      // non-fatal
    }
  }

  // ─── Approve KYC ───
  async function approveKYC(id: number) {
    actionLoadingId = id;
    try {
      const res = await authPut(`/api/v1/admin/kyc/${id}/review`, { status: 'APPROVED' });
      if (!res.ok) throw new Error('فشل قبول الطلب');
      // Update local state
      kycRequests = kycRequests.map((r) =>
        r.id === id ? { ...r, status: 'APPROVED' } : r
      );
      stats = { ...stats, pending: Math.max(0, stats.pending - 1), approved: stats.approved + 1 };
    } catch (e: any) {
      error = e.message;
    } finally {
      actionLoadingId = null;
    }
  }

  // ─── Open reject dialog ───
  function openRejectDialog(id: number) {
    rejectTargetId = id;
    rejectReason = '';
    rejectDialogOpen = true;
  }

  // ─── Submit rejection ───
  async function submitRejection() {
    if (!rejectTargetId || !rejectReason.trim()) return;
    rejectLoading = true;
    try {
      const res = await authPut(`/api/v1/admin/kyc/${rejectTargetId}/review`, {
        status: 'REJECTED',
        rejection_reason: rejectReason.trim()
      });
      if (!res.ok) throw new Error('فشل رفض الطلب');
      kycRequests = kycRequests.map((r) =>
        r.id === rejectTargetId ? { ...r, status: 'REJECTED', rejection_reason: rejectReason.trim() } : r
      );
      stats = { ...stats, pending: Math.max(0, stats.pending - 1), rejected: stats.rejected + 1 };
      rejectDialogOpen = false;
    } catch (e: any) {
      error = e.message;
    } finally {
      rejectLoading = false;
    }
  }

  // ─── Document preview ───
  function openPreview(kyc: KYCRequest) {
    previewUrl = kyc.document_url;
    previewType = detectDocType(kyc.document_url);
    previewName = `${kyc.full_name} — ${getDocTypeLabel(kyc.document_type)}`;
    previewOpen = true;
  }

  function closePreview() {
    previewOpen = false;
    previewUrl = '';
  }

  // ─── Search debounce ───
  let searchTimeout: ReturnType<typeof setTimeout>;
  $effect(() => {
    searchQuery; // track
    clearTimeout(searchTimeout);
    searchTimeout = setTimeout(() => {
      page = 1;
      fetchKYC();
    }, 400);
  });

  // ─── Status filter change ───
  $effect(() => {
    statusFilter; // track
    page = 1;
    fetchKYC();
  });

  // ─── Page change ───
  $effect(() => {
    page; // track
    fetchKYC();
  });

  // ─── SSE ───
  let eventSource: EventSource | null = null;

  function connectSSE() {
    const es = createAdminStream(['kyc']);
    if (!es) return;

    es.onopen = () => {
      sseConnected = true;
    };

    es.addEventListener('kyc', () => {
      newKycCount++;
      newKycFlash = true;
      setTimeout(() => (newKycFlash = false), 2000);
      // Refresh stats
      fetchStats();
    });

    es.onerror = () => {
      sseConnected = false;
      setTimeout(() => {
        es.close();
        connectSSE();
      }, 5000);
    };

    return es;
  }

  function handleNewKycClick() {
    newKycCount = 0;
    page = 1;
    fetchKYC();
    fetchStats();
  }

  // ─── Lifecycle ───
  onMount(() => {
    (async () => {
      await Promise.all([fetchKYC(), fetchStats()]);
      loading = false;
    })();

    eventSource = connectSSE() ?? null;

    return () => {
      eventSource?.close();
    };
  });

  // ─── Pagination helpers ───
  let pages = $derived.by(() => {
    const arr: number[] = [];
    const start = Math.max(1, page - 2);
    const end = Math.min(totalPages, page + 2);
    for (let i = start; i <= end; i++) arr.push(i);
    return arr;
  });

  // ─── Stat cards config ───
  const statCards = $derived([
    {
      label: 'قيد المراجعة',
      count: stats.pending,
      icon: Clock,
      pillClass: 'pill-gold',
      iconBg: 'rgba(245,181,68,0.12)',
      iconColor: '#f5b544'
    },
    {
      label: 'مقبول',
      count: stats.approved,
      icon: CheckCircle2,
      pillClass: 'pill-mint',
      iconBg: 'rgba(34,211,164,0.12)',
      iconColor: '#22d3a4'
    },
    {
      label: 'مرفوض',
      count: stats.rejected,
      icon: XCircle,
      pillClass: 'pill-rose',
      iconBg: 'rgba(244,63,122,0.12)',
      iconColor: '#f43f7a'
    }
  ]);
</script>

<!-- ─── Document Preview Modal ─── -->
{#if previewOpen}
  <div
    class="fixed inset-0 z-[100] flex items-center justify-center p-4"
    onkeydown={(e) => e.key === 'Escape' && closePreview()}
  >
    <!-- Backdrop -->
    <div
      class="absolute inset-0 bg-black/80 backdrop-blur-md"
      onclick={closePreview}
      role="presentation"
    ></div>

    <!-- Modal content -->
    <div class="relative z-10 w-full max-w-4xl max-h-[90vh] panel overflow-hidden flex flex-col">
      <!-- Header -->
      <div class="flex items-center justify-between p-4 border-b" style="border-color: var(--border-subtle);">
        <div class="flex items-center gap-3">
          <BadgeCheck size={20} style="color: var(--accent-gold);" />
          <div>
            <h3 class="font-bold text-sm">{previewName}</h3>
            <p class="text-xs" style="color: var(--text-tertiary);">معاينة المستند</p>
          </div>
        </div>
        <button
          class="btn-ghost rounded-lg p-2"
          onclick={closePreview}
          aria-label="إغلاق"
        >
          <X size={20} />
        </button>
      </div>

      <!-- Body -->
      <div class="flex-1 overflow-auto p-4 flex items-center justify-center min-h-[300px]">
        {#if previewType === 'pdf'}
          <iframe
            src={previewUrl}
            class="w-full h-[70vh] rounded-xl border"
            style="border-color: var(--border-subtle); background: white;"
            title="معاينة PDF"
          ></iframe>
        {:else}
          <img
            src={previewUrl}
            alt={previewName}
            class="max-w-full max-h-[70vh] rounded-xl object-contain"
            style="border: 1px solid var(--border-subtle);"
          />
        {/if}
      </div>
    </div>
  </div>
{/if}

<!-- ─── Reject Dialog ─── -->
{#if rejectDialogOpen}
  <div
    class="fixed inset-0 z-[100] flex items-center justify-center p-4"
    onkeydown={(e) => e.key === 'Escape' && (rejectDialogOpen = false)}
  >
    <!-- Backdrop -->
    <div
      class="absolute inset-0 bg-black/80 backdrop-blur-md"
      onclick={() => (rejectDialogOpen = false)}
      role="presentation"
    ></div>

    <!-- Dialog -->
    <div class="relative z-10 w-full max-w-md panel p-6 space-y-5">
      <div class="flex items-center justify-between">
        <div class="flex items-center gap-3">
          <div class="flex items-center justify-center w-10 h-10 rounded-xl" style="background: rgba(244,63,122,0.12);">
            <XCircle size={20} style="color: #f43f7a;" />
          </div>
          <h3 class="font-bold">رفض طلب التحقق</h3>
        </div>
        <button
          class="btn-ghost rounded-lg p-1.5"
          onclick={() => (rejectDialogOpen = false)}
          aria-label="إغلاق"
        >
          <X size={18} />
        </button>
      </div>

      <div>
        <label class="block text-xs font-medium mb-2" style="color: var(--text-secondary);">
          سبب الرفض <span style="color: #f43f7a;">*</span>
        </label>
        <textarea
          class="input-field min-h-[120px] resize-y"
          bind:value={rejectReason}
          placeholder="أدخل سبب رفض الطلب..."
          dir="rtl"
        ></textarea>
      </div>

      <div class="flex items-center gap-3 justify-end">
        <button
          class="btn-secondary"
          onclick={() => (rejectDialogOpen = false)}
          disabled={rejectLoading}
        >
          إلغاء
        </button>
        <button
          class="btn-danger flex items-center gap-2"
          onclick={submitRejection}
          disabled={rejectLoading || !rejectReason.trim()}
        >
          {#if rejectLoading}
            <Loader2 size={16} class="animate-spin" />
          {:else}
            <Send size={16} />
          {/if}
          رفض الطلب
        </button>
      </div>
    </div>
  </div>
{/if}

<!-- ─── Main Content ─── -->
<div class="space-y-6">
  <!-- Header -->
  <div class="flex items-center justify-between flex-wrap gap-4">
    <div>
      <h1 class="text-2xl lg:text-3xl font-extrabold text-gold-gradient">التحقق KYC</h1>
      <p class="text-sm mt-1" style="color: var(--text-tertiary);">مراجعة طباتات التحقق من الهوية</p>
    </div>

    <div class="flex items-center gap-3">
      <!-- SSE Live indicator -->
      {#if sseConnected}
        <span class="pill-mint">
          <span class="relative flex h-2 w-2">
            <span class="animate-ping absolute inline-flex h-full w-full rounded-full opacity-75" style="background: #22d3a4;"></span>
            <span class="relative inline-flex rounded-full h-2 w-2" style="background: #22d3a4;"></span>
          </span>
          مباشر
        </span>
      {:else}
        <span class="pill-rose">
          <span class="inline-flex rounded-full h-2 w-2" style="background: #f43f7a;"></span>
          غير متصل
        </span>
      {/if}

      <!-- New KYC indicator -->
      {#if newKycCount > 0}
        <button
          class="pill-gold flex items-center gap-2 cursor-pointer animate-pulse-glow transition-all"
          onclick={handleNewKycClick}
        >
          <BellRing size={14} />
          <span>{newKycCount} طلب جديد</span>
          <ChevronLeft size={14} />
        </button>
      {/if}
    </div>
  </div>

  <!-- Error Banner -->
  {#if error}
    <div class="panel p-4 flex items-center gap-3" style="border-color: rgba(244,63,122,0.3);">
      <AlertCircle size={20} style="color: #f43f7a;" />
      <p class="text-sm" style="color: #f43f7a;">{error}</p>
      <button class="mr-auto btn-ghost text-xs" onclick={() => (error = null)}>إغلاق</button>
    </div>
  {/if}

  <!-- Stats Cards -->
  <div class="grid grid-cols-1 sm:grid-cols-3 gap-5">
    {#each statCards as card}
      <div class="stat-card group">
        <div class="flex items-center justify-between">
          <div class="space-y-1">
            <p class="text-xs font-medium" style="color: var(--text-tertiary);">{card.label}</p>
            <p class="text-3xl font-bold font-mono tabular-nums" style="color: {card.iconColor};">
              {card.count.toLocaleString('ar-EG')}
            </p>
          </div>
          <div
            class="flex items-center justify-center w-12 h-12 rounded-xl transition-transform duration-300 group-hover:scale-110"
            style="background: {card.iconBg};"
          >
            <card.icon size={22} style="color: {card.iconColor};" />
          </div>
        </div>
      </div>
    {/each}
  </div>

  <!-- Search & Filter Bar -->
  <div class="panel p-4">
    <div class="flex flex-col sm:flex-row items-stretch sm:items-center gap-3">
      <!-- Search -->
      <div class="relative flex-1">
        <Search
          size={18}
          class="absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none"
          style="color: var(--text-quaternary);"
        />
        <input
          type="text"
          class="input-field pr-10"
          placeholder="بحث باسم المستخدم أو البريد الإلكتروني..."
          bind:value={searchQuery}
          dir="rtl"
        />
      </div>

      <!-- Status Filter -->
      <div class="relative">
        <Filter
          size={16}
          class="absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none"
          style="color: var(--text-quaternary);"
        />
        <select
          class="input-field pr-9 pl-8 appearance-none cursor-pointer min-w-[160px]"
          bind:value={statusFilter}
          dir="rtl"
        >
          <option value="">كل الحالات</option>
          <option value="PENDING">قيد المراجعة</option>
          <option value="APPROVED">مقبول</option>
          <option value="REJECTED">مرفوض</option>
        </select>
        <ChevronLeft
          size={14}
          class="absolute left-3 top-1/2 -translate-y-1/2 pointer-events-none"
          style="color: var(--text-quaternary);"
        />
      </div>
    </div>
  </div>

  <!-- KYC Cards List -->
  <div class="space-y-4">
    {#if loading}
      <!-- Skeleton -->
      {#each Array(6) as _}
        <div class="panel p-5">
          <div class="flex items-start justify-between">
            <div class="flex items-center gap-4 flex-1">
              <div class="animate-shimmer h-12 w-12 rounded-xl" style="background: rgba(255,255,255,0.06);"></div>
              <div class="space-y-2 flex-1">
                <div class="animate-shimmer h-4 w-40 rounded" style="background: rgba(255,255,255,0.06);"></div>
                <div class="animate-shimmer h-3 w-56 rounded" style="background: rgba(255,255,255,0.04);"></div>
              </div>
            </div>
            <div class="animate-shimmer h-7 w-24 rounded-full" style="background: rgba(255,255,255,0.06);"></div>
          </div>
          <div class="mt-4 flex gap-4">
            <div class="animate-shimmer h-3 w-32 rounded" style="background: rgba(255,255,255,0.04);"></div>
            <div class="animate-shimmer h-3 w-28 rounded" style="background: rgba(255,255,255,0.04);"></div>
            <div class="animate-shimmer h-3 w-36 rounded" style="background: rgba(255,255,255,0.04);"></div>
          </div>
          <div class="mt-4 flex gap-2 justify-end">
            <div class="animate-shimmer h-9 w-24 rounded-xl" style="background: rgba(255,255,255,0.06);"></div>
            <div class="animate-shimmer h-9 w-24 rounded-xl" style="background: rgba(255,255,255,0.06);"></div>
            <div class="animate-shimmer h-9 w-24 rounded-xl" style="background: rgba(255,255,255,0.06);"></div>
          </div>
        </div>
      {/each}
    {:else if kycRequests.length === 0}
      <!-- Empty state -->
      <div class="panel p-16 text-center">
        <ShieldCheck size={48} class="mx-auto mb-4 opacity-20" style="color: var(--text-quaternary);" />
        <p class="text-lg font-bold" style="color: var(--text-secondary);">لا توجد طباتات تحقق</p>
        <p class="text-sm mt-1" style="color: var(--text-quaternary);">
          {statusFilter || searchQuery ? 'جرّب تغيير عوامل التصفية' : 'ستظهر طباتات التحقق هنا عند تقديمها'}
        </p>
      </div>
    {:else}
      {#each kycRequests as kyc (kyc.id)}
        {@const sc = getStatusConfig(kyc.status)}
        {@const isPending = kyc.status === 'PENDING'}
        {@const isActing = actionLoadingId === kyc.id}

        <div class="panel p-5 transition-all duration-300 hover:border-white/[0.12]">
          <!-- Top row: user info + status pill -->
          <div class="flex items-start justify-between gap-4">
            <div class="flex items-center gap-4 min-w-0">
              <!-- Avatar -->
              <div
                class="flex items-center justify-center w-12 h-12 rounded-xl shrink-0 font-bold text-sm"
                style="background: {sc.iconBg}; color: {sc.iconColor};"
              >
                {kyc.full_name?.charAt(0) || kyc.user?.username?.charAt(0) || '?'}
              </div>

              <div class="min-w-0">
                <h3 class="font-bold text-sm truncate">{kyc.full_name || kyc.user?.username || '—'}</h3>
                <p class="text-xs mt-0.5 truncate" style="color: var(--text-tertiary);">
                  {kyc.user?.email || '—'}
                </p>
              </div>
            </div>

            <span class={sc.pillClass}>
              <sc.icon size={12} />
              {sc.label}
            </span>
          </div>

          <!-- Details row -->
          <div class="mt-4 flex flex-wrap gap-x-6 gap-y-2 text-xs" style="color: var(--text-secondary);">
            <div class="flex items-center gap-1.5">
              <FileText size={13} style="color: var(--text-quaternary);" />
              <span>{getDocTypeLabel(kyc.document_type)}</span>
            </div>
            <div class="flex items-center gap-1.5 font-mono">
              <Image size={13} style="color: var(--text-quaternary);" />
              <span>{maskDocNumber(kyc.document_number)}</span>
            </div>
            <div class="flex items-center gap-1.5">
              <Clock size={13} style="color: var(--text-quaternary);" />
              <span>{formatDate(kyc.created_at)}</span>
            </div>
          </div>

          <!-- Rejection reason (if rejected) -->
          {#if kyc.status === 'REJECTED' && kyc.rejection_reason}
            <div
              class="mt-3 p-3 rounded-lg text-xs"
              style="background: rgba(244,63,122,0.06); border: 1px solid rgba(244,63,122,0.12); color: var(--text-secondary);"
            >
              <span class="font-semibold" style="color: #f43f7a;">سبب الرفض: </span>
              {kyc.rejection_reason}
            </div>
          {/if}

          <!-- Actions row -->
          <div class="mt-4 flex items-center justify-between flex-wrap gap-2">
            <button
              class="btn-ghost flex items-center gap-2 text-xs"
              onclick={() => openPreview(kyc)}
            >
              <Eye size={15} />
              معاينة المستند
            </button>

            {#if isPending}
              <div class="flex items-center gap-2">
                <button
                  class="btn-buy flex items-center gap-1.5 text-xs"
                  onclick={() => approveKYC(kyc.id)}
                  disabled={isActing}
                >
                  {#if isActing}
                    <Loader2 size={14} class="animate-spin" />
                  {:else}
                    <CheckCircle2 size={14} />
                  {/if}
                  قبول
                </button>
                <button
                  class="btn-danger flex items-center gap-1.5 text-xs"
                  onclick={() => openRejectDialog(kyc.id)}
                  disabled={isActing}
                >
                  <XCircle size={14} />
                  رفض
                </button>
              </div>
            {/if}
          </div>
        </div>
      {/each}
    {/if}
  </div>

  <!-- Pagination -->
  {#if totalPages > 1}
    <div class="panel p-4 flex items-center justify-between flex-wrap gap-3">
      <p class="text-xs" style="color: var(--text-tertiary);">
        إجمالي {totalItems.toLocaleString('ar-EG')} طلب · صفحة {page} من {totalPages}
      </p>

      <div class="flex items-center gap-1">
        <button
          class="btn-ghost p-2 rounded-lg"
          onclick={() => (page = Math.max(1, page - 1))}
          disabled={page <= 1}
        >
          <ChevronRight size={18} />
        </button>

        {#if pages[0] > 1}
          <button class="btn-ghost px-3 py-1.5 rounded-lg text-xs" onclick={() => (page = 1)}>1</button>
          {#if pages[0] > 2}
            <span class="px-1 text-xs" style="color: var(--text-quaternary);">...</span>
          {/if}
        {/if}

        {#each pages as p}
          <button
            class="px-3 py-1.5 rounded-lg text-xs font-medium transition-all cursor-pointer"
            class:btn-primary={p === page}
            class:btn-ghost={p !== page}
            onclick={() => (page = p)}
            disabled={p === page}
          >
            {p}
          </button>
        {/each}

        {#if pages[pages.length - 1] < totalPages}
          {#if pages[pages.length - 1] < totalPages - 1}
            <span class="px-1 text-xs" style="color: var(--text-quaternary);">...</span>
          {/if}
          <button
            class="btn-ghost px-3 py-1.5 rounded-lg text-xs"
            onclick={() => (page = totalPages)}
          >
            {totalPages}
          </button>
        {/if}

        <button
          class="btn-ghost p-2 rounded-lg"
          onclick={() => (page = Math.min(totalPages, page + 1))}
          disabled={page >= totalPages}
        >
          <ChevronLeft size={18} />
        </button>
      </div>
    </div>
  {/if}
</div>

// admin/src/app/dashboard/kyc/page.tsx
"use client";

import { useEffect, useState } from "react";
import toast from "react-hot-toast";
import {
  Check,
  X,
  Search,
  Eye,
  ShieldCheck,
  Clock,
  CheckCircle2,
  XCircle,
  FileText,
  User,
  Calendar,
  Filter,
  Wifi,
} from "lucide-react";
import PromptDialog from "@/components/PromptDialog";
import { authGet, authPut } from "@/lib/api";
import { adminStream } from "@/lib/stream";

export default function AdminKYCPage() {
  const [requests, setRequests] = useState<any[]>([]);
  const [search, setSearch] = useState("");
  const [loading, setLoading] = useState(true);
  const [rejectTarget, setRejectTarget] = useState<number | null>(null);
  const [previewDoc, setPreviewDoc] = useState<string | null>(null);
  const [statusFilter, setStatusFilter] = useState<string>("ALL");
  const [liveNewCount, setLiveNewCount] = useState(0);

  const fetchKYC = () => {
    const token = localStorage.getItem("token");
    if (!token) return;
    setLoading(true);
    authGet("/api/v1/admin/kyc")
      .then((r) => r.json())
      .then((d) => {
        const data = d.data;
        setRequests(Array.isArray(data) ? data : []);
      })
      .catch(() => {})
      .finally(() => setLoading(false));
  };

  useEffect(() => {
    fetchKYC();
  }, []);

  // Live updates via SSE — refresh when a new KYC submission arrives
  useEffect(() => {
    const unsub = adminStream.on("kyc", () => {
      setLiveNewCount((n) => n + 1);
      // Silent refresh if no filter/search is active
      if (statusFilter === "ALL" && !search) {
        const token = localStorage.getItem("token");
        if (!token) return;
        authGet("/api/v1/admin/kyc")
          .then((r) => r.json())
          .then((d) => {
            const data = d.data;
            if (Array.isArray(data)) setRequests(data);
          })
          .catch(() => {});
      }
    });
    return unsub;
  }, [statusFilter, search]);

  const handleReview = async (
    id: number,
    status: string,
    rejectionReason = ""
  ) => {
    try {
      const body: any = { status };
      if (status === "REJECTED" && rejectionReason) {
        body.rejection_reason = rejectionReason;
      }
      const res = await authPut(`/api/v1/admin/kyc/${id}/review`, body);
      const data = await res.json();
      if (!res.ok) {
        toast.error(data.error || "فشل المراجعة");
        return;
      }
      toast.success(
        status === "APPROVED" ? "تم توثيق المستخدم" : "تم رفض الطلب"
      );
      fetchKYC();
    } catch {
      toast.error("حدث خطأ في الاتصال");
    }
  };

  const filtered = requests
    .filter((r) => {
      const matchesSearch =
        r.user?.username?.toLowerCase().includes(search.toLowerCase()) ||
        r.user?.email?.toLowerCase().includes(search.toLowerCase());
      const matchesStatus =
        statusFilter === "ALL" || r.status === statusFilter;
      return matchesSearch && matchesStatus;
    });

  // Stats
  const pendingCount = requests.filter((r) => r.status === "PENDING").length;
  const approvedCount = requests.filter((r) => r.status === "APPROVED").length;
  const rejectedCount = requests.filter((r) => r.status === "REJECTED").length;

  const getStatusBadge = (status: string) => {
    switch (status) {
      case "APPROVED":
        return "bg-emerald-500/10 text-emerald-400 border-emerald-500/20";
      case "PENDING":
        return "bg-yellow-500/10 text-yellow-400 border-yellow-500/20";
      case "REJECTED":
        return "bg-red-500/10 text-red-400 border-red-500/20";
      default:
        return "bg-muted/20 text-muted-foreground border-border/30";
    }
  };

  const getStatusLabel = (status: string) => {
    switch (status) {
      case "APPROVED":
        return "موثق";
      case "PENDING":
        return "قيد المراجعة";
      case "REJECTED":
        return "مرفوض";
      default:
        return status;
    }
  };

  const getStatusIcon = (status: string) => {
    switch (status) {
      case "APPROVED":
        return CheckCircle2;
      case "PENDING":
        return Clock;
      case "REJECTED":
        return XCircle;
      default:
        return Clock;
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center py-32">
        <div className="flex flex-col items-center gap-4">
          <span className="spinner h-8 w-8" />
          <p className="text-sm text-muted-foreground">جاري تحميل طلبات KYC...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6 animate-fade-in">
      {/* ─── Header ─── */}
      <div className="animate-slide-in-down">
        <div className="flex items-center gap-3 mb-2">
          <div className="w-10 h-10 rounded-xl bg-emerald-500/10 flex items-center justify-center">
            <ShieldCheck className="h-5 w-5 text-emerald-500" />
          </div>
          <div>
            <h1 className="text-2xl lg:text-3xl font-bold">طلبات KYC</h1>
            <p className="text-sm text-muted-foreground">
              مراجعة طلبات توثيق الهوية والتحقق من المستندات
            </p>
          </div>
          <div className="flex items-center gap-2 ml-auto">
            <div className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">
              <Wifi className="h-3.5 w-3.5" />
              <span>مباشر</span>
              <span className="relative flex h-2 w-2">
                <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75"></span>
                <span className="relative inline-flex rounded-full h-2 w-2 bg-emerald-500"></span>
              </span>
            </div>
            {liveNewCount > 0 && (
              <button
                onClick={() => { setLiveNewCount(0); fetchKYC(); }}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium bg-blue-500/10 text-blue-400 border border-blue-500/20 hover:bg-blue-500/20 transition-colors animate-pulse"
              >
                <FileText className="h-3.5 w-3.5" />
                <span>{liveNewCount} جديد — تحديث</span>
              </button>
            )}
          </div>
        </div>
      </div>

      {/* ─── Stats Row ─── */}
      <div className="grid grid-cols-3 gap-3 animate-slide-in-up delay-100">
        <div className="stat-card stat-card-yellow">
          <div className="relative z-10 flex items-center gap-3">
            <div className="p-2.5 rounded-xl bg-yellow-500/10">
              <Clock className="h-5 w-5 text-yellow-500" />
            </div>
            <div>
              <p className="text-2xl font-bold">{pendingCount}</p>
              <p className="text-[11px] text-muted-foreground font-medium">
                قيد المراجعة
              </p>
            </div>
          </div>
        </div>
        <div className="stat-card stat-card-emerald">
          <div className="relative z-10 flex items-center gap-3">
            <div className="p-2.5 rounded-xl bg-emerald-500/10">
              <CheckCircle2 className="h-5 w-5 text-emerald-500" />
            </div>
            <div>
              <p className="text-2xl font-bold">{approvedCount}</p>
              <p className="text-[11px] text-muted-foreground font-medium">
                تمت الموافقة
              </p>
            </div>
          </div>
        </div>
        <div className="stat-card stat-card-red">
          <div className="relative z-10 flex items-center gap-3">
            <div className="p-2.5 rounded-xl bg-red-500/10">
              <XCircle className="h-5 w-5 text-red-500" />
            </div>
            <div>
              <p className="text-2xl font-bold">{rejectedCount}</p>
              <p className="text-[11px] text-muted-foreground font-medium">
                مرفوضة
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* ─── Search & Filter Bar ─── */}
      <div className="glass-panel rounded-2xl p-4 animate-slide-in-up delay-200">
        <div className="flex flex-col sm:flex-row gap-3">
          {/* Search */}
          <div className="relative flex-1">
            <Search className="absolute right-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground/50" />
            <input
              type="text"
              className="input-field pr-10"
              placeholder="بحث باسم المستخدم أو البريد الإلكتروني..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
            />
          </div>

          {/* Status Filter */}
          <div className="relative">
            <Filter className="absolute right-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground/50 pointer-events-none" />
            <select
              className="input-field pr-10 appearance-none min-w-[160px]"
              value={statusFilter}
              onChange={(e) => setStatusFilter(e.target.value)}
            >
              <option value="ALL">جميع الحالات</option>
              <option value="PENDING">قيد المراجعة</option>
              <option value="APPROVED">موثق</option>
              <option value="REJECTED">مرفوض</option>
            </select>
          </div>
        </div>
      </div>

      {/* ─── KYC Requests Table ─── */}
      <div className="glass-panel rounded-2xl overflow-hidden animate-slide-in-up delay-300">
        {filtered.length > 0 ? (
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-border/20">
                  <th className="text-right p-4 text-muted-foreground font-medium text-xs">
                    المستخدم
                  </th>
                  <th className="text-right p-4 text-muted-foreground font-medium text-xs hidden md:table-cell">
                    البريد الإلكتروني
                  </th>
                  <th className="text-right p-4 text-muted-foreground font-medium text-xs hidden lg:table-cell">
                    نوع الهوية
                  </th>
                  <th className="text-right p-4 text-muted-foreground font-medium text-xs">
                    المستند
                  </th>
                  <th className="text-right p-4 text-muted-foreground font-medium text-xs">
                    الحالة
                  </th>
                  <th className="text-right p-4 text-muted-foreground font-medium text-xs hidden md:table-cell">
                    التاريخ
                  </th>
                  <th className="text-right p-4 text-muted-foreground font-medium text-xs">
                    إجراءات
                  </th>
                </tr>
              </thead>
              <tbody>
                {filtered.map((req: any, i: number) => {
                  const StatusIcon = getStatusIcon(req.status);
                  return (
                    <tr
                      key={i}
                      className="border-b border-border/10 hover:bg-muted/10 transition-colors duration-150"
                    >
                      {/* User */}
                      <td className="p-4">
                        <div className="flex items-center gap-3">
                          <div className="h-9 w-9 rounded-full bg-gradient-to-br from-emerald-500/20 to-teal-500/20 flex items-center justify-center text-sm font-bold text-primary border border-primary/20">
                            {(req.user?.username || req.username || "U")
                              .charAt(0)
                              .toUpperCase()}
                          </div>
                          <div>
                            <p className="font-medium text-sm">
                              {req.user?.username || req.username || "—"}
                            </p>
                            <p className="text-xs text-muted-foreground md:hidden">
                              {req.user?.email || req.email || "—"}
                            </p>
                          </div>
                        </div>
                      </td>

                      {/* Email */}
                      <td className="p-4 text-muted-foreground text-xs hidden md:table-cell">
                        {req.user?.email || req.email || "—"}
                      </td>

                      {/* Document Type */}
                      <td className="p-4 text-xs hidden lg:table-cell">
                        <div className="flex items-center gap-1.5">
                          <FileText className="h-3 w-3 text-muted-foreground/40" />
                          {req.document_type || "—"}
                        </div>
                      </td>

                      {/* Document Preview */}
                      <td className="p-4">
                        {req.document_url ? (
                          <button
                            onClick={() => setPreviewDoc(req.document_url)}
                            className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-blue-500/10 text-blue-400 hover:bg-blue-500/20 transition-all text-xs font-medium border border-blue-500/20"
                          >
                            <Eye className="h-3.5 w-3.5" />
                            عرض المستند
                          </button>
                        ) : (
                          <span className="text-xs text-muted-foreground/50">
                            لا يوجد مستند
                          </span>
                        )}
                      </td>

                      {/* Status */}
                      <td className="p-4">
                        <span
                          className={`inline-flex items-center gap-1 text-[11px] px-2.5 py-1 rounded-lg font-medium border ${getStatusBadge(
                            req.status
                          )}`}
                        >
                          <StatusIcon className="h-3 w-3" />
                          {getStatusLabel(req.status)}
                        </span>
                        {req.rejection_reason && req.status === "REJECTED" && (
                          <p
                            className="text-xs text-red-400/80 mt-1.5 max-w-[200px] truncate"
                            title={req.rejection_reason}
                          >
                            {req.rejection_reason}
                          </p>
                        )}
                      </td>

                      {/* Date */}
                      <td className="p-4 text-muted-foreground text-xs hidden md:table-cell">
                        <div className="flex items-center gap-1.5">
                          <Calendar className="h-3 w-3 text-muted-foreground/40" />
                          {req.created_at
                            ? new Date(req.created_at).toLocaleDateString(
                                "ar-EG",
                                {
                                  year: "numeric",
                                  month: "short",
                                  day: "numeric",
                                }
                              )
                            : "—"}
                        </div>
                      </td>

                      {/* Actions */}
                      <td className="p-4">
                        {req.status === "PENDING" ? (
                          <div className="flex items-center gap-2">
                            <button
                              onClick={() =>
                                handleReview(req.id, "APPROVED")
                              }
                              className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-emerald-500/10 text-emerald-400 hover:bg-emerald-500/20 transition-all text-xs font-medium border border-emerald-500/20"
                              title="موافقة"
                            >
                              <Check className="h-3.5 w-3.5" />
                              <span className="hidden sm:inline">موافقة</span>
                            </button>
                            <button
                              onClick={() => setRejectTarget(req.id)}
                              className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-red-500/10 text-red-400 hover:bg-red-500/20 transition-all text-xs font-medium border border-red-500/20"
                              title="رفض"
                            >
                              <X className="h-3.5 w-3.5" />
                              <span className="hidden sm:inline">رفض</span>
                            </button>
                          </div>
                        ) : (
                          <span className="text-xs text-muted-foreground/40">
                            —
                          </span>
                        )}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        ) : (
          /* Empty State */
          <div className="flex flex-col items-center justify-center py-20 text-center">
            <div className="w-20 h-20 rounded-2xl bg-muted/20 flex items-center justify-center mb-4">
              <ShieldCheck className="h-10 w-10 text-muted-foreground/30" />
            </div>
            <p className="text-sm text-muted-foreground font-medium">
              {search || statusFilter !== "ALL"
                ? "لا توجد نتائج مطابقة للبحث"
                : "لا توجد طلبات KYC"}
            </p>
            <p className="text-xs text-muted-foreground/50 mt-1">
              {search || statusFilter !== "ALL"
                ? "جرب تغيير معايير البحث أو الفلتر"
                : "ستظهر طلبات التوثيق هنا عند تقديمها من المستخدمين"}
            </p>
          </div>
        )}
      </div>

      {/* ─── Document Preview Modal ─── */}
      {previewDoc && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm animate-fade-in"
          onClick={() => setPreviewDoc(null)}
        >
          <div
            className="relative max-w-4xl max-h-[90vh] w-full mx-4 animate-scale-in"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="glass-panel-strong rounded-2xl p-4">
              <div className="flex items-center justify-between mb-3">
                <div className="flex items-center gap-2">
                  <div className="p-1.5 rounded-lg bg-blue-500/10">
                    <FileText className="h-4 w-4 text-blue-400" />
                  </div>
                  <h3 className="text-lg font-bold">معاينة المستند</h3>
                </div>
                <button
                  onClick={() => setPreviewDoc(null)}
                  className="p-2 rounded-xl hover:bg-muted/30 transition-all"
                >
                  <X className="h-5 w-5" />
                </button>
              </div>
              <div className="rounded-xl overflow-hidden bg-muted/10 max-h-[70vh] overflow-auto">
                {previewDoc.match(/\.(jpg|jpeg|png|gif|webp)$/i) ||
                !previewDoc.match(/\.pdf$/i) ? (
                  <img
                    src={`${
                      process.env.NEXT_PUBLIC_API_URL || "http://localhost:3000"
                    }${previewDoc}`}
                    alt="مستند KYC"
                    className="w-full h-auto"
                    onError={(e) => {
                      (e.target as HTMLImageElement).src = "";
                      (e.target as HTMLImageElement).alt = "فشل تحميل المستند";
                    }}
                  />
                ) : (
                  <iframe
                    src={`${
                      process.env.NEXT_PUBLIC_API_URL || "http://localhost:3000"
                    }${previewDoc}`}
                    className="w-full h-[70vh]"
                    title="مستند KYC"
                  />
                )}
              </div>
            </div>
          </div>
        </div>
      )}

      {/* ─── Rejection Prompt Dialog ─── */}
      <PromptDialog
        open={rejectTarget !== null}
        title="رفض طلب التحقق"
        message="أدخل سبب الرفض. سيتم إرسال هذا السبب للمستخدم."
        placeholder="مثال: الصورة غير واضحة"
        confirmLabel="رفض"
        cancelLabel="إلغاء"
        onConfirm={(reason) => {
          if (rejectTarget) handleReview(rejectTarget, "REJECTED", reason);
          setRejectTarget(null);
        }}
        onCancel={() => setRejectTarget(null)}
      />
    </div>
  );
}
