// frontend/src/routes/dashboard/security/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { auth } from '$lib/api/endpoints';
  import { parseApiResponse, ApiError } from '$lib/api/client';
  import { toasts } from '$lib/stores/toast';
  import { authStore } from '$lib/stores/auth';
  import NavTabs from '$lib/components/NavTabs.svelte';
  import {
    Shield, Smartphone, Key, Monitor, LogOut, Plus, Check,
    AlertTriangle, Lock, Fingerprint, ShieldCheck, ShieldAlert,
    Activity, MapPin, Wifi, Loader2, Sparkles, X, Copy
  } from 'lucide-svelte';

  let twoFaEnabled = $state(false);
  let showSetup = $state(false);
  let qrCode = $state('');
  let secret = $state('');
  let setupCode = $state('');
  let loading = $state(false);
  let sessions = $state<any[]>([]);
  let activeTab = $state<'2fa' | 'sessions' | 'api'>('2fa');
  let copiedSecret = $state(false);

  onMount(() => {
    (async () => {
      twoFaEnabled = $authStore?.two_fa_enabled || false;
      loadSessions();
    })();
  });

  async function loadSessions() {
    try {
      const res = await auth.getSessions();
      sessions = (await parseApiResponse<any[]>(res)) || [];
    } catch {}
  }

  async function setup2FA() {
    loading = true;
    try {
      const res = await auth.setup2FA();
      const data = await parseApiResponse<any>(res);
      qrCode = data.qr_code || data.qrcode || '';
      secret = data.secret || '';
      showSetup = true;
    } catch (err: any) {
      toasts.error('فشل إعداد 2FA');
    } finally {
      loading = false;
    }
  }

  async function confirmEnable2FA() {
    if (!setupCode || setupCode.length !== 6) {
      toasts.error('أدخل رمز 6 أرقام');
      return;
    }
    loading = true;
    try {
      await auth.enable2FA(setupCode);
      toasts.success('تم تفعيل المصادقة الثنائية');
      twoFaEnabled = true;
      showSetup = false;
      setupCode = '';
    } catch (err: any) {
      toasts.error(err instanceof ApiError ? err.message : 'رمز غير صحيح');
    } finally {
      loading = false;
    }
  }

  async function disable2FA() {
    const code = prompt('أدخل رمز المصادقة لإلغاء التفعيل');
    if (!code) return;
    try {
      await auth.disable2FA(code);
      toasts.success('تم إلغاء تفعيل المصادقة الثنائية');
      twoFaEnabled = false;
    } catch {
      toasts.error('فشل إلغاء التفعيل');
    }
  }

  function copySecret() {
    if (secret) {
      navigator.clipboard.writeText(secret);
      copiedSecret = true;
      setTimeout(() => (copiedSecret = false), 2000);
    }
  }

  // Security score calculation (0-100)
  const securityScore = $derived.by(() => {
    let score = 0;
    if (twoFaEnabled) score += 50;
    if (sessions.length <= 2) score += 25; else if (sessions.length <= 5) score += 15;
    score += 25; // baseline for having a verified account
    return Math.min(score, 100);
  });

  const scoreLabel = $derived(
    securityScore >= 90 ? 'ممتاز' :
    securityScore >= 70 ? 'جيد جداً' :
    securityScore >= 50 ? 'جيد' :
    'يحتاج تحسين'
  );

  const scoreColor = $derived(
    securityScore >= 90 ? '#22d3a4' :
    securityScore >= 70 ? '#f5b544' :
    securityScore >= 50 ? '#a855f7' :
    '#fb7185'
  );

  // SVG gauge calculation
  const gaugeRadius = 52;
  const gaugeCircumference = 2 * Math.PI * gaugeRadius;
  const gaugeOffset = $derived(gaugeCircumference - (securityScore / 100) * gaugeCircumference);

  // Security checklist items
  const checklist = $derived([
    { label: 'المصادقة الثنائية (2FA)', done: twoFaEnabled, icon: Fingerprint },
    { label: 'بريد إلكتروني مُوثّق', done: true, icon: Check },
    { label: 'كلمة مرور قوية', done: true, icon: Lock },
    { label: 'جلسات قليلة نشطة', done: sessions.length <= 2, icon: Monitor }
  ]);
</script>

<svelte:head><title>الأمان — NEXUS</title></svelte:head>

<div class="max-w-3xl mx-auto space-y-5 relative">
  <!-- Ambient aurora -->
  <div class="fixed inset-0 pointer-events-none overflow-hidden" aria-hidden="true">
    <div class="absolute -top-20 right-1/4 w-80 h-80 bg-accent-mint/6 blur-[120px] rounded-full animate-pulse-glow"></div>
    <div class="absolute bottom-0 -left-32 w-80 h-80 bg-accent-gold/5 blur-[120px] rounded-full animate-pulse-glow" style="animation-delay: 2s;"></div>
  </div>

  <!-- Header -->
  <div class="relative">
    <div class="flex items-center gap-3">
      <div class="w-11 h-11 rounded-2xl bg-gradient-to-br from-accent-mint/15 to-accent-gold/10 border border-accent-mint/20 flex items-center justify-center">
        <Shield size={22} class="text-accent-mint" />
      </div>
      <div>
        <h1 class="text-2xl sm:text-3xl font-bold text-white tracking-tight">الأمان</h1>
        <p class="text-sm text-slate-400 mt-0.5">حماية حسابك والتحكم في الجلسات</p>
      </div>
    </div>
  </div>

  <!-- Security score gauge + checklist -->
  <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
    <!-- Score gauge -->
    <div class="panel p-5 relative overflow-hidden">
      <div class="absolute -top-12 -right-12 w-32 h-32 blur-3xl rounded-full" style="background: {scoreColor}20;"></div>
      <div class="relative flex flex-col items-center">
        <h3 class="text-xs font-bold text-slate-400 uppercase tracking-wider mb-3 self-start">درجة الأمان</h3>
        <div class="relative w-32 h-32">
          <svg width="128" height="128" viewBox="0 0 128 128" class="-rotate-90">
            <circle cx="64" cy="64" r={gaugeRadius} stroke="rgba(255,255,255,0.05)" stroke-width="8" fill="none" />
            <circle
              cx="64"
              cy="64"
              r={gaugeRadius}
              stroke={scoreColor}
              stroke-width="8"
              fill="none"
              stroke-linecap="round"
              stroke-dasharray={gaugeCircumference}
              stroke-dashoffset={gaugeOffset}
              style="transition: stroke-dashoffset 1s ease-out, stroke 0.5s;"
            />
          </svg>
          <div class="absolute inset-0 flex flex-col items-center justify-center">
            <span class="text-3xl font-bold text-white tabular-nums">{securityScore}</span>
            <span class="text-[9px] text-slate-500 uppercase tracking-wider">من 100</span>
          </div>
        </div>
        <div class="mt-3 flex items-center gap-1.5 px-3 py-1 rounded-full" style="background: {scoreColor}15; border: 1px solid {scoreColor}30;">
          <ShieldCheck size={12} style="color: {scoreColor};" />
          <span class="text-xs font-bold" style="color: {scoreColor};">{scoreLabel}</span>
        </div>
      </div>
    </div>

    <!-- Checklist -->
    <div class="panel p-5">
      <h3 class="text-xs font-bold text-slate-400 uppercase tracking-wider mb-3">قائمة التحقق</h3>
      <div class="space-y-2.5">
        {#each checklist as item}
          <div class="flex items-center gap-2.5">
            <div class="w-7 h-7 rounded-lg flex items-center justify-center shrink-0 {item.done ? 'bg-accent-mint/15 border border-accent-mint/25' : 'bg-accent-gold/10 border border-accent-gold/20'}">
              {#if item.done}
                <Check size={14} class="text-accent-mint" />
              {:else}
                <item.icon size={14} class="text-accent-gold" />
              {/if}
            </div>
            <span class="text-xs font-medium text-white flex-1">{item.label}</span>
            {#if item.done}
              <span class="text-[9px] font-bold text-accent-mint uppercase tracking-wider">تم</span>
            {:else}
              <span class="text-[9px] font-bold text-accent-gold uppercase tracking-wider">معلّق</span>
            {/if}
          </div>
        {/each}
      </div>
    </div>
  </div>

  <!-- Nav tabs -->
  <NavTabs
    value={activeTab}
    onchange={(key) => (activeTab = key as any)}
    items={[
      { key: '2fa', label: 'المصادقة الثنائية', icon: Fingerprint },
      { key: 'sessions', label: 'الجلسات', icon: Monitor, count: sessions.length },
      { key: 'api', label: 'مفاتيح API', icon: Key }
    ]}
  />

  {#if activeTab === '2fa'}
    <div class="panel p-6 relative overflow-hidden">
      <div class="absolute top-0 inset-x-0 h-px pointer-events-none" style="background: linear-gradient(90deg, transparent, {twoFaEnabled ? 'rgba(34, 211, 164, 0.4)' : 'rgba(245, 181, 68, 0.4)'}, transparent);"></div>
      <div class="absolute -top-12 -right-12 w-32 h-32 blur-3xl rounded-full {twoFaEnabled ? 'bg-accent-mint/10' : 'bg-accent-gold/10'}"></div>

      <div class="relative">
        <div class="flex items-start justify-between mb-5">
          <div class="flex items-start gap-3">
            <div class="relative w-12 h-12 rounded-2xl {twoFaEnabled ? 'bg-accent-mint/10 border-accent-mint/20' : 'bg-accent-gold/10 border-accent-gold/20'} border flex items-center justify-center">
              <Shield size={22} class={twoFaEnabled ? 'text-accent-mint' : 'text-accent-gold'} />
              {#if twoFaEnabled}
                <span class="absolute -top-1 -right-1 w-5 h-5 rounded-full bg-accent-mint flex items-center justify-center border-2 border-ink-900">
                  <Check size={10} class="text-ink-950" />
                </span>
              {/if}
            </div>
            <div>
              <h3 class="text-base font-bold text-white">المصادقة الثنائية (2FA)</h3>
              <p class="text-xs text-slate-400 mt-0.5">طبقة حماية إضافية باستخدام تطبيق TOTP</p>
            </div>
          </div>
          {#if twoFaEnabled}
            <span class="pill-mint flex items-center gap-1"><Check size={10} /> مفعّلة</span>
          {:else}
            <span class="pill-gold flex items-center gap-1"><AlertTriangle size={10} /> غير مفعّلة</span>
          {/if}
        </div>

        {#if twoFaEnabled}
          <!-- Enabled state — premium card -->
          <div class="panel p-4 bg-accent-mint/5 border-accent-mint/15 mb-4">
            <div class="flex items-center gap-3">
              <div class="w-10 h-10 rounded-xl bg-accent-mint/15 flex items-center justify-center shrink-0">
                <ShieldCheck size={20} class="text-accent-mint" />
              </div>
              <div class="flex-1">
                <p class="text-sm font-semibold text-white">حسابك محمي بالمصادقة الثنائية</p>
                <p class="text-xs text-slate-400 mt-0.5">يُطلب رمز 2FA عند تسجيل الدخول والعمليات الحساسة</p>
              </div>
            </div>
          </div>
          <button onclick={disable2FA} class="btn-secondary text-accent-rose hover:bg-accent-rose/5 border-accent-rose/20">
            <X size={14} /> إلغاء التفعيل
          </button>
        {:else if showSetup}
          <!-- Setup wizard -->
          <div class="space-y-5">
            <!-- Step indicator -->
            <div class="flex items-center justify-center gap-2 mb-4">
              {#each [1, 2, 3] as step}
                <div class="flex items-center gap-2">
                  <div class="w-6 h-6 rounded-full {step === 1 ? 'bg-accent-gold text-ink-950' : 'bg-white/5 text-slate-500'} flex items-center justify-center text-[10px] font-bold">
                    {step}
                  </div>
                  {#if step < 3}
                    <div class="w-8 h-px bg-white/10"></div>
                  {/if}
                </div>
              {/each}
            </div>

            {#if qrCode}
              <div class="flex flex-col items-center gap-3">
                <div class="relative">
                  <div class="absolute inset-0 bg-accent-gold/20 blur-2xl rounded-2xl"></div>
                  <img src={qrCode} alt="QR Code" class="relative w-44 h-44 rounded-2xl bg-white p-3 shadow-2xl" />
                </div>
                <p class="text-xs text-slate-400 text-center max-w-xs">
                  امسح الرمز باستخدام تطبيق المصادقة (Google Authenticator, Authy, 1Password)
                </p>
              </div>
            {/if}

            {#if secret}
              <div class="panel p-3 bg-ink-950/60 border-accent-gold/15">
                <div class="flex items-center justify-between mb-1">
                  <p class="text-[10px] text-slate-500 font-bold uppercase tracking-wider">المفتاح السري</p>
                  <button onclick={copySecret} class="text-[10px] text-accent-gold hover:underline flex items-center gap-1">
                    {#if copiedSecret}
                      <Check size={10} /> تم النسخ
                    {:else}
                      <Copy size={10} /> نسخ
                    {/if}
                  </button>
                </div>
                <code class="text-xs font-mono text-accent-gold break-all leading-relaxed">{secret}</code>
              </div>
            {/if}

            <div>
              <span class="input-label flex items-center gap-1.5">
                <Key size={12} class="text-accent-gold" />
                أدخل الرمز من تطبيق المصادقة
              </span>
              <input
                bind:value={setupCode}
                type="text"
                maxlength="6"
                inputmode="numeric"
                placeholder="000000"
                class="input text-center text-2xl tracking-[0.5em] font-mono font-bold"
              />
              <p class="text-[10px] text-slate-500 mt-1.5 text-center">رمز من 6 أرقام يتجدّد كل 30 ثانية</p>
            </div>

            <div class="flex gap-2">
              <button onclick={confirmEnable2FA} disabled={loading || setupCode.length !== 6} class="btn-primary flex-1">
                {#if loading}
                  <Loader2 size={16} class="animate-spin" /> جارٍ التحقق...
                {:else}
                  <Check size={16} /> تأكيد التفعيل
                {/if}
              </button>
              <button onclick={() => (showSetup = false)} class="btn-secondary">إلغاء</button>
            </div>
          </div>
        {:else}
          <!-- Initial state -->
          <div class="space-y-4">
            <div class="panel p-4 bg-accent-gold/5 border-accent-gold/15 flex items-start gap-3">
              <div class="w-9 h-9 rounded-xl bg-accent-gold/15 flex items-center justify-center shrink-0">
                <ShieldAlert size={18} class="text-accent-gold" />
              </div>
              <div class="flex-1">
                <p class="text-sm font-semibold text-white">حسابك غير محمي بالكامل</p>
                <p class="text-xs text-slate-400 mt-0.5 leading-relaxed">
                  فعّل المصادقة الثنائية لإضافة طبقة حماية إضافية. سيُطلب رمز سري عند كل تسجيل دخول أو عملية حساسة.
                </p>
              </div>
            </div>
            <button onclick={setup2FA} disabled={loading} class="btn-primary w-full py-3">
              {#if loading}
                <Loader2 size={16} class="animate-spin" /> جارٍ التحضير...
              {:else}
                <Plus size={16} /> تفعيل المصادقة الثنائية
              {/if}
            </button>
          </div>
        {/if}
      </div>
    </div>
  {:else if activeTab === 'sessions'}
    <div class="panel overflow-hidden relative">
      <div class="absolute top-0 inset-x-0 h-px pointer-events-none" style="background: linear-gradient(90deg, transparent, rgba(168, 85, 247, 0.3), transparent);"></div>
      <div class="px-5 py-4 border-b border-white/5 flex items-center justify-between">
        <h3 class="text-sm font-bold text-white flex items-center gap-2">
          <div class="w-7 h-7 rounded-lg bg-accent-violet/10 border border-accent-violet/20 flex items-center justify-center">
            <Monitor size={14} class="text-accent-violet" />
          </div>
          الجلسات النشطة
        </h3>
        <span class="text-xs text-slate-500">{sessions.length} جلسة</span>
      </div>
      {#if sessions.length === 0}
        <div class="py-16 text-center">
          <div class="relative inline-block mb-3">
            <div class="absolute inset-0 bg-accent-violet/10 blur-2xl rounded-full"></div>
            <Monitor size={40} class="relative text-slate-600 mx-auto" />
          </div>
          <p class="text-sm font-medium text-slate-300">لا توجد جلسات نشطة</p>
          <p class="text-xs text-slate-500 mt-1">ستظهر هنا جميع الأجهزة المتصلة بحسابك</p>
        </div>
      {:else}
        <div class="divide-y divide-white/5">
          {#each sessions as s}
            <div class="flex items-center justify-between px-5 py-3.5 hover:bg-white/[0.02] transition-colors group">
              <div class="flex items-center gap-3">
                <div class="relative w-10 h-10 rounded-xl bg-white/[0.03] border border-white/5 flex items-center justify-center">
                  {#if s.current}
                    <Smartphone size={16} class="text-accent-mint" />
                  {:else}
                    <Monitor size={16} class="text-slate-400" />
                  {/if}
                  {#if s.current}
                    <span class="absolute -bottom-0.5 -right-0.5 w-3 h-3 rounded-full bg-accent-mint border-2 border-ink-900"></span>
                  {/if}
                </div>
                <div>
                  <p class="text-sm font-semibold text-white flex items-center gap-1.5">
                    {s.device || s.user_agent || 'جهاز'}
                    {#if s.current}
                      <span class="pill-mint text-[9px] px-1.5 py-0">الحالية</span>
                    {/if}
                  </p>
                  <div class="flex items-center gap-3 mt-0.5">
                    <p class="text-xs text-slate-400 flex items-center gap-1">
                      <MapPin size={9} />
                      {s.ip_address || 'IP غير معروف'}
                    </p>
                    {#if s.last_active}
                      <p class="text-[10px] text-slate-500 flex items-center gap-1">
                        <Activity size={9} />
                        {s.last_active}
                      </p>
                    {/if}
                  </div>
                </div>
              </div>
              {#if !s.current}
                <button
                  onclick={async () => {
                    try {
                      await auth.revokeSession(s.id);
                      toasts.success('تم إنهاء الجلسة');
                      loadSessions();
                    } catch {
                      toasts.error('فشل إنهاء الجلسة');
                    }
                  }}
                  class="p-2 rounded-lg text-slate-500 hover:bg-accent-rose/10 hover:text-accent-rose transition-colors opacity-0 group-hover:opacity-100"
                  aria-label="إنهاء الجلسة"
                  title="إنهاء الجلسة"
                >
                  <LogOut size={14} />
                </button>
              {/if}
            </div>
          {/each}
        </div>
      {/if}
    </div>
  {:else if activeTab === 'api'}
    <div class="panel p-6 relative overflow-hidden">
      <div class="absolute -top-12 -right-12 w-32 h-32 bg-accent-gold/8 blur-3xl rounded-full"></div>
      <div class="relative">
        <h3 class="text-base font-bold text-white mb-2 flex items-center gap-2">
          <div class="w-8 h-8 rounded-xl bg-accent-gold/10 border border-accent-gold/20 flex items-center justify-center">
            <Key size={16} class="text-accent-gold" />
          </div>
          مفاتيح API
        </h3>
        <p class="text-xs text-slate-400 mb-4 leading-relaxed">
          أنشئ مفاتيح API للوصول البرمجي إلى حسابك. استخدم المفاتيح بمسؤولية ولا تشاركها مع أي طرف خارجي.
        </p>

        <!-- Permission tiers -->
        <div class="grid grid-cols-3 gap-2 mb-4">
          <div class="panel p-3 text-center bg-accent-mint/5 border-accent-mint/15">
            <Lock size={14} class="text-accent-mint mx-auto mb-1" />
            <p class="text-[10px] font-bold text-white">قراءة</p>
            <p class="text-[9px] text-slate-500 mt-0.5">افتراضي</p>
          </div>
          <div class="panel p-3 text-center bg-accent-gold/5 border-accent-gold/15">
            <Activity size={14} class="text-accent-gold mx-auto mb-1" />
            <p class="text-[10px] font-bold text-white">تداول</p>
            <p class="text-[9px] text-slate-500 mt-0.5">يتطلب 2FA</p>
          </div>
          <div class="panel p-3 text-center bg-accent-rose/5 border-accent-rose/15">
            <AlertTriangle size={14} class="text-accent-rose mx-auto mb-1" />
            <p class="text-[10px] font-bold text-white">سحب</p>
            <p class="text-[9px] text-slate-500 mt-0.5">مُعطّل</p>
          </div>
        </div>

        <div class="panel p-3 bg-accent-gold/5 border-accent-gold/15 mb-4 flex items-start gap-2">
          <Lock size={14} class="text-accent-gold shrink-0 mt-0.5" />
          <p class="text-[11px] text-slate-300 leading-relaxed">
            سيتم تطبيق صلاحيات القراءة فقط افتراضياً. تحتاج الصلاحيات الأخرى (تداول، سحب) إلى تفعيل 2FA أولاً.
          </p>
        </div>
        <button onclick={() => toasts.info('سيتم إضافة هذه الميزة قريباً')} class="btn-secondary w-full">
          <Plus size={14} /> إنشاء مفتاح جديد
        </button>
      </div>
    </div>
  {/if}
</div>

// frontend/src/app/dashboard/security/page.tsx
"use client";

import { useState, useEffect, useRef } from "react";
import { useRouter } from "next/navigation";
import toast from "react-hot-toast";
import QRCode from "qrcode";
import {
  Shield,
  ShieldCheck,
  ShieldOff,
  QrCode,
  Key,
  Copy,
  Download,
  AlertTriangle,
  CheckCircle,
  Loader2,
  Monitor,
  Smartphone,
  Trash2,
  Mail,
  Lock,
  Eye,
  EyeOff,
  ShieldAlert,
  Lightbulb,
  Globe,
  Chrome,
} from "lucide-react";
import { authGet, authPost } from "@/lib/api";

interface User {
  id: number;
  email: string;
  username: string;
  two_fa_enabled: boolean;
  email_verified: boolean;
}

export default function SecurityPage() {
  const router = useRouter();
  const [user, setUser] = useState<User | null>(null);
  const [loading, setLoading] = useState(true);

  // 2FA Setup State
  const [setupStep, setSetupStep] = useState<"idle" | "setup" | "verify" | "backup">("idle");
  const [totpSecret, setTotpSecret] = useState("");
  const [otpauthUrl, setOtpauthUrl] = useState("");
  const [verifyCode, setVerifyCode] = useState("");
  const [backupCodes, setBackupCodes] = useState<string[]>([]);
  const [setupLoading, setSetupLoading] = useState(false);
  const [verifyLoading, setVerifyLoading] = useState(false);
  const [qrDataUrl, setQrDataUrl] = useState("");
  const qrRef = useRef<HTMLDivElement>(null);

  // Disable 2FA State
  const [showDisable, setShowDisable] = useState(false);
  const [disablePassword, setDisablePassword] = useState("");
  const [disableCode, setDisableCode] = useState("");
  const [disableLoading, setDisableLoading] = useState(false);
  const [showDisablePwd, setShowDisablePwd] = useState(false);

  // Sessions State
  const [sessions, setSessions] = useState<any[]>([]);
  const [sessionsLoading, setSessionsLoading] = useState(false);

  // Copied states
  const [copiedSecret, setCopiedSecret] = useState(false);
  const [copiedCodes, setCopiedCodes] = useState(false);

  useEffect(() => {
    const token = localStorage.getItem("token");
    if (!token) {
      router.push("/login");
      return;
    }

    const userData = localStorage.getItem("user");
    if (userData) {
      try {
        setUser(JSON.parse(userData));
      } catch {
        router.push("/login");
        return;
      }
    }
    setLoading(false);
    fetchSessions();
  }, [router]);

  const fetchSessions = async () => {
    setSessionsLoading(true);
    try {
      const res = await authGet("/api/v1/auth/sessions");
      if (res.ok) {
        const data = await res.json();
        setSessions(data.data || []);
      }
    } catch {
      // Silently fail
    } finally {
      setSessionsLoading(false);
    }
  };

  const handleRevokeSession = async (sessionId: number) => {
    try {
      const res = await authPost(`/api/v1/auth/sessions/${sessionId}/revoke`);
      const data = await res.json();
      if (!res.ok) {
        toast.error(data.error || "فشل إنهاء الجلسة");
        return;
      }
      toast.success(data.message || "تم إنهاء الجلسة");
      fetchSessions();
    } catch {
      toast.error("حدث خطأ في الاتصال");
    }
  };

  // --- 2FA Setup Flow ---
  const handleSetup2FA = async () => {
    setSetupLoading(true);
    try {
      const res = await authPost("/api/v1/auth/setup-2fa");
      const data = await res.json();
      if (!res.ok) {
        toast.error(data.error || "فشل إعداد المصادقة الثنائية");
        return;
      }
      setTotpSecret(data.secret);
      setOtpauthUrl(data.otpauth_url);
      setSetupStep("setup");
      // Generate QR code locally (security: never send TOTP secret to external service)
      try {
        const dataUrl = await QRCode.toDataURL(data.otpauth_url, {
          width: 200,
          margin: 2,
          color: { dark: "#000000", light: "#ffffff" },
        });
        setQrDataUrl(dataUrl);
      } catch {
        // Fallback: the URL is still available for manual entry
        setQrDataUrl("");
      }
    } catch {
      toast.error("حدث خطأ في الاتصال");
    } finally {
      setSetupLoading(false);
    }
  };

  const handleVerify2FA = async () => {
    if (verifyCode.length !== 6) {
      toast.error("يجب إدخال 6 أرقام");
      return;
    }
    setVerifyLoading(true);
    try {
      const res = await authPost("/api/v1/auth/enable-2fa", { code: verifyCode });
      const data = await res.json();
      if (!res.ok) {
        toast.error(data.error || "رمز التحقق غير صحيح");
        return;
      }
      setBackupCodes(data.backup_codes || []);
      setSetupStep("backup");

      // Update local user data
      if (user) {
        const updatedUser = { ...user, two_fa_enabled: true };
        setUser(updatedUser);
        localStorage.setItem("user", JSON.stringify(updatedUser));
      }

      toast.success(data.message || "تم تفعيل المصادقة الثنائية بنجاح!");
    } catch {
      toast.error("حدث خطأ في الاتصال");
    } finally {
      setVerifyLoading(false);
    }
  };

  const handleDisable2FA = async () => {
    if (!disablePassword || !disableCode) {
      toast.error("يجب إدخال كلمة المرور ورمز التحقق");
      return;
    }
    setDisableLoading(true);
    try {
      const res = await authPost("/api/v1/auth/disable-2fa", { password: disablePassword, code: disableCode });
      const data = await res.json();
      if (!res.ok) {
        toast.error(data.error || "فشل تعطيل المصادقة الثنائية");
        return;
      }

      if (user) {
        const updatedUser = { ...user, two_fa_enabled: false };
        setUser(updatedUser);
        localStorage.setItem("user", JSON.stringify(updatedUser));
      }

      setShowDisable(false);
      setDisablePassword("");
      setDisableCode("");
      setSetupStep("idle");
      toast.success(data.message || "تم تعطيل المصادقة الثنائية");
    } catch {
      toast.error("حدث خطأ في الاتصال");
    } finally {
      setDisableLoading(false);
    }
  };

  const copyToClipboard = (text: string, type: "secret" | "codes") => {
    navigator.clipboard.writeText(text);
    if (type === "secret") {
      setCopiedSecret(true);
      setTimeout(() => setCopiedSecret(false), 2000);
    } else {
      setCopiedCodes(true);
      setTimeout(() => setCopiedCodes(false), 2000);
    }
    toast.success("تم النسخ");
  };

  const downloadBackupCodes = () => {
    const content = `EgMoney - رموز الاحتياط للمصادقة الثنائية
تاريخ الإنشاء: ${new Date().toLocaleDateString("ar-EG")}

${backupCodes.map((c, i) => `${i + 1}. ${c}`).join("\n")}

⚠️ احفظ هذه الرموز في مكان آمن. كل رمز يُستخدم مرة واحدة فقط.
إذا فقدت الوصول لتطبيق المصادقة، يمكنك استخدام هذه الرموز لتسجيل الدخول.`;
    const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "egmoney-backup-codes.txt";
    a.click();
    URL.revokeObjectURL(url);
  };

  const extractBrowser = (ua: string) => {
    if (!ua) return "متصفح";
    if (ua.includes("Edg/")) return "Edge";
    if (ua.includes("OPR/") || ua.includes("Opera")) return "Opera";
    if (ua.includes("Chrome/")) return "Chrome";
    if (ua.includes("Firefox/")) return "Firefox";
    if (ua.includes("Safari/") && !ua.includes("Chrome")) return "Safari";
    return "متصفح";
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[60vh]">
        <Loader2 className="h-8 w-8 animate-spin text-emerald-500" />
      </div>
    );
  }

  if (!user) return null;

  return (
    <div className="space-y-6 max-w-3xl">
      {/* ── Page Header ── */}
      <div className="animate-slide-in-up">
        <h1 className="text-3xl font-bold flex items-center gap-3">
          <div className="h-10 w-10 rounded-xl bg-gradient-to-br from-emerald-500 to-teal-600 flex items-center justify-center shadow-lg shadow-emerald-500/20">
            <Shield className="h-5 w-5 text-white" />
          </div>
          الأمان والحماية
        </h1>
        <p className="text-muted-foreground mt-2 text-sm">إدارة إعدادات أمان حسابك</p>
      </div>

      {/* ── Email Verification Status ── */}
      <div
        className="glass-panel rounded-2xl p-5 animate-slide-in-up"
        style={{ animationDelay: "80ms", animationFillMode: "both" }}
      >
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-4">
            <div
              className={`h-11 w-11 rounded-xl flex items-center justify-center ${
                user.email_verified ? "bg-emerald-500/10" : "bg-yellow-500/10"
              }`}
            >
              {user.email_verified ? (
                <Mail className="h-5 w-5 text-emerald-500" />
              ) : (
                <AlertTriangle className="h-5 w-5 text-yellow-500" />
              )}
            </div>
            <div>
              <h3 className="font-bold text-base">تأكيد البريد الإلكتروني</h3>
              <p className="text-sm text-muted-foreground mt-0.5">{user.email}</p>
            </div>
          </div>
          <span
            className={`text-xs px-3 py-1.5 rounded-full font-medium ${
              user.email_verified
                ? "bg-emerald-500/10 text-emerald-400 border border-emerald-500/20"
                : "bg-yellow-500/10 text-yellow-400 border border-yellow-500/20"
            }`}
          >
            {user.email_verified ? "مؤكد ✓" : "غير مؤكد"}
          </span>
        </div>
      </div>

      {/* ── Two-Factor Authentication ── */}
      <div
        className="glass-panel rounded-2xl overflow-hidden animate-slide-in-up"
        style={{ animationDelay: "160ms", animationFillMode: "both" }}
      >
        {/* 2FA Card Header */}
        <div className="p-5 border-b border-border/30">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <div
                className={`h-11 w-11 rounded-xl flex items-center justify-center ${
                  user.two_fa_enabled ? "bg-emerald-500/10" : "bg-primary/10"
                }`}
              >
                {user.two_fa_enabled ? (
                  <ShieldCheck className="h-5 w-5 text-emerald-500" />
                ) : (
                  <ShieldOff className="h-5 w-5 text-muted-foreground" />
                )}
              </div>
              <div>
                <h3 className="font-bold text-base">المصادقة الثنائية (2FA)</h3>
                <p className="text-xs text-muted-foreground mt-0.5">طبقة حماية إضافية لحسابك</p>
              </div>
            </div>
            <span
              className={`text-xs px-3 py-1.5 rounded-full font-medium ${
                user.two_fa_enabled
                  ? "bg-emerald-500/10 text-emerald-400 border border-emerald-500/20"
                  : "bg-red-500/10 text-red-400 border border-red-500/20"
              }`}
            >
              {user.two_fa_enabled ? "مفعلة" : "غير مفعلة"}
            </span>
          </div>
        </div>

        <div className="p-5">
          {/* 2FA is NOT enabled - Show setup flow */}
          {!user.two_fa_enabled && setupStep === "idle" && (
            <div className="space-y-4">
              <div className="p-4 rounded-xl bg-blue-500/5 border border-blue-500/15 flex items-start gap-3">
                <Shield className="h-5 w-5 text-blue-400 shrink-0 mt-0.5" />
                <p className="text-sm text-muted-foreground leading-relaxed">
                  المصادقة الثنائية تضيف طبقة حماية إضافية لحسابك. عند تفعيلها، سيُطلب منك إدخال رمز تحقق من تطبيق المصادقة (مثل Google Authenticator أو Authy) عند كل تسجيل دخول.
                </p>
              </div>
              <button onClick={handleSetup2FA} disabled={setupLoading} className="btn-primary gap-2 min-w-[180px]">
                {setupLoading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Shield className="h-4 w-4" />}
                إعداد المصادقة الثنائية
              </button>
            </div>
          )}

          {/* Step: Show QR Code */}
          {setupStep === "setup" && (
            <div className="space-y-5 animate-scale-in">
              {/* Step indicator */}
              <div className="flex items-center gap-2">
                <div className="flex items-center gap-1.5">
                  <span className="h-6 w-6 rounded-full bg-emerald-500 text-white text-xs flex items-center justify-center font-bold">1</span>
                  <span className="text-xs font-medium text-emerald-400">مسح الرمز</span>
                </div>
                <div className="h-px flex-1 bg-border/50" />
                <div className="flex items-center gap-1.5">
                  <span className="h-6 w-6 rounded-full bg-muted/50 text-muted-foreground text-xs flex items-center justify-center font-bold">2</span>
                  <span className="text-xs font-medium text-muted-foreground">التحقق</span>
                </div>
                <div className="h-px flex-1 bg-border/50" />
                <div className="flex items-center gap-1.5">
                  <span className="h-6 w-6 rounded-full bg-muted/50 text-muted-foreground text-xs flex items-center justify-center font-bold">3</span>
                  <span className="text-xs font-medium text-muted-foreground">رموز الاحتياط</span>
                </div>
              </div>

              <div className="p-4 rounded-xl bg-yellow-500/5 border border-yellow-500/15 flex items-start gap-3">
                <AlertTriangle className="h-5 w-5 text-yellow-500 shrink-0 mt-0.5" />
                <p className="text-sm text-muted-foreground leading-relaxed">
                  امسح رمز QR بتطبيق المصادقة أولاً، ثم أدخل الكود أدناه
                </p>
              </div>

              {/* QR Code */}
              <div className="flex justify-center">
                <div ref={qrRef} className="bg-white rounded-2xl p-4 inline-block shadow-xl">
                  {qrDataUrl ? (
                    <img src={qrDataUrl} alt="2FA QR Code" width={200} height={200} className="rounded-lg" />
                  ) : (
                    <QrCode className="h-[200px] w-[200px] text-gray-300" />
                  )}
                </div>
              </div>

              {/* Manual Entry */}
              <div className="space-y-2">
                <label className="block text-sm font-medium text-muted-foreground text-center">أو أدخل المفتاح يدوياً</label>
                <div className="flex items-center gap-2">
                  <code
                    className="flex-1 bg-background/50 border border-border/50 rounded-xl px-4 py-2.5 text-sm font-mono text-center tracking-wider break-all"
                    dir="ltr"
                  >
                    {totpSecret}
                  </code>
                  <button
                    onClick={() => copyToClipboard(totpSecret, "secret")}
                    className={`h-10 w-10 rounded-xl flex items-center justify-center border transition-all shrink-0 ${
                      copiedSecret
                        ? "bg-emerald-500/10 border-emerald-500/20 text-emerald-500"
                        : "border-border/50 text-muted-foreground hover:bg-muted/50 hover:text-foreground"
                    }`}
                  >
                    {copiedSecret ? <CheckCircle className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
                  </button>
                </div>
              </div>

              {/* Verify Code Input */}
              <div className="space-y-2">
                <label className="block text-sm font-medium">أدخل رمز التحقق من تطبيق المصادقة</label>
                <input
                  type="text"
                  className="input-field text-center text-2xl tracking-[0.5em] font-mono"
                  placeholder="000000"
                  value={verifyCode}
                  onChange={(e) => setVerifyCode(e.target.value.replace(/\D/g, "").slice(0, 6))}
                  maxLength={6}
                  dir="ltr"
                />
              </div>

              <div className="flex gap-3">
                <button
                  onClick={() => {
                    setSetupStep("idle");
                    setVerifyCode("");
                  }}
                  className="btn-ghost flex-1"
                >
                  إلغاء
                </button>
                <button
                  onClick={handleVerify2FA}
                  disabled={verifyLoading || verifyCode.length !== 6}
                  className="btn-primary flex-1 gap-2"
                >
                  {verifyLoading ? <Loader2 className="h-4 w-4 animate-spin" /> : <CheckCircle className="h-4 w-4" />}
                  تفعيل
                </button>
              </div>
            </div>
          )}

          {/* Step: Show Backup Codes */}
          {setupStep === "backup" && (
            <div className="space-y-5 animate-scale-in">
              {/* Step indicator */}
              <div className="flex items-center gap-2">
                <div className="flex items-center gap-1.5">
                  <span className="h-6 w-6 rounded-full bg-emerald-500 text-white text-xs flex items-center justify-center font-bold">1</span>
                  <span className="text-xs font-medium text-emerald-400">مسح الرمز</span>
                </div>
                <div className="h-px flex-1 bg-emerald-500/30" />
                <div className="flex items-center gap-1.5">
                  <span className="h-6 w-6 rounded-full bg-emerald-500 text-white text-xs flex items-center justify-center font-bold">2</span>
                  <span className="text-xs font-medium text-emerald-400">التحقق</span>
                </div>
                <div className="h-px flex-1 bg-emerald-500/30" />
                <div className="flex items-center gap-1.5">
                  <span className="h-6 w-6 rounded-full bg-emerald-500 text-white text-xs flex items-center justify-center font-bold">3</span>
                  <span className="text-xs font-medium text-emerald-400">رموز الاحتياط</span>
                </div>
              </div>

              <div className="p-4 rounded-xl bg-red-500/5 border border-red-500/15 flex items-start gap-3">
                <AlertTriangle className="h-5 w-5 text-red-400 shrink-0 mt-0.5" />
                <p className="text-sm text-muted-foreground leading-relaxed">
                  احفظ رموز الاحتياط في مكان آمن! لن تظهر مرة أخرى. يمكنك استخدامها لتسجيل الدخول إذا فقدت الوصول لتطبيق المصادقة.
                </p>
              </div>

              <div className="grid grid-cols-2 gap-2">
                {backupCodes.map((code, i) => (
                  <div
                    key={i}
                    className="bg-background/50 border border-border/40 rounded-xl px-4 py-2.5 text-center font-mono text-sm tracking-wider"
                    dir="ltr"
                  >
                    {code}
                  </div>
                ))}
              </div>

              <div className="flex gap-3">
                <button
                  onClick={() => {
                    copyToClipboard(backupCodes.join("\n"), "codes");
                  }}
                  className={`btn-ghost flex-1 gap-2 ${copiedCodes ? "text-emerald-500" : ""}`}
                >
                  {copiedCodes ? <CheckCircle className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
                  {copiedCodes ? "تم النسخ" : "نسخ الكل"}
                </button>
                <button onClick={downloadBackupCodes} className="btn-primary flex-1 gap-2">
                  <Download className="h-4 w-4" />
                  تحميل
                </button>
              </div>

              <button onClick={() => setSetupStep("idle")} className="btn-primary w-full">
                لقد حفظت رموز الاحتياط - متابعة
              </button>
            </div>
          )}

          {/* 2FA IS enabled - Show disable option */}
          {user.two_fa_enabled && !showDisable && (
            <div className="space-y-4">
              <div className="p-4 rounded-xl bg-emerald-500/5 border border-emerald-500/15 flex items-start gap-3">
                <ShieldCheck className="h-5 w-5 text-emerald-500 shrink-0 mt-0.5" />
                <p className="text-sm text-muted-foreground leading-relaxed">
                  المصادقة الثنائية مُفعلة على حسابك. سيُطلب منك رمز التحقق عند كل تسجيل دخول.
                </p>
              </div>
              <button
                onClick={() => setShowDisable(true)}
                className="btn-danger gap-2"
              >
                <ShieldOff className="h-4 w-4" />
                تعطيل المصادقة الثنائية
              </button>
            </div>
          )}

          {/* Disable 2FA Form */}
          {user.two_fa_enabled && showDisable && (
            <div className="space-y-5 animate-scale-in">
              <div className="p-4 rounded-xl bg-red-500/5 border border-red-500/15 flex items-start gap-3">
                <ShieldAlert className="h-5 w-5 text-red-400 shrink-0 mt-0.5" />
                <p className="text-sm text-muted-foreground leading-relaxed">
                  تعطيل المصادقة الثنائية يقلل أمان حسابك. سيُطلب منك كلمة المرور ورمز التحقق لتأكيد التعطيل.
                </p>
              </div>
              <div>
                <label className="block text-sm font-medium mb-2 text-muted-foreground">كلمة المرور</label>
                <div className="relative">
                  <div className="absolute right-3 top-1/2 -translate-y-1/2">
                    <Lock className="h-4 w-4 text-muted-foreground" />
                  </div>
                  <input
                    type={showDisablePwd ? "text" : "password"}
                    className="input-field pr-10 pl-10"
                    placeholder="أدخل كلمة المرور"
                    value={disablePassword}
                    onChange={(e) => setDisablePassword(e.target.value)}
                  />
                  <button
                    type="button"
                    onClick={() => setShowDisablePwd(!showDisablePwd)}
                    className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground transition-colors"
                  >
                    {showDisablePwd ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
                  </button>
                </div>
              </div>
              <div>
                <label className="block text-sm font-medium mb-2 text-muted-foreground">رمز التحقق (TOTP أو رمز احتياط)</label>
                <input
                  type="text"
                  className="input-field text-center text-xl tracking-[0.3em] font-mono"
                  placeholder="أدخل الرمز"
                  value={disableCode}
                  onChange={(e) => setDisableCode(e.target.value.toUpperCase())}
                  dir="ltr"
                />
              </div>
              <div className="flex gap-3">
                <button
                  onClick={() => {
                    setShowDisable(false);
                    setDisablePassword("");
                    setDisableCode("");
                  }}
                  className="btn-ghost flex-1"
                >
                  إلغاء
                </button>
                <button
                  onClick={handleDisable2FA}
                  disabled={disableLoading || !disablePassword || !disableCode}
                  className="btn-danger flex-1 gap-2"
                >
                  {disableLoading ? <Loader2 className="h-4 w-4 animate-spin" /> : <ShieldOff className="h-4 w-4" />}
                  تعطيل المصادقة الثنائية
                </button>
              </div>
            </div>
          )}
        </div>
      </div>

      {/* ── Active Sessions ── */}
      <div
        className="glass-panel rounded-2xl overflow-hidden animate-slide-in-up"
        style={{ animationDelay: "240ms", animationFillMode: "both" }}
      >
        <div className="p-5 border-b border-border/30">
          <div className="flex items-center gap-3">
            <div className="h-10 w-10 rounded-xl bg-primary/10 flex items-center justify-center">
              <Monitor className="h-5 w-5 text-primary" />
            </div>
            <div>
              <h3 className="font-bold text-base">الجلسات النشطة</h3>
              <p className="text-xs text-muted-foreground mt-0.5">الأجهزة التي سجلت الدخول منها</p>
            </div>
          </div>
        </div>

        <div className="p-4">
          {sessionsLoading ? (
            <div className="flex justify-center py-8">
              <Loader2 className="h-6 w-6 animate-spin text-emerald-500" />
            </div>
          ) : sessions.length === 0 ? (
            <div className="flex flex-col items-center justify-center py-12 text-center">
              <div className="h-14 w-14 rounded-2xl bg-muted/30 flex items-center justify-center mb-3">
                <Monitor className="h-7 w-7 text-muted-foreground/40" />
              </div>
              <p className="text-sm text-muted-foreground">لا توجد جلسات نشطة</p>
            </div>
          ) : (
            <div className="space-y-2 max-h-80 overflow-y-auto">
              {sessions.map((session: any) => {
                const isMobile = /mobile|android|iphone/i.test(session.user_agent || "");
                const DeviceIcon = isMobile ? Smartphone : Monitor;
                const browser = extractBrowser(session.user_agent || "");
                const isCurrent = session.ip_address === "current";

                return (
                  <div
                    key={session.id}
                    className="flex items-center gap-3 p-3.5 rounded-xl bg-background/30 border border-border/30 hover:bg-muted/10 transition-colors"
                  >
                    <div className={`h-10 w-10 rounded-xl flex items-center justify-center shrink-0 ${isMobile ? "bg-purple-500/10" : "bg-blue-500/10"}`}>
                      <DeviceIcon className={`h-5 w-5 ${isMobile ? "text-purple-400" : "text-blue-400"}`} />
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2">
                        <div className="flex items-center gap-1.5">
                          <Chrome className="h-3.5 w-3.5 text-muted-foreground" />
                          <p className="text-sm font-medium truncate">{browser}</p>
                        </div>
                        {isCurrent && (
                          <span className="text-[10px] px-2 py-0.5 rounded-full bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 font-medium">
                            الجلسة الحالية
                          </span>
                        )}
                      </div>
                      <div className="flex items-center gap-1.5 mt-0.5">
                        <Globe className="h-3 w-3 text-muted-foreground" />
                        <p className="text-xs text-muted-foreground truncate" dir="ltr">
                          {session.ip_address} · {new Date(session.created_at).toLocaleDateString("ar-EG", { year: "numeric", month: "short", day: "numeric" })}
                        </p>
                      </div>
                    </div>
                    {!isCurrent && (
                      <button
                        onClick={() => handleRevokeSession(session.id)}
                        className="h-8 w-8 rounded-lg flex items-center justify-center text-muted-foreground hover:text-red-400 hover:bg-red-500/10 transition-colors shrink-0 border border-transparent hover:border-red-500/20"
                        title="إنهاء الجلسة"
                      >
                        <Trash2 className="h-4 w-4" />
                      </button>
                    )}
                  </div>
                );
              })}
            </div>
          )}
        </div>
      </div>

      {/* ── Security Tips ── */}
      <div
        className="glass-panel rounded-2xl p-5 animate-slide-in-up"
        style={{ animationDelay: "320ms", animationFillMode: "both" }}
      >
        <div className="flex items-center gap-3 mb-4">
          <div className="h-10 w-10 rounded-xl bg-yellow-500/10 flex items-center justify-center">
            <Lightbulb className="h-5 w-5 text-yellow-500" />
          </div>
          <div>
            <h3 className="font-bold text-base">نصائح أمنية</h3>
            <p className="text-xs text-muted-foreground mt-0.5">إرشادات لحماية حسابك</p>
          </div>
        </div>

        <div className="space-y-3">
          {[
            { text: "استخدم كلمة مرور قوية وفريدة لحسابك", done: true },
            { text: "فعّل المصادقة الثنائية لحماية إضافية", done: user.two_fa_enabled },
            { text: "احفظ رموز الاحتياط في مكان آمن خارج الإنترنت", done: user.two_fa_enabled },
            { text: "لا تشارك رمز التحقق أو رموز الاحتياط مع أي شخص", done: true },
            { text: "تحقق من نشاط حسابك بانتظام من خلال سجل التدقيق", done: false },
          ].map((tip, i) => (
            <div key={i} className="flex items-center gap-3 p-3 rounded-xl bg-background/30 border border-border/20">
              <div
                className={`h-6 w-6 rounded-full flex items-center justify-center shrink-0 ${
                  tip.done ? "bg-emerald-500/10" : "bg-muted/30"
                }`}
              >
                <CheckCircle className={`h-4 w-4 ${tip.done ? "text-emerald-500" : "text-muted-foreground/40"}`} />
              </div>
              <p className={`text-sm ${tip.done ? "text-foreground" : "text-muted-foreground"}`}>{tip.text}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
