// frontend/src/app/dashboard/admin/kyc/page.tsx
"use client";

import { useEffect, useState } from "react";
import toast from "react-hot-toast";
import {
  FileText,
  Loader2,
  CheckCircle2,
  XCircle,
  Clock,
  User,
  CreditCard,
  Fingerprint,
  CalendarDays,
  ExternalLink,
  Inbox,
  Filter,
  ChevronLeft,
  ChevronRight,
  X,
  AlertTriangle,
  ShieldCheck,
  ShieldAlert,
  Eye,
} from "lucide-react";
import { authGet, authPut } from "@/lib/api";

interface KYCRequest {
  id: number;
  user_id: number;
  username: string;
  email: string;
  full_name: string;
  document_type: string;
  document_number: string;
  document_url: string;
  status: "PENDING" | "APPROVED" | "REJECTED";
  rejection_reason: string;
  created_at: string;
  reviewed_at?: string;
}

const STATUS_TABS = [
  { value: "", label: "الكل", icon: Filter },
  { value: "PENDING", label: "معلق", icon: Clock },
  { value: "APPROVED", label: "مقبول", icon: CheckCircle2 },
  { value: "REJECTED", label: "مرفوض", icon: XCircle },
];

const getDocTypeLabel = (type: string) => {
  switch (type) {
    case "passport": return "جواز سفر";
    case "national_id": return "بطاقة وطنية";
    case "driving_license": return "رخصة قيادة";
    default: return type;
  }
};

export default function AdminKYCPage() {
  const [requests, setRequests] = useState<KYCRequest[]>([]);
  const [loading, setLoading] = useState(true);
  const [statusFilter, setStatusFilter] = useState("");
  const [page, setPage] = useState(1);
  const [total, setTotal] = useState(0);
  const [reviewing, setReviewing] = useState<number | null>(null);
  const [reviewModal, setReviewModal] = useState<{ id: number; action: "APPROVED" | "REJECTED" } | null>(null);
  const [rejectionReason, setRejectionReason] = useState("");
  const limit = 20;
  const totalPages = Math.ceil(total / limit);

  useEffect(() => {
    fetchRequests();
  }, [statusFilter, page]);

  const fetchRequests = async () => {
    setLoading(true);
    try {
      const params = new URLSearchParams();
      if (statusFilter) params.set("status", statusFilter);
      params.set("page", page.toString());
      params.set("limit", limit.toString());
      const res = await authGet(`/api/v1/admin/kyc?${params.toString()}`);
      if (res.ok) {
        const data = await res.json();
        setRequests(Array.isArray(data.data) ? data.data : []);
        setTotal(data.total || 0);
      } else {
        toast.error("فشل تحميل طلبات التحقق");
      }
    } catch {
      toast.error("حدث خطأ في الاتصال");
    } finally {
      setLoading(false);
    }
  };

  const handleReview = async () => {
    if (!reviewModal) return;
    if (reviewModal.action === "REJECTED" && !rejectionReason.trim()) {
      toast.error("يرجى إدخال سبب الرفض");
      return;
    }
    setReviewing(reviewModal.id);
    try {
      const body: any = { status: reviewModal.action };
      if (reviewModal.action === "REJECTED") {
        body.rejection_reason = rejectionReason;
      }
      const res = await authPut(`/api/v1/admin/kyc/${reviewModal.id}/review`, body);
      const data = await res.json();
      if (!res.ok) {
        toast.error(data.error || "فشل مراجعة الطلب");
        return;
      }
      toast.success(data.message || `تم ${reviewModal.action === "APPROVED" ? "قبول" : "رفض"} الطلب بنجاح`);
      setRequests(prev =>
        prev.map(r => r.id === reviewModal.id ? { ...r, status: reviewModal.action, rejection_reason: reviewModal.action === "REJECTED" ? rejectionReason : r.rejection_reason } : r)
      );
      setReviewModal(null);
      setRejectionReason("");
    } catch {
      toast.error("حدث خطأ في الاتصال");
    } finally {
      setReviewing(null);
    }
  };

  const getStatusConfig = (status: string) => {
    switch (status) {
      case "APPROVED":
        return {
          label: "مقبول",
          cls: "bg-emerald-500/10 text-emerald-400 border-emerald-500/20",
          icon: ShieldCheck,
          dotColor: "bg-emerald-500",
        };
      case "PENDING":
        return {
          label: "معلق",
          cls: "bg-yellow-500/10 text-yellow-400 border-yellow-500/20",
          icon: Clock,
          dotColor: "bg-yellow-500",
        };
      case "REJECTED":
        return {
          label: "مرفوض",
          cls: "bg-red-500/10 text-red-400 border-red-500/20",
          icon: ShieldAlert,
          dotColor: "bg-red-500",
        };
      default:
        return {
          label: status,
          cls: "bg-gray-500/10 text-gray-400 border-gray-500/20",
          icon: Clock,
          dotColor: "bg-gray-500",
        };
    }
  };

  return (
    <div className="space-y-6">
      {/* ── Header ── */}
      <div className="animate-slide-in-up">
        <div className="flex items-center gap-3">
          <div className="h-11 w-11 rounded-xl bg-gradient-to-br from-emerald-500 to-teal-600 flex items-center justify-center shadow-lg shadow-emerald-500/20">
            <FileText className="h-6 w-6 text-white" />
          </div>
          <div>
            <h1 className="text-2xl sm:text-3xl font-bold">طلبات التحقق (KYC)</h1>
            <p className="text-muted-foreground text-sm mt-0.5">مراجعة طلبات التحقق من الهوية</p>
          </div>
        </div>
      </div>

      {/* ── Filter Tabs ── */}
      <div className="glass-panel rounded-2xl p-3 animate-slide-in-up" style={{ animationDelay: "80ms" }}>
        <div className="flex items-center gap-2 overflow-x-auto pb-1">
          <div className="h-8 w-8 rounded-lg bg-primary/10 flex items-center justify-center shrink-0">
            <Filter className="h-4 w-4 text-primary" />
          </div>
          {STATUS_TABS.map((tab) => {
            const Icon = tab.icon;
            return (
              <button
                key={tab.value}
                onClick={() => { setStatusFilter(tab.value); setPage(1); }}
                className={`inline-flex items-center gap-1.5 px-4 py-2 rounded-xl text-sm whitespace-nowrap transition-all duration-200 ${
                  statusFilter === tab.value
                    ? "bg-primary/15 text-primary font-semibold shadow-sm shadow-primary/10"
                    : "text-muted-foreground hover:bg-muted/30 hover:text-foreground"
                }`}
              >
                <Icon className="h-3.5 w-3.5" />
                {tab.label}
              </button>
            );
          })}
          {total > 0 && (
            <span className="text-xs text-muted-foreground mr-auto flex items-center gap-1.5 pr-2">
              {total} طلب
            </span>
          )}
        </div>
      </div>

      {/* ── KYC Cards ── */}
      {loading ? (
        <div className="flex flex-col items-center justify-center py-20 gap-3">
          <div className="h-16 w-16 rounded-2xl bg-emerald-500/10 flex items-center justify-center">
            <Loader2 className="h-8 w-8 animate-spin text-emerald-500" />
          </div>
          <p className="text-sm text-muted-foreground">جاري تحميل الطلبات...</p>
        </div>
      ) : requests.length === 0 ? (
        <div className="glass-panel rounded-2xl flex flex-col items-center justify-center py-20 text-center animate-fade-in">
          <div className="h-20 w-20 rounded-2xl bg-muted/20 flex items-center justify-center mb-5">
            <Inbox className="h-10 w-10 text-muted-foreground/30" />
          </div>
          <h3 className="text-lg font-bold mb-2">لا توجد طلبات</h3>
          <p className="text-sm text-muted-foreground max-w-xs">لا توجد طلبات تحقق مطابقة للفلتر المحدد</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
          {requests.map((req, i) => {
            const statusConfig = getStatusConfig(req.status);
            const StatusIcon = statusConfig.icon;
            return (
              <div
                key={req.id}
                className="glass-panel rounded-2xl p-5 animate-slide-in-up"
                style={{ animationDelay: `${Math.min(i * 60, 400)}ms` }}
              >
                {/* Top row: status + user */}
                <div className="flex items-start justify-between mb-4">
                  <div className="flex items-center gap-3">
                    <div className="h-10 w-10 rounded-full bg-gradient-to-br from-emerald-400 to-teal-500 flex items-center justify-center shrink-0">
                      <span className="text-sm font-bold text-white">{req.username?.charAt(0)?.toUpperCase() || "U"}</span>
                    </div>
                    <div>
                      <p className="font-semibold text-sm">{req.username}</p>
                      <p className="text-xs text-muted-foreground" dir="ltr">{req.email}</p>
                    </div>
                  </div>
                  <span className={`inline-flex items-center gap-1.5 text-[11px] px-2.5 py-1 rounded-full font-semibold border ${statusConfig.cls}`}>
                    <span className={`h-1.5 w-1.5 rounded-full ${statusConfig.dotColor}`} />
                    {statusConfig.label}
                  </span>
                </div>

                {/* Details Grid */}
                <div className="grid grid-cols-2 gap-2.5 mb-4">
                  <div className="bg-background/60 rounded-xl p-3 border border-border/20">
                    <div className="flex items-center gap-1.5 mb-1.5">
                      <User className="h-3 w-3 text-muted-foreground" />
                      <p className="text-[10px] text-muted-foreground">الاسم الكامل</p>
                    </div>
                    <p className="text-xs font-semibold">{req.full_name}</p>
                  </div>
                  <div className="bg-background/60 rounded-xl p-3 border border-border/20">
                    <div className="flex items-center gap-1.5 mb-1.5">
                      <CreditCard className="h-3 w-3 text-muted-foreground" />
                      <p className="text-[10px] text-muted-foreground">نوع المستند</p>
                    </div>
                    <p className="text-xs font-semibold">{getDocTypeLabel(req.document_type)}</p>
                  </div>
                  <div className="bg-background/60 rounded-xl p-3 border border-border/20">
                    <div className="flex items-center gap-1.5 mb-1.5">
                      <Fingerprint className="h-3 w-3 text-muted-foreground" />
                      <p className="text-[10px] text-muted-foreground">رقم المستند</p>
                    </div>
                    <p className="text-xs font-semibold font-mono" dir="ltr">{req.document_number}</p>
                  </div>
                  <div className="bg-background/60 rounded-xl p-3 border border-border/20">
                    <div className="flex items-center gap-1.5 mb-1.5">
                      <CalendarDays className="h-3 w-3 text-muted-foreground" />
                      <p className="text-[10px] text-muted-foreground">تاريخ التقديم</p>
                    </div>
                    <p className="text-xs font-semibold">
                      {new Date(req.created_at).toLocaleDateString("ar-EG")}
                    </p>
                  </div>
                </div>

                {/* Document Link */}
                {req.document_url && (
                  <a
                    href={req.document_url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="flex items-center gap-2 p-2.5 rounded-xl bg-blue-500/5 border border-blue-500/10 hover:bg-blue-500/10 transition-all duration-200 mb-4 text-xs text-blue-400"
                  >
                    <Eye className="h-3.5 w-3.5" />
                    عرض المستند
                    <ExternalLink className="h-3 w-3 mr-auto" />
                  </a>
                )}

                {/* Rejection Reason */}
                {req.status === "REJECTED" && req.rejection_reason && (
                  <div className="p-3 rounded-xl bg-red-500/5 border border-red-500/10 mb-4">
                    <div className="flex items-center gap-2 mb-1.5">
                      <AlertTriangle className="h-3.5 w-3.5 text-red-400" />
                      <p className="text-[11px] font-semibold text-red-400">سبب الرفض</p>
                    </div>
                    <p className="text-xs text-muted-foreground">{req.rejection_reason}</p>
                  </div>
                )}

                {/* Actions */}
                {req.status === "PENDING" && (
                  <div className="flex gap-2">
                    <button
                      onClick={() => setReviewModal({ id: req.id, action: "APPROVED" })}
                      disabled={reviewing === req.id}
                      className="flex-1 inline-flex items-center justify-center gap-1.5 px-3 py-2 rounded-xl bg-emerald-500/10 text-emerald-400 text-xs font-semibold border border-emerald-500/20 hover:bg-emerald-500/20 transition-all duration-200"
                    >
                      {reviewing === req.id ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <CheckCircle2 className="h-3.5 w-3.5" />}
                      قبول
                    </button>
                    <button
                      onClick={() => { setReviewModal({ id: req.id, action: "REJECTED" }); setRejectionReason(""); }}
                      disabled={reviewing === req.id}
                      className="flex-1 inline-flex items-center justify-center gap-1.5 px-3 py-2 rounded-xl bg-red-500/10 text-red-400 text-xs font-semibold border border-red-500/20 hover:bg-red-500/20 transition-all duration-200"
                    >
                      {reviewing === req.id ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <XCircle className="h-3.5 w-3.5" />}
                      رفض
                    </button>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}

      {/* ── Pagination ── */}
      {totalPages > 1 && (
        <div className="flex items-center justify-center gap-2 animate-slide-in-up">
          <button
            onClick={() => setPage(p => Math.max(1, p - 1))}
            disabled={page === 1}
            className="btn-ghost text-sm gap-1 disabled:opacity-30 disabled:cursor-not-allowed"
          >
            <ChevronRight className="h-4 w-4" />
            السابق
          </button>
          <div className="flex items-center gap-1 mx-2">
            {Array.from({ length: Math.min(5, totalPages) }, (_, i) => {
              let pageNum: number;
              if (totalPages <= 5) pageNum = i + 1;
              else if (page <= 3) pageNum = i + 1;
              else if (page >= totalPages - 2) pageNum = totalPages - 4 + i;
              else pageNum = page - 2 + i;
              return (
                <button
                  key={pageNum}
                  onClick={() => setPage(pageNum)}
                  className={`w-9 h-9 rounded-xl text-sm font-medium transition-all duration-200 ${
                    pageNum === page
                      ? "bg-primary/15 text-primary shadow-sm shadow-primary/10"
                      : "text-muted-foreground hover:bg-muted/30 hover:text-foreground"
                  }`}
                >
                  {pageNum}
                </button>
              );
            })}
          </div>
          <button
            onClick={() => setPage(p => Math.min(totalPages, p + 1))}
            disabled={page === totalPages}
            className="btn-ghost text-sm gap-1 disabled:opacity-30 disabled:cursor-not-allowed"
          >
            التالي
            <ChevronLeft className="h-4 w-4" />
          </button>
          <span className="text-xs text-muted-foreground pr-3 border-r border-border/30 mr-2">
            صفحة <span className="font-semibold text-foreground">{page}</span> من {totalPages}
          </span>
        </div>
      )}

      {/* ── Review Modal ── */}
      {reviewModal && (
        <div className="fixed inset-0 bg-black/60 z-50 flex items-center justify-center p-4 animate-fade-in" style={{ backdropFilter: "blur(4px)" }}>
          <div className="glass-panel-strong rounded-2xl p-6 w-full max-w-md animate-scale-in">
            <div className="flex items-center justify-between mb-5">
              <div className="flex items-center gap-3">
                <div className={`h-9 w-9 rounded-lg flex items-center justify-center ${
                  reviewModal.action === "APPROVED" ? "bg-emerald-500/10" : "bg-red-500/10"
                }`}>
                  {reviewModal.action === "APPROVED" ? (
                    <CheckCircle2 className="h-5 w-5 text-emerald-500" />
                  ) : (
                    <XCircle className="h-5 w-5 text-red-500" />
                  )}
                </div>
                <h3 className="font-bold">
                  {reviewModal.action === "APPROVED" ? "تأكيد قبول الطلب" : "تأكيد رفض الطلب"}
                </h3>
              </div>
              <button onClick={() => { setReviewModal(null); setRejectionReason(""); }} className="btn-ghost p-1.5 rounded-lg">
                <X className="h-4 w-4" />
              </button>
            </div>

            <p className="text-sm text-muted-foreground mb-4">
              {reviewModal.action === "APPROVED"
                ? "هل أنت متأكد من قبول طلب التحقق هذا؟ سيتم منح المستخدم صلاحيات التحقق الكاملة."
                : "يرجى إدخال سبب الرفض. سيتم إرساله للمستخدم."}
            </p>

            {reviewModal.action === "REJECTED" && (
              <div className="mb-4">
                <label className="block text-sm font-medium mb-2">سبب الرفض *</label>
                <textarea
                  className="input-field min-h-[100px] resize-none"
                  placeholder="أدخل سبب الرفض..."
                  value={rejectionReason}
                  onChange={(e) => setRejectionReason(e.target.value)}
                />
              </div>
            )}

            <div className="flex gap-3">
              <button
                onClick={handleReview}
                disabled={reviewing !== null || (reviewModal.action === "REJECTED" && !rejectionReason.trim())}
                className={`flex-1 inline-flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl text-sm font-semibold transition-all duration-200 disabled:opacity-50 ${
                  reviewModal.action === "APPROVED"
                    ? "bg-emerald-500/20 text-emerald-400 border border-emerald-500/20 hover:bg-emerald-500/30"
                    : "bg-red-500/20 text-red-400 border border-red-500/20 hover:bg-red-500/30"
                }`}
              >
                {reviewing !== null ? <Loader2 className="h-4 w-4 animate-spin" /> : null}
                {reviewModal.action === "APPROVED" ? "تأكيد القبول" : "تأكيد الرفض"}
              </button>
              <button
                onClick={() => { setReviewModal(null); setRejectionReason(""); }}
                className="btn-ghost flex-1"
              >
                إلغاء
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// admin/src/routes/dashboard/kyc/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import {
    ShieldCheck,
    Search,
    Filter,
    Eye,
    CheckCircle2,
    XCircle,
    Clock,
    FileText,
    ChevronRight,
    ChevronLeft,
    AlertCircle,
    Loader2,
    X,
    Send,
    BellRing,
    Image,
    BadgeCheck
  } from 'lucide-svelte';
  import { authGet, authPut, API, getToken } from '$lib/api/client';
  import type { KYCRequest } from '$lib/api/types';
  import { createAdminStream } from '$lib/api/types';

  // ─── Types ───
  interface KYCPageResponse {
    success: boolean;
    data: KYCRequest[];
    pagination: {
      page: number;
      limit: number;
      total: number;
      totalPages: number;
    };
  }

  interface KYCStats {
    pending: number;
    approved: number;
    rejected: number;
  }

  // ─── State ───
  let kycRequests = $state<KYCRequest[]>([]);
  let loading = $state(true);
  let error = $state<string | null>(null);
  let page = $state(1);
  let totalPages = $state(1);
  let totalItems = $state(0);
  const limit = 20;

  let searchQuery = $state('');
  let statusFilter = $state<string>('');
  let stats = $state<KYCStats>({ pending: 0, approved: 0, rejected: 0 });

  // ─── Document preview modal ───
  let previewOpen = $state(false);
  let previewUrl = $state('');
  let previewType = $state<'image' | 'pdf'>('image');
  let previewName = $state('');

  // ─── Reject dialog ───
  let rejectDialogOpen = $state(false);
  let rejectTargetId = $state<number | null>(null);
  let rejectReason = $state('');
  let rejectLoading = $state(false);

  // ─── SSE live indicator ───
  let sseConnected = $state(false);
  let newKycCount = $state(0);
  let newKycFlash = $state(false);

  // ─── Action loading per card ───
  let actionLoadingId = $state<number | null>(null);

  // ─── Document type labels (Arabic) ───
  const docTypeLabels: Record<string, string> = {
    PASSPORT: 'جواز سفر',
    NATIONAL_ID: 'بطاقة وطنية',
    DRIVERS_LICENSE: 'رخصة قيادة',
    UTILITY_BILL: 'فاتورة مرافق',
    BANK_STATEMENT: 'كشف حساب بنكي',
    SELFIE: 'صورة شخصية'
  };

  // ─── Status config ───
  const statusConfig: Record<string, { label: string; pillClass: string; icon: typeof Clock; color: string }> = {
    PENDING: { label: 'قيد المراجعة', pillClass: 'pill-gold', icon: Clock, color: '#f5b544' },
    APPROVED: { label: 'مقبول', pillClass: 'pill-mint', icon: CheckCircle2, color: '#22d3a4' },
    REJECTED: { label: 'مرفوض', pillClass: 'pill-rose', icon: XCircle, color: '#f43f7a' }
  };

  // ─── Helpers ───
  function formatDate(iso: string): string {
    const d = new Date(iso);
    return d.toLocaleDateString('ar-EG', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  }

  function getDocTypeLabel(type: string): string {
    return docTypeLabels[type] || type;
  }

  function detectDocType(url: string): 'image' | 'pdf' {
    const lower = url.toLowerCase();
    if (lower.endsWith('.pdf') || lower.includes('.pdf?')) return 'pdf';
    return 'image';
  }

  function maskDocNumber(num: string): string {
    if (!num || num.length <= 4) return num;
    return num.slice(0, -4).replace(/./g, '•') + num.slice(-4);
  }

  function getStatusConfig(status: string) {
    return statusConfig[status] || statusConfig.PENDING;
  }

  // ─── Fetch KYC requests ───
  async function fetchKYC() {
    loading = true;
    error = null;
    try {
      const params = new URLSearchParams({ page: String(page), limit: String(limit) });
      if (statusFilter) params.set('status', statusFilter);
      if (searchQuery.trim()) params.set('search', searchQuery.trim());

      const res = await authGet(`/api/v1/admin/kyc?${params.toString()}`);
      if (!res.ok) throw new Error('فشل تحميل طباتات KYC');
      const json: KYCPageResponse = await res.json();

      if (json.success) {
        kycRequests = json.data;
        totalPages = json.pagination.totalPages;
        totalItems = json.pagination.total;
      }
    } catch (e: any) {
      error = e.message;
    } finally {
      loading = false;
    }
  }

  // ─── Fetch stats ───
  async function fetchStats() {
    try {
      const res = await authGet('/api/v1/admin/kyc/stats');
      if (!res.ok) return;
      const json = await res.json();
      if (json.success) {
        stats = json.data;
      }
    } catch {
      // non-fatal
    }
  }

  // ─── Approve KYC ───
  async function approveKYC(id: number) {
    actionLoadingId = id;
    try {
      const res = await authPut(`/api/v1/admin/kyc/${id}/review`, { status: 'APPROVED' });
      if (!res.ok) throw new Error('فشل قبول الطلب');
      // Update local state
      kycRequests = kycRequests.map((r) =>
        r.id === id ? { ...r, status: 'APPROVED' } : r
      );
      stats = { ...stats, pending: Math.max(0, stats.pending - 1), approved: stats.approved + 1 };
    } catch (e: any) {
      error = e.message;
    } finally {
      actionLoadingId = null;
    }
  }

  // ─── Open reject dialog ───
  function openRejectDialog(id: number) {
    rejectTargetId = id;
    rejectReason = '';
    rejectDialogOpen = true;
  }

  // ─── Submit rejection ───
  async function submitRejection() {
    if (!rejectTargetId || !rejectReason.trim()) return;
    rejectLoading = true;
    try {
      const res = await authPut(`/api/v1/admin/kyc/${rejectTargetId}/review`, {
        status: 'REJECTED',
        rejection_reason: rejectReason.trim()
      });
      if (!res.ok) throw new Error('فشل رفض الطلب');
      kycRequests = kycRequests.map((r) =>
        r.id === rejectTargetId ? { ...r, status: 'REJECTED', rejection_reason: rejectReason.trim() } : r
      );
      stats = { ...stats, pending: Math.max(0, stats.pending - 1), rejected: stats.rejected + 1 };
      rejectDialogOpen = false;
    } catch (e: any) {
      error = e.message;
    } finally {
      rejectLoading = false;
    }
  }

  // ─── Document preview ───
  function openPreview(kyc: KYCRequest) {
    previewUrl = kyc.document_url;
    previewType = detectDocType(kyc.document_url);
    previewName = `${kyc.full_name} — ${getDocTypeLabel(kyc.document_type)}`;
    previewOpen = true;
  }

  function closePreview() {
    previewOpen = false;
    previewUrl = '';
  }

  // ─── Search debounce ───
  let searchTimeout: ReturnType<typeof setTimeout>;
  $effect(() => {
    searchQuery; // track
    clearTimeout(searchTimeout);
    searchTimeout = setTimeout(() => {
      page = 1;
      fetchKYC();
    }, 400);
  });

  // ─── Status filter change ───
  $effect(() => {
    statusFilter; // track
    page = 1;
    fetchKYC();
  });

  // ─── Page change ───
  $effect(() => {
    page; // track
    fetchKYC();
  });

  // ─── SSE ───
  let eventSource: EventSource | null = null;

  function connectSSE() {
    const es = createAdminStream(['kyc']);
    if (!es) return;

    es.onopen = () => {
      sseConnected = true;
    };

    es.addEventListener('kyc', () => {
      newKycCount++;
      newKycFlash = true;
      setTimeout(() => (newKycFlash = false), 2000);
      // Refresh stats
      fetchStats();
    });

    es.onerror = () => {
      sseConnected = false;
      setTimeout(() => {
        es.close();
        connectSSE();
      }, 5000);
    };

    return es;
  }

  function handleNewKycClick() {
    newKycCount = 0;
    page = 1;
    fetchKYC();
    fetchStats();
  }

  // ─── Lifecycle ───
  onMount(() => {
    (async () => {
      await Promise.all([fetchKYC(), fetchStats()]);
      loading = false;
    })();

    eventSource = connectSSE() ?? null;

    return () => {
      eventSource?.close();
    };
  });

  // ─── Pagination helpers ───
  let pages = $derived.by(() => {
    const arr: number[] = [];
    const start = Math.max(1, page - 2);
    const end = Math.min(totalPages, page + 2);
    for (let i = start; i <= end; i++) arr.push(i);
    return arr;
  });

  // ─── Stat cards config ───
  const statCards = $derived([
    {
      label: 'قيد المراجعة',
      count: stats.pending,
      icon: Clock,
      pillClass: 'pill-gold',
      iconBg: 'rgba(245,181,68,0.12)',
      iconColor: '#f5b544'
    },
    {
      label: 'مقبول',
      count: stats.approved,
      icon: CheckCircle2,
      pillClass: 'pill-mint',
      iconBg: 'rgba(34,211,164,0.12)',
      iconColor: '#22d3a4'
    },
    {
      label: 'مرفوض',
      count: stats.rejected,
      icon: XCircle,
      pillClass: 'pill-rose',
      iconBg: 'rgba(244,63,122,0.12)',
      iconColor: '#f43f7a'
    }
  ]);
</script>

<!-- ─── Document Preview Modal ─── -->
{#if previewOpen}
  <div
    class="fixed inset-0 z-[100] flex items-center justify-center p-4"
    onkeydown={(e) => e.key === 'Escape' && closePreview()}
  >
    <!-- Backdrop -->
    <div
      class="absolute inset-0 bg-black/80 backdrop-blur-md"
      onclick={closePreview}
      role="presentation"
    ></div>

    <!-- Modal content -->
    <div class="relative z-10 w-full max-w-4xl max-h-[90vh] panel overflow-hidden flex flex-col">
      <!-- Header -->
      <div class="flex items-center justify-between p-4 border-b" style="border-color: var(--border-subtle);">
        <div class="flex items-center gap-3">
          <BadgeCheck size={20} style="color: var(--accent-gold);" />
          <div>
            <h3 class="font-bold text-sm">{previewName}</h3>
            <p class="text-xs" style="color: var(--text-tertiary);">معاينة المستند</p>
          </div>
        </div>
        <button
          class="btn-ghost rounded-lg p-2"
          onclick={closePreview}
          aria-label="إغلاق"
        >
          <X size={20} />
        </button>
      </div>

      <!-- Body -->
      <div class="flex-1 overflow-auto p-4 flex items-center justify-center min-h-[300px]">
        {#if previewType === 'pdf'}
          <iframe
            src={previewUrl}
            class="w-full h-[70vh] rounded-xl border"
            style="border-color: var(--border-subtle); background: white;"
            title="معاينة PDF"
          ></iframe>
        {:else}
          <img
            src={previewUrl}
            alt={previewName}
            class="max-w-full max-h-[70vh] rounded-xl object-contain"
            style="border: 1px solid var(--border-subtle);"
          />
        {/if}
      </div>
    </div>
  </div>
{/if}

<!-- ─── Reject Dialog ─── -->
{#if rejectDialogOpen}
  <div
    class="fixed inset-0 z-[100] flex items-center justify-center p-4"
    onkeydown={(e) => e.key === 'Escape' && (rejectDialogOpen = false)}
  >
    <!-- Backdrop -->
    <div
      class="absolute inset-0 bg-black/80 backdrop-blur-md"
      onclick={() => (rejectDialogOpen = false)}
      role="presentation"
    ></div>

    <!-- Dialog -->
    <div class="relative z-10 w-full max-w-md panel p-6 space-y-5">
      <div class="flex items-center justify-between">
        <div class="flex items-center gap-3">
          <div class="flex items-center justify-center w-10 h-10 rounded-xl" style="background: rgba(244,63,122,0.12);">
            <XCircle size={20} style="color: #f43f7a;" />
          </div>
          <h3 class="font-bold">رفض طلب التحقق</h3>
        </div>
        <button
          class="btn-ghost rounded-lg p-1.5"
          onclick={() => (rejectDialogOpen = false)}
          aria-label="إغلاق"
        >
          <X size={18} />
        </button>
      </div>

      <div>
        <label class="block text-xs font-medium mb-2" style="color: var(--text-secondary);">
          سبب الرفض <span style="color: #f43f7a;">*</span>
        </label>
        <textarea
          class="input-field min-h-[120px] resize-y"
          bind:value={rejectReason}
          placeholder="أدخل سبب رفض الطلب..."
          dir="rtl"
        ></textarea>
      </div>

      <div class="flex items-center gap-3 justify-end">
        <button
          class="btn-secondary"
          onclick={() => (rejectDialogOpen = false)}
          disabled={rejectLoading}
        >
          إلغاء
        </button>
        <button
          class="btn-danger flex items-center gap-2"
          onclick={submitRejection}
          disabled={rejectLoading || !rejectReason.trim()}
        >
          {#if rejectLoading}
            <Loader2 size={16} class="animate-spin" />
          {:else}
            <Send size={16} />
          {/if}
          رفض الطلب
        </button>
      </div>
    </div>
  </div>
{/if}

<!-- ─── Main Content ─── -->
<div class="space-y-6">
  <!-- Header -->
  <div class="flex items-center justify-between flex-wrap gap-4">
    <div>
      <h1 class="text-2xl lg:text-3xl font-extrabold text-gold-gradient">التحقق KYC</h1>
      <p class="text-sm mt-1" style="color: var(--text-tertiary);">مراجعة طباتات التحقق من الهوية</p>
    </div>

    <div class="flex items-center gap-3">
      <!-- SSE Live indicator -->
      {#if sseConnected}
        <span class="pill-mint">
          <span class="relative flex h-2 w-2">
            <span class="animate-ping absolute inline-flex h-full w-full rounded-full opacity-75" style="background: #22d3a4;"></span>
            <span class="relative inline-flex rounded-full h-2 w-2" style="background: #22d3a4;"></span>
          </span>
          مباشر
        </span>
      {:else}
        <span class="pill-rose">
          <span class="inline-flex rounded-full h-2 w-2" style="background: #f43f7a;"></span>
          غير متصل
        </span>
      {/if}

      <!-- New KYC indicator -->
      {#if newKycCount > 0}
        <button
          class="pill-gold flex items-center gap-2 cursor-pointer animate-pulse-glow transition-all"
          onclick={handleNewKycClick}
        >
          <BellRing size={14} />
          <span>{newKycCount} طلب جديد</span>
          <ChevronLeft size={14} />
        </button>
      {/if}
    </div>
  </div>

  <!-- Error Banner -->
  {#if error}
    <div class="panel p-4 flex items-center gap-3" style="border-color: rgba(244,63,122,0.3);">
      <AlertCircle size={20} style="color: #f43f7a;" />
      <p class="text-sm" style="color: #f43f7a;">{error}</p>
      <button class="mr-auto btn-ghost text-xs" onclick={() => (error = null)}>إغلاق</button>
    </div>
  {/if}

  <!-- Stats Cards -->
  <div class="grid grid-cols-1 sm:grid-cols-3 gap-5">
    {#each statCards as card}
      <div class="stat-card group">
        <div class="flex items-center justify-between">
          <div class="space-y-1">
            <p class="text-xs font-medium" style="color: var(--text-tertiary);">{card.label}</p>
            <p class="text-3xl font-bold font-mono tabular-nums" style="color: {card.iconColor};">
              {card.count.toLocaleString('ar-EG')}
            </p>
          </div>
          <div
            class="flex items-center justify-center w-12 h-12 rounded-xl transition-transform duration-300 group-hover:scale-110"
            style="background: {card.iconBg};"
          >
            <card.icon size={22} style="color: {card.iconColor};" />
          </div>
        </div>
      </div>
    {/each}
  </div>

  <!-- Search & Filter Bar -->
  <div class="panel p-4">
    <div class="flex flex-col sm:flex-row items-stretch sm:items-center gap-3">
      <!-- Search -->
      <div class="relative flex-1">
        <Search
          size={18}
          class="absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none"
          style="color: var(--text-quaternary);"
        />
        <input
          type="text"
          class="input-field pr-10"
          placeholder="بحث باسم المستخدم أو البريد الإلكتروني..."
          bind:value={searchQuery}
          dir="rtl"
        />
      </div>

      <!-- Status Filter -->
      <div class="relative">
        <Filter
          size={16}
          class="absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none"
          style="color: var(--text-quaternary);"
        />
        <select
          class="input-field pr-9 pl-8 appearance-none cursor-pointer min-w-[160px]"
          bind:value={statusFilter}
          dir="rtl"
        >
          <option value="">كل الحالات</option>
          <option value="PENDING">قيد المراجعة</option>
          <option value="APPROVED">مقبول</option>
          <option value="REJECTED">مرفوض</option>
        </select>
        <ChevronLeft
          size={14}
          class="absolute left-3 top-1/2 -translate-y-1/2 pointer-events-none"
          style="color: var(--text-quaternary);"
        />
      </div>
    </div>
  </div>

  <!-- KYC Cards List -->
  <div class="space-y-4">
    {#if loading}
      <!-- Skeleton -->
      {#each Array(6) as _}
        <div class="panel p-5">
          <div class="flex items-start justify-between">
            <div class="flex items-center gap-4 flex-1">
              <div class="animate-shimmer h-12 w-12 rounded-xl" style="background: rgba(255,255,255,0.06);"></div>
              <div class="space-y-2 flex-1">
                <div class="animate-shimmer h-4 w-40 rounded" style="background: rgba(255,255,255,0.06);"></div>
                <div class="animate-shimmer h-3 w-56 rounded" style="background: rgba(255,255,255,0.04);"></div>
              </div>
            </div>
            <div class="animate-shimmer h-7 w-24 rounded-full" style="background: rgba(255,255,255,0.06);"></div>
          </div>
          <div class="mt-4 flex gap-4">
            <div class="animate-shimmer h-3 w-32 rounded" style="background: rgba(255,255,255,0.04);"></div>
            <div class="animate-shimmer h-3 w-28 rounded" style="background: rgba(255,255,255,0.04);"></div>
            <div class="animate-shimmer h-3 w-36 rounded" style="background: rgba(255,255,255,0.04);"></div>
          </div>
          <div class="mt-4 flex gap-2 justify-end">
            <div class="animate-shimmer h-9 w-24 rounded-xl" style="background: rgba(255,255,255,0.06);"></div>
            <div class="animate-shimmer h-9 w-24 rounded-xl" style="background: rgba(255,255,255,0.06);"></div>
            <div class="animate-shimmer h-9 w-24 rounded-xl" style="background: rgba(255,255,255,0.06);"></div>
          </div>
        </div>
      {/each}
    {:else if kycRequests.length === 0}
      <!-- Empty state -->
      <div class="panel p-16 text-center">
        <ShieldCheck size={48} class="mx-auto mb-4 opacity-20" style="color: var(--text-quaternary);" />
        <p class="text-lg font-bold" style="color: var(--text-secondary);">لا توجد طباتات تحقق</p>
        <p class="text-sm mt-1" style="color: var(--text-quaternary);">
          {statusFilter || searchQuery ? 'جرّب تغيير عوامل التصفية' : 'ستظهر طباتات التحقق هنا عند تقديمها'}
        </p>
      </div>
    {:else}
      {#each kycRequests as kyc (kyc.id)}
        {@const sc = getStatusConfig(kyc.status)}
        {@const isPending = kyc.status === 'PENDING'}
        {@const isActing = actionLoadingId === kyc.id}

        <div class="panel p-5 transition-all duration-300 hover:border-white/[0.12]">
          <!-- Top row: user info + status pill -->
          <div class="flex items-start justify-between gap-4">
            <div class="flex items-center gap-4 min-w-0">
              <!-- Avatar -->
              <div
                class="flex items-center justify-center w-12 h-12 rounded-xl shrink-0 font-bold text-sm"
                style="background: {sc.iconBg}; color: {sc.iconColor};"
              >
                {kyc.full_name?.charAt(0) || kyc.user?.username?.charAt(0) || '?'}
              </div>

              <div class="min-w-0">
                <h3 class="font-bold text-sm truncate">{kyc.full_name || kyc.user?.username || '—'}</h3>
                <p class="text-xs mt-0.5 truncate" style="color: var(--text-tertiary);">
                  {kyc.user?.email || '—'}
                </p>
              </div>
            </div>

            <span class={sc.pillClass}>
              <sc.icon size={12} />
              {sc.label}
            </span>
          </div>

          <!-- Details row -->
          <div class="mt-4 flex flex-wrap gap-x-6 gap-y-2 text-xs" style="color: var(--text-secondary);">
            <div class="flex items-center gap-1.5">
              <FileText size={13} style="color: var(--text-quaternary);" />
              <span>{getDocTypeLabel(kyc.document_type)}</span>
            </div>
            <div class="flex items-center gap-1.5 font-mono">
              <Image size={13} style="color: var(--text-quaternary);" />
              <span>{maskDocNumber(kyc.document_number)}</span>
            </div>
            <div class="flex items-center gap-1.5">
              <Clock size={13} style="color: var(--text-quaternary);" />
              <span>{formatDate(kyc.created_at)}</span>
            </div>
          </div>

          <!-- Rejection reason (if rejected) -->
          {#if kyc.status === 'REJECTED' && kyc.rejection_reason}
            <div
              class="mt-3 p-3 rounded-lg text-xs"
              style="background: rgba(244,63,122,0.06); border: 1px solid rgba(244,63,122,0.12); color: var(--text-secondary);"
            >
              <span class="font-semibold" style="color: #f43f7a;">سبب الرفض: </span>
              {kyc.rejection_reason}
            </div>
          {/if}

          <!-- Actions row -->
          <div class="mt-4 flex items-center justify-between flex-wrap gap-2">
            <button
              class="btn-ghost flex items-center gap-2 text-xs"
              onclick={() => openPreview(kyc)}
            >
              <Eye size={15} />
              معاينة المستند
            </button>

            {#if isPending}
              <div class="flex items-center gap-2">
                <button
                  class="btn-buy flex items-center gap-1.5 text-xs"
                  onclick={() => approveKYC(kyc.id)}
                  disabled={isActing}
                >
                  {#if isActing}
                    <Loader2 size={14} class="animate-spin" />
                  {:else}
                    <CheckCircle2 size={14} />
                  {/if}
                  قبول
                </button>
                <button
                  class="btn-danger flex items-center gap-1.5 text-xs"
                  onclick={() => openRejectDialog(kyc.id)}
                  disabled={isActing}
                >
                  <XCircle size={14} />
                  رفض
                </button>
              </div>
            {/if}
          </div>
        </div>
      {/each}
    {/if}
  </div>

  <!-- Pagination -->
  {#if totalPages > 1}
    <div class="panel p-4 flex items-center justify-between flex-wrap gap-3">
      <p class="text-xs" style="color: var(--text-tertiary);">
        إجمالي {totalItems.toLocaleString('ar-EG')} طلب · صفحة {page} من {totalPages}
      </p>

      <div class="flex items-center gap-1">
        <button
          class="btn-ghost p-2 rounded-lg"
          onclick={() => (page = Math.max(1, page - 1))}
          disabled={page <= 1}
        >
          <ChevronRight size={18} />
        </button>

        {#if pages[0] > 1}
          <button class="btn-ghost px-3 py-1.5 rounded-lg text-xs" onclick={() => (page = 1)}>1</button>
          {#if pages[0] > 2}
            <span class="px-1 text-xs" style="color: var(--text-quaternary);">...</span>
          {/if}
        {/if}

        {#each pages as p}
          <button
            class="px-3 py-1.5 rounded-lg text-xs font-medium transition-all cursor-pointer"
            class:btn-primary={p === page}
            class:btn-ghost={p !== page}
            onclick={() => (page = p)}
            disabled={p === page}
          >
            {p}
          </button>
        {/each}

        {#if pages[pages.length - 1] < totalPages}
          {#if pages[pages.length - 1] < totalPages - 1}
            <span class="px-1 text-xs" style="color: var(--text-quaternary);">...</span>
          {/if}
          <button
            class="btn-ghost px-3 py-1.5 rounded-lg text-xs"
            onclick={() => (page = totalPages)}
          >
            {totalPages}
          </button>
        {/if}

        <button
          class="btn-ghost p-2 rounded-lg"
          onclick={() => (page = Math.min(totalPages, page + 1))}
          disabled={page >= totalPages}
        >
          <ChevronLeft size={18} />
        </button>
      </div>
    </div>
  {/if}
</div>
