// admin/src/app/dashboard/ads/page.tsx
"use client";

import { useEffect, useState } from "react";
import toast from "react-hot-toast";
import { Plus, Pencil, Trash2, Eye, EyeOff } from "lucide-react";

interface Ad {
  id: number;
  title: string;
  link: string;
  image_url: string;
  position: string;
  active: boolean;
  sort_order: number;
  created_at: string;
  updated_at: string;
}

const POSITIONS = [
  { value: "hero", label: "الهيرو (أعلى الصفحة)" },
  { value: "section", label: "قسم داخلي" },
  { value: "bottom", label: "أسفل الصفحة" },
];

const emptyAd = { title: "", link: "", image_url: "", position: "hero", active: true, sort_order: 0 };

export default function AdsPage() {
  const [ads, setAds] = useState<Ad[]>([]);
  const [loading, setLoading] = useState(true);
  const [showForm, setShowForm] = useState(false);
  const [editing, setEditing] = useState<Ad | null>(null);
  const [form, setForm] = useState<{ title: string; link: string; image_url: string; position: string; active: boolean; sort_order: number }>(emptyAd);

  const fetchAds = async () => {
    const token = localStorage.getItem("token");
    const res = await fetch("https://api.eg-money.local/api/admin/ads", {
      headers: { Authorization: `Bearer ${token}` },
    });
    if (res.ok) {
      const data = await res.json();
      setAds(data);
    }
    setLoading(false);
  };

  useEffect(() => { fetchAds(); }, []);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const token = localStorage.getItem("token");
    const url = editing
      ? `https://api.eg-money.local/api/admin/ads/${editing.id}`
      : "https://api.eg-money.local/api/admin/ads";
    const method = editing ? "PUT" : "POST";

    const res = await fetch(url, {
      method,
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` },
      body: JSON.stringify(form),
    });

    if (res.ok) {
      toast.success(editing ? "تم تحديث الإعلان" : "تم إضافة الإعلان");
      setShowForm(false);
      setEditing(null);
      setForm(emptyAd);
      fetchAds();
    } else {
      const err = await res.json();
      toast.error(err.error || "فشل العملية");
    }
  };

  const handleDelete = async (id: number) => {
    if (!confirm("هل أنت متأكد من حذف هذا الإعلان؟")) return;
    const token = localStorage.getItem("token");
    const res = await fetch(`https://api.eg-money.local/api/admin/ads/${id}`, {
      method: "DELETE",
      headers: { Authorization: `Bearer ${token}` },
    });
    if (res.ok) {
      toast.success("تم حذف الإعلان");
      fetchAds();
    } else {
      toast.error("فشل الحذف");
    }
  };

  const handleEdit = (ad: Ad) => {
    setEditing(ad);
    setForm({ title: ad.title, link: ad.link, image_url: ad.image_url, position: ad.position, active: ad.active, sort_order: ad.sort_order });
    setShowForm(true);
  };

  if (loading) return <div className="flex items-center justify-center py-20"><span className="spinner h-8 w-8" /></div>;

  return (
    <div>
      <div className="flex items-center justify-between mb-8">
        <h1 className="text-2xl font-bold">إدارة الإعلانات التسويقية</h1>
        <button onClick={() => { setEditing(null); setForm(emptyAd); setShowForm(true); }} className="btn-primary gap-2">
          <Plus className="h-4 w-4" /> إضافة إعلان
        </button>
      </div>

      {showForm && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60" onClick={() => setShowForm(false)}>
          <div className="glass-panel-strong rounded-2xl p-6 w-full max-w-lg mx-4" onClick={e => e.stopPropagation()}>
            <h2 className="text-lg font-bold mb-4">{editing ? "تعديل الإعلان" : "إضافة إعلان جديد"}</h2>
            <form onSubmit={handleSubmit} className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-muted-foreground mb-1">العنوان</label>
                <input className="input-field" value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} required />
              </div>
              <div>
                <label className="block text-sm font-medium text-muted-foreground mb-1">الرابط</label>
                <input className="input-field" value={form.link} onChange={e => setForm({ ...form, link: e.target.value })} placeholder="https://" />
              </div>
              <div>
                <label className="block text-sm font-medium text-muted-foreground mb-1">رابط الصورة</label>
                <input className="input-field" value={form.image_url} onChange={e => setForm({ ...form, image_url: e.target.value })} placeholder="https://example.com/banner.jpg" />
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-muted-foreground mb-1">الموضع</label>
                  <select className="input-field" value={form.position} onChange={e => setForm({ ...form, position: e.target.value })}>
                    {POSITIONS.map(p => <option key={p.value} value={p.value}>{p.label}</option>)}
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-medium text-muted-foreground mb-1">الترتيب</label>
                  <input type="number" className="input-field" value={form.sort_order} onChange={e => setForm({ ...form, sort_order: parseInt(e.target.value) || 0 })} />
                </div>
              </div>
              <label className="flex items-center gap-2 cursor-pointer">
                <input type="checkbox" checked={form.active} onChange={e => setForm({ ...form, active: e.target.checked })} className="rounded" />
                <span className="text-sm">نشط</span>
              </label>
              <div className="flex gap-3 pt-2">
                <button type="submit" className="btn-primary flex-1">{editing ? "تحديث" : "إضافة"}</button>
                <button type="button" onClick={() => setShowForm(false)} className="btn-ghost flex-1">إلغاء</button>
              </div>
            </form>
          </div>
        </div>
      )}

      <div className="glass-panel rounded-2xl overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-border/50 text-muted-foreground text-xs">
                <th className="text-right p-4">العنوان</th>
                <th className="text-right p-4 hidden md:table-cell">الموضع</th>
                <th className="text-right p-4 hidden md:table-cell">الترتيب</th>
                <th className="text-right p-4">الحالة</th>
                <th className="text-right p-4">الإجراءات</th>
              </tr>
            </thead>
            <tbody>
              {ads.length === 0 && (
                <tr><td colSpan={5} className="p-8 text-center text-muted-foreground">لا توجد إعلانات. أضف أول إعلان الآن.</td></tr>
              )}
              {ads.map(ad => (
                <tr key={ad.id} className="border-b border-border/20 card-hover">
                  <td className="p-4">
                    <div className="flex items-center gap-3">
                      {ad.image_url && (
                        <img src={ad.image_url} alt="" className="h-10 w-16 rounded-lg object-cover bg-muted" onError={e => { (e.target as HTMLImageElement).style.display = "none"; }} />
                      )}
                      <div>
                        <p className="font-medium">{ad.title}</p>
                        {ad.link && <p className="text-[10px] text-muted-foreground truncate max-w-[200px]">{ad.link}</p>}
                      </div>
                    </div>
                  </td>
                  <td className="p-4 hidden md:table-cell">
                    <span className="text-xs bg-muted/50 px-2 py-1 rounded-lg">{POSITIONS.find(p => p.value === ad.position)?.label || ad.position}</span>
                  </td>
                  <td className="p-4 hidden md:table-cell text-muted-foreground">{ad.sort_order}</td>
                  <td className="p-4">
                    {ad.active ? (
                      <span className="flex items-center gap-1 text-xs text-emerald-500"><Eye className="h-3 w-3" /> نشط</span>
                    ) : (
                      <span className="flex items-center gap-1 text-xs text-muted-foreground"><EyeOff className="h-3 w-3" /> مخفي</span>
                    )}
                  </td>
                  <td className="p-4">
                    <div className="flex items-center gap-2">
                      <button onClick={() => handleEdit(ad)} className="btn-ghost p-1.5 text-xs"><Pencil className="h-3.5 w-3.5" /></button>
                      <button onClick={() => handleDelete(ad.id)} className="btn-ghost p-1.5 text-xs text-red-500 hover:bg-red-500/10"><Trash2 className="h-3.5 w-3.5" /></button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}

// frontend/src/routes/dashboard/admin/ads/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { authGet, parseApiResponse } from '$lib/api/client';
  import { toasts } from '$lib/stores/toast';
  import { formatDate } from '$lib/utils/format';
  import { Megaphone, Plus, Edit, Trash2, Eye, EyeOff } from 'lucide-svelte';

  let ads = $state<any[]>([]);
  let loading = $state(true);
  let showForm = $state(false);
  let editing = $state<any>(null);

  let title = $state('');
  let content = $state('');
  let position = $state('top_banner');
  let active = $state(true);

  onMount(() => {
(async () => {
    await loadAds();
    loading = false;
  
  })();
});

  async function loadAds() {
    try {
      const res = await authGet('/api/v1/admin/ads');
      const data = await parseApiResponse<any>(res);
      ads = data?.ads || data || [];
    } catch {
      ads = [];
    }
  }

  function resetForm() {
    title = '';
    content = '';
    position = 'top_banner';
    active = true;
    editing = null;
  }

  async function saveAd() {
    if (!title.trim() || !content.trim()) {
      toasts.error('العنوان والمحتوى مطلوبان');
      return;
    }
    try {
      const { authPost, authPut } = await import('$lib/api/client');
      const body = { title, content, position, active };
      if (editing) {
        await authPut(`/api/v1/admin/ads/${editing.id}`, body);
        toasts.success('تم تحديث الإعلان');
      } else {
        await authPost('/api/v1/admin/ads', body);
        toasts.success('تم إنشاء الإعلان');
      }
      resetForm();
      showForm = false;
      loadAds();
    } catch {
      toasts.error('فشل الحفظ');
    }
  }

  async function deleteAd(id: number) {
    if (!confirm('هل أنت متأكد من الحذف؟')) return;
    try {
      const { authDelete } = await import('$lib/api/client');
      await authDelete(`/api/v1/admin/ads/${id}`);
      toasts.success('تم الحذف');
      loadAds();
    } catch {
      toasts.error('فشل الحذف');
    }
  }

  function editAd(ad: any) {
    editing = ad;
    title = ad.title;
    content = ad.content;
    position = ad.position;
    active = ad.active;
    showForm = true;
  }
</script>

<svelte:head><title>الإعلانات — لوحة الإدارة</title></svelte:head>

<div class="space-y-5">
  <div class="flex items-center justify-between">
    <div>
      <h1 class="text-2xl sm:text-3xl font-bold text-white">الإعلانات</h1>
      <p class="text-sm text-slate-400 mt-1">إدارة الإعلانات والبانرات</p>
    </div>
    <button onclick={() => { resetForm(); showForm = true; }} class="btn-primary">
      <Plus size={16} /> إعلان جديد
    </button>
  </div>

  {#if showForm}
    <div class="panel p-6">
      <h3 class="text-base font-bold text-white mb-4">{editing ? 'تعديل إعلان' : 'إعلان جديد'}</h3>
      <form onsubmit={(e) => { e.preventDefault(); saveAd(); }} class="space-y-4">
        <div>
          <label class="input-label" for="title">العنوان</label>
          <input id="title" bind:value={title} type="text" class="input" placeholder="عنوان الإعلان" />
        </div>
        <div>
          <label class="input-label" for="content">المحتوى</label>
          <textarea id="content" bind:value={content} rows="3" class="input resize-none" placeholder="نص الإعلان"></textarea>
        </div>
        <div class="grid sm:grid-cols-2 gap-4">
          <div>
            <label class="input-label" for="position">الموضع</label>
            <select id="position" bind:value={position} class="input">
              <option value="top_banner">بانر علوي</option>
              <option value="sidebar">الشريط الجانبي</option>
              <option value="popup">نافذة منبثقة</option>
              <option value="notification">إشعار</option>
            </select>
          </div>
          <div>
            <span class="input-label">الحالة</span>
            <label class="flex items-center gap-2 input cursor-pointer">
              <input type="checkbox" bind:checked={active} class="w-4 h-4" />
              <span class="text-sm">نشط</span>
            </label>
          </div>
        </div>
        <div class="flex gap-2">
          <button type="submit" class="btn-primary">{editing ? 'تحديث' : 'إنشاء'}</button>
          <button type="button" onclick={() => { resetForm(); showForm = false; }} class="btn-secondary">إلغاء</button>
        </div>
      </form>
    </div>
  {/if}

  <div class="panel overflow-hidden">
    {#if loading}
      <div class="p-6 space-y-3">
        {#each Array(3) as _}<div class="h-20 rounded-xl bg-white/5 animate-shimmer"></div>{/each}
      </div>
    {:else if ads.length === 0}
      <div class="py-16 text-center text-slate-500">
        <Megaphone size={40} class="mx-auto mb-3 opacity-30" />
        <p class="text-sm">لا توجد إعلانات</p>
      </div>
    {:else}
      <div class="divide-y divide-white/5">
        {#each ads as ad}
          <div class="px-5 py-4 hover:bg-white/[0.02]">
            <div class="flex items-start justify-between gap-4">
              <div class="flex-1 min-w-0">
                <div class="flex items-center gap-2 mb-1">
                  <h3 class="text-sm font-bold text-white">{ad.title}</h3>
                  <span class="pill {ad.active ? 'pill-mint' : 'pill-rose'} text-[10px]">
                    {ad.active ? 'نشط' : 'موقوف'}
                  </span>
                  <span class="pill-gold text-[10px]">{ad.position}</span>
                </div>
                <p class="text-xs text-slate-400 line-clamp-2">{ad.content}</p>
                <p class="text-[10px] text-slate-500 mt-1">{formatDate(ad.created_at)}</p>
              </div>
              <div class="flex gap-1">
                <button onclick={() => editAd(ad)} class="p-1.5 rounded-lg text-slate-400 hover:bg-white/5 hover:text-white" aria-label="تعديل">
                  <Edit size={14} />
                </button>
                <button onclick={() => deleteAd(ad.id)} class="p-1.5 rounded-lg text-accent-rose hover:bg-accent-rose/10" aria-label="حذف">
                  <Trash2 size={14} />
                </button>
              </div>
            </div>
          </div>
        {/each}
      </div>
    {/if}
  </div>
</div>
