// admin/src/app/dashboard/kyc/page.tsx
"use client";

import { useEffect, useState } from "react";
import toast from "react-hot-toast";
import { Check, X, Search } from "lucide-react";
import PromptDialog from "@/components/PromptDialog";
import { authGet, authPut } from "@/lib/api";

export default function AdminKYCPage() {
  const [requests, setRequests] = useState<any[]>([]);
  const [search, setSearch] = useState("");
  const [loading, setLoading] = useState(true);
  const [rejectTarget, setRejectTarget] = useState<number | null>(null);

  const fetchKYC = () => {
    const token = localStorage.getItem("token");
    if (!token) return;
    setLoading(true);
    authGet("/api/v1/admin/kyc")
      .then(r => r.json()).then(d => {
        const data = d.data;
        setRequests(Array.isArray(data) ? data : []);
      }).catch(() => {})
      .finally(() => setLoading(false));
  };

  useEffect(() => { fetchKYC(); }, []);

  const handleReview = async (id: number, status: string, rejectionReason = "") => {
    try {
      const body: any = { status };
      if (status === "REJECTED" && rejectionReason) {
        body.rejection_reason = rejectionReason;
      }
      const res = await authPut(`/api/v1/admin/kyc/${id}/review`, body);
      const data = await res.json();
      if (!res.ok) { toast.error(data.error || "فشل المراجعة"); return; }
      toast.success(status === "APPROVED" ? "تم توثيق المستخدم" : "تم رفض الطلب");
      fetchKYC();
    } catch { toast.error("حدث خطأ في الاتصال"); }
  };

  const filtered = requests.filter(r =>
    r.user?.username?.toLowerCase().includes(search.toLowerCase()) ||
    r.user?.email?.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold">طلبات KYC</h1>
        <p className="text-muted-foreground mt-1">مراجعة طلبات توثيق الهوية</p>
      </div>

      <div className="relative max-w-md">
        <Search className="absolute right-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
        <input type="text" className="input-field pr-10" placeholder="بحث..." value={search} onChange={e => setSearch(e.target.value)} />
      </div>

      <div className="glass-panel rounded-2xl overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-border/50">
                <th className="text-right p-4 text-muted-foreground font-medium">المستخدم</th>
                <th className="text-right p-4 text-muted-foreground font-medium">البريد</th>
                <th className="text-right p-4 text-muted-foreground font-medium">نوع الهوية</th>
                <th className="text-right p-4 text-muted-foreground font-medium">الحالة</th>
                <th className="text-right p-4 text-muted-foreground font-medium">تاريخ الطلب</th>
                <th className="text-right p-4 text-muted-foreground font-medium">إجراءات</th>
              </tr>
            </thead>
            <tbody>
              {filtered.map((req: any, i: number) => (
                <tr key={i} className="border-b border-border/20 hover:bg-muted/10 transition-all">
                  <td className="p-4 font-medium">{req.user?.username || req.username || "—"}</td>
                  <td className="p-4 text-muted-foreground">{req.user?.email || req.email || "—"}</td>
                  <td className="p-4">{req.document_type || "—"}</td>
                  <td className="p-4">
                    <span className={`text-[11px] px-2 py-0.5 rounded font-medium ${
                      req.status === "APPROVED" ? "bg-emerald-500/10 text-emerald-500" :
                      req.status === "PENDING" ? "bg-yellow-500/10 text-yellow-500" :
                      "bg-red-500/10 text-red-500"
                    }`}>
                      {req.status === "APPROVED" ? "موثق" : req.status === "PENDING" ? "قيد المراجعة" : "مرفوض"}
                    </span>
                  </td>
                  <td className="p-4 text-muted-foreground text-xs">{req.created_at ? new Date(req.created_at).toLocaleDateString("ar-EG") : "—"}</td>
                  <td className="p-4">
                    <div className="flex items-center gap-2">
                      {req.status === "PENDING" && (
                        <>
                          <button onClick={() => handleReview(req.id, "APPROVED")} className="p-2 rounded-lg bg-emerald-500/10 text-emerald-500 hover:bg-emerald-500/20 transition-all" title="موافقة"><Check className="h-4 w-4" /></button>
                          <button onClick={() => setRejectTarget(req.id)} className="p-2 rounded-lg bg-red-500/10 text-red-500 hover:bg-red-500/20 transition-all" title="رفض"><X className="h-4 w-4" /></button>
                        </>
                      )}
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        {!loading && filtered.length === 0 && <div className="text-center py-12 text-muted-foreground">لا توجد طلبات KYC</div>}
      </div>

      {/* Rejection Prompt Dialog */}
      <PromptDialog
        open={rejectTarget !== null}
        title="رفض طلب التحقق"
        message="أدخل سبب الرفض. سيتم إرسال هذا السبب للمستخدم."
        placeholder="مثال: الصورة غير واضحة"
        confirmLabel="رفض"
        cancelLabel="إلغاء"
        onConfirm={(reason) => {
          if (rejectTarget) handleReview(rejectTarget, "REJECTED", reason);
          setRejectTarget(null);
        }}
        onCancel={() => setRejectTarget(null)}
      />
    </div>
  );
}

// frontend/src/routes/dashboard/admin/kyc/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { authGet, parseApiResponse } from '$lib/api/client';
  import { formatDate } from '$lib/utils/format';
  import { toasts } from '$lib/stores/toast';
  import { Check, X, FileText, Clock, AlertCircle } from 'lucide-svelte';

  let requests = $state<any[]>([]);
  let loading = $state(true);
  let filter = $state<'pending' | 'approved' | 'rejected' | 'all'>('pending');

  onMount(() => {
(async () => {
    await loadRequests();
    loading = false;
  
  })();
});

  async function loadRequests() {
    try {
      const res = await authGet(`/api/v1/admin/kyc?status=${filter}`);
      const data = await parseApiResponse<any>(res);
      requests = data?.requests || data || [];
    } catch {
      requests = [];
    }
  }

  $effect(() => {
    loadRequests();
  });

  async function approve(id: number) {
    try {
      const { authPost } = await import('$lib/api/client');
      await authPost(`/api/v1/admin/kyc/${id}/approve`);
      toasts.success('تمت الموافقة على الطلب');
      loadRequests();
    } catch {
      toasts.error('فشل الموافقة');
    }
  }

  async function reject(id: number) {
    const reason = prompt('سبب الرفض:');
    if (!reason) return;
    try {
      const { authPost } = await import('$lib/api/client');
      await authPost(`/api/v1/admin/kyc/${id}/reject`, { reason });
      toasts.success('تم رفض الطلب');
      loadRequests();
    } catch {
      toasts.error('فشل الرفض');
    }
  }
</script>

<svelte:head><title>طلبات التحقق — لوحة الإدارة</title></svelte:head>

<div class="space-y-5">
  <div>
    <h1 class="text-2xl sm:text-3xl font-bold text-white">طلبات التحقق (KYC)</h1>
    <p class="text-sm text-slate-400 mt-1">مراجعة طلبات التحقق من الهوية</p>
  </div>

  <div class="flex gap-1">
    {#each [{ k: 'pending', l: 'معلّقة' }, { k: 'approved', l: 'موافق عليها' }, { k: 'rejected', l: 'مرفوضة' }, { k: 'all', l: 'الكل' }] as f}
      <button
        onclick={() => (filter = f.k as any)}
        class="px-3 py-1.5 rounded-lg text-xs font-medium transition-colors {filter === f.k ? 'bg-accent-gold/15 text-accent-gold' : 'bg-white/[0.03] text-slate-400 hover:bg-white/5'}"
      >
        {f.l}
      </button>
    {/each}
  </div>

  {#if loading}
    <div class="space-y-3">
      {#each Array(3) as _}<div class="panel p-6 animate-shimmer h-32"></div>{/each}
    </div>
  {:else if requests.length === 0}
    <div class="panel py-16 text-center text-slate-500">
      <FileText size={40} class="mx-auto mb-3 opacity-30" />
      <p class="text-sm">لا توجد طلبات</p>
    </div>
  {:else}
    <div class="space-y-3">
      {#each requests as r}
        <div class="panel p-5">
          <div class="flex items-start justify-between gap-4 mb-4">
            <div>
              <div class="flex items-center gap-2 mb-1">
                <h3 class="text-base font-bold text-white">{r.full_name}</h3>
                <span class="pill-gold">{r.document_type}</span>
              </div>
              <p class="text-xs text-slate-400">رقم المستند: <span class="font-mono">{r.document_number}</span></p>
              <p class="text-xs text-slate-400 mt-1">تاريخ الإرسال: {formatDate(r.created_at)}</p>
            </div>
            <span class="pill {r.status === 'APPROVED' ? 'pill-mint' : r.status === 'PENDING' ? 'pill-gold' : 'pill-rose'}">
              {r.status === 'APPROVED' ? 'موافق' : r.status === 'PENDING' ? 'معلّق' : 'مرفوض'}
            </span>
          </div>

          {#if r.document_url}
            <div class="mb-4">
              <a href={r.document_url} target="_blank" class="block panel p-3 bg-ink-950/60 hover:border-accent-gold/30 transition-colors">
                <div class="flex items-center gap-2 text-xs text-slate-300">
                  <FileText size={14} />
                  عرض المستند المرفق
                </div>
              </a>
            </div>
          {/if}

          {#if r.status === 'PENDING'}
            <div class="flex gap-2">
              <button onclick={() => approve(r.id)} class="btn-buy text-xs py-2">
                <Check size={14} /> موافقة
              </button>
              <button onclick={() => reject(r.id)} class="btn-sell text-xs py-2">
                <X size={14} /> رفض
              </button>
            </div>
          {/if}

          {#if r.rejection_reason}
            <div class="panel p-3 bg-accent-rose/5 border-accent-rose/20 mt-3">
              <p class="text-xs text-slate-300"><span class="font-bold text-accent-rose">سبب الرفض:</span> {r.rejection_reason}</p>
            </div>
          {/if}
        </div>
      {/each}
    </div>
  {/if}
</div>
