// admin/src/app/dashboard/fees/page.tsx
"use client";

import { useEffect, useState } from "react";
import toast from "react-hot-toast";
import { Percent, Save, RefreshCw, Info, Shield, ShieldCheck, TrendingUp, TrendingDown, DollarSign } from "lucide-react";
import { authGet, authPut } from "@/lib/api";

interface FeeSchedule {
  id: number;
  user_type: string;
  order_type: string;
  maker_fee: number;
  taker_fee: number;
  min_fee: number;
  created_at: string;
  updated_at: string;
}

export default function AdminFeesPage() {
  const [fees, setFees] = useState<FeeSchedule[]>([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState<number | null>(null);
  const [editValues, setEditValues] = useState<Record<number, { maker_fee: string; taker_fee: string; min_fee: string }>>({});
  const [changedIds, setChangedIds] = useState<Set<number>>(new Set());

  const fetchFees = async () => {
    setLoading(true);
    try {
      const res = await authGet("/api/v1/admin/fees");
      if (res.ok) {
        const data = await res.json();
        setFees(data.data || []);
        const ev: Record<number, { maker_fee: string; taker_fee: string; min_fee: string }> = {};
        (data.data || []).forEach((f: FeeSchedule) => {
          ev[f.id] = {
            maker_fee: (f.maker_fee * 100).toFixed(4),
            taker_fee: (f.taker_fee * 100).toFixed(4),
            min_fee: f.min_fee.toFixed(8),
          };
        });
        setEditValues(ev);
        setChangedIds(new Set());
      }
    } catch {
      toast.error("فشل تحميل جدول الرسوم");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchFees();
  }, []);

  const handleSave = async (feeId: number) => {
    const vals = editValues[feeId];
    if (!vals) return;

    const makerFee = parseFloat(vals.maker_fee) / 100;
    const takerFee = parseFloat(vals.taker_fee) / 100;
    const minFee = parseFloat(vals.min_fee);

    if (isNaN(makerFee) || isNaN(takerFee) || isNaN(minFee)) {
      toast.error("يرجى إدخال قيم صحيحة");
      return;
    }
    if (makerFee < 0 || takerFee < 0 || minFee < 0) {
      toast.error("لا يمكن أن تكون القيم سالبة");
      return;
    }
    if (makerFee > 1 || takerFee > 1) {
      toast.error("نسبة الرسوم لا يمكن أن تتجاوز 100%");
      return;
    }

    setSaving(feeId);
    try {
      const res = await authPut(`/api/v1/admin/fees/${feeId}`, {
        maker_fee: makerFee,
        taker_fee: takerFee,
        min_fee: minFee,
      });
      const data = await res.json();
      if (!res.ok) {
        toast.error(data.error || "فشل تحديث الرسوم");
        return;
      }
      toast.success("تم تحديث جدول الرسوم بنجاح");
      fetchFees();
    } catch {
      toast.error("حدث خطأ في الاتصال");
    } finally {
      setSaving(null);
    }
  };

  const handleFieldChange = (feeId: number, field: string, value: string) => {
    setEditValues(prev => ({
      ...prev,
      [feeId]: { ...prev[feeId], [field]: value },
    }));
    // Check if value differs from original
    const fee = fees.find(f => f.id === feeId);
    if (fee) {
      const originalValue = field === "maker_fee"
        ? (fee.maker_fee * 100).toFixed(4)
        : field === "taker_fee"
          ? (fee.taker_fee * 100).toFixed(4)
          : fee.min_fee.toFixed(8);
      if (value !== originalValue) {
        setChangedIds(prev => new Set(prev).add(feeId));
      } else {
        setChangedIds(prev => {
          const next = new Set(prev);
          next.delete(feeId);
          return next;
        });
      }
    }
  };

  const getUserTypeLabel = (type: string) => {
    switch (type) {
      case "USER": return "مستخدم عادي";
      case "VERIFIED_USER": return "مستخدم موثق";
      default: return type;
    }
  };

  const getOrderTypeLabel = (type: string) => {
    switch (type) {
      case "MARKET": return "سوقي (Market)";
      case "LIMIT": return "محدد (Limit)";
      case "STOP_LIMIT": return "شرطي (Stop Limit)";
      case "TAKE_PROFIT": return "جني أرباح (Take Profit)";
      default: return type;
    }
  };

  const getUserTypeBadgeColor = (type: string) => {
    switch (type) {
      case "USER": return "bg-blue-500/10 text-blue-400 border-blue-500/20";
      case "VERIFIED_USER": return "bg-emerald-500/10 text-emerald-400 border-emerald-500/20";
      default: return "bg-gray-500/10 text-gray-400 border-gray-500/20";
    }
  };

  const getUserTypeIcon = (type: string) => {
    switch (type) {
      case "USER": return Shield;
      case "VERIFIED_USER": return ShieldCheck;
      default: return Shield;
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center py-32">
        <div className="flex flex-col items-center gap-4">
          <span className="spinner h-8 w-8" />
          <p className="text-sm text-muted-foreground">جاري تحميل جدول الرسوم...</p>
        </div>
      </div>
    );
  }

  // Summary stats
  const userAvgMaker = fees.filter(f => f.user_type === "USER").reduce((s, f) => s + f.maker_fee, 0) / Math.max(1, fees.filter(f => f.user_type === "USER").length);
  const userAvgTaker = fees.filter(f => f.user_type === "USER").reduce((s, f) => s + f.taker_fee, 0) / Math.max(1, fees.filter(f => f.user_type === "USER").length);
  const verifiedAvgMaker = fees.filter(f => f.user_type === "VERIFIED_USER").reduce((s, f) => s + f.maker_fee, 0) / Math.max(1, fees.filter(f => f.user_type === "VERIFIED_USER").length);
  const verifiedAvgTaker = fees.filter(f => f.user_type === "VERIFIED_USER").reduce((s, f) => s + f.taker_fee, 0) / Math.max(1, fees.filter(f => f.user_type === "VERIFIED_USER").length);

  return (
    <div className="space-y-6 animate-fade-in">
      {/* ─── Header ─── */}
      <div className="animate-slide-in-down">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-emerald-500/10 flex items-center justify-center">
              <Percent className="h-5 w-5 text-emerald-500" />
            </div>
            <div>
              <h1 className="text-2xl lg:text-3xl font-bold">رسوم التداول</h1>
              <p className="text-sm text-muted-foreground">إدارة جدول رسوم العمولات حسب نوع المستخدم والأوردر</p>
            </div>
          </div>
          <button onClick={fetchFees} disabled={loading} className="btn-ghost flex items-center gap-2 text-sm">
            <RefreshCw className={`h-4 w-4 ${loading ? "animate-spin" : ""}`} />
            تحديث
          </button>
        </div>
      </div>

      {/* ─── Info Card ─── */}
      <div className="glass-panel rounded-2xl p-5 animate-slide-in-up delay-100">
        <div className="flex items-start gap-3">
          <div className="h-9 w-9 rounded-lg bg-blue-500/10 flex items-center justify-center shrink-0">
            <Info className="h-5 w-5 text-blue-400" />
          </div>
          <div className="text-sm text-muted-foreground space-y-1.5">
            <p><strong className="text-foreground">رسوم الصانع (Maker):</strong> تُطبق عندما يضع المستخدم أوردراً محدداً لا يتم تنفيذه فوراً ويضيف سيولة للسوق.</p>
            <p><strong className="text-foreground">رسوم الآخذ (Taker):</strong> تُطبق عندما يأخذ المستخدم أوردراً من السوق (تنفيذ فوري).</p>
            <p><strong className="text-foreground">الحد الأدنى للرسوم:</strong> أقل مبلغ يُخصم كرسوم بغض النظر عن نسبة العمولة.</p>
          </div>
        </div>
      </div>

      {/* ─── Stats Summary Row ─── */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3 animate-slide-in-up delay-200">
        <div className="stat-card stat-card-blue">
          <div className="relative z-10 flex items-center gap-3">
            <div className="p-2 rounded-lg bg-blue-500/10">
              <TrendingUp className="h-4 w-4 text-blue-500" />
            </div>
            <div>
              <p className="text-lg font-bold">{(userAvgMaker * 100).toFixed(2)}%</p>
              <p className="text-[10px] text-muted-foreground">صانع - عادي</p>
            </div>
          </div>
        </div>
        <div className="stat-card stat-card-orange">
          <div className="relative z-10 flex items-center gap-3">
            <div className="p-2 rounded-lg bg-orange-500/10">
              <TrendingDown className="h-4 w-4 text-orange-500" />
            </div>
            <div>
              <p className="text-lg font-bold">{(userAvgTaker * 100).toFixed(2)}%</p>
              <p className="text-[10px] text-muted-foreground">آخذ - عادي</p>
            </div>
          </div>
        </div>
        <div className="stat-card stat-card-emerald">
          <div className="relative z-10 flex items-center gap-3">
            <div className="p-2 rounded-lg bg-emerald-500/10">
              <TrendingUp className="h-4 w-4 text-emerald-500" />
            </div>
            <div>
              <p className="text-lg font-bold">{(verifiedAvgMaker * 100).toFixed(2)}%</p>
              <p className="text-[10px] text-muted-foreground">صانع - موثق</p>
            </div>
          </div>
        </div>
        <div className="stat-card stat-card-teal">
          <div className="relative z-10 flex items-center gap-3">
            <div className="p-2 rounded-lg bg-teal-500/10">
              <TrendingDown className="h-4 w-4 text-teal-500" />
            </div>
            <div>
              <p className="text-lg font-bold">{(verifiedAvgTaker * 100).toFixed(2)}%</p>
              <p className="text-[10px] text-muted-foreground">آخذ - موثق</p>
            </div>
          </div>
        </div>
      </div>

      {/* ─── Fees Table ─── */}
      {fees.length === 0 ? (
        <div className="glass-panel rounded-2xl p-16 text-center animate-slide-in-up delay-300">
          <Percent className="h-12 w-12 text-muted-foreground/30 mx-auto mb-3" />
          <p className="text-muted-foreground font-medium">لا توجد جداول رسوم</p>
          <p className="text-xs text-muted-foreground/60 mt-1">سيتم عرض جدول الرسوم هنا عند إضافته</p>
        </div>
      ) : (
        <div className="glass-panel rounded-2xl overflow-hidden animate-slide-in-up delay-300">
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-border/50 bg-muted/10">
                  <th className="text-right p-4 text-muted-foreground font-medium">نوع المستخدم</th>
                  <th className="text-right p-4 text-muted-foreground font-medium">نوع الأوردر</th>
                  <th className="text-right p-4 text-muted-foreground font-medium">رسوم الصانع (%)</th>
                  <th className="text-right p-4 text-muted-foreground font-medium">رسوم الآخذ (%)</th>
                  <th className="text-right p-4 text-muted-foreground font-medium">الحد الأدنى</th>
                  <th className="text-right p-4 text-muted-foreground font-medium">آخر تحديث</th>
                  <th className="text-right p-4 text-muted-foreground font-medium">إجراء</th>
                </tr>
              </thead>
              <tbody>
                {fees.map((fee) => {
                  const ev = editValues[fee.id];
                  const UserIcon = getUserTypeIcon(fee.user_type);
                  const hasChanged = changedIds.has(fee.id);
                  return (
                    <tr key={fee.id} className={`border-b border-border/20 hover:bg-muted/5 transition-all ${hasChanged ? "bg-primary/5" : ""}`}>
                      <td className="p-4">
                        <span className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-lg text-xs font-medium border ${getUserTypeBadgeColor(fee.user_type)}`}>
                          <UserIcon className="h-3 w-3" />
                          {getUserTypeLabel(fee.user_type)}
                        </span>
                      </td>
                      <td className="p-4 font-medium text-sm">{getOrderTypeLabel(fee.order_type)}</td>
                      <td className="p-4">
                        <div className="relative">
                          <input
                            type="number"
                            step="0.001"
                            min="0"
                            max="100"
                            className={`input-field w-28 text-center font-mono text-sm ${hasChanged ? "border-primary/50 ring-1 ring-primary/20" : ""}`}
                            value={ev?.maker_fee || ""}
                            onChange={(e) => handleFieldChange(fee.id, "maker_fee", e.target.value)}
                          />
                          {hasChanged && (
                            <div className="absolute -top-1 -right-1 w-2 h-2 rounded-full bg-primary" />
                          )}
                        </div>
                      </td>
                      <td className="p-4">
                        <div className="relative">
                          <input
                            type="number"
                            step="0.001"
                            min="0"
                            max="100"
                            className={`input-field w-28 text-center font-mono text-sm ${hasChanged ? "border-primary/50 ring-1 ring-primary/20" : ""}`}
                            value={ev?.taker_fee || ""}
                            onChange={(e) => handleFieldChange(fee.id, "taker_fee", e.target.value)}
                          />
                        </div>
                      </td>
                      <td className="p-4">
                        <div className="relative">
                          <input
                            type="number"
                            step="0.00000001"
                            min="0"
                            className={`input-field w-32 text-center font-mono text-sm ${hasChanged ? "border-primary/50 ring-1 ring-primary/20" : ""}`}
                            value={ev?.min_fee || ""}
                            onChange={(e) => handleFieldChange(fee.id, "min_fee", e.target.value)}
                          />
                        </div>
                      </td>
                      <td className="p-4 text-muted-foreground text-xs">
                        {fee.updated_at ? new Date(fee.updated_at).toLocaleDateString("ar-EG", { year: "numeric", month: "short", day: "numeric" }) : "—"}
                      </td>
                      <td className="p-4">
                        <button
                          onClick={() => handleSave(fee.id)}
                          disabled={saving === fee.id || !hasChanged}
                          className={`inline-flex items-center gap-1.5 px-3.5 py-2 rounded-lg text-xs font-medium transition-all disabled:opacity-40 ${
                            hasChanged
                              ? "bg-primary/10 text-primary hover:bg-primary/20 border border-primary/20"
                              : "bg-muted/20 text-muted-foreground"
                          }`}
                        >
                          {saving === fee.id ? <span className="spinner h-3.5 w-3.5" /> : <Save className="h-3.5 w-3.5" />}
                          حفظ
                        </button>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* ─── Fee Summary Cards ─── */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 animate-slide-in-up delay-400">
        <div className="glass-panel rounded-2xl p-5 relative overflow-hidden">
          <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-l from-blue-500 to-blue-400/50" />
          <div className="flex items-center gap-2.5 mb-4">
            <div className="w-8 h-8 rounded-lg bg-blue-500/10 flex items-center justify-center">
              <Shield className="h-4 w-4 text-blue-500" />
            </div>
            <h3 className="font-bold text-sm text-blue-400">مستخدم عادي</h3>
          </div>
          <div className="space-y-2 text-sm">
            {fees.filter(f => f.user_type === "USER").map(f => (
              <div key={f.id} className="flex justify-between items-center py-2 px-3 rounded-lg hover:bg-muted/10 transition-colors">
                <span className="text-muted-foreground text-xs">{getOrderTypeLabel(f.order_type)}</span>
                <div className="flex items-center gap-4">
                  <span className="text-xs text-muted-foreground flex items-center gap-1">
                    <TrendingUp className="h-3 w-3 text-blue-400" />
                    صانع: <span className="text-foreground font-medium">{(f.maker_fee * 100).toFixed(2)}%</span>
                  </span>
                  <span className="text-xs text-muted-foreground flex items-center gap-1">
                    <TrendingDown className="h-3 w-3 text-orange-400" />
                    آخذ: <span className="text-foreground font-medium">{(f.taker_fee * 100).toFixed(2)}%</span>
                  </span>
                  <span className="text-xs text-muted-foreground flex items-center gap-1">
                    <DollarSign className="h-3 w-3 text-muted-foreground" />
                    <span className="text-foreground font-mono">{f.min_fee.toFixed(8)}</span>
                  </span>
                </div>
              </div>
            ))}
            {fees.filter(f => f.user_type === "USER").length === 0 && (
              <p className="text-xs text-muted-foreground/60 text-center py-4">لا توجد بيانات</p>
            )}
          </div>
        </div>
        <div className="glass-panel rounded-2xl p-5 relative overflow-hidden">
          <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-l from-emerald-500 to-teal-400/50" />
          <div className="flex items-center gap-2.5 mb-4">
            <div className="w-8 h-8 rounded-lg bg-emerald-500/10 flex items-center justify-center">
              <ShieldCheck className="h-4 w-4 text-emerald-500" />
            </div>
            <h3 className="font-bold text-sm text-emerald-400">مستخدم موثق</h3>
          </div>
          <div className="space-y-2 text-sm">
            {fees.filter(f => f.user_type === "VERIFIED_USER").map(f => (
              <div key={f.id} className="flex justify-between items-center py-2 px-3 rounded-lg hover:bg-muted/10 transition-colors">
                <span className="text-muted-foreground text-xs">{getOrderTypeLabel(f.order_type)}</span>
                <div className="flex items-center gap-4">
                  <span className="text-xs text-muted-foreground flex items-center gap-1">
                    <TrendingUp className="h-3 w-3 text-emerald-400" />
                    صانع: <span className="text-foreground font-medium">{(f.maker_fee * 100).toFixed(2)}%</span>
                  </span>
                  <span className="text-xs text-muted-foreground flex items-center gap-1">
                    <TrendingDown className="h-3 w-3 text-orange-400" />
                    آخذ: <span className="text-foreground font-medium">{(f.taker_fee * 100).toFixed(2)}%</span>
                  </span>
                  <span className="text-xs text-muted-foreground flex items-center gap-1">
                    <DollarSign className="h-3 w-3 text-muted-foreground" />
                    <span className="text-foreground font-mono">{f.min_fee.toFixed(8)}</span>
                  </span>
                </div>
              </div>
            ))}
            {fees.filter(f => f.user_type === "VERIFIED_USER").length === 0 && (
              <p className="text-xs text-muted-foreground/60 text-center py-4">لا توجد بيانات</p>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

// admin/src/routes/dashboard/fees/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import {
    Percent, ArrowUpDown, Save, RotateCcw, Loader2,
    AlertCircle, CheckCircle2, TrendingUp, TrendingDown,
    Coins, ShieldCheck, User, BadgeCheck, CircleDot
  } from 'lucide-svelte';
  import { authGet, authPut } from '$lib/api/client';
  import type { FeeSchedule } from '$lib/api/types';
  import PageHeader from '$lib/components/PageHeader.svelte';
  import ErrorAlert from '$lib/components/ErrorAlert.svelte';
  import { toast } from '$lib/stores/toast';
  import { formatPercent } from '$lib/utils/helpers';

  // ─── Label Maps ─────────────────────────────────────────────
  const userTypeLabels: Record<string, string> = {
    USER: 'مستخدم عادي',
    VERIFIED_USER: 'مستخدم موثّق'
  };

  const userTypeConfig: Record<string, { icon: any; color: string; bg: string }> = {
    USER: { icon: User, color: '#3b82f6', bg: 'rgba(59,130,246,0.12)' },
    VERIFIED_USER: { icon: BadgeCheck, color: '#22d3a4', bg: 'rgba(34,211,164,0.12)' }
  };

  const orderTypeLabels: Record<string, string> = {
    MARKET: 'سوقي',
    LIMIT: 'محدد',
    STOP_LIMIT: 'وقف محدد',
    TAKE_PROFIT: 'جني الأرباح'
  };

  // ─── State ──────────────────────────────────────────────────
  let fees = $state<FeeSchedule[]>([]);
  let loading = $state(true);
  let error = $state('');
  let saving = $state<number | null>(null);
  let refreshing = $state(false);

  // Track edited fields: key = `${feeId}-${field}`, value = true
  let dirtyFields = $state<Record<string, boolean>>({});
  // Track original values for reset
  let originalFees = $state<FeeSchedule[]>([]);
  // Track current edit values: key = feeId, value = partial fields
  let editValues = $state<Record<number, { maker_fee?: number; taker_fee?: number; min_fee?: number }>>({});

  // ─── Computed ───────────────────────────────────────────────
  let groupedFees = $derived(() => {
    const groups: Record<string, FeeSchedule[]> = {};
    for (const fee of fees) {
      if (!groups[fee.user_type]) groups[fee.user_type] = [];
      groups[fee.user_type].push(fee);
    }
    return groups;
  });

  let summaryStats = $derived(() => {
    const result: Record<string, { avgMaker: number; avgTaker: number }> = {};
    for (const [type, group] of Object.entries(groupedFees())) {
      const avgMaker = group.reduce((s, f) => s + f.maker_fee, 0) / (group.length || 1);
      const avgTaker = group.reduce((s, f) => s + f.taker_fee, 0) / (group.length || 1);
      result[type] = { avgMaker, avgTaker };
    }
    return result;
  });

  // ─── Helpers ────────────────────────────────────────────────
  function getFieldValue(fee: FeeSchedule, field: 'maker_fee' | 'taker_fee' | 'min_fee'): number {
    return editValues[fee.id]?.[field] ?? fee[field];
  }

  function setFieldValue(fee: FeeSchedule, field: 'maker_fee' | 'taker_fee' | 'min_fee', value: number) {
    if (!editValues[fee.id]) editValues[fee.id] = {};
    editValues[fee.id][field] = value;
    const key = `${fee.id}-${field}`;
    const original = originalFees.find(f => f.id === fee.id);
    if (original && original[field] !== value) {
      dirtyFields[key] = true;
    } else {
      delete dirtyFields[key];
    }
    // Trigger reactivity
    editValues = { ...editValues };
    dirtyFields = { ...dirtyFields };
  }

  function isFieldDirty(feeId: number, field: string): boolean {
    return !!dirtyFields[`${feeId}-${field}`];
  }

  function isFeeDirty(feeId: number): boolean {
    return Object.keys(dirtyFields).some(k => k.startsWith(`${feeId}-`));
  }

  // ─── API ────────────────────────────────────────────────────
  async function fetchFees() {
    try {
      error = '';
      const res = await authGet('/api/v1/admin/fees');
      if (!res.ok) throw new Error('فشل تحميل جداول الرسوم');
      const json = await res.json();
      if (json.success) {
        fees = json.data;
        originalFees = json.data.map((f: FeeSchedule) => ({ ...f }));
        editValues = {};
        dirtyFields = {};
      }
    } catch (e: any) {
      error = e.message;
    } finally {
      loading = false;
      refreshing = false;
    }
  }

  async function handleSave(feeId: number) {
    const edits = editValues[feeId];
    if (!edits) return;

    saving = feeId;
    try {
      const res = await authPut(`/api/v1/admin/fees/${feeId}`, edits);
      if (!res.ok) throw new Error('فشل حفظ التعديلات');
      const json = await res.json();
      if (json.success) {
        fees = fees.map(f => f.id === feeId ? json.data : f);
        originalFees = originalFees.map(f => f.id === feeId ? { ...json.data } : f);
        // Clear dirty state for this fee
        for (const key of Object.keys(dirtyFields)) {
          if (key.startsWith(`${feeId}-`)) delete dirtyFields[key];
        }
        delete editValues[feeId];
        dirtyFields = { ...dirtyFields };
        editValues = { ...editValues };
        toast.success('تم حفظ الرسوم بنجاح');
      }
    } catch (e: any) {
      toast.error(e.message);
    } finally {
      saving = null;
    }
  }

  function handleReset(feeId: number) {
    const original = originalFees.find(f => f.id === feeId);
    if (!original) return;

    editValues[feeId] = {
      maker_fee: original.maker_fee,
      taker_fee: original.taker_fee,
      min_fee: original.min_fee
    };

    for (const key of Object.keys(dirtyFields)) {
      if (key.startsWith(`${feeId}-`)) delete dirtyFields[key];
    }

    dirtyFields = { ...dirtyFields };
    editValues = { ...editValues };
    toast.info('تم إعادة القيم الأصلية');
  }

  async function handleRefresh() {
    refreshing = true;
    await fetchFees();
    toast.success('تم تحديث البيانات');
  }

  // ─── Lifecycle ──────────────────────────────────────────────
  onMount(() => {
    fetchFees();
  });
</script>

<div class="space-y-6">
  <!-- Header -->
  <PageHeader title="إدارة الرسوم" subtitle="تعديل جداول الرسوم حسب نوع المستخدم ونوع الأمر">
    <button class="btn-ghost text-sm flex items-center gap-2" onclick={handleRefresh} disabled={refreshing}>
      {#if refreshing}
        <Loader2 size={16} class="animate-spin" />
      {:else}
        <RotateCcw size={16} />
      {/if}
      تحديث
    </button>
  </PageHeader>

  <!-- Error -->
  {#if error}
    <ErrorAlert message={error} onclose={() => (error = '')} />
  {/if}

  <!-- Summary Cards -->
  {#if !loading && fees.length > 0}
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5">
      {#each Object.entries(summaryStats()) as [type, stats] (type)}
        {@const cfg = userTypeConfig[type]}
        {@const Icon = cfg?.icon || User}
        <div class="stat-card group">
          <div class="flex items-start justify-between">
            <div class="flex-1 min-w-0">
              <p class="text-[11px] font-semibold tracking-wider uppercase" style="color: var(--text-quaternary);">{userTypeLabels[type] || type}</p>
              <div class="mt-2 space-y-1">
                <div class="flex items-center gap-2">
                  <TrendingUp size={13} style="color: #22d3a4;" />
                  <span class="text-xs" style="color: var(--text-tertiary);">صانع:</span>
                  <span class="text-sm font-bold tabular-nums" style="color: #22d3a4;">{formatPercent(stats.avgMaker)}</span>
                </div>
                <div class="flex items-center gap-2">
                  <TrendingDown size={13} style="color: #f43f7a;" />
                  <span class="text-xs" style="color: var(--text-tertiary);">آخذ:</span>
                  <span class="text-sm font-bold tabular-nums" style="color: #f43f7a;">{formatPercent(stats.avgTaker)}</span>
                </div>
              </div>
            </div>
            <div class="flex items-center justify-center w-11 h-11 rounded-xl shrink-0" style="background: {cfg?.bg || 'rgba(59,130,246,0.12)'}; box-shadow: 0 0 20px {cfg?.bg || 'rgba(59,130,246,0.12)'};">
              <Icon size={20} style="color: {cfg?.color || '#3b82f6'};" />
            </div>
          </div>
        </div>
      {/each}
    </div>
  {/if}

  <!-- Fee Tables -->
  {#if loading}
    <div class="space-y-8">
      {#each Array(2) as _}
        <div class="panel p-6 space-y-4">
          <div class="animate-shimmer h-6 w-40 rounded" style="background: rgba(255,255,255,0.05);"></div>
          {#each Array(4) as _}
            <div class="flex items-center gap-4">
              <div class="animate-shimmer h-4 w-24 rounded" style="background: rgba(255,255,255,0.04);"></div>
              <div class="animate-shimmer h-10 flex-1 rounded-lg" style="background: rgba(255,255,255,0.03);"></div>
              <div class="animate-shimmer h-10 flex-1 rounded-lg" style="background: rgba(255,255,255,0.03);"></div>
              <div class="animate-shimmer h-10 flex-1 rounded-lg" style="background: rgba(255,255,255,0.03);"></div>
            </div>
          {/each}
        </div>
      {/each}
    </div>
  {:else if fees.length > 0}
    <div class="space-y-8">
      {#each Object.entries(groupedFees()) as [userType, group] (userType)}
        {@const cfg = userTypeConfig[userType]}
        {@const Icon = cfg?.icon || User}

        <div class="panel overflow-hidden">
          <!-- Group Header -->
          <div class="flex items-center gap-3 p-5 border-b" style="border-color: rgba(255,255,255,0.06);">
            <div class="flex items-center justify-center w-10 h-10 rounded-xl" style="background: {cfg?.bg};">
              <Icon size={20} style="color: {cfg?.color};" />
            </div>
            <div>
              <h2 class="font-bold text-lg" style="color: var(--text-primary);">{userTypeLabels[userType] || userType}</h2>
              <p class="text-xs" style="color: var(--text-quaternary);">{group.length} نوع أوامر</p>
            </div>
            <div class="mr-auto flex items-center gap-1.5">
              <Coins size={14} style="color: var(--text-quaternary);" />
              <span class="text-xs" style="color: var(--text-quaternary);">جدول الرسوم</span>
            </div>
          </div>

          <!-- Table -->
          <div class="overflow-x-auto">
            <table class="data-table w-full">
              <thead>
                <tr>
                  <th style="min-width: 140px;">نوع الأمر</th>
                  <th style="min-width: 140px;">رسوم الصانع</th>
                  <th style="min-width: 140px;">رسوم الآخذ</th>
                  <th style="min-width: 140px;">الحد الأدنى</th>
                  <th style="min-width: 160px;">إجراءات</th>
                </tr>
              </thead>
              <tbody>
                {#each group as fee (fee.id)}
                  <tr>
                    <!-- Order Type -->
                    <td>
                      <div class="flex items-center gap-2">
                        <ArrowUpDown size={14} style="color: var(--text-quaternary);" />
                        <span class="font-medium text-sm">{orderTypeLabels[fee.order_type] || fee.order_type}</span>
                      </div>
                    </td>

                    <!-- Maker Fee -->
                    <td>
                      <div class="relative">
                        <input
                          type="number"
                          step="0.01"
                          class="input-field w-full tabular-nums text-left"
                          value={getFieldValue(fee, 'maker_fee')}
                          oninput={(e) => setFieldValue(fee, 'maker_fee', parseFloat((e.target as HTMLInputElement).value) || 0)}
                          style={isFieldDirty(fee.id, 'maker_fee') ? 'border-color: rgba(245,181,68,0.5); box-shadow: 0 0 0 1px rgba(245,181,68,0.2);' : ''}
                        />
                        {#if isFieldDirty(fee.id, 'maker_fee')}
                          <CircleDot size={12} class="absolute left-2 top-1/2 -translate-y-1/2" style="color: #f5b544;" />
                        {/if}
                      </div>
                    </td>

                    <!-- Taker Fee -->
                    <td>
                      <div class="relative">
                        <input
                          type="number"
                          step="0.01"
                          class="input-field w-full tabular-nums text-left"
                          value={getFieldValue(fee, 'taker_fee')}
                          oninput={(e) => setFieldValue(fee, 'taker_fee', parseFloat((e.target as HTMLInputElement).value) || 0)}
                          style={isFieldDirty(fee.id, 'taker_fee') ? 'border-color: rgba(245,181,68,0.5); box-shadow: 0 0 0 1px rgba(245,181,68,0.2);' : ''}
                        />
                        {#if isFieldDirty(fee.id, 'taker_fee')}
                          <CircleDot size={12} class="absolute left-2 top-1/2 -translate-y-1/2" style="color: #f5b544;" />
                        {/if}
                      </div>
                    </td>

                    <!-- Min Fee -->
                    <td>
                      <div class="relative">
                        <input
                          type="number"
                          step="0.01"
                          class="input-field w-full tabular-nums text-left"
                          value={getFieldValue(fee, 'min_fee')}
                          oninput={(e) => setFieldValue(fee, 'min_fee', parseFloat((e.target as HTMLInputElement).value) || 0)}
                          style={isFieldDirty(fee.id, 'min_fee') ? 'border-color: rgba(245,181,68,0.5); box-shadow: 0 0 0 1px rgba(245,181,68,0.2);' : ''}
                        />
                        {#if isFieldDirty(fee.id, 'min_fee')}
                          <CircleDot size={12} class="absolute left-2 top-1/2 -translate-y-1/2" style="color: #f5b544;" />
                        {/if}
                      </div>
                    </td>

                    <!-- Actions -->
                    <td>
                      <div class="flex items-center gap-2">
                        <button
                          class="btn-primary text-xs flex items-center gap-1.5"
                          onclick={() => handleSave(fee.id)}
                          disabled={saving === fee.id || !isFeeDirty(fee.id)}
                        >
                          {#if saving === fee.id}
                            <Loader2 size={13} class="animate-spin" />
                          {:else}
                            <Save size={13} />
                          {/if}
                          حفظ
                        </button>
                        <button
                          class="btn-ghost text-xs flex items-center gap-1.5"
                          onclick={() => handleReset(fee.id)}
                          disabled={!isFeeDirty(fee.id)}
                        >
                          <RotateCcw size={13} />
                          إعادة
                        </button>
                      </div>
                    </td>
                  </tr>
                {/each}
              </tbody>
            </table>
          </div>
        </div>
      {/each}
    </div>
  {:else}
    <div class="panel p-8 flex flex-col items-center text-center">
      <Percent size={32} style="color: var(--text-quaternary);" />
      <p class="text-sm mt-2" style="color: var(--text-quaternary);">لا توجد جداول رسوم</p>
    </div>
  {/if}
</div>
