// frontend/src/app/dashboard/admin/transactions/page.tsx
"use client";

import { useEffect, useState } from "react";
import toast from "react-hot-toast";
import {
  ArrowRightLeft,
  Loader2,
  CheckCircle2,
  XCircle,
  Clock,
  Inbox,
  Filter,
  ChevronLeft,
  ChevronRight,
  X,
  AlertTriangle,
  ArrowUpRight,
  ArrowDownRight,
  DollarSign,
  CalendarDays,
  Hash,
  User,
  Banknote,
  SendHorizonal,
} from "lucide-react";
import { authGet, authPut } from "@/lib/api";

interface Transaction {
  id: number;
  user_id: number;
  username: string;
  email: string;
  type: "DEPOSIT" | "WITHDRAWAL";
  currency: string;
  amount: string;
  status: "PENDING" | "APPROVED" | "REJECTED";
  rejection_reason: string;
  tx_hash: string;
  wallet_address: string;
  created_at: string;
  reviewed_at?: string;
}

const STATUS_TABS = [
  { value: "", label: "الكل", icon: Filter },
  { value: "PENDING", label: "معلق", icon: Clock },
  { value: "APPROVED", label: "مقبول", icon: CheckCircle2 },
  { value: "REJECTED", label: "مرفوض", icon: XCircle },
];

const TYPE_TABS = [
  { value: "", label: "الكل" },
  { value: "DEPOSIT", label: "إيداع" },
  { value: "WITHDRAWAL", label: "سحب" },
];

export default function AdminTransactionsPage() {
  const [transactions, setTransactions] = useState<Transaction[]>([]);
  const [loading, setLoading] = useState(true);
  const [statusFilter, setStatusFilter] = useState("");
  const [typeFilter, setTypeFilter] = useState("");
  const [page, setPage] = useState(1);
  const [total, setTotal] = useState(0);
  const [reviewing, setReviewing] = useState<number | null>(null);
  const [reviewModal, setReviewModal] = useState<{ id: number; action: "APPROVED" | "REJECTED"; type: string } | null>(null);
  const [rejectionReason, setRejectionReason] = useState("");
  const limit = 20;
  const totalPages = Math.ceil(total / limit);

  useEffect(() => {
    fetchTransactions();
  }, [statusFilter, typeFilter, page]);

  const fetchTransactions = async () => {
    setLoading(true);
    try {
      const params = new URLSearchParams();
      if (statusFilter) params.set("status", statusFilter);
      if (typeFilter) params.set("type", typeFilter);
      params.set("page", page.toString());
      params.set("limit", limit.toString());
      const res = await authGet(`/api/v1/admin/transactions?${params.toString()}`);
      if (res.ok) {
        const data = await res.json();
        setTransactions(Array.isArray(data.data) ? data.data : []);
        setTotal(data.total || 0);
      } else {
        toast.error("فشل تحميل المعاملات");
      }
    } catch {
      toast.error("حدث خطأ في الاتصال");
    } finally {
      setLoading(false);
    }
  };

  const handleReview = async () => {
    if (!reviewModal) return;
    if (reviewModal.action === "REJECTED" && !rejectionReason.trim()) {
      toast.error("يرجى إدخال سبب الرفض");
      return;
    }
    setReviewing(reviewModal.id);
    try {
      const body: any = { status: reviewModal.action };
      if (reviewModal.action === "REJECTED") {
        body.rejection_reason = rejectionReason;
      }
      const res = await authPut(`/api/v1/admin/transactions/${reviewModal.id}/review`, body);
      const data = await res.json();
      if (!res.ok) {
        toast.error(data.error || "فشل مراجعة المعاملة");
        return;
      }
      toast.success(data.message || `تم ${reviewModal.action === "APPROVED" ? "قبول" : "رفض"} المعاملة بنجاح`);
      setTransactions(prev =>
        prev.map(t => t.id === reviewModal.id ? { ...t, status: reviewModal.action, rejection_reason: reviewModal.action === "REJECTED" ? rejectionReason : t.rejection_reason } : t)
      );
      setReviewModal(null);
      setRejectionReason("");
    } catch {
      toast.error("حدث خطأ في الاتصال");
    } finally {
      setReviewing(null);
    }
  };

  const getStatusConfig = (status: string) => {
    switch (status) {
      case "APPROVED":
        return { label: "مقبول", cls: "bg-emerald-500/10 text-emerald-400 border-emerald-500/20", dotColor: "bg-emerald-500" };
      case "PENDING":
        return { label: "معلق", cls: "bg-yellow-500/10 text-yellow-400 border-yellow-500/20", dotColor: "bg-yellow-500" };
      case "REJECTED":
        return { label: "مرفوض", cls: "bg-red-500/10 text-red-400 border-red-500/20", dotColor: "bg-red-500" };
      default:
        return { label: status, cls: "bg-gray-500/10 text-gray-400 border-gray-500/20", dotColor: "bg-gray-500" };
    }
  };

  const getTypeConfig = (type: string) => {
    switch (type) {
      case "DEPOSIT":
        return { label: "إيداع", icon: Banknote, color: "text-emerald-400", bg: "bg-emerald-500/10" };
      case "WITHDRAWAL":
        return { label: "سحب", icon: SendHorizonal, color: "text-red-400", bg: "bg-red-500/10" };
      default:
        return { label: type, icon: ArrowRightLeft, color: "text-muted-foreground", bg: "bg-muted/20" };
    }
  };

  return (
    <div className="space-y-6">
      {/* ── Header ── */}
      <div className="animate-slide-in-up">
        <div className="flex items-center gap-3">
          <div className="h-11 w-11 rounded-xl bg-gradient-to-br from-emerald-500 to-teal-600 flex items-center justify-center shadow-lg shadow-emerald-500/20">
            <ArrowRightLeft className="h-6 w-6 text-white" />
          </div>
          <div>
            <h1 className="text-2xl sm:text-3xl font-bold">إدارة المعاملات</h1>
            <p className="text-muted-foreground text-sm mt-0.5">مراجعة ومعالجة عمليات الإيداع والسحب</p>
          </div>
        </div>
      </div>

      {/* ── Info Banner ── */}
      <div className="p-4 rounded-2xl bg-blue-500/5 border border-blue-500/15 animate-slide-in-up" style={{ animationDelay: "50ms" }}>
        <div className="flex items-start gap-3">
          <AlertTriangle className="h-5 w-5 text-blue-400 shrink-0 mt-0.5" />
          <div className="text-sm text-muted-foreground leading-relaxed">
            <p><span className="font-semibold text-foreground">ملاحظة: </span>قبول إيداع سيتم إضافة الرصيد للمستخدم. رفض سحب سيتم إرجاع الرصيد للمستخدم.</p>
          </div>
        </div>
      </div>

      {/* ── Filter Tabs ── */}
      <div className="glass-panel rounded-2xl p-3 animate-slide-in-up" style={{ animationDelay: "80ms" }}>
        <div className="flex flex-wrap items-center gap-2">
          <div className="h-8 w-8 rounded-lg bg-primary/10 flex items-center justify-center shrink-0">
            <Filter className="h-4 w-4 text-primary" />
          </div>
          {STATUS_TABS.map((tab) => {
            const Icon = tab.icon;
            return (
              <button
                key={tab.value}
                onClick={() => { setStatusFilter(tab.value); setPage(1); }}
                className={`inline-flex items-center gap-1.5 px-4 py-2 rounded-xl text-sm whitespace-nowrap transition-all duration-200 ${
                  statusFilter === tab.value
                    ? "bg-primary/15 text-primary font-semibold shadow-sm shadow-primary/10"
                    : "text-muted-foreground hover:bg-muted/30 hover:text-foreground"
                }`}
              >
                <Icon className="h-3.5 w-3.5" />
                {tab.label}
              </button>
            );
          })}
          <div className="h-6 w-px bg-border/30 mx-1" />
          {TYPE_TABS.map((tab) => (
            <button
              key={tab.value}
              onClick={() => { setTypeFilter(tab.value); setPage(1); }}
              className={`inline-flex items-center px-3 py-2 rounded-xl text-sm whitespace-nowrap transition-all duration-200 ${
                typeFilter === tab.value
                  ? "bg-blue-500/15 text-blue-400 font-semibold"
                  : "text-muted-foreground hover:bg-muted/30 hover:text-foreground"
              }`}
            >
              {tab.label}
            </button>
          ))}
          {total > 0 && (
            <span className="text-xs text-muted-foreground mr-auto flex items-center gap-1.5 pr-2">
              {total} معاملة
            </span>
          )}
        </div>
      </div>

      {/* ── Transactions Table ── */}
      <div className="glass-panel rounded-2xl overflow-hidden animate-slide-in-up" style={{ animationDelay: "160ms" }}>
        {loading ? (
          <div className="flex flex-col items-center justify-center py-20 gap-3">
            <div className="h-16 w-16 rounded-2xl bg-emerald-500/10 flex items-center justify-center">
              <Loader2 className="h-8 w-8 animate-spin text-emerald-500" />
            </div>
            <p className="text-sm text-muted-foreground">جاري تحميل المعاملات...</p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-border/40 bg-muted/20">
                  <th className="text-right p-4 text-muted-foreground font-medium">
                    <div className="flex items-center gap-1.5"><Hash className="h-3.5 w-3.5" /> رقم</div>
                  </th>
                  <th className="text-right p-4 text-muted-foreground font-medium">
                    <div className="flex items-center gap-1.5"><User className="h-3.5 w-3.5" /> المستخدم</div>
                  </th>
                  <th className="text-right p-4 text-muted-foreground font-medium">النوع</th>
                  <th className="text-right p-4 text-muted-foreground font-medium">
                    <div className="flex items-center gap-1.5"><DollarSign className="h-3.5 w-3.5" /> المبلغ</div>
                  </th>
                  <th className="text-right p-4 text-muted-foreground font-medium">الحالة</th>
                  <th className="text-right p-4 text-muted-foreground font-medium">
                    <div className="flex items-center gap-1.5"><CalendarDays className="h-3.5 w-3.5" /> التاريخ</div>
                  </th>
                  <th className="text-right p-4 text-muted-foreground font-medium">إجراءات</th>
                </tr>
              </thead>
              <tbody>
                {transactions.map((tx) => {
                  const statusConfig = getStatusConfig(tx.status);
                  const typeConfig = getTypeConfig(tx.type);
                  const TypeIcon = typeConfig.icon;
                  return (
                    <tr key={tx.id} className="border-b border-border/15 hover:bg-emerald-500/[0.03] transition-all duration-200">
                      <td className="p-4 font-mono text-xs text-muted-foreground">#{tx.id}</td>
                      <td className="p-4">
                        <div className="flex items-center gap-2">
                          <div className="h-7 w-7 rounded-full bg-gradient-to-br from-emerald-400 to-teal-500 flex items-center justify-center shrink-0">
                            <span className="text-[10px] font-bold text-white">{tx.username?.charAt(0)?.toUpperCase() || "U"}</span>
                          </div>
                          <div>
                            <p className="text-xs font-semibold">{tx.username}</p>
                          </div>
                        </div>
                      </td>
                      <td className="p-4">
                        <span className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-lg text-xs font-semibold ${typeConfig.bg} ${typeConfig.color}`}>
                          <TypeIcon className="h-3 w-3" />
                          {typeConfig.label}
                        </span>
                      </td>
                      <td className="p-4">
                        <span className="font-semibold tabular-nums">{parseFloat(tx.amount || "0").toFixed(4)}</span>
                        <span className="text-xs text-muted-foreground mr-1">{tx.currency}</span>
                      </td>
                      <td className="p-4">
                        <span className={`inline-flex items-center gap-1.5 text-[11px] px-2.5 py-1 rounded-full font-semibold border ${statusConfig.cls}`}>
                          <span className={`h-1.5 w-1.5 rounded-full ${statusConfig.dotColor}`} />
                          {statusConfig.label}
                        </span>
                      </td>
                      <td className="p-4 text-muted-foreground text-xs">
                        {new Date(tx.created_at).toLocaleDateString("ar-EG", {
                          year: "numeric",
                          month: "short",
                          day: "numeric",
                        })}
                      </td>
                      <td className="p-4">
                        {tx.status === "PENDING" && (
                          <div className="flex items-center gap-2">
                            <button
                              onClick={() => setReviewModal({ id: tx.id, action: "APPROVED", type: tx.type })}
                              disabled={reviewing === tx.id}
                              className="inline-flex items-center gap-1 text-xs text-emerald-400 hover:text-emerald-300 hover:bg-emerald-500/10 px-2.5 py-1.5 rounded-lg transition-all duration-200 border border-transparent hover:border-emerald-500/20"
                            >
                              {reviewing === tx.id ? <Loader2 className="h-3 w-3 animate-spin" /> : <CheckCircle2 className="h-3 w-3" />}
                              قبول
                            </button>
                            <button
                              onClick={() => { setReviewModal({ id: tx.id, action: "REJECTED", type: tx.type }); setRejectionReason(""); }}
                              disabled={reviewing === tx.id}
                              className="inline-flex items-center gap-1 text-xs text-red-400 hover:text-red-300 hover:bg-red-500/10 px-2.5 py-1.5 rounded-lg transition-all duration-200 border border-transparent hover:border-red-500/20"
                            >
                              <XCircle className="h-3 w-3" />
                              رفض
                            </button>
                          </div>
                        )}
                        {tx.status === "REJECTED" && tx.rejection_reason && (
                          <p className="text-xs text-red-400/80 max-w-[200px] truncate" title={tx.rejection_reason}>
                            {tx.rejection_reason}
                          </p>
                        )}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}

        {/* Empty State */}
        {!loading && transactions.length === 0 && (
          <div className="flex flex-col items-center justify-center py-20 text-center animate-fade-in">
            <div className="h-20 w-20 rounded-2xl bg-muted/20 flex items-center justify-center mb-5">
              <Inbox className="h-10 w-10 text-muted-foreground/30" />
            </div>
            <h3 className="text-lg font-bold mb-2">لا توجد معاملات</h3>
            <p className="text-sm text-muted-foreground max-w-xs">لا توجد معاملات مطابقة للفلتر المحدد</p>
          </div>
        )}
      </div>

      {/* ── Pagination ── */}
      {totalPages > 1 && (
        <div className="flex items-center justify-center gap-2 animate-slide-in-up">
          <button
            onClick={() => setPage(p => Math.max(1, p - 1))}
            disabled={page === 1}
            className="btn-ghost text-sm gap-1 disabled:opacity-30 disabled:cursor-not-allowed"
          >
            <ChevronRight className="h-4 w-4" />
            السابق
          </button>
          <div className="flex items-center gap-1 mx-2">
            {Array.from({ length: Math.min(5, totalPages) }, (_, i) => {
              let pageNum: number;
              if (totalPages <= 5) pageNum = i + 1;
              else if (page <= 3) pageNum = i + 1;
              else if (page >= totalPages - 2) pageNum = totalPages - 4 + i;
              else pageNum = page - 2 + i;
              return (
                <button
                  key={pageNum}
                  onClick={() => setPage(pageNum)}
                  className={`w-9 h-9 rounded-xl text-sm font-medium transition-all duration-200 ${
                    pageNum === page
                      ? "bg-primary/15 text-primary shadow-sm shadow-primary/10"
                      : "text-muted-foreground hover:bg-muted/30 hover:text-foreground"
                  }`}
                >
                  {pageNum}
                </button>
              );
            })}
          </div>
          <button
            onClick={() => setPage(p => Math.min(totalPages, p + 1))}
            disabled={page === totalPages}
            className="btn-ghost text-sm gap-1 disabled:opacity-30 disabled:cursor-not-allowed"
          >
            التالي
            <ChevronLeft className="h-4 w-4" />
          </button>
          <span className="text-xs text-muted-foreground pr-3 border-r border-border/30 mr-2">
            صفحة <span className="font-semibold text-foreground">{page}</span> من {totalPages}
          </span>
        </div>
      )}

      {/* ── Review Modal ── */}
      {reviewModal && (
        <div className="fixed inset-0 bg-black/60 z-50 flex items-center justify-center p-4 animate-fade-in" style={{ backdropFilter: "blur(4px)" }}>
          <div className="glass-panel-strong rounded-2xl p-6 w-full max-w-md animate-scale-in">
            <div className="flex items-center justify-between mb-5">
              <div className="flex items-center gap-3">
                <div className={`h-9 w-9 rounded-lg flex items-center justify-center ${
                  reviewModal.action === "APPROVED" ? "bg-emerald-500/10" : "bg-red-500/10"
                }`}>
                  {reviewModal.action === "APPROVED" ? (
                    <CheckCircle2 className="h-5 w-5 text-emerald-500" />
                  ) : (
                    <XCircle className="h-5 w-5 text-red-500" />
                  )}
                </div>
                <h3 className="font-bold">
                  {reviewModal.action === "APPROVED" ? "تأكيد قبول المعاملة" : "تأكيد رفض المعاملة"}
                </h3>
              </div>
              <button onClick={() => { setReviewModal(null); setRejectionReason(""); }} className="btn-ghost p-1.5 rounded-lg">
                <X className="h-4 w-4" />
              </button>
            </div>

            <div className="p-3 rounded-xl bg-muted/20 border border-border/20 mb-4">
              <p className="text-sm">
                <span className="text-muted-foreground">نوع المعاملة: </span>
                <span className="font-semibold">{reviewModal.type === "DEPOSIT" ? "إيداع" : "سحب"}</span>
              </p>
              {reviewModal.action === "APPROVED" && reviewModal.type === "DEPOSIT" && (
                <p className="text-xs text-emerald-400 mt-1 flex items-center gap-1">
                  <ArrowUpRight className="h-3 w-3" />
                  سيتم إضافة الرصيد للمستخدم
                </p>
              )}
              {reviewModal.action === "APPROVED" && reviewModal.type === "WITHDRAWAL" && (
                <p className="text-xs text-emerald-400 mt-1 flex items-center gap-1">
                  <ArrowDownRight className="h-3 w-3" />
                  سيتم خصم الرصيد من المستخدم
                </p>
              )}
              {reviewModal.action === "REJECTED" && reviewModal.type === "WITHDRAWAL" && (
                <p className="text-xs text-yellow-400 mt-1 flex items-center gap-1">
                  <ArrowUpRight className="h-3 w-3" />
                  سيتم إرجاع الرصيد للمستخدم
                </p>
              )}
            </div>

            {reviewModal.action === "REJECTED" && (
              <div className="mb-4">
                <label className="block text-sm font-medium mb-2">سبب الرفض *</label>
                <textarea
                  className="input-field min-h-[100px] resize-none"
                  placeholder="أدخل سبب الرفض..."
                  value={rejectionReason}
                  onChange={(e) => setRejectionReason(e.target.value)}
                />
              </div>
            )}

            <div className="flex gap-3">
              <button
                onClick={handleReview}
                disabled={reviewing !== null || (reviewModal.action === "REJECTED" && !rejectionReason.trim())}
                className={`flex-1 inline-flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl text-sm font-semibold transition-all duration-200 disabled:opacity-50 ${
                  reviewModal.action === "APPROVED"
                    ? "bg-emerald-500/20 text-emerald-400 border border-emerald-500/20 hover:bg-emerald-500/30"
                    : "bg-red-500/20 text-red-400 border border-red-500/20 hover:bg-red-500/30"
                }`}
              >
                {reviewing !== null ? <Loader2 className="h-4 w-4 animate-spin" /> : null}
                {reviewModal.action === "APPROVED" ? "تأكيد القبول" : "تأكيد الرفض"}
              </button>
              <button
                onClick={() => { setReviewModal(null); setRejectionReason(""); }}
                className="btn-ghost flex-1"
              >
                إلغاء
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// admin/src/routes/dashboard/transactions/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import {
    Search,
    Filter,
    ArrowLeftRight,
    CheckCircle2,
    XCircle,
    Clock,
    Copy,
    Check,
    ChevronRight,
    ChevronLeft,
    AlertCircle,
    TrendingUp,
    TrendingDown,
    Hash,
    BellRing,
    RefreshCw,
    Loader2
  } from 'lucide-svelte';
  import { authGet, authPut } from '$lib/api/client';
  import type { AdminTransaction } from '$lib/api/types';
  import { createAdminStream } from '$lib/api/types';

  // ─── Types ───
  type StatusFilter = 'ALL' | 'PENDING' | 'COMPLETED' | 'REJECTED';

  interface PaginationMeta {
    page: number;
    limit: number;
    total: number;
    totalPages: number;
  }

  interface TransactionsResponse {
    success: boolean;
    data: AdminTransaction[];
    meta: PaginationMeta;
  }

  // ─── State ───
  let transactions = $state<AdminTransaction[]>([]);
  let meta = $state<PaginationMeta>({ page: 1, limit: 20, total: 0, totalPages: 0 });
  let loading = $state(true);
  let error = $state<string | null>(null);

  // Filters
  let searchQuery = $state('');
  let statusFilter = $state<StatusFilter>('ALL');
  let currentPage = $state(1);
  const limit = 20;

  // Action state
  let approvingId = $state<number | null>(null);
  let rejectingId = $state<number | null>(null);
  let txIdInputs = $state<Record<number, string>>({});
  let actionError = $state<Record<number, string>>({});

  // Copy feedback
  let copiedField = $state<string | null>(null);

  // SSE live indicator
  let sseConnected = $state(false);
  let newTransactionCount = $state(0);

  // Debounce timer
  let searchTimer: ReturnType<typeof setTimeout> | null = null;
  let debouncedSearch = $state('');

  // ─── Status config ───
  const statusConfig: Record<string, { label: string; pillClass: string; icon: typeof Clock }> = {
    PENDING: { label: 'معلق', pillClass: 'pill-gold', icon: Clock },
    COMPLETED: { label: 'مكتمل', pillClass: 'pill-mint', icon: CheckCircle2 },
    REJECTED: { label: 'مرفوض', pillClass: 'pill-rose', icon: XCircle }
  };

  const filterOptions: { value: StatusFilter; label: string }[] = [
    { value: 'ALL', label: 'الكل' },
    { value: 'PENDING', label: 'معلق' },
    { value: 'COMPLETED', label: 'مكتمل' },
    { value: 'REJECTED', label: 'مرفوض' }
  ];

  // ─── Derived ───
  let stats = $derived({
    pending: transactions.filter((t) => t.status === 'PENDING').length,
    completed: transactions.filter((t) => t.status === 'COMPLETED').length,
    rejected: transactions.filter((t) => t.status === 'REJECTED').length
  });

  let pages = $derived.by(() => {
    const arr: number[] = [];
    const start = Math.max(1, currentPage - 2);
    const end = Math.min(meta.totalPages, currentPage + 2);
    for (let i = start; i <= end; i++) arr.push(i);
    return arr;
  });

  // ─── Helpers ───
  function formatDate(iso: string): string {
    const d = new Date(iso);
    return d.toLocaleDateString('ar-EG', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  }

  function formatAmount(n: number): string {
    return n.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 8 });
  }

  function truncateMiddle(str: string, maxLen: number = 16): string {
    if (!str || str.length <= maxLen) return str || '—';
    const half = Math.floor(maxLen / 2);
    return str.slice(0, half) + '...' + str.slice(-half);
  }

  async function copyToClipboard(text: string, fieldId: string) {
    if (!text) return;
    try {
      await navigator.clipboard.writeText(text);
      copiedField = fieldId;
      setTimeout(() => {
        copiedField = null;
      }, 2000);
    } catch {
      // fallback
      const ta = document.createElement('textarea');
      ta.value = text;
      document.body.appendChild(ta);
      ta.select();
      document.execCommand('copy');
      document.body.removeChild(ta);
      copiedField = fieldId;
      setTimeout(() => {
        copiedField = null;
      }, 2000);
    }
  }

  // ─── Fetch ───
  async function fetchTransactions() {
    loading = true;
    error = null;
    try {
      const params = new URLSearchParams({
        page: String(currentPage),
        limit: String(limit)
      });
      if (debouncedSearch) params.set('search', debouncedSearch);
      if (statusFilter !== 'ALL') params.set('status', statusFilter);

      const res = await authGet(`/api/v1/admin/transactions?${params}`);
      if (!res.ok) throw new Error('فشل تحميل المعاملات');
      const json: TransactionsResponse = await res.json();
      if (json.success) {
        transactions = json.data;
        meta = json.meta;
      }
    } catch (e: any) {
      error = e.message;
    } finally {
      loading = false;
    }
  }

  // ─── Actions ───
  async function approveTransaction(id: number) {
    const txId = txIdInputs[id]?.trim();
    if (!txId) {
      actionError[id] = 'يرجى إدخال معرف المعاملة (TxID)';
      return;
    }
    approvingId = id;
    actionError[id] = '';
    try {
      const res = await authPut(`/api/v1/admin/transactions/${id}/review`, {
        action: 'approve',
        tx_id: txId
      });
      if (!res.ok) {
        const body = await res.json().catch(() => ({}));
        throw new Error(body.message || 'فشل قبول المعاملة');
      }
      // Update local state optimistically
      transactions = transactions.map((t) =>
        t.id === id ? { ...t, status: 'COMPLETED', tx_id: txId } : t
      );
      delete txIdInputs[id];
    } catch (e: any) {
      actionError[id] = e.message;
    } finally {
      approvingId = null;
    }
  }

  async function rejectTransaction(id: number) {
    rejectingId = id;
    actionError[id] = '';
    try {
      const res = await authPut(`/api/v1/admin/transactions/${id}/review`, {
        action: 'reject'
      });
      if (!res.ok) {
        const body = await res.json().catch(() => ({}));
        throw new Error(body.message || 'فشل رفض المعاملة');
      }
      transactions = transactions.map((t) =>
        t.id === id ? { ...t, status: 'REJECTED' } : t
      );
    } catch (e: any) {
      actionError[id] = e.message;
    } finally {
      rejectingId = null;
    }
  }

  // ─── Filter handlers ───
  function handleSearchInput() {
    if (searchTimer) clearTimeout(searchTimer);
    searchTimer = setTimeout(() => {
      debouncedSearch = searchQuery;
      currentPage = 1;
      fetchTransactions();
    }, 400);
  }

  function handleStatusChange(status: StatusFilter) {
    statusFilter = status;
    currentPage = 1;
    fetchTransactions();
  }

  function goToPage(page: number) {
    if (page < 1 || page > meta.totalPages || page === currentPage) return;
    currentPage = page;
    fetchTransactions();
  }

  // ─── SSE ───
  function connectSSE() {
    const es = createAdminStream(['transaction']);
    if (!es) return null;

    es.onopen = () => {
      sseConnected = true;
    };

    es.addEventListener('transaction', () => {
      newTransactionCount++;
    });

    es.onerror = () => {
      sseConnected = false;
      setTimeout(() => {
        es.close();
        connectSSE();
      }, 5000);
    };

    return es;
  }

  function refreshWithNew() {
    newTransactionCount = 0;
    fetchTransactions();
  }

  // ─── Lifecycle ───
  let eventSource: EventSource | null = $state(null);

  onMount(() => {
    fetchTransactions();
    eventSource = connectSSE();

    return () => {
      eventSource?.close();
    };
  });
</script>

<!-- ─── Page Content ─── -->
<div class="relative z-10 space-y-6">

  <!-- ─── Header ─── -->
  <div class="flex items-center justify-between flex-wrap gap-4">
    <div>
      <h1 class="text-2xl lg:text-3xl font-extrabold text-gold-gradient">المعاملات</h1>
      <p class="text-sm mt-1" style="color: var(--text-tertiary);">إدارة الإيداعات والسحوبات</p>
    </div>

    <div class="flex items-center gap-3">
      {#if sseConnected}
        <span class="pill-mint">
          <span class="relative flex h-2 w-2">
            <span class="animate-ping absolute inline-flex h-full w-full rounded-full opacity-75" style="background: #22d3a4;"></span>
            <span class="relative inline-flex rounded-full h-2 w-2" style="background: #22d3a4;"></span>
          </span>
          مباشر
        </span>
      {:else}
        <span class="pill-rose">
          <span class="inline-flex rounded-full h-2 w-2" style="background: #f43f7a;"></span>
          غير متصل
        </span>
      {/if}

      {#if newTransactionCount > 0}
        <button
          class="pill-gold flex items-center gap-2 cursor-pointer animate-pulse-glow"
          onclick={refreshWithNew}
        >
          <BellRing size={14} />
          <span>{newTransactionCount} معاملة جديدة</span>
          <RefreshCw size={12} />
        </button>
      {/if}
    </div>
  </div>

  <!-- ─── Error Banner ─── -->
  {#if error}
    <div class="panel p-4 flex items-center gap-3" style="border-color: rgba(244,63,122,0.3);">
      <AlertCircle size={20} style="color: #f43f7a;" />
      <p class="text-sm" style="color: #f43f7a;">{error}</p>
      <button class="btn-ghost mr-auto" onclick={() => fetchTransactions()}>
        <RefreshCw size={14} />
      </button>
    </div>
  {/if}

  <!-- ─── Stats Row ─── -->
  <div class="grid grid-cols-1 sm:grid-cols-3 gap-4">
    <div class="stat-card flex items-center gap-4">
      <div class="flex items-center justify-center w-11 h-11 rounded-xl" style="background: rgba(245,181,68,0.12);">
        <Clock size={20} style="color: #f5b544;" />
      </div>
      <div>
        <p class="text-xs font-medium" style="color: var(--text-tertiary);">معلق</p>
        <p class="text-2xl font-bold font-mono" style="color: #f5b544;">{stats.pending}</p>
      </div>
    </div>

    <div class="stat-card flex items-center gap-4">
      <div class="flex items-center justify-center w-11 h-11 rounded-xl" style="background: rgba(34,211,164,0.12);">
        <CheckCircle2 size={20} style="color: #22d3a4;" />
      </div>
      <div>
        <p class="text-xs font-medium" style="color: var(--text-tertiary);">مكتمل</p>
        <p class="text-2xl font-bold font-mono" style="color: #22d3a4;">{stats.completed}</p>
      </div>
    </div>

    <div class="stat-card flex items-center gap-4">
      <div class="flex items-center justify-center w-11 h-11 rounded-xl" style="background: rgba(244,63,122,0.12);">
        <XCircle size={20} style="color: #f43f7a;" />
      </div>
      <div>
        <p class="text-xs font-medium" style="color: var(--text-tertiary);">مرفوض</p>
        <p class="text-2xl font-bold font-mono" style="color: #f43f7a;">{stats.rejected}</p>
      </div>
    </div>
  </div>

  <!-- ─── Filters ─── -->
  <div class="panel p-4">
    <div class="flex flex-col sm:flex-row gap-3">
      <!-- Search -->
      <div class="relative flex-1">
        <Search size={18} class="absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none" style="color: var(--text-quaternary);" />
        <input
          type="text"
          class="input-field pr-10"
          placeholder="بحث باسم المستخدم، البريد، أو العملة..."
          bind:value={searchQuery}
          oninput={handleSearchInput}
        />
      </div>

      <!-- Status Filter -->
      <div class="flex items-center gap-1.5 flex-wrap">
        <Filter size={16} style="color: var(--text-quaternary);" class="shrink-0" />
        {#each filterOptions as opt}
          <button
            class="px-3 py-2 rounded-lg text-xs font-semibold transition-all cursor-pointer"
            class:ring-1={statusFilter === opt.value}
            style={statusFilter === opt.value
              ? 'background: rgba(245,181,68,0.12); color: #f5b544; ring-color: rgba(245,181,68,0.3);'
              : 'background: rgba(255,255,255,0.04); color: var(--text-secondary);'}
            onclick={() => handleStatusChange(opt.value)}
          >
            {opt.label}
          </button>
        {/each}
      </div>
    </div>
  </div>

  <!-- ─── Data Table ─── -->
  <div class="panel overflow-hidden">
    <div class="overflow-x-auto scrollbar-none">
      <table class="w-full text-sm">
        <thead>
          <tr style="color: var(--text-tertiary); background: rgba(255,255,255,0.02);" class="text-xs">
            <th class="text-right py-3.5 px-4 font-medium">المستخدم</th>
            <th class="text-right py-3.5 px-4 font-medium">النوع</th>
            <th class="text-right py-3.5 px-4 font-medium">العملة</th>
            <th class="text-right py-3.5 px-4 font-medium">المبلغ</th>
            <th class="text-right py-3.5 px-4 font-medium">الحالة</th>
            <th class="text-right py-3.5 px-4 font-medium hidden lg:table-cell">العنوان</th>
            <th class="text-right py-3.5 px-4 font-medium hidden xl:table-cell">TxID</th>
            <th class="text-right py-3.5 px-4 font-medium">الإجراءات</th>
          </tr>
        </thead>

        <tbody>
          {#if loading}
            <!-- Skeleton rows -->
            {#each Array(8) as _, i}
              <tr class="border-t" style="border-color: var(--border-subtle);">
                <td class="py-3.5 px-4" colspan="8">
                  <div class="flex items-center gap-4">
                    <div class="animate-shimmer h-8 w-8 rounded-full" style="background: rgba(255,255,255,0.06);"></div>
                    <div class="flex-1 space-y-2">
                      <div class="animate-shimmer h-3 w-1/4 rounded" style="background: rgba(255,255,255,0.06);"></div>
                      <div class="animate-shimmer h-3 w-1/6 rounded" style="background: rgba(255,255,255,0.04);"></div>
                    </div>
                  </div>
                </td>
              </tr>
            {/each}
          {:else if transactions.length === 0}
            <tr>
              <td colspan="8" class="py-16 text-center">
                <ArrowLeftRight size={48} class="mx-auto mb-4 opacity-20" style="color: var(--text-quaternary);" />
                <p class="text-sm font-medium" style="color: var(--text-quaternary);">لا توجد معاملات</p>
                <p class="text-xs mt-1" style="color: var(--text-quaternary);">قم بتغيير عوامل التصفية أو انتظر معاملات جديدة</p>
              </td>
            </tr>
          {:else}
            {#each transactions as tx (tx.id)}
              {@const cfg = statusConfig[tx.status] ?? statusConfig.PENDING}
              {@const isPending = tx.status === 'PENDING'}
              {@const isActing = approvingId === tx.id || rejectingId === tx.id}
              <tr
                class="border-t transition-colors hover:bg-white/[0.02]"
                style="border-color: var(--border-subtle);"
              >
                <!-- المستخدم -->
                <td class="py-3.5 px-4">
                  <div class="flex items-center gap-2.5">
                    <div
                      class="flex items-center justify-center w-8 h-8 rounded-full text-xs font-bold shrink-0"
                      style="background: rgba(168,85,247,0.12); color: #a855f7;"
                    >
                      {tx.username?.charAt(0)?.toUpperCase() || '?'}
                    </div>
                    <div class="min-w-0">
                      <p class="font-medium truncate max-w-[130px]">{tx.username || '—'}</p>
                      <p class="text-xs truncate max-w-[130px]" style="color: var(--text-quaternary);">{tx.email || '—'}</p>
                    </div>
                  </div>
                </td>

                <!-- النوع -->
                <td class="py-3.5 px-4">
                  {#if tx.type === 'deposit'}
                    <span class="pill-mint">
                      <TrendingUp size={12} />
                      إيداع
                    </span>
                  {:else}
                    <span class="pill-rose">
                      <TrendingDown size={12} />
                      سحب
                    </span>
                  {/if}
                </td>

                <!-- العملة -->
                <td class="py-3.5 px-4">
                  <span class="font-mono font-semibold text-xs" style="color: var(--accent-cyan);">
                    {tx.currency?.toUpperCase() || '—'}
                  </span>
                </td>

                <!-- المبلغ -->
                <td class="py-3.5 px-4">
                  <span class="font-mono font-semibold tabular-nums">
                    {formatAmount(tx.amount)}
                  </span>
                </td>

                <!-- الحالة -->
                <td class="py-3.5 px-4">
                  <span class={cfg.pillClass}>
                    <cfg.icon size={12} />
                    {cfg.label}
                  </span>
                </td>

                <!-- العنوان -->
                <td class="py-3.5 px-4 hidden lg:table-cell">
                  {#if tx.address}
                    <div class="flex items-center gap-1.5">
                      <span
                        class="font-mono text-xs truncate max-w-[140px] cursor-pointer hover:underline"
                        style="color: var(--text-secondary);"
                        title={tx.address}
                        onclick={() => copyToClipboard(tx.address, `addr-${tx.id}`)}
                      >
                        {truncateMiddle(tx.address)}
                      </span>
                      <button
                        class="shrink-0 p-1 rounded transition-colors hover:bg-white/5 cursor-pointer"
                        onclick={() => copyToClipboard(tx.address, `addr-${tx.id}`)}
                        title="نسخ العنوان"
                      >
                        {#if copiedField === `addr-${tx.id}`}
                          <Check size={12} style="color: #22d3a4;" />
                        {:else}
                          <Copy size={12} style="color: var(--text-quaternary);" />
                        {/if}
                      </button>
                    </div>
                  {:else}
                    <span style="color: var(--text-quaternary);">—</span>
                  {/if}
                </td>

                <!-- TxID -->
                <td class="py-3.5 px-4 hidden xl:table-cell">
                  {#if tx.tx_id}
                    <div class="flex items-center gap-1.5">
                      <span
                        class="font-mono text-xs truncate max-w-[140px] cursor-pointer hover:underline"
                        style="color: var(--text-secondary);"
                        title={tx.tx_id}
                        onclick={() => copyToClipboard(tx.tx_id, `txid-${tx.id}`)}
                      >
                        {truncateMiddle(tx.tx_id)}
                      </span>
                      <button
                        class="shrink-0 p-1 rounded transition-colors hover:bg-white/5 cursor-pointer"
                        onclick={() => copyToClipboard(tx.tx_id, `txid-${tx.id}`)}
                        title="نسخ TxID"
                      >
                        {#if copiedField === `txid-${tx.id}`}
                          <Check size={12} style="color: #22d3a4;" />
                        {:else}
                          <Copy size={12} style="color: var(--text-quaternary);" />
                        {/if}
                      </button>
                    </div>
                  {:else}
                    <span style="color: var(--text-quaternary);">—</span>
                  {/if}
                </td>

                <!-- الإجراءات -->
                <td class="py-3.5 px-4">
                  {#if isPending}
                    <div class="space-y-2 min-w-[200px]">
                      <!-- Inline TxID input for approve -->
                      <div class="flex items-center gap-2">
                        <div class="relative flex-1">
                          <Hash size={12} class="absolute right-2.5 top-1/2 -translate-y-1/2 pointer-events-none" style="color: var(--text-quaternary);" />
                          <input
                            type="text"
                            class="w-full px-3 py-1.5 pr-8 rounded-lg text-xs font-mono outline-none transition-all"
                            style="background: rgba(255,255,255,0.04); border: 1px solid rgba(255,255,255,0.08); color: var(--text-primary);"
                            placeholder="أدخل TxID..."
                            bind:value={txIdInputs[tx.id]}
                            onfocus={(e) => {
                              (e.target as HTMLInputElement).style.borderColor = 'rgba(245,181,68,0.5)';
                              (e.target as HTMLInputElement).style.boxShadow = '0 0 0 3px rgba(245,181,68,0.1)';
                            }}
                            onblur={(e) => {
                              (e.target as HTMLInputElement).style.borderColor = 'rgba(255,255,255,0.08)';
                              (e.target as HTMLInputElement).style.boxShadow = 'none';
                            }}
                          />
                        </div>
                        <button
                          class="btn-buy px-3 py-1.5 text-xs flex items-center gap-1 shrink-0"
                          onclick={() => approveTransaction(tx.id)}
                          disabled={isActing}
                        >
                          {#if approvingId === tx.id}
                            <Loader2 size={12} class="animate-spin" />
                          {:else}
                            <CheckCircle2 size={12} />
                          {/if}
                          قبول
                        </button>
                      </div>

                      <!-- Reject button -->
                      <div class="flex items-center gap-2">
                        <button
                          class="btn-danger px-3 py-1.5 text-xs flex items-center gap-1"
                          onclick={() => rejectTransaction(tx.id)}
                          disabled={isActing}
                        >
                          {#if rejectingId === tx.id}
                            <Loader2 size={12} class="animate-spin" />
                          {:else}
                            <XCircle size={12} />
                          {/if}
                          رفض
                        </button>

                        {#if actionError[tx.id]}
                          <span class="text-xs" style="color: #f43f7a;">{actionError[tx.id]}</span>
                        {/if}
                      </div>
                    </div>
                  {:else}
                    <span class="text-xs" style="color: var(--text-quaternary);">—</span>
                  {/if}
                </td>
              </tr>
            {/each}
          {/if}
        </tbody>
      </table>
    </div>

    <!-- ─── Pagination ─── -->
    {#if !loading && meta.totalPages > 1}
      <div class="glass-divider"></div>
      <div class="flex items-center justify-between px-4 py-3">
        <p class="text-xs" style="color: var(--text-quaternary);">
          عرض {((currentPage - 1) * limit) + 1}–{Math.min(currentPage * limit, meta.total)} من {meta.total}
        </p>

        <div class="flex items-center gap-1">
          <button
            class="p-1.5 rounded-lg transition-colors cursor-pointer hover:bg-white/5 disabled:opacity-30 disabled:cursor-not-allowed"
            onclick={() => goToPage(currentPage - 1)}
            disabled={currentPage <= 1}
          >
            <ChevronRight size={16} style="color: var(--text-secondary);" />
          </button>

          {#if pages[0] > 1}
            <button
              class="w-8 h-8 rounded-lg text-xs font-medium transition-colors cursor-pointer hover:bg-white/5"
              style="color: var(--text-secondary);"
              onclick={() => goToPage(1)}
            >
              1
            </button>
            {#if pages[0] > 2}
              <span class="w-8 text-center text-xs" style="color: var(--text-quaternary);">...</span>
            {/if}
          {/if}

          {#each pages as p}
            <button
              class="w-8 h-8 rounded-lg text-xs font-semibold transition-colors cursor-pointer {p !== currentPage ? 'hover:bg-white/5' : ''}"
              style={p === currentPage
                ? 'background: rgba(245,181,68,0.15); color: #f5b544;'
                : 'color: var(--text-secondary);'}
              onclick={() => goToPage(p)}
            >
              {p}
            </button>
          {/each}

          {#if pages[pages.length - 1] < meta.totalPages}
            {#if pages[pages.length - 1] < meta.totalPages - 1}
              <span class="w-8 text-center text-xs" style="color: var(--text-quaternary);">...</span>
            {/if}
            <button
              class="w-8 h-8 rounded-lg text-xs font-medium transition-colors cursor-pointer hover:bg-white/5"
              style="color: var(--text-secondary);"
              onclick={() => goToPage(meta.totalPages)}
            >
              {meta.totalPages}
            </button>
          {/if}

          <button
            class="p-1.5 rounded-lg transition-colors cursor-pointer hover:bg-white/5 disabled:opacity-30 disabled:cursor-not-allowed"
            onclick={() => goToPage(currentPage + 1)}
            disabled={currentPage >= meta.totalPages}
          >
            <ChevronLeft size={16} style="color: var(--text-secondary);" />
          </button>
        </div>
      </div>
    {/if}
  </div>
</div>
