// frontend/src/routes/dashboard/admin/transactions/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { authGet, parseApiResponse } from '$lib/api/client';
  import { formatPrice, formatDate } from '$lib/utils/format';
  import { Check, X, Clock, ArrowRightLeft } from 'lucide-svelte';
  import { toasts } from '$lib/stores/toast';

  let transactions = $state<any[]>([]);
  let loading = $state(true);
  let filter = $state<'all' | 'pending' | 'approved' | 'rejected'>('pending');

  onMount(() => {
(async () => {
    await loadTransactions();
    loading = false;
  
  })();
});

  async function loadTransactions() {
    try {
      const res = await authGet(`/api/v1/admin/transactions?status=${filter}`);
      const data = await parseApiResponse<any>(res);
      transactions = data?.transactions || data || [];
    } catch {
      transactions = [];
    }
  }

  $effect(() => {
    loadTransactions();
  });

  async function approve(id: number) {
    try {
      const { authPost } = await import('$lib/api/client');
      await authPost(`/api/v1/admin/transactions/${id}/approve`);
      toasts.success('تمت الموافقة');
      loadTransactions();
    } catch {
      toasts.error('فشل');
    }
  }

  async function reject(id: number) {
    try {
      const { authPost } = await import('$lib/api/client');
      await authPost(`/api/v1/admin/transactions/${id}/reject`);
      toasts.success('تم الرفض');
      loadTransactions();
    } catch {
      toasts.error('فشل');
    }
  }
</script>

<svelte:head><title>المعاملات — لوحة الإدارة</title></svelte:head>

<div class="space-y-5">
  <div>
    <h1 class="text-2xl sm:text-3xl font-bold text-white">المعاملات</h1>
    <p class="text-sm text-slate-400 mt-1">إدارة طلبات الإيداع والسحب</p>
  </div>

  <div class="flex gap-1">
    {#each [{ k: 'pending', l: 'معلّقة' }, { k: 'approved', l: 'موافق عليها' }, { k: 'rejected', l: 'مرفوضة' }, { k: 'all', l: 'الكل' }] as f}
      <button
        onclick={() => (filter = f.k as any)}
        class="px-3 py-1.5 rounded-lg text-xs font-medium transition-colors {filter === f.k ? 'bg-accent-gold/15 text-accent-gold' : 'bg-white/[0.03] text-slate-400 hover:bg-white/5'}"
      >
        {f.l}
      </button>
    {/each}
  </div>

  <div class="panel overflow-hidden">
    {#if loading}
      <div class="p-6 space-y-3">
        {#each Array(5) as _}<div class="h-12 rounded-xl bg-white/5 animate-shimmer"></div>{/each}
      </div>
    {:else if transactions.length === 0}
      <div class="py-16 text-center text-slate-500">
        <ArrowRightLeft size={40} class="mx-auto mb-3 opacity-30" />
        <p class="text-sm">لا توجد معاملات</p>
      </div>
    {:else}
      <div class="overflow-x-auto">
        <table class="w-full text-sm">
          <thead>
            <tr class="text-[10px] uppercase tracking-wider text-slate-500 border-b border-white/5">
              <th class="text-right font-medium px-5 py-3">المستخدم</th>
              <th class="text-right font-medium px-5 py-3">النوع</th>
              <th class="text-right font-medium px-5 py-3">العملة</th>
              <th class="text-right font-medium px-5 py-3">المبلغ</th>
              <th class="text-right font-medium px-5 py-3">التاريخ</th>
              <th class="text-right font-medium px-5 py-3">الحالة</th>
              <th class="text-left font-medium px-5 py-3">إجراءات</th>
            </tr>
          </thead>
          <tbody>
            {#each transactions as t}
              <tr class="border-b border-white/5 last:border-0 hover:bg-white/[0.02]">
                <td class="px-5 py-3 text-slate-300">{t.user_username || t.user_id}</td>
                <td class="px-5 py-3">
                  <span class="pill {t.type === 'DEPOSIT' ? 'pill-mint' : 'pill-rose'}">
                    {t.type === 'DEPOSIT' ? 'إيداع' : 'سحب'}
                  </span>
                </td>
                <td class="px-5 py-3 font-semibold text-white">{t.currency}</td>
                <td class="px-5 py-3 font-mono text-slate-300 tabular-nums">{formatPrice(t.amount, 6)}</td>
                <td class="px-5 py-3 text-xs text-slate-400">{formatDate(t.created_at)}</td>
                <td class="px-5 py-3">
                  <span class="pill {t.status === 'APPROVED' || t.status === 'COMPLETED' ? 'pill-mint' : t.status === 'PENDING' ? 'pill-gold' : 'pill-rose'}">
                    {t.status === 'APPROVED' || t.status === 'COMPLETED' ? 'موافق' : t.status === 'PENDING' ? 'معلّق' : 'مرفوض'}
                  </span>
                </td>
                <td class="px-5 py-3 text-left">
                  {#if t.status === 'PENDING'}
                    <div class="flex gap-1 justify-end">
                      <button onclick={() => approve(t.id)} class="p-1.5 rounded-lg text-accent-mint hover:bg-accent-mint/10" aria-label="موافقة">
                        <Check size={14} />
                      </button>
                      <button onclick={() => reject(t.id)} class="p-1.5 rounded-lg text-accent-rose hover:bg-accent-rose/10" aria-label="رفض">
                        <X size={14} />
                      </button>
                    </div>
                  {/if}
                </td>
              </tr>
            {/each}
          </tbody>
        </table>
      </div>
    {/if}
  </div>
</div>

// admin/src/app/dashboard/transactions/page.tsx
"use client";

import { useEffect, useState } from "react";
import toast from "react-hot-toast";
import { Search, Check, X, Copy, CheckCircle2 } from "lucide-react";
import { authGet, authPut } from "@/lib/api";

export default function AdminTransactionsPage() {
  const [transactions, setTransactions] = useState<any[]>([]);
  const [search, setSearch] = useState("");
  const [loading, setLoading] = useState(true);
  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);
  const [reviewingId, setReviewingId] = useState<number | null>(null);
  const [txInputs, setTxInputs] = useState<Record<number, string>>({});
  const [copiedId, setCopiedId] = useState<number | null>(null);

  const fetchTransactions = () => {
    const token = localStorage.getItem("token");
    if (!token) return;
    setLoading(true);
    authGet(`/api/v1/admin/transactions?page=${page}&limit=20`)
      .then(r => r.json()).then(d => {
        const data = d.data;
        setTransactions(Array.isArray(data) ? data : []);
        if (d.total) setTotalPages(Math.ceil(d.total / 20));
      }).catch(() => {}).finally(() => setLoading(false));
  };

  useEffect(() => { fetchTransactions(); }, [page]);

  const handleReview = async (id: number, action: "approve" | "reject") => {
    setReviewingId(id);
    try {
      const body: any = { action };
      if (action === "approve" && txInputs[id]) body.tx_id = txInputs[id];
      const res = await authPut(`/api/v1/admin/transactions/${id}/review`, body);
      const data = await res.json();
      if (!res.ok) { toast.error(data.error || "فشل المراجعة"); return; }
      toast.success(data.message || (action === "approve" ? "تمت الموافقة على المعاملة" : "تم رفض المعاملة"));
      fetchTransactions();
    } catch { toast.error("حدث خطأ في الاتصال"); }
    finally { setReviewingId(null); }
  };

  const filtered = transactions.filter(t =>
    t.user?.username?.toLowerCase().includes(search.toLowerCase()) ||
    t.user?.email?.toLowerCase().includes(search.toLowerCase()) ||
    t.currency?.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold">المعاملات</h1>
        <p className="text-muted-foreground mt-1">إدارة عمليات السحب والإيداع</p>
      </div>

      <div className="relative max-w-md">
        <Search className="absolute right-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
        <input type="text" className="input-field pr-10" placeholder="بحث..." value={search} onChange={e => setSearch(e.target.value)} />
      </div>

      <div className="glass-panel rounded-2xl overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-border/50">
                <th className="text-right p-4 text-muted-foreground font-medium">المستخدم</th>
                <th className="text-right p-4 text-muted-foreground font-medium">النوع</th>
                <th className="text-right p-4 text-muted-foreground font-medium">العملة</th>
                <th className="text-right p-4 text-muted-foreground font-medium">الكمية</th>
                <th className="text-right p-4 text-muted-foreground font-medium">العنوان</th>
                <th className="text-right p-4 text-muted-foreground font-medium">TxID</th>
                <th className="text-right p-4 text-muted-foreground font-medium">الحالة</th>
                <th className="text-right p-4 text-muted-foreground font-medium">التاريخ</th>
                <th className="text-right p-4 text-muted-foreground font-medium">إجراءات</th>
              </tr>
            </thead>
            <tbody>
              {filtered.map((tx: any, i: number) => (
                <tr key={i} className="border-b border-border/20 hover:bg-muted/10 transition-all">
                  <td className="p-4">
                    <div>
                      <p className="font-medium">{tx.user?.username || tx.username || "—"}</p>
                      <p className="text-[10px] text-muted-foreground">{tx.user?.email || tx.email || ""}</p>
                    </div>
                  </td>
                  <td className="p-4">
                    <span className={`text-[11px] px-2 py-0.5 rounded font-medium ${tx.type === "deposit" ? "bg-emerald-500/10 text-emerald-500" : "bg-red-500/10 text-red-500"}`}>
                      {tx.type === "deposit" ? "إيداع" : "سحب"}
                    </span>
                  </td>
                  <td className="p-4 font-medium">{tx.currency}</td>
                  <td className="p-4 tabular-nums">{parseFloat(tx.amount || "0").toFixed(8)}</td>
                  <td className="p-4">
                    <div className="flex items-center gap-1">
                      <span className="text-xs text-muted-foreground max-w-[100px] truncate block">{tx.address || "—"}</span>
                      {tx.address && (
                        <button onClick={() => { navigator.clipboard.writeText(tx.address); setCopiedId(tx.id); setTimeout(() => setCopiedId(null), 2000); }} className="text-muted-foreground hover:text-foreground flex-shrink-0">
                          {copiedId === tx.id ? <CheckCircle2 className="h-3 w-3 text-emerald-500" /> : <Copy className="h-3 w-3" />}
                        </button>
                      )}
                    </div>
                  </td>
                  <td className="p-4">
                    <div className="flex items-center gap-1">
                      <span className="text-xs text-muted-foreground max-w-[80px] truncate block">{tx.tx_id || "—"}</span>
                      {tx.tx_id && (
                        <button onClick={() => { navigator.clipboard.writeText(tx.tx_id); setCopiedId(tx.id); setTimeout(() => setCopiedId(null), 2000); }} className="text-muted-foreground hover:text-foreground flex-shrink-0">
                          {copiedId === tx.id ? <CheckCircle2 className="h-3 w-3 text-emerald-500" /> : <Copy className="h-3 w-3" />}
                        </button>
                      )}
                    </div>
                  </td>
                  <td className="p-4">
                    <span className={`text-[11px] px-2 py-0.5 rounded font-medium ${
                      tx.status === "COMPLETED" ? "bg-emerald-500/10 text-emerald-500" :
                      tx.status === "PENDING" ? "bg-yellow-500/10 text-yellow-500" :
                      "bg-red-500/10 text-red-500"
                    }`}>
                      {tx.status === "COMPLETED" ? "مكتمل" : tx.status === "PENDING" ? "قيد الانتظار" : "مرفوض"}
                    </span>
                  </td>
                  <td className="p-4 text-muted-foreground text-xs">{tx.created_at ? new Date(tx.created_at).toLocaleDateString("ar-EG", { year: "numeric", month: "short", day: "numeric" }) : "—"}</td>
                  <td className="p-4">
                    {tx.status === "PENDING" && (
                      <div className="flex items-center gap-2">
                        <div className="flex flex-col gap-1">
                          <input
                            type="text"
                            className="input-field text-xs py-1 px-2 w-24"
                            placeholder="TxID"
                            value={txInputs[tx.id] || ""}
                            onChange={e => setTxInputs(prev => ({ ...prev, [tx.id]: e.target.value }))}
                          />
                          <div className="flex gap-1">
                            <button onClick={() => handleReview(tx.id, "approve")} disabled={reviewingId === tx.id} className="p-1.5 rounded-lg bg-emerald-500/10 text-emerald-500 hover:bg-emerald-500/20 transition-all disabled:opacity-50" title="موافقة">
                              {reviewingId === tx.id ? <span className="spinner h-3 w-3" /> : <Check className="h-3.5 w-3.5" />}
                            </button>
                            <button onClick={() => handleReview(tx.id, "reject")} disabled={reviewingId === tx.id} className="p-1.5 rounded-lg bg-red-500/10 text-red-500 hover:bg-red-500/20 transition-all disabled:opacity-50" title="رفض">
                              <X className="h-3.5 w-3.5" />
                            </button>
                          </div>
                        </div>
                      </div>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        {!loading && filtered.length === 0 && <div className="text-center py-12 text-muted-foreground">لا توجد معاملات</div>}
      </div>

      {totalPages > 1 && (
        <div className="flex items-center justify-center gap-2">
          {Array.from({ length: totalPages }, (_, i) => i + 1).map(p => (
            <button key={p} onClick={() => setPage(p)} className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-all ${p === page ? "bg-primary text-primary-foreground" : "bg-muted/30 text-muted-foreground hover:bg-muted/50"}`}>
              {p}
            </button>
          ))}
        </div>
      )}
    </div>
  );
}
