// frontend/src/app/dashboard/notifications/page.tsx
"use client";

import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import toast from "react-hot-toast";
import {
  Bell,
  Check,
  CheckCheck,
  Loader2,
  Filter,
} from "lucide-react";
import { authGet, authPut } from "@/lib/api";

interface Notification {
  id: number;
  type: string;
  title: string;
  body: string;
  data: string;
  read: boolean;
  created_at: string;
}

const NOTIF_TYPES = [
  { value: "", label: "الكل" },
  { value: "ORDER_FILLED", label: "تنفيذ أوامر" },
  { value: "ORDER_CANCELLED", label: "إلغاء أوامر" },
  { value: "ORDER_TRIGGERED", label: "تفعيل أوامر" },
  { value: "DEPOSIT_APPROVED", label: "إيداعات" },
  { value: "WITHDRAWAL_APPROVED", label: "سحوبات" },
  { value: "KYC_APPROVED", label: "تحقق KYC" },
];

export default function NotificationsPage() {
  const router = useRouter();
  const [notifications, setNotifications] = useState<Notification[]>([]);
  const [loading, setLoading] = useState(true);
  const [page, setPage] = useState(1);
  const [total, setTotal] = useState(0);
  const [unreadCount, setUnreadCount] = useState(0);
  const [filter, setFilter] = useState("");
  const limit = 20;

  useEffect(() => {
    const token = localStorage.getItem("token");
    if (!token) {
      router.push("/login");
      return;
    }
    fetchNotifications();
  }, [router, page, filter]);

  const fetchNotifications = async () => {
    setLoading(true);
    try {
      const res = await authGet(
        `/api/v1/notifications?limit=${limit}&page=${page}`
      );
      if (res.ok) {
        const data = await res.json();
        let notifs = data.data || [];
        if (filter) {
          notifs = notifs.filter((n: Notification) => n.type === filter);
        }
        setNotifications(notifs);
        setTotal(data.total || notifs.length);
        setUnreadCount(data.unread_count || 0);
      }
    } catch {
      toast.error("حدث خطأ في الاتصال");
    } finally {
      setLoading(false);
    }
  };

  const handleMarkRead = async (id: number) => {
    try {
      await authPut(`/api/v1/notifications/${id}/read`);
      setNotifications((prev) =>
        prev.map((n) => (n.id === id ? { ...n, read: true } : n))
      );
      setUnreadCount((prev) => Math.max(0, prev - 1));
    } catch {
      toast.error("حدث خطأ");
    }
  };

  const handleMarkAllRead = async () => {
    try {
      await authPut("/api/v1/notifications/read-all");
      setNotifications((prev) => prev.map((n) => ({ ...n, read: true })));
      setUnreadCount(0);
      toast.success("تم تعيين الكل كمقروء");
    } catch {
      toast.error("حدث خطأ");
    }
  };

  const getNotifIcon = (type: string) => {
    switch (type) {
      case "ORDER_FILLED": return "✅";
      case "ORDER_CANCELLED": return "❌";
      case "ORDER_TRIGGERED": return "⚡";
      case "DEPOSIT_APPROVED": return "💰";
      case "WITHDRAWAL_APPROVED": return "📤";
      case "WITHDRAWAL_REJECTED": return "🚫";
      case "KYC_APPROVED": return "🛡️";
      case "KYC_REJECTED": return "⚠️";
      default: return "🔔";
    }
  };

  const getNotifColor = (type: string) => {
    switch (type) {
      case "ORDER_FILLED": return "bg-emerald-500/10";
      case "ORDER_CANCELLED": return "bg-red-500/10";
      case "ORDER_TRIGGERED": return "bg-blue-500/10";
      case "DEPOSIT_APPROVED": return "bg-emerald-500/10";
      case "WITHDRAWAL_APPROVED": return "bg-blue-500/10";
      case "WITHDRAWAL_REJECTED": return "bg-red-500/10";
      case "KYC_APPROVED": return "bg-emerald-500/10";
      case "KYC_REJECTED": return "bg-yellow-500/10";
      default: return "bg-muted/10";
    }
  };

  const formatTimeAgo = (dateStr: string) => {
    const diff = Date.now() - new Date(dateStr).getTime();
    const mins = Math.floor(diff / 60000);
    if (mins < 1) return "الآن";
    if (mins < 60) return `منذ ${mins} دقيقة`;
    const hours = Math.floor(mins / 60);
    if (hours < 24) return `منذ ${hours} ساعة`;
    const days = Math.floor(hours / 24);
    return `منذ ${days} يوم`;
  };

  const formatDate = (dateStr: string) => {
    return new Date(dateStr).toLocaleDateString("ar-EG", {
      year: "numeric",
      month: "long",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    });
  };

  const totalPages = Math.ceil(total / limit);

  return (
    <div className="space-y-6 max-w-3xl">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold flex items-center gap-3">
            <Bell className="h-7 w-7 text-emerald-500" />
            الإشعارات
            {unreadCount > 0 && (
              <span className="text-sm bg-red-500/10 text-red-400 px-2.5 py-0.5 rounded-full">
                {unreadCount} غير مقروء
              </span>
            )}
          </h1>
          <p className="text-muted-foreground mt-1">
            جميع إشعاراتك وتنبيهاتك في مكان واحد
          </p>
        </div>
        {unreadCount > 0 && (
          <button onClick={handleMarkAllRead} className="btn-ghost gap-2 text-sm">
            <CheckCheck className="h-4 w-4" />
            تعيين الكل كمقروء
          </button>
        )}
      </div>

      {/* Filter Tabs */}
      <div className="glass-panel rounded-2xl p-3">
        <div className="flex items-center gap-2 overflow-x-auto pb-1">
          <Filter className="h-4 w-4 text-muted-foreground shrink-0" />
          {NOTIF_TYPES.map((type) => (
            <button
              key={type.value}
              onClick={() => { setFilter(type.value); setPage(1); }}
              className={`px-3 py-1.5 rounded-lg text-sm whitespace-nowrap transition-colors ${
                filter === type.value
                  ? "bg-primary/10 text-primary font-medium"
                  : "text-muted-foreground hover:bg-muted/30"
              }`}
            >
              {type.label}
            </button>
          ))}
        </div>
      </div>

      {/* Notifications List */}
      {loading ? (
        <div className="flex items-center justify-center min-h-[40vh]">
          <Loader2 className="h-8 w-8 animate-spin text-emerald-500" />
        </div>
      ) : notifications.length === 0 ? (
        <div className="glass-panel rounded-2xl p-12 text-center">
          <div className="w-20 h-20 mx-auto mb-4 rounded-full bg-muted/10 flex items-center justify-center">
            <Bell className="h-10 w-10 text-muted-foreground" />
          </div>
          <h2 className="text-xl font-bold mb-2">لا توجد إشعارات</h2>
          <p className="text-muted-foreground">
            {filter ? "لا توجد إشعارات من هذا النوع" : "ستظهر إشعاراتك هنا عند استلامها"}
          </p>
        </div>
      ) : (
        <div className="space-y-2">
          {notifications.map((notif) => (
            <div
              key={notif.id}
              className={`glass-panel rounded-xl p-4 transition-colors cursor-pointer hover:bg-muted/5 ${
                !notif.read ? "border-l-4 border-l-primary" : ""
              }`}
              onClick={() => !notif.read && handleMarkRead(notif.id)}
            >
              <div className="flex items-start gap-3">
                <div className={`w-10 h-10 rounded-xl ${getNotifColor(notif.type)} flex items-center justify-center shrink-0`}>
                  <span className="text-lg">{getNotifIcon(notif.type)}</span>
                </div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 mb-1">
                    <h3 className={`text-sm font-medium ${!notif.read ? "text-foreground" : "text-muted-foreground"}`}>
                      {notif.title}
                    </h3>
                    {!notif.read && <span className="h-2 w-2 rounded-full bg-primary shrink-0" />}
                  </div>
                  <p className="text-sm text-muted-foreground leading-relaxed">{notif.body}</p>
                  <p className="text-xs text-muted-foreground/70 mt-2">
                    {formatDate(notif.created_at)} · {formatTimeAgo(notif.created_at)}
                  </p>
                </div>
                {!notif.read && (
                  <button
                    onClick={(e) => { e.stopPropagation(); handleMarkRead(notif.id); }}
                    className="shrink-0 p-1.5 rounded-lg hover:bg-muted/30 text-muted-foreground hover:text-primary transition-colors"
                    title="تعيين كمقروء"
                  >
                    <Check className="h-4 w-4" />
                  </button>
                )}
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Pagination */}
      {totalPages > 1 && (
        <div className="flex items-center justify-center gap-2 pt-4">
          <button onClick={() => setPage((p) => Math.max(1, p - 1))} disabled={page === 1} className="btn-ghost text-sm disabled:opacity-30">
            السابق
          </button>
          <span className="text-sm text-muted-foreground">
            صفحة {page} من {totalPages}
          </span>
          <button onClick={() => setPage((p) => Math.min(totalPages, p + 1))} disabled={page === totalPages} className="btn-ghost text-sm disabled:opacity-30">
            التالي
          </button>
        </div>
      )}
    </div>
  );
}

// frontend/src/routes/dashboard/notifications/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { notifications as notifApi } from '$lib/api/endpoints';
  import { parseApiResponse } from '$lib/api/client';
  import { toasts } from '$lib/stores/toast';
  import { timeAgo } from '$lib/utils/format';
  import NavTabs from '$lib/components/NavTabs.svelte';
  import {
    Bell, Check, CheckCheck, Zap, Ban, Banknote, SendHorizonal,
    ShieldCheck, AlertTriangle, X, Filter
  } from 'lucide-svelte';

  let notifications = $state<any[]>([]);
  let loading = $state(true);
  let tab = $state<'all' | 'unread' | 'trading' | 'wallet' | 'security'>('all');

  onMount(() => {
(async () => {
    await loadNotifications();
    loading = false;
  
  })();
});

  async function loadNotifications() {
    try {
      const params: any = { limit: 50 };
      if (tab === 'unread') params.unread_only = true;
      const res = await notifApi.getList(params);
      notifications = (await parseApiResponse<any[]>(res)) || [];
    } catch {}
  }

  // Filter by category when on a category tab
  const filtered = $derived.by(() => {
    if (tab === 'all' || tab === 'unread') return notifications;
    if (tab === 'trading') return notifications.filter((n) => n.type?.startsWith('ORDER'));
    if (tab === 'wallet') return notifications.filter((n) => n.type?.startsWith('DEPOSIT') || n.type?.startsWith('WITHDRAWAL'));
    if (tab === 'security') return notifications.filter((n) => n.type?.startsWith('KYC'));
    return notifications;
  });

  const unreadCount = $derived(notifications.filter((n) => !n.read).length);

  async function markRead(id: number) {
    try {
      await notifApi.markRead(id);
      notifications = notifications.map((n) => (n.id === id ? { ...n, read: true } : n));
    } catch {}
  }

  async function markAllRead() {
    try {
      await notifApi.markAllRead();
      notifications = notifications.map((n) => ({ ...n, read: true }));
      toasts.success('تم تعليم الكل كمقروء');
    } catch {}
  }

  function getNotifIcon(type: string) {
    const map: Record<string, { icon: typeof Bell; bg: string; fg: string }> = {
      ORDER_FILLED: { icon: Check, bg: 'bg-accent-mint/15', fg: 'text-accent-mint' },
      ORDER_CANCELLED: { icon: Ban, bg: 'bg-accent-rose/15', fg: 'text-accent-rose' },
      ORDER_TRIGGERED: { icon: Zap, bg: 'bg-accent-gold/15', fg: 'text-accent-gold' },
      DEPOSIT_APPROVED: { icon: Banknote, bg: 'bg-accent-mint/15', fg: 'text-accent-mint' },
      WITHDRAWAL_APPROVED: { icon: SendHorizonal, bg: 'bg-accent-azure/15', fg: 'text-accent-azure' },
      WITHDRAWAL_REJECTED: { icon: AlertTriangle, bg: 'bg-accent-rose/15', fg: 'text-accent-rose' },
      KYC_APPROVED: { icon: ShieldCheck, bg: 'bg-accent-mint/15', fg: 'text-accent-mint' },
      KYC_REJECTED: { icon: AlertTriangle, bg: 'bg-accent-rose/15', fg: 'text-accent-rose' }
    };
    return map[type] || { icon: Bell, bg: 'bg-white/5', fg: 'text-slate-300' };
  }

  $effect(() => {
    loadNotifications();
  });
</script>

<svelte:head><title>الإشعارات — NEXUS</title></svelte:head>

<div class="max-w-3xl mx-auto space-y-5">
  <div class="flex items-center justify-between">
    <div>
      <h1 class="text-2xl sm:text-3xl font-bold text-white">الإشعارات</h1>
      <p class="text-sm text-slate-400 mt-1">كل تنبيهات حسابك في مكان واحد</p>
    </div>
    <button onclick={markAllRead} class="btn-ghost text-xs">
      <CheckCheck size={14} /> تعليم الكل كمقروء
    </button>
  </div>

  <!-- Nav tabs -->
  <NavTabs
    value={tab}
    onchange={(key) => (tab = key as any)}
    items={[
      { key: 'all', label: 'الكل', icon: Bell, count: notifications.length },
      { key: 'unread', label: 'غير المقروءة', icon: Filter, count: unreadCount },
      { key: 'trading', label: 'التداول', icon: Zap },
      { key: 'wallet', label: 'المحفظة', icon: Banknote },
      { key: 'security', label: 'الأمان', icon: ShieldCheck }
    ]}
  />

  <div class="panel overflow-hidden">
    {#if loading}
      <div class="p-4 space-y-3">
        {#each Array(5) as _}<div class="h-16 rounded-xl bg-white/5 animate-shimmer"></div>{/each}
      </div>
    {:else if filtered.length === 0}
      <div class="py-16 text-center text-slate-500">
        <Bell size={40} class="mx-auto mb-3 opacity-30" />
        <p class="text-sm">لا توجد إشعارات</p>
      </div>
    {:else}
      <div class="divide-y divide-white/5">
        {#each filtered as n}
          {@const ic = getNotifIcon(n.type)}
          <div class="flex items-start gap-3 px-5 py-4 hover:bg-white/[0.02] transition-colors {!n.read ? 'bg-accent-gold/[0.03]' : ''}">
            <div class="w-10 h-10 rounded-xl {ic.bg} flex items-center justify-center shrink-0">
              <ic.icon size={16} class={ic.fg} />
            </div>
            <div class="flex-1 min-w-0">
              <div class="flex items-center gap-2">
                <p class="text-sm font-semibold text-white">{n.title}</p>
                {#if !n.read}<span class="w-1.5 h-1.5 rounded-full bg-accent-gold shrink-0"></span>{/if}
              </div>
              <p class="text-xs text-slate-400 mt-1 leading-relaxed">{n.body}</p>
              <p class="text-[10px] text-slate-500 mt-1.5">{timeAgo(n.created_at)}</p>
            </div>
            {#if !n.read}
              <button
                onclick={() => markRead(n.id)}
                class="p-1.5 rounded-lg text-slate-400 hover:bg-white/5 hover:text-white shrink-0"
                aria-label="تعليم كمقروء"
              >
                <Check size={14} />
              </button>
            {/if}
          </div>
        {/each}
      </div>
    {/if}
  </div>
</div>
