// admin/src/routes/dashboard/users/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import {
    Search, Users, MailCheck, Shield, AlertCircle, Mail,
    ToggleLeft, ToggleRight, Loader2, Filter, UserCheck, UserX
  } from 'lucide-svelte';
  import StatCard from '$lib/components/StatCard.svelte';
  import Pagination from '$lib/components/Pagination.svelte';
  import EmptyState from '$lib/components/EmptyState.svelte';
  import LiveIndicator from '$lib/components/LiveIndicator.svelte';
  import PageHeader from '$lib/components/PageHeader.svelte';
  import ErrorAlert from '$lib/components/ErrorAlert.svelte';
  import { authGet, authPut } from '$lib/api/client';
  import type { AdminUser } from '$lib/api/types';
  import type { UserStats } from '$lib/api/types';
  import { createAdminStream } from '$lib/api/types';
  import { formatDate, getStatusConfig } from '$lib/utils/helpers';

  // ─── State ──────────────────────────────────────────────────
  let users = $state<AdminUser[]>([]);
  let stats = $state<UserStats | null>(null);
  let loading = $state(true);
  let statsLoading = $state(true);
  let error = $state('');
  let searchQuery = $state('');
  let roleFilter = $state('');
  let kycFilter = $state('');
  let currentPage = $state(1);
  let totalPages = $state(1);
  let totalUsers = $state(0);
  const limit = 15;
  let sseConnected = $state(false);
  let togglingUserId = $state<number | null>(null);
  let verifyingUserId = $state<number | null>(null);

  // ─── Role helpers ───────────────────────────────────────────
  const roleLabels: Record<string, string> = { ADMIN: 'مدير', USER: 'مستخدم' };
  const rolePillClasses: Record<string, string> = { ADMIN: 'pill-gold', USER: 'pill-azure' };

  // ─── Debounced search ───────────────────────────────────────
  let searchTimeout: ReturnType<typeof setTimeout>;

  $effect(() => {
    clearTimeout(searchTimeout);
    searchTimeout = setTimeout(() => {
      currentPage = 1;
      fetchUsers();
    }, 350);
  });

  // ─── Re-fetch when filters or page change ───────────────────
  $effect(() => {
    roleFilter;
    kycFilter;
    currentPage;
    fetchUsers();
  });

  // ─── API Calls ──────────────────────────────────────────────
  async function fetchUsers() {
    try {
      const params = new URLSearchParams({
        page: String(currentPage),
        limit: String(limit)
      });
      if (searchQuery) params.set('search', searchQuery);
      if (roleFilter) params.set('role', roleFilter);
      if (kycFilter) params.set('kyc_status', kycFilter);

      const res = await authGet(`/api/v1/admin/users?${params}`);
      if (!res.ok) throw new Error('فشل تحميل المستخدمين');
      const json = await res.json();
      if (json.success) {
        users = json.data;
        totalPages = json.pagination.totalPages;
        totalUsers = json.pagination.total;
      }
    } catch (e: any) {
      error = e.message || 'حدث خطأ أثناء تحميل المستخدمين';
    }
  }

  async function fetchStats() {
    try {
      statsLoading = true;
      const res = await authGet('/api/v1/admin/users/stats');
      if (!res.ok) throw new Error('فشل تحميل الإحصائيات');
      const json = await res.json();
      if (json.success) stats = json.data;
    } catch {
      /* non-fatal */
    } finally {
      statsLoading = false;
    }
  }

  async function toggleRole(user: AdminUser) {
    const newRole = user.role === 'ADMIN' ? 'USER' : 'ADMIN';
    togglingUserId = user.id;
    try {
      const res = await authPut(`/api/v1/admin/users/${user.id}/role`, { role: newRole });
      if (!res.ok) throw new Error('فشل تحديث الدور');
      const json = await res.json();
      if (json.success) {
        users = users.map(u => u.id === user.id ? { ...u, role: newRole } : u);
        fetchStats();
      }
    } catch (e: any) {
      error = e.message || 'حدث خطأ أثناء تحديث الدور';
    } finally {
      togglingUserId = null;
    }
  }

  async function verifyEmail(user: AdminUser) {
    verifyingUserId = user.id;
    try {
      const res = await authPut(`/api/v1/admin/users/${user.id}/verify-email`);
      if (!res.ok) throw new Error('فشل توثيق البريد');
      const json = await res.json();
      if (json.success) {
        users = users.map(u =>
          u.id === user.id ? { ...u, email_verified: true } : u
        );
        fetchStats();
      }
    } catch (e: any) {
      error = e.message || 'حدث خطأ أثناء توثيق البريد';
    } finally {
      verifyingUserId = null;
    }
  }

  // ─── SSE ────────────────────────────────────────────────────
  let eventSource: EventSource | null = null;

  function connectSSE() {
    const es = createAdminStream(['users', 'user-stats']);
    if (!es) return;
    es.onopen = () => { sseConnected = true; };
    es.addEventListener('users', (e) => {
      try {
        const data: AdminUser = JSON.parse(e.data);
        if (data) {
          users = users.map(u => u.id === data.id ? data : u);
        }
      } catch { /* ignore parse errors */ }
    });
    es.addEventListener('user-stats', (e) => {
      try {
        const data: UserStats = JSON.parse(e.data);
        if (data) stats = data;
      } catch { /* ignore parse errors */ }
    });
    es.onerror = () => {
      sseConnected = false;
      setTimeout(() => { es.close(); connectSSE(); }, 5000);
    };
    eventSource = es;
  }

  // ─── Lifecycle ──────────────────────────────────────────────
  onMount(async () => {
    await Promise.all([fetchUsers(), fetchStats()]);
    loading = false;
    connectSSE();
    return () => { eventSource?.close(); };
  });

  // ─── Helpers ────────────────────────────────────────────────
  function getUserInitials(user: AdminUser): string {
    if (!user.username) return '؟';
    const parts = user.username.trim().split(/\s+/);
    return parts.length >= 2
      ? parts[0][0] + parts[1][0]
      : parts[0].slice(0, 2);
  }

  function getAvatarColor(id: number): string {
    const colors = ['#f5b544', '#a855f7', '#22d3a4', '#3b82f6', '#f43f7a'];
    return colors[id % colors.length];
  }
</script>

<!-- Aurora Background -->
<div class="pointer-events-none fixed inset-0 z-0 overflow-hidden" aria-hidden="true">
  <div class="absolute -top-32 right-1/4 w-[500px] h-[500px] rounded-full opacity-[0.06] blur-[120px]" style="background: var(--accent-gold);"></div>
  <div class="absolute top-1/3 -left-20 w-[400px] h-[400px] rounded-full opacity-[0.05] blur-[100px]" style="background: var(--accent-violet);"></div>
  <div class="absolute bottom-10 right-10 w-[350px] h-[350px] rounded-full opacity-[0.04] blur-[100px]" style="background: var(--accent-mint);"></div>
</div>

<div class="relative z-10 space-y-8">
  <!-- Header -->
  <PageHeader title="إدارة المستخدمين" subtitle="عرض وإدارة حسابات المستخدمين">
    <LiveIndicator connected={sseConnected} />
  </PageHeader>

  <!-- Error Alert -->
  <ErrorAlert message={error} onclose={() => { error = ''; }} />

  <!-- Stats Row -->
  <div class="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-5">
    <StatCard
      label="إجمالي المستخدمين"
      value={stats?.total ?? 0}
      icon={Users}
      iconColor="#f5b544"
      iconBg="rgba(245,181,68,0.1)"
      chartColor="#f5b544"
      chartSeed={10}
      loading={statsLoading}
    />
    <StatCard
      label="المدراء"
      value={stats?.admins ?? 0}
      icon={Shield}
      iconColor="#a855f7"
      iconBg="rgba(168,85,247,0.1)"
      chartColor="#a855f7"
      chartSeed={11}
      loading={statsLoading}
    />
    <StatCard
      label="بريد موثّق"
      value={stats?.emailVerified ?? 0}
      icon={MailCheck}
      iconColor="#22d3a4"
      iconBg="rgba(34,211,164,0.1)"
      chartColor="#22d3a4"
      chartSeed={12}
      loading={statsLoading}
    />
    <StatCard
      label="KYC موثّق"
      value={stats?.kycVerified ?? 0}
      icon={UserCheck}
      iconColor="#3b82f6"
      iconBg="rgba(59,130,246,0.1)"
      chartColor="#3b82f6"
      chartSeed={13}
      loading={statsLoading}
    />
  </div>

  <!-- Filters & Search -->
  <div class="panel p-5">
    <div class="flex flex-col lg:flex-row items-stretch lg:items-center gap-4">
      <!-- Search -->
      <div class="relative flex-1">
        <Search size={18} class="absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none" style="color: var(--text-quaternary);" />
        <input
          type="text"
          class="input-field w-full pr-10 pl-4"
          placeholder="بحث بالاسم أو البريد الإلكتروني..."
          bind:value={searchQuery}
        />
      </div>

      <!-- Role Filter -->
      <div class="relative min-w-[160px]">
        <Filter size={16} class="absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none" style="color: var(--text-quaternary);" />
        <select class="input-field w-full pr-10 pl-4 appearance-none cursor-pointer" bind:value={roleFilter}>
          <option value="">جميع الأدوار</option>
          <option value="ADMIN">مدير</option>
          <option value="USER">مستخدم</option>
        </select>
      </div>

      <!-- KYC Filter -->
      <div class="relative min-w-[160px]">
        <Filter size={16} class="absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none" style="color: var(--text-quaternary);" />
        <select class="input-field w-full pr-10 pl-4 appearance-none cursor-pointer" bind:value={kycFilter}>
          <option value="">جميع حالات KYC</option>
          <option value="VERIFIED">موثّق</option>
          <option value="PENDING">قيد المراجعة</option>
          <option value="REJECTED">مرفوض</option>
          <option value="NONE">لا يوجد</option>
        </select>
      </div>
    </div>
  </div>

  <!-- Data Table -->
  <div class="panel overflow-hidden">
    <div class="data-table">
      <table class="w-full">
        <thead>
          <tr class="glass-divider">
            <th class="text-right px-5 py-4 text-[11px] font-semibold tracking-wider uppercase" style="color: var(--text-quaternary);">المستخدم</th>
            <th class="text-right px-5 py-4 text-[11px] font-semibold tracking-wider uppercase" style="color: var(--text-quaternary);">الدور</th>
            <th class="text-right px-5 py-4 text-[11px] font-semibold tracking-wider uppercase" style="color: var(--text-quaternary);">البريد الإلكتروني</th>
            <th class="text-right px-5 py-4 text-[11px] font-semibold tracking-wider uppercase" style="color: var(--text-quaternary);">KYC</th>
            <th class="text-right px-5 py-4 text-[11px] font-semibold tracking-wider uppercase" style="color: var(--text-quaternary);">تاريخ التسجيل</th>
            <th class="text-center px-5 py-4 text-[11px] font-semibold tracking-wider uppercase" style="color: var(--text-quaternary);">الإجراءات</th>
          </tr>
        </thead>
        <tbody>
          {#if loading}
            {#each Array(8) as _}
              <tr class="glass-divider">
                <td class="px-5 py-4">
                  <div class="flex items-center gap-3">
                    <div class="animate-shimmer w-9 h-9 rounded-full" style="background: rgba(255,255,255,0.04);"></div>
                    <div class="space-y-2">
                      <div class="animate-shimmer h-3 w-24 rounded" style="background: rgba(255,255,255,0.04);"></div>
                      <div class="animate-shimmer h-2.5 w-16 rounded" style="background: rgba(255,255,255,0.03);"></div>
                    </div>
                  </div>
                </td>
                <td class="px-5 py-4"><div class="animate-shimmer h-6 w-16 rounded-full" style="background: rgba(255,255,255,0.04);"></div></td>
                <td class="px-5 py-4"><div class="animate-shimmer h-3 w-32 rounded" style="background: rgba(255,255,255,0.04);"></div></td>
                <td class="px-5 py-4"><div class="animate-shimmer h-6 w-20 rounded-full" style="background: rgba(255,255,255,0.04);"></div></td>
                <td class="px-5 py-4"><div class="animate-shimmer h-3 w-28 rounded" style="background: rgba(255,255,255,0.04);"></div></td>
                <td class="px-5 py-4"><div class="flex justify-center gap-2"><div class="animate-shimmer h-8 w-8 rounded-lg" style="background: rgba(255,255,255,0.04);"></div><div class="animate-shimmer h-8 w-8 rounded-lg" style="background: rgba(255,255,255,0.04);"></div></div></td>
              </tr>
            {/each}
          {:else if users.length > 0}
            {#each users as user (user.id)}
              <tr class="glass-divider transition-colors hover:bg-white/[0.015]">
                <!-- User Column -->
                <td class="px-5 py-4">
                  <div class="flex items-center gap-3">
                    <div
                      class="flex items-center justify-center w-9 h-9 rounded-full text-xs font-bold shrink-0"
                      style="background: {getAvatarColor(user.id)}15; color: {getAvatarColor(user.id)};"
                    >
                      {getUserInitials(user)}
                    </div>
                    <div class="min-w-0">
                      <p class="text-sm font-semibold truncate" style="color: var(--text-primary);">{user.username || '—'}</p>
                      <p class="text-[11px] font-mono tabular-nums" style="color: var(--text-quaternary);">#{user.id}</p>
                    </div>
                  </div>
                </td>

                <!-- Role Column -->
                <td class="px-5 py-4">
                  <span class={rolePillClasses[user.role] || 'pill-azure'}>
                    {roleLabels[user.role] || user.role}
                  </span>
                </td>

                <!-- Email Column -->
                <td class="px-5 py-4">
                  <div class="flex items-center gap-2">
                    <span class="text-sm truncate max-w-[200px]" style="color: var(--text-secondary);">{user.email}</span>
                    {#if user.email_verified}
                      <MailCheck size={14} style="color: #22d3a4;" class="shrink-0" />
                    {:else}
                      <Mail size={14} style="color: var(--text-quaternary);" class="shrink-0" />
                    {/if}
                  </div>
                </td>

                <!-- KYC Column -->
                <td class="px-5 py-4">
                  <span class={getStatusConfig(user.kyc_status || 'NONE').pillClass}>{getStatusConfig(user.kyc_status || 'NONE').label}</span>
                </td>

                <!-- Registration Date Column -->
                <td class="px-5 py-4">
                  <span class="text-sm tabular-nums whitespace-nowrap" style="color: var(--text-tertiary);">
                    {formatDate(user.created_at)}
                  </span>
                </td>

                <!-- Actions Column -->
                <td class="px-5 py-4">
                  <div class="flex items-center justify-center gap-2">
                    <!-- Toggle Role -->
                    <button
                      class="btn-ghost p-2 rounded-lg transition-all duration-200 cursor-pointer"
                      title={user.role === 'ADMIN' ? 'تغيير إلى مستخدم' : 'تغيير إلى مدير'}
                      onclick={() => toggleRole(user)}
                      disabled={togglingUserId === user.id}
                    >
                      {#if togglingUserId === user.id}
                        <Loader2 size={16} class="animate-spin" style="color: var(--text-quaternary);" />
                      {:else if user.role === 'ADMIN'}
                        <ToggleRight size={16} style="color: #f5b544;" />
                      {:else}
                        <ToggleLeft size={16} style="color: var(--text-quaternary);" />
                      {/if}
                    </button>

                    <!-- Verify Email -->
                    {#if !user.email_verified}
                      <button
                        class="btn-ghost p-2 rounded-lg transition-all duration-200 cursor-pointer"
                        title="توثيق البريد الإلكتروني"
                        onclick={() => verifyEmail(user)}
                        disabled={verifyingUserId === user.id}
                      >
                        {#if verifyingUserId === user.id}
                          <Loader2 size={16} class="animate-spin" style="color: var(--text-quaternary);" />
                        {:else}
                          <MailCheck size={16} style="color: #22d3a4;" />
                        {/if}
                      </button>
                    {:else}
                      <div class="p-2">
                        <MailCheck size={16} style="color: rgba(34,211,164,0.35);" />
                      </div>
                    {/if}
                  </div>
                </td>
              </tr>
            {/each}
          {/if}
        </tbody>
      </table>
    </div>

    <!-- Empty State -->
    {#if !loading && users.length === 0}
      <EmptyState
        icon={UserX}
        title="لا يوجد مستخدمون"
        description="لم يتم العثور على مستخدمين مطابقين لمعايير البحث"
      />
    {/if}

    <!-- Pagination -->
    {#if !loading && users.length > 0}
      <div class="px-5 pb-5">
        <Pagination
          bind:page={currentPage}
          totalPages={totalPages}
          totalItems={totalUsers}
          itemLabel="مستخدم"
        />
      </div>
    {/if}
  </div>
</div>

// frontend/src/app/dashboard/admin/users/page.tsx
"use client";

import { useEffect, useState } from "react";
import toast from "react-hot-toast";
import {
  Users,
  Search,
  Loader2,
  Mail,
  Shield,
  UserCheck,
  ShieldCheck,
  ChevronLeft,
  ChevronRight,
  Inbox,
  CalendarDays,
  Filter,
  CheckCircle2,
  XCircle,
  X,
} from "lucide-react";
import { authGet, authPut } from "@/lib/api";

interface UserItem {
  id: number;
  username: string;
  email: string;
  role: string;
  email_verified: boolean;
  kyc_status: string;
  created_at: string;
}

const ROLE_OPTIONS = [
  { value: "USER", label: "مستخدم", color: "bg-blue-500/10 text-blue-400 border-blue-500/20" },
  { value: "ADMIN", label: "مدير", color: "bg-emerald-500/10 text-emerald-400 border-emerald-500/20" },
];

export default function AdminUsersPage() {
  const [users, setUsers] = useState<UserItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");
  const [roleFilter, setRoleFilter] = useState("");
  const [page, setPage] = useState(1);
  const [total, setTotal] = useState(0);
  const [updatingRole, setUpdatingRole] = useState<number | null>(null);
  const [verifyingEmail, setVerifyingEmail] = useState<number | null>(null);
  const [roleModal, setRoleModal] = useState<{ userId: number; currentRole: string } | null>(null);
  const limit = 20;
  const totalPages = Math.ceil(total / limit);

  useEffect(() => {
    fetchUsers();
  }, [page, roleFilter]);

  const fetchUsers = async () => {
    setLoading(true);
    try {
      const params = new URLSearchParams();
      if (roleFilter) params.set("role", roleFilter);
      if (search) params.set("search", search);
      params.set("page", page.toString());
      params.set("limit", limit.toString());
      const res = await authGet(`/api/v1/admin/users?${params.toString()}`);
      if (res.ok) {
        const data = await res.json();
        setUsers(Array.isArray(data.data) ? data.data : []);
        setTotal(data.total || 0);
      } else {
        toast.error("فشل تحميل المستخدمين");
      }
    } catch {
      toast.error("حدث خطأ في الاتصال");
    } finally {
      setLoading(false);
    }
  };

  const handleSearch = () => {
    setPage(1);
    fetchUsers();
  };

  const handleUpdateRole = async (userId: number, newRole: string) => {
    setUpdatingRole(userId);
    try {
      const res = await authPut(`/api/v1/admin/user/${userId}/role`, { role: newRole });
      const data = await res.json();
      if (!res.ok) {
        toast.error(data.error || "فشل تحديث الدور");
        return;
      }
      toast.success(data.message || "تم تحديث الدور بنجاح");
      setUsers(prev => prev.map(u => u.id === userId ? { ...u, role: newRole } : u));
      setRoleModal(null);
    } catch {
      toast.error("حدث خطأ في الاتصال");
    } finally {
      setUpdatingRole(null);
    }
  };

  const handleVerifyEmail = async (userId: number) => {
    setVerifyingEmail(userId);
    try {
      const res = await authPut(`/api/v1/admin/user/${userId}/verify-email`);
      const data = await res.json();
      if (!res.ok) {
        toast.error(data.error || "فشل تأكيد البريد");
        return;
      }
      toast.success(data.message || "تم تأكيد البريد الإلكتروني بنجاح");
      setUsers(prev => prev.map(u => u.id === userId ? { ...u, email_verified: true } : u));
    } catch {
      toast.error("حدث خطأ في الاتصال");
    } finally {
      setVerifyingEmail(null);
    }
  };

  const getRoleBadge = (role: string) => {
    const roleOption = ROLE_OPTIONS.find(r => r.value === role);
    if (!roleOption) return { label: role, color: "bg-gray-500/10 text-gray-400 border-gray-500/20" };
    return roleOption;
  };

  const getKycBadge = (status: string) => {
    switch (status) {
      case "APPROVED":
        return { label: "مؤكد", color: "bg-emerald-500/10 text-emerald-400 border-emerald-500/20" };
      case "PENDING":
        return { label: "معلق", color: "bg-yellow-500/10 text-yellow-400 border-yellow-500/20" };
      case "REJECTED":
        return { label: "مرفوض", color: "bg-red-500/10 text-red-400 border-red-500/20" };
      default:
        return { label: "غير مقدم", color: "bg-gray-500/10 text-gray-400 border-gray-500/20" };
    }
  };

  return (
    <div className="space-y-6">
      {/* ── Header ── */}
      <div className="animate-slide-in-up">
        <div className="flex items-center gap-3">
          <div className="h-11 w-11 rounded-xl bg-gradient-to-br from-emerald-500 to-teal-600 flex items-center justify-center shadow-lg shadow-emerald-500/20">
            <Users className="h-6 w-6 text-white" />
          </div>
          <div>
            <h1 className="text-2xl sm:text-3xl font-bold">إدارة المستخدمين</h1>
            <p className="text-muted-foreground text-sm mt-0.5">عرض وإدارة حسابات المستخدمين والأدوار</p>
          </div>
        </div>
      </div>

      {/* ── Search & Filter ── */}
      <div className="glass-panel rounded-2xl p-4 animate-slide-in-up" style={{ animationDelay: "80ms" }}>
        <div className="flex flex-col sm:flex-row gap-3">
          <div className="flex-1 relative">
            <Search className="absolute right-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
            <input
              type="text"
              className="input-field pr-10"
              placeholder="بحث بالاسم أو البريد الإلكتروني..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && handleSearch()}
            />
          </div>
          <div className="flex gap-2">
            <select
              className="input-field w-auto min-w-[140px]"
              value={roleFilter}
              onChange={(e) => { setRoleFilter(e.target.value); setPage(1); }}
            >
              <option value="">جميع الأدوار</option>
              <option value="USER">مستخدم</option>
              <option value="ADMIN">مدير</option>
            </select>
            <button onClick={handleSearch} className="btn-primary gap-2">
              <Search className="h-4 w-4" />
              بحث
            </button>
          </div>
        </div>
      </div>

      {/* ── Users Table ── */}
      <div className="glass-panel rounded-2xl overflow-hidden animate-slide-in-up" style={{ animationDelay: "160ms" }}>
        {loading ? (
          <div className="flex flex-col items-center justify-center py-20 gap-3">
            <div className="h-16 w-16 rounded-2xl bg-emerald-500/10 flex items-center justify-center">
              <Loader2 className="h-8 w-8 animate-spin text-emerald-500" />
            </div>
            <p className="text-sm text-muted-foreground">جاري تحميل المستخدمين...</p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-border/40 bg-muted/20">
                  <th className="text-right p-4 text-muted-foreground font-medium">
                    <div className="flex items-center gap-1.5"><Users className="h-3.5 w-3.5" /> المستخدم</div>
                  </th>
                  <th className="text-right p-4 text-muted-foreground font-medium">
                    <div className="flex items-center gap-1.5"><Mail className="h-3.5 w-3.5" /> البريد الإلكتروني</div>
                  </th>
                  <th className="text-right p-4 text-muted-foreground font-medium">
                    <div className="flex items-center gap-1.5"><Shield className="h-3.5 w-3.5" /> الدور</div>
                  </th>
                  <th className="text-right p-4 text-muted-foreground font-medium">
                    <div className="flex items-center gap-1.5"><ShieldCheck className="h-3.5 w-3.5" /> التحقق</div>
                  </th>
                  <th className="text-right p-4 text-muted-foreground font-medium">KYC</th>
                  <th className="text-right p-4 text-muted-foreground font-medium">
                    <div className="flex items-center gap-1.5"><CalendarDays className="h-3.5 w-3.5" /> التاريخ</div>
                  </th>
                  <th className="text-right p-4 text-muted-foreground font-medium">إجراءات</th>
                </tr>
              </thead>
              <tbody>
                {users.map((user) => {
                  const roleBadge = getRoleBadge(user.role);
                  const kycBadge = getKycBadge(user.kyc_status);
                  return (
                    <tr key={user.id} className="border-b border-border/15 hover:bg-emerald-500/[0.03] transition-all duration-200">
                      <td className="p-4">
                        <div className="flex items-center gap-3">
                          <div className="h-9 w-9 rounded-full bg-gradient-to-br from-emerald-400 to-teal-500 flex items-center justify-center shrink-0">
                            <span className="text-xs font-bold text-white">{user.username?.charAt(0)?.toUpperCase() || "U"}</span>
                          </div>
                          <span className="font-semibold">{user.username}</span>
                        </div>
                      </td>
                      <td className="p-4 text-muted-foreground" dir="ltr">
                        {user.email}
                      </td>
                      <td className="p-4">
                        <span className={`inline-flex items-center gap-1 text-[11px] px-2.5 py-1 rounded-full font-semibold border ${roleBadge.color}`}>
                          {roleBadge.label}
                        </span>
                      </td>
                      <td className="p-4">
                        {user.email_verified ? (
                          <span className="inline-flex items-center gap-1 text-[11px] px-2.5 py-1 rounded-full font-semibold bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">
                            <CheckCircle2 className="h-3 w-3" /> مؤكد
                          </span>
                        ) : (
                          <span className="inline-flex items-center gap-1 text-[11px] px-2.5 py-1 rounded-full font-semibold bg-red-500/10 text-red-400 border border-red-500/20">
                            <XCircle className="h-3 w-3" /> غير مؤكد
                          </span>
                        )}
                      </td>
                      <td className="p-4">
                        <span className={`inline-flex items-center gap-1 text-[11px] px-2.5 py-1 rounded-full font-semibold border ${kycBadge.color}`}>
                          {kycBadge.label}
                        </span>
                      </td>
                      <td className="p-4 text-muted-foreground text-xs">
                        {new Date(user.created_at).toLocaleDateString("ar-EG", {
                          year: "numeric",
                          month: "short",
                          day: "numeric",
                        })}
                      </td>
                      <td className="p-4">
                        <div className="flex items-center gap-2">
                          <button
                            onClick={() => setRoleModal({ userId: user.id, currentRole: user.role })}
                            disabled={updatingRole === user.id}
                            className="inline-flex items-center gap-1 text-xs text-blue-400 hover:text-blue-300 hover:bg-blue-500/10 px-2.5 py-1.5 rounded-lg transition-all duration-200 border border-transparent hover:border-blue-500/20"
                          >
                            {updatingRole === user.id ? (
                              <Loader2 className="h-3 w-3 animate-spin" />
                            ) : (
                              <Shield className="h-3 w-3" />
                            )}
                            تغيير الدور
                          </button>
                          {!user.email_verified && (
                            <button
                              onClick={() => handleVerifyEmail(user.id)}
                              disabled={verifyingEmail === user.id}
                              className="inline-flex items-center gap-1 text-xs text-emerald-400 hover:text-emerald-300 hover:bg-emerald-500/10 px-2.5 py-1.5 rounded-lg transition-all duration-200 border border-transparent hover:border-emerald-500/20"
                            >
                              {verifyingEmail === user.id ? (
                                <Loader2 className="h-3 w-3 animate-spin" />
                              ) : (
                                <UserCheck className="h-3 w-3" />
                              )}
                              تأكيد البريد
                            </button>
                          )}
                        </div>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}

        {/* Empty State */}
        {!loading && users.length === 0 && (
          <div className="flex flex-col items-center justify-center py-20 text-center animate-fade-in">
            <div className="h-20 w-20 rounded-2xl bg-muted/20 flex items-center justify-center mb-5">
              <Inbox className="h-10 w-10 text-muted-foreground/30" />
            </div>
            <h3 className="text-lg font-bold mb-2">لا توجد نتائج</h3>
            <p className="text-sm text-muted-foreground max-w-xs">لم يتم العثور على مستخدمين مطابقين لمعايير البحث</p>
          </div>
        )}
      </div>

      {/* ── Pagination ── */}
      {totalPages > 1 && (
        <div className="flex items-center justify-center gap-2 animate-slide-in-up" style={{ animationDelay: "240ms" }}>
          <button
            onClick={() => setPage(p => Math.max(1, p - 1))}
            disabled={page === 1}
            className="btn-ghost text-sm gap-1 disabled:opacity-30 disabled:cursor-not-allowed"
          >
            <ChevronRight className="h-4 w-4" />
            السابق
          </button>
          <div className="flex items-center gap-1 mx-2">
            {Array.from({ length: Math.min(5, totalPages) }, (_, i) => {
              let pageNum: number;
              if (totalPages <= 5) pageNum = i + 1;
              else if (page <= 3) pageNum = i + 1;
              else if (page >= totalPages - 2) pageNum = totalPages - 4 + i;
              else pageNum = page - 2 + i;
              return (
                <button
                  key={pageNum}
                  onClick={() => setPage(pageNum)}
                  className={`w-9 h-9 rounded-xl text-sm font-medium transition-all duration-200 ${
                    pageNum === page
                      ? "bg-primary/15 text-primary shadow-sm shadow-primary/10"
                      : "text-muted-foreground hover:bg-muted/30 hover:text-foreground"
                  }`}
                >
                  {pageNum}
                </button>
              );
            })}
          </div>
          <button
            onClick={() => setPage(p => Math.min(totalPages, p + 1))}
            disabled={page === totalPages}
            className="btn-ghost text-sm gap-1 disabled:opacity-30 disabled:cursor-not-allowed"
          >
            التالي
            <ChevronLeft className="h-4 w-4" />
          </button>
          <span className="text-xs text-muted-foreground pr-3 border-r border-border/30 mr-2">
            صفحة <span className="font-semibold text-foreground">{page}</span> من {totalPages}
          </span>
        </div>
      )}

      {/* ── Role Change Modal ── */}
      {roleModal && (
        <div className="fixed inset-0 bg-black/60 z-50 flex items-center justify-center p-4 animate-fade-in" style={{ backdropFilter: "blur(4px)" }}>
          <div className="glass-panel-strong rounded-2xl p-6 w-full max-w-sm animate-scale-in">
            <div className="flex items-center justify-between mb-5">
              <div className="flex items-center gap-3">
                <div className="h-9 w-9 rounded-lg bg-blue-500/10 flex items-center justify-center">
                  <Shield className="h-5 w-5 text-blue-500" />
                </div>
                <h3 className="font-bold">تغيير دور المستخدم</h3>
              </div>
              <button onClick={() => setRoleModal(null)} className="btn-ghost p-1.5 rounded-lg">
                <X className="h-4 w-4" />
              </button>
            </div>

            <p className="text-sm text-muted-foreground mb-4">
              الدور الحالي: <span className="font-semibold text-foreground">{getRoleBadge(roleModal.currentRole).label}</span>
            </p>

            <div className="space-y-2 mb-6">
              {ROLE_OPTIONS.map((role) => (
                <button
                  key={role.value}
                  onClick={() => handleUpdateRole(roleModal.userId, role.value)}
                  disabled={updatingRole === roleModal.userId}
                  className={`w-full flex items-center justify-between p-3 rounded-xl border transition-all duration-200 hover:bg-muted/20 ${
                    roleModal.currentRole === role.value
                      ? "border-primary/30 bg-primary/5"
                      : "border-border/30"
                  }`}
                >
                  <div className="flex items-center gap-3">
                    <span className={`inline-flex items-center text-[11px] px-2.5 py-1 rounded-full font-semibold border ${role.color}`}>
                      {role.label}
                    </span>
                    {roleModal.currentRole === role.value && (
                      <span className="text-[10px] text-muted-foreground">(الحالي)</span>
                    )}
                  </div>
                  {updatingRole === roleModal.userId ? (
                    <Loader2 className="h-4 w-4 animate-spin text-primary" />
                  ) : (
                    <ChevronLeft className="h-4 w-4 text-muted-foreground" />
                  )}
                </button>
              ))}
            </div>

            <button onClick={() => setRoleModal(null)} className="btn-ghost w-full">
              إلغاء
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
