// admin/src/app/dashboard/users/page.tsx
"use client";

import { useEffect, useState } from "react";
import toast from "react-hot-toast";
import { Search, Shield, ShieldOff } from "lucide-react";
import { authGet, authPut } from "@/lib/api";

export default function AdminUsersPage() {
  const [users, setUsers] = useState<any[]>([]);
  const [search, setSearch] = useState("");
  const [loading, setLoading] = useState(true);

  const fetchUsers = () => {
    const token = localStorage.getItem("token");
    if (!token) return;
    setLoading(true);
    authGet("/api/v1/admin/users")
      .then(r => r.json()).then(d => setUsers(Array.isArray(d) ? d : Array.isArray(d.users) ? d.users : [])).catch(() => {})
      .finally(() => setLoading(false));
  };

  useEffect(() => { fetchUsers(); }, []);

  const handleRoleChange = async (userId: number, role: string) => {
    try {
      const res = await authPut(`/api/v1/admin/user/${userId}/role`, { role });
      const data = await res.json();
      if (!res.ok) { toast.error(data.error || "فشل تحديث الدور"); return; }
      toast.success("تم تحديث دور المستخدم");
      fetchUsers();
    } catch { toast.error("حدث خطأ في الاتصال"); }
  };

  const filtered = users.filter(u => 
    u.username?.toLowerCase().includes(search.toLowerCase()) ||
    u.email?.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold">المستخدمين</h1>
        <p className="text-muted-foreground mt-1">إدارة مستخدمي المنصة</p>
      </div>

      <div className="relative max-w-md">
        <Search className="absolute right-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
        <input type="text" className="input-field pr-10" placeholder="بحث عن مستخدم..." value={search} onChange={e => setSearch(e.target.value)} />
      </div>

      <div className="glass-panel rounded-2xl overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-border/50">
                <th className="text-right p-4 text-muted-foreground font-medium">المستخدم</th>
                <th className="text-right p-4 text-muted-foreground font-medium">البريد</th>
                <th className="text-right p-4 text-muted-foreground font-medium">الدور</th>
                <th className="text-right p-4 text-muted-foreground font-medium">KYC</th>
                <th className="text-right p-4 text-muted-foreground font-medium">تاريخ التسجيل</th>
                <th className="text-right p-4 text-muted-foreground font-medium">إجراءات</th>
              </tr>
            </thead>
            <tbody>
              {filtered.map((u: any, i: number) => (
                <tr key={i} className="border-b border-border/20 hover:bg-muted/10 transition-all">
                  <td className="p-4">
                    <div className="flex items-center gap-3">
                      <div className="h-8 w-8 rounded-full bg-primary/20 flex items-center justify-center text-xs font-bold text-primary">{u.username?.charAt(0)?.toUpperCase()}</div>
                      <span className="font-medium">{u.username}</span>
                    </div>
                  </td>
                  <td className="p-4 text-muted-foreground">{u.email}</td>
                  <td className="p-4">
                    <span className={`text-[11px] px-2 py-0.5 rounded font-medium ${u.role === "ADMIN" ? "bg-purple-500/10 text-purple-500" : "bg-blue-500/10 text-blue-500"}`}>
                      {u.role}
                    </span>
                  </td>
                  <td className="p-4">
                    <span className={`text-[11px] px-2 py-0.5 rounded font-medium ${
                      u.kyc_status === "VERIFIED" ? "bg-emerald-500/10 text-emerald-500" :
                      u.kyc_status === "PENDING" ? "bg-yellow-500/10 text-yellow-500" :
                      u.kyc_status === "REJECTED" ? "bg-red-500/10 text-red-500" :
                      "bg-gray-500/10 text-gray-400"
                    }`}>
                      {u.kyc_status === "VERIFIED" ? "موثق" : u.kyc_status === "PENDING" ? "قيد المراجعة" : u.kyc_status === "REJECTED" ? "مرفوض" : "غير موثق"}
                    </span>
                  </td>
                  <td className="p-4 text-muted-foreground text-xs">{u.created_at ? new Date(u.created_at).toLocaleDateString("ar-EG") : "—"}</td>
                  <td className="p-4">
                    <button
                      onClick={() => handleRoleChange(u.id, u.role === "ADMIN" ? "USER" : "ADMIN")}
                      className={`p-2 rounded-lg transition-all ${u.role === "ADMIN" ? "bg-red-500/10 text-red-500 hover:bg-red-500/20" : "bg-primary/10 text-primary hover:bg-primary/20"}`}
                      title={u.role === "ADMIN" ? "إزالة صلاحية الإدارة" : "منح صلاحية الإدارة"}
                    >
                      {u.role === "ADMIN" ? <ShieldOff className="h-4 w-4" /> : <Shield className="h-4 w-4" />}
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        {!loading && filtered.length === 0 && <div className="text-center py-12 text-muted-foreground">لا يوجد مستخدمين</div>}
      </div>
    </div>
  );
}

// frontend/src/routes/dashboard/admin/users/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { authGet, parseApiResponse } from '$lib/api/client';
  import { formatPrice, formatDate, timeAgo } from '$lib/utils/format';
  import { Search, Ban, Check, UserPlus, Users as UsersIcon, RefreshCw } from 'lucide-svelte';

  let users = $state<any[]>([]);
  let loading = $state(true);
  let search = $state('');
  let filter = $state<'all' | 'verified' | 'unverified' | 'admin'>('all');

  onMount(() => {
(async () => {
    await loadUsers();
    loading = false;
  
  })();
});

  async function loadUsers() {
    try {
      const res = await authGet('/api/v1/admin/users?limit=100');
      const data = await parseApiResponse<any>(res);
      users = data?.users || data || [];
    } catch {
      users = [];
    }
  }

  const filteredUsers = $derived.by(() => {
    let list = users;
    if (filter === 'verified') list = list.filter((u) => u.email_verified);
    else if (filter === 'unverified') list = list.filter((u) => !u.email_verified);
    else if (filter === 'admin') list = list.filter((u) => u.role === 'admin' || u.role === 'ADMIN');
    if (search.trim()) {
      const q = search.trim().toLowerCase();
      list = list.filter((u) =>
        u.username?.toLowerCase().includes(q) || u.email?.toLowerCase().includes(q)
      );
    }
    return list;
  });

  async function toggleAdmin(u: any) {
    try {
      await authGet(`/api/v1/admin/users/${u.id}/role`).catch(() => {});
      await loadUsers();
    } catch {}
  }
</script>

<svelte:head><title>المستخدمين — لوحة الإدارة</title></svelte:head>

<div class="space-y-5">
  <div class="flex items-center justify-between">
    <div>
      <h1 class="text-2xl sm:text-3xl font-bold text-white">المستخدمين</h1>
      <p class="text-sm text-slate-400 mt-1">{users.length} مستخدم مسجّل</p>
    </div>
    <button onclick={loadUsers} class="btn-ghost" aria-label="تحديث">
      <RefreshCw size={16} class={loading ? 'animate-spin' : ''} />
    </button>
  </div>

  <!-- Filters + search -->
  <div class="flex flex-wrap gap-3 items-center">
    <div class="relative flex-1 min-w-64">
      <Search size={14} class="absolute right-3 top-1/2 -translate-y-1/2 text-slate-500" />
      <input
        bind:value={search}
        type="text"
        placeholder="بحث بالاسم أو البريد..."
        class="input pr-10 py-2 text-sm"
      />
    </div>
    <div class="flex gap-1">
      {#each [{ k: 'all', l: 'الكل' }, { k: 'verified', l: 'مُوثّق' }, { k: 'unverified', l: 'غير مُوثّق' }, { k: 'admin', l: 'إداري' }] as f}
        <button
          onclick={() => (filter = f.k as any)}
          class="px-3 py-1.5 rounded-lg text-xs font-medium transition-colors {filter === f.k ? 'bg-accent-gold/15 text-accent-gold' : 'bg-white/[0.03] text-slate-400 hover:bg-white/5'}"
        >
          {f.l}
        </button>
      {/each}
    </div>
  </div>

  <div class="panel overflow-hidden">
    {#if loading}
      <div class="p-6 space-y-3">
        {#each Array(8) as _}<div class="h-12 rounded-xl bg-white/5 animate-shimmer"></div>{/each}
      </div>
    {:else if filteredUsers.length === 0}
      <div class="py-16 text-center text-slate-500">
        <UsersIcon size={40} class="mx-auto mb-3 opacity-30" />
        <p class="text-sm">لا يوجد مستخدمون</p>
      </div>
    {:else}
      <div class="overflow-x-auto">
        <table class="w-full text-sm">
          <thead>
            <tr class="text-[10px] uppercase tracking-wider text-slate-500 border-b border-white/5">
              <th class="text-right font-medium px-5 py-3">المستخدم</th>
              <th class="text-right font-medium px-5 py-3">البريد</th>
              <th class="text-right font-medium px-5 py-3">الدور</th>
              <th class="text-right font-medium px-5 py-3">الحالة</th>
              <th class="text-right font-medium px-5 py-3">التسجيل</th>
              <th class="text-left font-medium px-5 py-3">إجراءات</th>
            </tr>
          </thead>
          <tbody>
            {#each filteredUsers as u}
              <tr class="border-b border-white/5 last:border-0 hover:bg-white/[0.02]">
                <td class="px-5 py-3">
                  <div class="flex items-center gap-2.5">
                    <div class="w-8 h-8 rounded-full bg-gradient-to-br from-accent-gold/30 to-accent-violet/30 border border-white/10 flex items-center justify-center text-[10px] font-bold text-white">
                      {(u.username || '??').slice(0, 2).toUpperCase()}
                    </div>
                    <span class="font-semibold text-white">{u.username}</span>
                  </div>
                </td>
                <td class="px-5 py-3 text-slate-400">{u.email}</td>
                <td class="px-5 py-3">
                  <span class="pill {u.role === 'admin' || u.role === 'ADMIN' ? 'pill-gold' : 'pill-mint'}">{u.role}</span>
                </td>
                <td class="px-5 py-3">
                  {#if u.email_verified}
                    <span class="pill-mint text-[10px]"><Check size={10} /> مُوثّق</span>
                  {:else}
                    <span class="pill-rose text-[10px]">غير مُوثّق</span>
                  {/if}
                </td>
                <td class="px-5 py-3 text-xs text-slate-400">{timeAgo(u.created_at)}</td>
                <td class="px-5 py-3 text-left">
                  <button
                    onclick={() => toggleAdmin(u)}
                    class="text-accent-gold hover:underline text-xs"
                  >
                    تبديل الدور
                  </button>
                </td>
              </tr>
            {/each}
          </tbody>
        </table>
      </div>
    {/if}
  </div>
</div>
