// admin/src/app/dashboard/page.tsx
"use client";

import { useEffect, useState, useRef } from "react";
import {
  Users,
  Wallet,
  Clock,
  TrendingUp,
  ArrowDownToLine,
  Shield,
  ScrollText,
  Activity,
  Zap,
  LayoutDashboard,
} from "lucide-react";
import { authGet } from "@/lib/api";

// ─── Count-Up Hook ───
function useCountUp(target: number, duration = 1200) {
  const [count, setCount] = useState(0);
  const started = useRef(false);

  useEffect(() => {
    if (started.current || target === 0) {
      if (target === 0) setCount(0);
      return;
    }
    started.current = true;
    const startTime = performance.now();
    const step = (now: number) => {
      const elapsed = now - startTime;
      const progress = Math.min(elapsed / duration, 1);
      const eased = 1 - Math.pow(1 - progress, 3); // ease-out cubic
      setCount(Math.round(eased * target));
      if (progress < 1) requestAnimationFrame(step);
    };
    requestAnimationFrame(step);
  }, [target, duration]);

  return count;
}

// ─── Stat Card Component ───
function StatCard({
  label,
  value,
  icon: Icon,
  colorClass,
  statCardClass,
  delay,
}: {
  label: string;
  value: number;
  icon: any;
  colorClass: string;
  statCardClass: string;
  delay: string;
}) {
  const animatedValue = useCountUp(value);
  return (
    <div
      className={`stat-card ${statCardClass} animate-slide-in-up ${delay}`}
    >
      <div className="relative z-10">
        <div
          className={`inline-flex p-2.5 rounded-xl mb-3 ${colorClass}`}
        >
          <Icon className="h-5 w-5" />
        </div>
        <p className="text-3xl font-bold tabular-nums animate-count-up">
          {animatedValue.toLocaleString("ar-EG")}
        </p>
        <p className="text-xs text-muted-foreground mt-1.5 font-medium">
          {label}
        </p>
      </div>
    </div>
  );
}

export default function AdminDashboard() {
  const [stats, setStats] = useState<any>(null);
  const [auditLogs, setAuditLogs] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const token = localStorage.getItem("token");
    if (!token) return;

    Promise.all([
      authGet("/api/v1/admin/stats").then((r) => r.json()),
      authGet("/api/v1/admin/audit-logs").then((r) => r.json()),
    ])
      .then(([statsData, logsData]) => {
        // API returns { success: true, data: { ... } }
        setStats(statsData?.data || statsData);
        const logs = logsData?.data || logsData;
        setAuditLogs(Array.isArray(logs) ? logs : []);
      })
      .catch(() => {})
      .finally(() => setLoading(false));
  }, []);

  if (loading) {
    return (
      <div className="flex items-center justify-center py-32">
        <div className="flex flex-col items-center gap-4">
          <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-emerald-500 to-teal-600 flex items-center justify-center glow-emerald animate-pulse">
            <Zap className="h-6 w-6 text-white" />
          </div>
          <span className="spinner h-6 w-6" />
          <p className="text-sm text-muted-foreground">جاري تحميل البيانات...</p>
        </div>
      </div>
    );
  }

  const statCards = [
    {
      label: "إجمالي المستخدمين",
      value: stats?.totalUsers || 0,
      icon: Users,
      colorClass: "bg-blue-500/10 text-blue-500",
      statCardClass: "stat-card-blue",
    },
    {
      label: "إجمالي الطلبات",
      value: stats?.totalOrders || 0,
      icon: TrendingUp,
      colorClass: "bg-purple-500/10 text-purple-500",
      statCardClass: "stat-card-purple",
    },
    {
      label: "إجمالي المعاملات",
      value: stats?.totalTransactions || 0,
      icon: Wallet,
      colorClass: "bg-emerald-500/10 text-emerald-500",
      statCardClass: "stat-card-emerald",
    },
    {
      label: "إيداعات معلقة",
      value: stats?.pendingDeposits || 0,
      icon: ArrowDownToLine,
      colorClass: "bg-teal-500/10 text-teal-500",
      statCardClass: "stat-card-teal",
    },
    {
      label: "سحوبات معلقة",
      value: stats?.pendingWithdrawals || 0,
      icon: Clock,
      colorClass: "bg-yellow-500/10 text-yellow-500",
      statCardClass: "stat-card-yellow",
    },
    {
      label: "تحقق معلق KYC",
      value: stats?.pendingKYC || 0,
      icon: Shield,
      colorClass: "bg-orange-500/10 text-orange-500",
      statCardClass: "stat-card-orange",
    },
  ];

  const delays = ["delay-100", "delay-200", "delay-300", "delay-400", "delay-500", "delay-600"];

  const getActionBadge = (action: string) => {
    const lower = (action || "").toLowerCase();
    if (lower.includes("login") || lower.includes("دخول"))
      return "bg-blue-500/10 text-blue-400 border-blue-500/20";
    if (lower.includes("approve") || lower.includes("موافق"))
      return "bg-emerald-500/10 text-emerald-400 border-emerald-500/20";
    if (lower.includes("reject") || lower.includes("رفض"))
      return "bg-red-500/10 text-red-400 border-red-500/20";
    if (lower.includes("update") || lower.includes("تحديث"))
      return "bg-purple-500/10 text-purple-400 border-purple-500/20";
    if (lower.includes("delete") || lower.includes("حذف"))
      return "bg-red-500/10 text-red-400 border-red-500/20";
    if (lower.includes("create") || lower.includes("إنش"))
      return "bg-teal-500/10 text-teal-400 border-teal-500/20";
    return "bg-muted/30 text-muted-foreground border-border/30";
  };

  return (
    <div className="space-y-8">
      {/* ─── Welcome Header ─── */}
      <div className="animate-slide-in-down">
        <div className="flex items-center gap-3 mb-2">
          <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-emerald-500 to-teal-600 flex items-center justify-center shadow-lg shadow-emerald-500/20">
            <LayoutDashboard className="h-5 w-5 text-white" />
          </div>
          <div>
            <h1 className="text-2xl lg:text-3xl font-bold">لوحة الإدارة</h1>
            <p className="text-sm text-muted-foreground">
              نظرة عامة على منصة EgMoney والنشاط الأخير
            </p>
          </div>
        </div>
      </div>

      {/* ─── Stat Cards Grid ─── */}
      <div className="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-6 gap-4">
        {statCards.map((item, i) => (
          <StatCard
            key={i}
            label={item.label}
            value={item.value}
            icon={item.icon}
            colorClass={item.colorClass}
            statCardClass={item.statCardClass}
            delay={delays[i]}
          />
        ))}
      </div>

      {/* ─── Audit Logs Section ─── */}
      <div className="glass-panel rounded-2xl overflow-hidden animate-slide-in-up delay-500">
        {/* Header */}
        <div className="p-6 border-b border-border/30">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="w-9 h-9 rounded-xl bg-purple-500/10 flex items-center justify-center">
                <ScrollText className="h-4.5 w-4.5 text-purple-500" />
              </div>
              <div>
                <h2 className="text-lg font-bold">سجل التدقيق</h2>
                <p className="text-xs text-muted-foreground">آخر العمليات التي قام بها المديرون</p>
              </div>
            </div>
            <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
              <Activity className="h-3.5 w-3.5 text-emerald-500" />
              <span className="status-dot-online" />
              <span>مباشر</span>
            </div>
          </div>
        </div>

        {/* Table */}
        {auditLogs.length > 0 ? (
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-border/20">
                  <th className="text-right p-4 text-muted-foreground font-medium text-xs">
                    الإجراء
                  </th>
                  <th className="text-right p-4 text-muted-foreground font-medium text-xs">
                    المدير
                  </th>
                  <th className="text-right p-4 text-muted-foreground font-medium text-xs">
                    التاريخ
                  </th>
                </tr>
              </thead>
              <tbody>
                {auditLogs.map((log: any, i: number) => (
                  <tr
                    key={i}
                    className="border-b border-border/10 hover:bg-muted/10 transition-colors duration-150"
                  >
                    <td className="p-4">
                      <span
                        className={`inline-flex items-center px-2.5 py-1 rounded-lg text-xs font-medium border ${getActionBadge(
                          log.action || log.message || ""
                        )}`}
                      >
                        {log.action || log.message}
                      </span>
                    </td>
                    <td className="p-4">
                      <div className="flex items-center gap-2">
                        <div className="h-6 w-6 rounded-full bg-primary/10 flex items-center justify-center text-[10px] font-bold text-primary">
                          {(log.username || "A")
                            .charAt(0)
                            .toUpperCase()}
                        </div>
                        <span className="text-muted-foreground text-xs">
                          {log.username || "admin"}
                        </span>
                      </div>
                    </td>
                    <td className="p-4 text-xs text-muted-foreground whitespace-nowrap">
                      {new Date(
                        log.createdAt || log.created_at
                      ).toLocaleDateString("ar-EG", {
                        year: "numeric",
                        month: "short",
                        day: "numeric",
                        hour: "2-digit",
                        minute: "2-digit",
                      })}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        ) : (
          <div className="flex flex-col items-center justify-center py-16 text-center">
            <div className="w-16 h-16 rounded-2xl bg-muted/20 flex items-center justify-center mb-4">
              <ScrollText className="h-8 w-8 text-muted-foreground/30" />
            </div>
            <p className="text-sm text-muted-foreground font-medium">لا توجد سجلات تدقيق</p>
            <p className="text-xs text-muted-foreground/50 mt-1">
              ستظهر هنا سجلات العمليات التي يقوم بها المديرون
            </p>
          </div>
        )}
      </div>
    </div>
  );
}

// admin/src/routes/dashboard/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import {
    Users, ShoppingCart, ArrowLeftRight, TrendingUp, TrendingDown,
    ShieldCheck, Activity, Clock, AlertCircle, Zap
  } from 'lucide-svelte';
  import { authGet } from '$lib/api/client';
  import type { AdminStats, AuditLog } from '$lib/api/types';
  import { createAdminStream } from '$lib/api/types';
  import { formatNumber, formatDate, getActionLabel, getActionPill, formatCompact } from '$lib/utils/helpers';
  import StatCard from '$lib/components/StatCard.svelte';
  import LiveIndicator from '$lib/components/LiveIndicator.svelte';
  import PageHeader from '$lib/components/PageHeader.svelte';

  let stats = $state<AdminStats | null>(null);
  let auditLogs = $state<AuditLog[]>([]);
  let loading = $state(true);
  let sseConnected = $state(false);
  let error = $state<string | null>(null);

  const statCards = [
    { key: 'totalUsers' as const, label: 'إجمالي المستخدمين', icon: Users, iconColor: '#f5b544', iconBg: 'rgba(245,181,68,0.1)', chartColor: '#f5b544', sparkSeed: 1 },
    { key: 'totalOrders' as const, label: 'إجمالي الأوامر', icon: ShoppingCart, iconColor: '#3b82f6', iconBg: 'rgba(59,130,246,0.1)', chartColor: '#3b82f6', sparkSeed: 2 },
    { key: 'totalTransactions' as const, label: 'إجمالي المعاملات', icon: ArrowLeftRight, iconColor: '#a855f7', iconBg: 'rgba(168,85,247,0.1)', chartColor: '#a855f7', sparkSeed: 3 },
    { key: 'pendingDeposits' as const, label: 'إيداعات معلقة', icon: TrendingUp, iconColor: '#22d3a4', iconBg: 'rgba(34,211,164,0.1)', chartColor: '#22d3a4', sparkSeed: 4 },
    { key: 'pendingWithdrawals' as const, label: 'سحوبات معلقة', icon: TrendingDown, iconColor: '#f43f7a', iconBg: 'rgba(244,63,122,0.1)', chartColor: '#f43f7a', sparkSeed: 5 },
    { key: 'pendingKYC' as const, label: 'طلبات KYC معلقة', icon: ShieldCheck, iconColor: '#3b82f6', iconBg: 'rgba(59,130,246,0.1)', chartColor: '#3b82f6', sparkSeed: 6 }
  ];

  async function fetchStats() {
    try {
      const res = await authGet('/api/v1/admin/stats');
      if (!res.ok) throw new Error('فشل تحميل الإحصائيات');
      const json = await res.json();
      if (json.success) stats = json.data;
    } catch (e: any) { error = e.message; }
  }

  async function fetchAuditLogs() {
    try {
      const res = await authGet('/api/v1/admin/audit-logs?limit=8');
      if (!res.ok) throw new Error('فشل تحميل سجل المراجعة');
      const json = await res.json();
      if (json.success) auditLogs = json.data;
    } catch { /* non-fatal */ }
  }

  let eventSource: EventSource | null = $state(null);

  function connectSSE() {
    const es = createAdminStream(['stats', 'audit']);
    if (!es) return;
    es.onopen = () => { sseConnected = true; };
    es.addEventListener('stats', (e) => {
      try { const data = JSON.parse(e.data); if (data) stats = data; } catch {}
    });
    es.addEventListener('audit', (e) => {
      try {
        const entry: AuditLog = JSON.parse(e.data);
        if (entry) auditLogs = [entry, ...auditLogs].slice(0, 8);
      } catch {}
    });
    es.onerror = () => {
      sseConnected = false;
      setTimeout(() => { es.close(); connectSSE(); }, 5000);
    };
    return es;
  }

  onMount(() => {
    (async () => {
      await Promise.all([fetchStats(), fetchAuditLogs()]);
      loading = false;
      eventSource = connectSSE() ?? null;
    })();
    return () => { eventSource?.close(); };
  });
</script>

<!-- Aurora Background -->
<div class="pointer-events-none fixed inset-0 z-0 overflow-hidden" aria-hidden="true">
  <div class="absolute -top-32 right-1/4 w-[500px] h-[500px] rounded-full opacity-[0.06] blur-[120px]" style="background: var(--accent-gold);"></div>
  <div class="absolute top-1/3 -left-20 w-[400px] h-[400px] rounded-full opacity-[0.05] blur-[100px]" style="background: var(--accent-violet);"></div>
  <div class="absolute bottom-10 right-10 w-[350px] h-[350px] rounded-full opacity-[0.04] blur-[100px]" style="background: var(--accent-mint);"></div>
</div>

<div class="relative z-10 space-y-8">
  <PageHeader title="لوحة التحكم" subtitle="نظرة عامة على النظام">
    <LiveIndicator connected={sseConnected} />
  </PageHeader>

  {#if error}
    <div class="panel p-4 flex items-center gap-3" style="border-color: rgba(244,63,122,0.2);">
      <AlertCircle size={20} style="color: #f43f7a;" />
      <p class="text-sm" style="color: #f43f7a;">{error}</p>
    </div>
  {/if}

  <!-- Stat Cards -->
  <div class="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-5">
    {#each statCards as card, i}
      <StatCard
        label={card.label}
        value={stats ? stats[card.key] : 0}
        icon={card.icon}
        iconColor={card.iconColor}
        iconBg={card.iconBg}
        chartColor={card.chartColor}
        chartSeed={card.sparkSeed}
        loading={loading}
      />
    {/each}
  </div>

  <!-- Recent Audit Logs -->
  <div class="panel p-6">
    <div class="flex items-center justify-between mb-5">
      <div class="flex items-center gap-3">
        <div class="flex items-center justify-center w-10 h-10 rounded-xl" style="background: rgba(168,85,247,0.1);">
          <Activity size={20} style="color: #a855f7;" />
        </div>
        <div>
          <h2 class="text-lg font-bold">سجل المراجعة الأخير</h2>
          <p class="text-xs" style="color: var(--text-quaternary);">آخر الأنشطة المسجلة</p>
        </div>
      </div>
      <a href="/dashboard/audit-logs" class="btn-ghost text-xs">عرض الكل</a>
    </div>

    {#if loading}
      <div class="space-y-4">
        {#each Array(5) as _}
          <div class="flex items-center gap-4">
            <div class="animate-shimmer h-8 w-8 rounded-full" style="background: rgba(255,255,255,0.04);"></div>
            <div class="flex-1 space-y-2">
              <div class="animate-shimmer h-3 w-1/3 rounded" style="background: rgba(255,255,255,0.04);"></div>
              <div class="animate-shimmer h-3 w-1/4 rounded" style="background: rgba(255,255,255,0.03);"></div>
            </div>
          </div>
        {/each}
      </div>
    {:else if auditLogs.length > 0}
      <div class="space-y-1">
        {#each auditLogs as log (log.id)}
          <div class="flex items-center gap-4 py-3 px-3 rounded-xl transition-colors hover:bg-white/[0.02]">
            <div class="flex items-center justify-center w-8 h-8 rounded-full text-xs font-bold shrink-0" style="background: rgba(59,130,246,0.08); color: #3b82f6;">
              {log.username?.charAt(0)?.toUpperCase() || '?'}
            </div>
            <div class="flex-1 min-w-0">
              <div class="flex items-center gap-2">
                <span class="font-medium text-sm truncate">{log.username || '—'}</span>
                <span class={getActionPill(log.action)}>{getActionLabel(log.action)}</span>
              </div>
              {#if log.details}
                <p class="text-xs truncate mt-0.5" style="color: var(--text-quaternary);">{log.details}</p>
              {/if}
            </div>
            <div class="flex items-center gap-1.5 shrink-0" style="color: var(--text-quaternary);">
              <Clock size={11} />
              <span class="text-[11px] whitespace-nowrap tabular-nums">{formatDate(log.createdAt)}</span>
            </div>
          </div>
        {/each}
      </div>
    {:else}
      <div class="flex flex-col items-center py-8">
        <Activity size={32} style="color: var(--text-quaternary);" />
        <p class="text-sm mt-2" style="color: var(--text-quaternary);">لا توجد سجلات مراجعة</p>
      </div>
    {/if}
  </div>

  <!-- Quick Stats Footer -->
  {#if stats}
    <div class="grid grid-cols-2 lg:grid-cols-4 gap-4">
      <div class="panel p-4 flex items-center gap-3">
        <div class="flex items-center justify-center w-9 h-9 rounded-lg" style="background: rgba(245,181,68,0.08);">
          <Zap size={18} style="color: #f5b544;" />
        </div>
        <div>
          <p class="text-[11px]" style="color: var(--text-quaternary);">المعاملات المعلقة</p>
          <p class="text-lg font-bold tabular-nums" style="color: #f5b544;">{(stats.pendingDeposits || 0) + (stats.pendingWithdrawals || 0)}</p>
        </div>
      </div>
      <div class="panel p-4 flex items-center gap-3">
        <div class="flex items-center justify-center w-9 h-9 rounded-lg" style="background: rgba(168,85,247,0.08);">
          <ShieldCheck size={18} style="color: #a855f7;" />
        </div>
        <div>
          <p class="text-[11px]" style="color: var(--text-quaternary);">KYC معلق</p>
          <p class="text-lg font-bold tabular-nums" style="color: #a855f7;">{stats.pendingKYC || 0}</p>
        </div>
      </div>
      <div class="panel p-4 flex items-center gap-3">
        <div class="flex items-center justify-center w-9 h-9 rounded-lg" style="background: rgba(34,211,164,0.08);">
          <Users size={18} style="color: #22d3a4;" />
        </div>
        <div>
          <p class="text-[11px]" style="color: var(--text-quaternary);">إجمالي المستخدمين</p>
          <p class="text-lg font-bold tabular-nums" style="color: #22d3a4;">{formatCompact(stats.totalUsers || 0)}</p>
        </div>
      </div>
      <div class="panel p-4 flex items-center gap-3">
        <div class="flex items-center justify-center w-9 h-9 rounded-lg" style="background: rgba(59,130,246,0.08);">
          <ShoppingCart size={18} style="color: #3b82f6;" />
        </div>
        <div>
          <p class="text-[11px]" style="color: var(--text-quaternary);">إجمالي الأوامر</p>
          <p class="text-lg font-bold tabular-nums" style="color: #3b82f6;">{formatCompact(stats.totalOrders || 0)}</p>
        </div>
      </div>
    </div>
  {/if}
</div>
