// frontend/src/routes/dashboard/profile/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { wallet } from '$lib/api/endpoints';
  import { authStore } from '$lib/stores/auth';
  import { parseApiResponse, ApiError } from '$lib/api/client';
  import { toasts } from '$lib/stores/toast';
  import { usdToEgp, egpCompact, usdEgpRate } from '$lib/utils/currency';
  import { wallet as walletApi } from '$lib/api/endpoints';
  import NavTabs from '$lib/components/NavTabs.svelte';
  import { User, Mail, Calendar, Shield, Save, Check, Lock, Bell, Coins, Globe } from 'lucide-svelte';

  let fullName = $state('');
  let username = $state('');
  let email = $state('');
  let loading = $state(false);
  let verified = $state(false);
  let activeTab = $state<'personal' | 'security' | 'preferences'>('personal');
  let currentRate = $state(48.5);
  let balances = $state<any[]>([]);
  let totalUsd = $state(0);
  let totalEgp = $state(0);

  // Display preferences (EGP-first by default)
  let preferredCurrency = $state<'EGP' | 'USD'>('EGP');
  let preferredLanguage = $state<'ar' | 'en'>('ar');
  let emailNotifs = $state(true);
  let pushNotifs = $state(true);

  const unsubRate = usdEgpRate.subscribe((r) => (currentRate = r));

  onMount(() => {
(async () => {
    if ($authStore) {
      fullName = $authStore.full_name || '';
      username = $authStore.username || '';
      email = $authStore.email || '';
      verified = $authStore.email_verified || false;
    }
    try {
      const res = await wallet.getUserInfo();
      const data = await parseApiResponse<any>(res);
      if (data) {
        fullName = data.full_name || fullName;
        username = data.username || username;
        email = data.email || email;
        verified = data.email_verified ?? verified;
      }
    } catch {}

    // Load balances for stats summary
    try {
      const bRes = await walletApi.getBalances();
      const data = (await parseApiResponse<any[]>(bRes)) || [];
      balances = data.filter((b) => parseFloat(b.balance) > 0);
      totalUsd = balances.reduce((sum, b) => {
        const bal = parseFloat(b.balance);
        return sum + (b.currency === 'USDT' ? bal : 0);
      }, 0);
      totalEgp = usdToEgp(totalUsd, currentRate);
    } catch {}

    // Load saved prefs
    if (typeof localStorage !== 'undefined') {
      const pc = localStorage.getItem('preferred_currency');
      if (pc === 'EGP' || pc === 'USD') preferredCurrency = pc;
      const pl = localStorage.getItem('preferred_language');
      if (pl === 'ar' || pl === 'en') preferredLanguage = pl;
    }
  })();
  return unsubRate;
});

  async function handleSave() {
    if (!fullName.trim()) {
      toasts.error('الاسم الكامل مطلوب');
      return;
    }
    loading = true;
    try {
      const res = await wallet.updateProfile({ full_name: fullName.trim() });
      await parseApiResponse(res);
      toasts.success('تم تحديث الملف الشخصي');
    } catch (err: any) {
      if (err instanceof ApiError) toasts.error(err.message);
      else toasts.error('فشل التحديث');
    } finally {
      loading = false;
    }
  }

  function savePreferences() {
    if (typeof localStorage !== 'undefined') {
      localStorage.setItem('preferred_currency', preferredCurrency);
      localStorage.setItem('preferred_language', preferredLanguage);
    }
    toasts.success('تم حفظ التفضيلات');
  }
</script>

<svelte:head><title>الملف الشخصي — NEXUS</title></svelte:head>

<div class="max-w-3xl mx-auto space-y-5">
  <div>
    <h1 class="text-2xl sm:text-3xl font-bold text-white">الملف الشخصي</h1>
    <p class="text-sm text-slate-400 mt-1">إدارة معلوماتك الشخصية وتفضيلاتك</p>
  </div>

  <!-- Profile header card -->
  <div class="panel p-6 relative overflow-hidden">
    <div class="absolute inset-0 opacity-25 pointer-events-none" aria-hidden="true">
      <div class="absolute -top-10 -right-10 w-40 h-40 bg-accent-gold/20 blur-3xl rounded-full"></div>
    </div>
    <div class="relative flex items-center gap-4">
      <div class="w-20 h-20 rounded-2xl bg-gradient-to-br from-accent-gold to-accent-rose flex items-center justify-center text-2xl font-bold text-ink-950 shrink-0">
        {(username || '??').slice(0, 2).toUpperCase()}
      </div>
      <div class="min-w-0 flex-1">
        <h2 class="text-xl font-bold text-white truncate">{fullName || username || 'مستخدم'}</h2>
        <p class="text-sm text-slate-400 truncate">{email}</p>
        <div class="flex items-center gap-2 mt-2 flex-wrap">
          {#if verified}
            <span class="pill-mint"><Check size={10} /> بريد مُوثّق</span>
          {:else}
            <span class="pill-gold">بريد غير مُوثّق</span>
          {/if}
          <span class="pill bg-accent-gold/10 text-accent-gold border border-accent-gold/20">
            <Coins size={10} /> {egpCompact(totalEgp)}
          </span>
        </div>
      </div>
    </div>
  </div>

  <!-- Nav tabs -->
  <NavTabs
    value={activeTab}
    onchange={(key) => (activeTab = key as any)}
    items={[
      { key: 'personal', label: 'المعلومات الشخصية', icon: User },
      { key: 'security', label: 'الأمان', icon: Shield },
      { key: 'preferences', label: 'التفضيلات', icon: Globe }
    ]}
  />

  {#if activeTab === 'personal'}
    <div class="panel p-6">
      <form onsubmit={(e) => { e.preventDefault(); handleSave(); }} class="space-y-4">
        <div>
          <label class="input-label" for="fullName">الاسم الكامل</label>
          <div class="relative">
            <User size={16} class="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400" />
            <input id="fullName" bind:value={fullName} type="text" class="input pr-10" placeholder="الاسم الكامل" />
          </div>
        </div>

        <div>
          <label class="input-label" for="username">اسم المستخدم</label>
          <div class="relative">
            <User size={16} class="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400" />
            <input id="username" bind:value={username} type="text" disabled class="input pr-10 opacity-60" />
          </div>
          <p class="text-[10px] text-slate-500 mt-1">لا يمكن تغيير اسم المستخدم</p>
        </div>

        <div>
          <label class="input-label" for="email">البريد الإلكتروني</label>
          <div class="relative">
            <Mail size={16} class="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400" />
            <input id="email" bind:value={email} type="email" disabled class="input pr-10 opacity-60" />
          </div>
          <p class="text-[10px] text-slate-500 mt-1">لا يمكن تغيير البريد الإلكتروني</p>
        </div>

        <button type="submit" disabled={loading} class="btn-primary">
          {#if loading}
            <svg class="animate-spin h-4 w-4" viewBox="0 0 24 24" fill="none">
              <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4" />
              <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
            </svg>
          {:else}
            <Save size={16} /> حفظ التغييرات
          {/if}
        </button>
      </form>
    </div>
  {:else if activeTab === 'security'}
    <div class="panel p-6 space-y-4">
      <h3 class="text-base font-bold text-white flex items-center gap-2">
        <Lock size={18} class="text-accent-gold" /> تغيير كلمة المرور
      </h3>
      <form onsubmit={(e) => { e.preventDefault(); toasts.info('سيتم إضافة هذه الميزة قريباً'); }} class="space-y-4">
        <div>
          <label class="input-label" for="curPwd">كلمة المرور الحالية</label>
          <input id="curPwd" type="password" class="input" placeholder="••••••••" />
        </div>
        <div class="grid sm:grid-cols-2 gap-4">
          <div>
            <label class="input-label" for="newPwd">كلمة المرور الجديدة</label>
            <input id="newPwd" type="password" class="input" placeholder="••••••••" />
          </div>
          <div>
            <label class="input-label" for="confPwd">تأكيد كلمة المرور</label>
            <input id="confPwd" type="password" class="input" placeholder="••••••••" />
          </div>
        </div>
        <button type="submit" class="btn-secondary">تغيير كلمة المرور</button>
      </form>

      <div class="border-t border-white/5 pt-4">
        <a href="/dashboard/security" class="flex items-center justify-between p-3 rounded-xl hover:bg-white/5 transition-colors">
          <div class="flex items-center gap-3">
            <Shield size={18} class="text-accent-mint" />
            <div>
              <p class="text-sm font-medium text-white">المصادقة الثنائية والجلسات</p>
              <p class="text-xs text-slate-400">إدارة 2FA والجلسات النشطة ومفاتيح API</p>
            </div>
          </div>
          <span class="text-xs text-accent-gold">→</span>
        </a>
      </div>
    </div>
  {:else if activeTab === 'preferences'}
    <div class="panel p-6 space-y-5">
      <div>
        <h3 class="text-base font-bold text-white mb-4 flex items-center gap-2">
          <Globe size={18} class="text-accent-gold" /> تفضيلات العرض
        </h3>

        <!-- Currency preference -->
        <div class="space-y-2">
          <span class="input-label">العملة الأساسية للعرض</span>
          <div class="grid grid-cols-2 gap-2">
            <button
              type="button"
              onclick={() => (preferredCurrency = 'EGP')}
              class="p-3 rounded-xl border text-right transition-all {preferredCurrency === 'EGP'
                ? 'border-accent-gold/40 bg-accent-gold/10'
                : 'border-white/10 bg-white/[0.02] hover:bg-white/5'}"
            >
              <div class="flex items-center justify-between">
                <div>
                  <p class="text-sm font-bold text-white">ج.م</p>
                  <p class="text-[10px] text-slate-400">الجنيه المصري</p>
                </div>
                {#if preferredCurrency === 'EGP'}
                  <Check size={16} class="text-accent-gold" />
                {/if}
              </div>
            </button>
            <button
              type="button"
              onclick={() => (preferredCurrency = 'USD')}
              class="p-3 rounded-xl border text-right transition-all {preferredCurrency === 'USD'
                ? 'border-accent-gold/40 bg-accent-gold/10'
                : 'border-white/10 bg-white/[0.02] hover:bg-white/5'}"
            >
              <div class="flex items-center justify-between">
                <div>
                  <p class="text-sm font-bold text-white">USD</p>
                  <p class="text-[10px] text-slate-400">دولار أمريكي</p>
                </div>
                {#if preferredCurrency === 'USD'}
                  <Check size={16} class="text-accent-gold" />
                {/if}
              </div>
            </button>
          </div>
          <p class="text-[10px] text-slate-500 mt-1">
            الجنيه المصري هو العملة الافتراضية في المنصة. سيتم عرض جميع الأرصدة والصفقات بهذه العملة.
          </p>
        </div>

        <!-- Language preference -->
        <div class="space-y-2 mt-4">
          <span class="input-label">اللغة</span>
          <div class="grid grid-cols-2 gap-2">
            <button
              type="button"
              onclick={() => (preferredLanguage = 'ar')}
              class="p-3 rounded-xl border text-right transition-all {preferredLanguage === 'ar'
                ? 'border-accent-gold/40 bg-accent-gold/10'
                : 'border-white/10 bg-white/[0.02] hover:bg-white/5'}"
            >
              <div class="flex items-center justify-between">
                <div>
                  <p class="text-sm font-bold text-white">العربية</p>
                  <p class="text-[10px] text-slate-400">RTL</p>
                </div>
                {#if preferredLanguage === 'ar'}
                  <Check size={16} class="text-accent-gold" />
                {/if}
              </div>
            </button>
            <button
              type="button"
              onclick={() => (preferredLanguage = 'en')}
              class="p-3 rounded-xl border text-right transition-all {preferredLanguage === 'en'
                ? 'border-accent-gold/40 bg-accent-gold/10'
                : 'border-white/10 bg-white/[0.02] hover:bg-white/5'}"
            >
              <div class="flex items-center justify-between">
                <div>
                  <p class="text-sm font-bold text-white">English</p>
                  <p class="text-[10px] text-slate-400">LTR</p>
                </div>
                {#if preferredLanguage === 'en'}
                  <Check size={16} class="text-accent-gold" />
                {/if}
              </div>
            </button>
          </div>
        </div>

        <!-- Notifications -->
        <div class="space-y-3 mt-4">
          <span class="input-label">الإشعارات</span>
          <label class="flex items-center justify-between p-3 rounded-xl bg-white/[0.02] border border-white/5 cursor-pointer">
            <div class="flex items-center gap-3">
              <Mail size={16} class="text-slate-300" />
              <div>
                <p class="text-sm font-medium text-white">إشعارات البريد الإلكتروني</p>
                <p class="text-[10px] text-slate-500">تلقي تحديثات الصفقات والمعاملات</p>
              </div>
            </div>
            <button
              type="button"
              aria-label="تبديل إشعارات البريد الإلكتروني"
              onclick={() => (emailNotifs = !emailNotifs)}
              class="relative w-10 h-6 rounded-full transition-colors {emailNotifs ? 'bg-accent-mint' : 'bg-white/10'}"
            >
              <span class="absolute top-0.5 {emailNotifs ? 'left-0.5' : 'right-0.5'} w-5 h-5 rounded-full bg-white transition-all"></span>
            </button>
          </label>
          <label class="flex items-center justify-between p-3 rounded-xl bg-white/[0.02] border border-white/5 cursor-pointer">
            <div class="flex items-center gap-3">
              <Bell size={16} class="text-slate-300" />
              <div>
                <p class="text-sm font-medium text-white">الإشعارات الفورية</p>
                <p class="text-[10px] text-slate-500">تنبيهات في المتصفح</p>
              </div>
            </div>
            <button
              type="button"
              aria-label="تبديل الإشعارات الفورية"
              onclick={() => (pushNotifs = !pushNotifs)}
              class="relative w-10 h-6 rounded-full transition-colors {pushNotifs ? 'bg-accent-mint' : 'bg-white/10'}"
            >
              <span class="absolute top-0.5 {pushNotifs ? 'left-0.5' : 'right-0.5'} w-5 h-5 rounded-full bg-white transition-all"></span>
            </button>
          </label>
        </div>
      </div>

      <button onclick={savePreferences} class="btn-primary w-full">
        <Save size={16} /> حفظ التفضيلات
      </button>
    </div>
  {/if}
</div>

// frontend/src/app/dashboard/profile/page.tsx
"use client";

import { useEffect, useState } from "react";
import toast from "react-hot-toast";
import {
  User,
  Mail,
  Save,
  Shield,
  Lock,
  Eye,
  EyeOff,
  MapPin,
  Phone,
  Loader2,
  BadgeCheck,
  KeyRound,
  UserCircle,
} from "lucide-react";
import { authPut, authPost } from "@/lib/api";

export default function ProfilePage() {
  const [user, setUser] = useState<any>({ username: "", email: "" });
  const [profileForm, setProfileForm] = useState({ full_name: "", country: "", phone: "" });
  const [passwordForm, setPasswordForm] = useState({ current_password: "", new_password: "", confirm_password: "" });
  const [showPwd, setShowPwd] = useState({ current: false, new: false, confirm: false });
  const [saving, setSaving] = useState(false);
  const [changingPwd, setChangingPwd] = useState(false);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const token = localStorage.getItem("token");
    if (!token) return;
    const userData = JSON.parse(localStorage.getItem("user") || "{}");
    setUser(userData);
    setProfileForm({
      full_name: userData.full_name || "",
      country: userData.country || "",
      phone: userData.phone || "",
    });
    setLoading(false);
  }, []);

  const handleUpdateProfile = async (e: React.FormEvent) => {
    e.preventDefault();
    setSaving(true);
    try {
      const res = await authPut("/api/v1/user/profile", profileForm);
      const data = await res.json();
      if (!res.ok) {
        toast.error(data.error || "فشل تحديث الملف");
        return;
      }
      const updatedUser = { ...user, ...profileForm };
      localStorage.setItem("user", JSON.stringify(updatedUser));
      setUser(updatedUser);
      toast.success("تم تحديث الملف الشخصي");
    } catch {
      toast.error("حدث خطأ في الاتصال");
    } finally {
      setSaving(false);
    }
  };

  const handleChangePassword = async (e: React.FormEvent) => {
    e.preventDefault();
    if (passwordForm.new_password !== passwordForm.confirm_password) {
      toast.error("كلمة المرور الجديدة غير متطابقة");
      return;
    }
    setChangingPwd(true);
    try {
      const res = await authPost("/api/v1/user/change-password", {
        current_password: passwordForm.current_password,
        new_password: passwordForm.new_password,
      });
      const data = await res.json();
      if (!res.ok) {
        toast.error(data.error || "فشل تغيير كلمة المرور");
        return;
      }
      toast.success("تم تغيير كلمة المرور بنجاح");
      setPasswordForm({ current_password: "", new_password: "", confirm_password: "" });
    } catch {
      toast.error("حدث خطأ في الاتصال");
    } finally {
      setChangingPwd(false);
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[60vh]">
        <Loader2 className="h-8 w-8 animate-spin text-emerald-500" />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* ── Header ── */}
      <div className="animate-slide-in-up">
        <h1 className="text-3xl font-bold flex items-center gap-3">
          <div className="h-10 w-10 rounded-xl bg-gradient-to-br from-emerald-500 to-teal-600 flex items-center justify-center shadow-lg shadow-emerald-500/20">
            <UserCircle className="h-5 w-5 text-white" />
          </div>
          الملف الشخصي
        </h1>
        <p className="text-muted-foreground mt-2 text-sm">إدارة معلومات حسابك وإعدادات الأمان</p>
      </div>

      {/* ── Two-Column Layout ── */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* LEFT: Profile Info Card */}
        <div className="glass-panel rounded-2xl overflow-hidden animate-slide-in-up" style={{ animationDelay: "100ms", animationFillMode: "both" }}>
          {/* Profile Header with gradient */}
          <div className="relative h-28 bg-gradient-to-l from-emerald-600 via-teal-600 to-emerald-700 overflow-hidden">
            <div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_30%,rgba(255,255,255,0.12),transparent_60%)]" />
            <div className="absolute inset-0 bg-dots-pattern opacity-20" />
          </div>

          {/* Avatar that overlaps the header */}
          <div className="relative px-6 -mt-12">
            <div className="inline-block">
              <div className="h-20 w-20 rounded-2xl bg-gradient-to-br from-emerald-400 to-teal-600 flex items-center justify-center text-3xl font-bold text-white ring-4 ring-card shadow-xl shadow-emerald-500/20">
                {user.username?.charAt(0)?.toUpperCase() || "U"}
              </div>
            </div>
          </div>

          {/* User Info */}
          <div className="px-6 pt-3 pb-2">
            <div className="flex items-center gap-2">
              <h2 className="text-xl font-bold">{user.full_name || user.username}</h2>
              {user.role && (
                <span className="text-[11px] px-2.5 py-0.5 rounded-full bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 font-medium flex items-center gap-1">
                  <BadgeCheck className="h-3 w-3" />
                  {user.role === "admin" ? "مدير" : user.role === "super_admin" ? "مدير عام" : "مستخدم"}
                </span>
              )}
            </div>
            <p className="text-sm text-muted-foreground mt-0.5 flex items-center gap-1.5">
              <Mail className="h-3.5 w-3.5" />
              {user.email}
            </p>
          </div>

          {/* Edit Form */}
          <form onSubmit={handleUpdateProfile} className="p-6 pt-4 space-y-5">
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium mb-2 text-muted-foreground flex items-center gap-1.5">
                  <User className="h-3.5 w-3.5" />
                  الاسم الكامل
                </label>
                <input
                  type="text"
                  className="input-field"
                  placeholder="أدخل اسمك الكامل"
                  value={profileForm.full_name}
                  onChange={(e) => setProfileForm({ ...profileForm, full_name: e.target.value })}
                />
              </div>
              <div>
                <label className="block text-sm font-medium mb-2 text-muted-foreground flex items-center gap-1.5">
                  <Mail className="h-3.5 w-3.5" />
                  البريد الإلكتروني
                </label>
                <input
                  type="email"
                  className="input-field opacity-60 cursor-not-allowed"
                  value={user.email}
                  disabled
                />
              </div>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium mb-2 text-muted-foreground flex items-center gap-1.5">
                  <MapPin className="h-3.5 w-3.5" />
                  الدولة
                </label>
                <input
                  type="text"
                  className="input-field"
                  placeholder="مصر"
                  value={profileForm.country}
                  onChange={(e) => setProfileForm({ ...profileForm, country: e.target.value })}
                />
              </div>
              <div>
                <label className="block text-sm font-medium mb-2 text-muted-foreground flex items-center gap-1.5">
                  <Phone className="h-3.5 w-3.5" />
                  رقم الهاتف
                </label>
                <input
                  type="tel"
                  className="input-field"
                  placeholder="+20 100 000 0000"
                  value={profileForm.phone}
                  onChange={(e) => setProfileForm({ ...profileForm, phone: e.target.value })}
                />
              </div>
            </div>
            <div className="pt-2">
              <button type="submit" disabled={saving} className="btn-primary gap-2 min-w-[140px]">
                {saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}
                {saving ? "جاري الحفظ..." : "حفظ التغييرات"}
              </button>
            </div>
          </form>
        </div>

        {/* RIGHT: Password Change Card */}
        <div className="glass-panel rounded-2xl p-6 animate-slide-in-up" style={{ animationDelay: "200ms", animationFillMode: "both" }}>
          {/* Lock Icon Header */}
          <div className="flex items-center gap-4 mb-6">
            <div className="h-12 w-12 rounded-xl bg-gradient-to-br from-primary/20 to-primary/5 flex items-center justify-center border border-primary/10">
              <KeyRound className="h-6 w-6 text-primary" />
            </div>
            <div>
              <h2 className="text-xl font-bold">الأمان</h2>
              <p className="text-sm text-muted-foreground">تغيير كلمة المرور</p>
            </div>
          </div>

          {/* Security level indicator */}
          <div className="p-4 rounded-xl bg-emerald-500/5 border border-emerald-500/10 mb-6 flex items-center gap-3">
            <Shield className="h-5 w-5 text-emerald-500 shrink-0" />
            <p className="text-sm text-muted-foreground">
              نوصي باستخدام كلمة مرور قوية تحتوي على أحرف كبيرة وصغيرة وأرقام ورموز.
            </p>
          </div>

          <form onSubmit={handleChangePassword} className="space-y-5">
            {/* Current Password */}
            <div>
              <label className="block text-sm font-medium mb-2 text-muted-foreground">كلمة المرور الحالية</label>
              <div className="relative">
                <div className="absolute right-3 top-1/2 -translate-y-1/2">
                  <Lock className="h-4 w-4 text-muted-foreground" />
                </div>
                <input
                  type={showPwd.current ? "text" : "password"}
                  className="input-field pr-10 pl-10"
                  placeholder="••••••••"
                  value={passwordForm.current_password}
                  onChange={(e) => setPasswordForm({ ...passwordForm, current_password: e.target.value })}
                  required
                />
                <button
                  type="button"
                  onClick={() => setShowPwd({ ...showPwd, current: !showPwd.current })}
                  className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground transition-colors"
                >
                  {showPwd.current ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
                </button>
              </div>
            </div>

            {/* New Password */}
            <div>
              <label className="block text-sm font-medium mb-2 text-muted-foreground">كلمة المرور الجديدة</label>
              <div className="relative">
                <div className="absolute right-3 top-1/2 -translate-y-1/2">
                  <Lock className="h-4 w-4 text-muted-foreground" />
                </div>
                <input
                  type={showPwd.new ? "text" : "password"}
                  className="input-field pr-10 pl-10"
                  placeholder="••••••••"
                  value={passwordForm.new_password}
                  onChange={(e) => setPasswordForm({ ...passwordForm, new_password: e.target.value })}
                  required
                  minLength={6}
                />
                <button
                  type="button"
                  onClick={() => setShowPwd({ ...showPwd, new: !showPwd.new })}
                  className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground transition-colors"
                >
                  {showPwd.new ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
                </button>
              </div>
            </div>

            {/* Confirm Password */}
            <div>
              <label className="block text-sm font-medium mb-2 text-muted-foreground">تأكيد كلمة المرور</label>
              <div className="relative">
                <div className="absolute right-3 top-1/2 -translate-y-1/2">
                  <Lock className="h-4 w-4 text-muted-foreground" />
                </div>
                <input
                  type={showPwd.confirm ? "text" : "password"}
                  className="input-field pr-10 pl-10"
                  placeholder="••••••••"
                  value={passwordForm.confirm_password}
                  onChange={(e) => setPasswordForm({ ...passwordForm, confirm_password: e.target.value })}
                  required
                  minLength={6}
                />
                <button
                  type="button"
                  onClick={() => setShowPwd({ ...showPwd, confirm: !showPwd.confirm })}
                  className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground transition-colors"
                >
                  {showPwd.confirm ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
                </button>
              </div>
              {passwordForm.confirm_password && passwordForm.new_password !== passwordForm.confirm_password && (
                <p className="text-xs text-red-400 mt-1.5 flex items-center gap-1">
                  <EyeOff className="h-3 w-3" />
                  كلمة المرور غير متطابقة
                </p>
              )}
            </div>

            <div className="pt-2">
              <button type="submit" disabled={changingPwd} className="btn-primary gap-2 min-w-[160px]">
                {changingPwd ? <Loader2 className="h-4 w-4 animate-spin" /> : <Shield className="h-4 w-4" />}
                {changingPwd ? "جاري التغيير..." : "تغيير كلمة المرور"}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
}
