// admin/src/lib/components/DataTable.svelte
<script lang="ts">
  let {
    headers = [] as { key: string; label: string; hidden?: string }[],
    rows = [] as any[],
    loading = false,
    emptyIcon = null as any,
    emptyTitle = 'لا توجد بيانات',
    emptyDescription = '',
    rowKey = 'id',
    children
  } = $props<{
    headers: { key: string; label: string; hidden?: string }[];
    rows: any[];
    loading?: boolean;
    emptyIcon?: any;
    emptyTitle?: string;
    emptyDescription?: string;
    rowKey?: string;
    children: import('svelte').Snippet<{ row: any; index: number }>;
  }>();
</script>

{#if loading}
  <div class="space-y-3">
    {#each Array(6) as _}
      <div class="panel p-4 flex items-center gap-4">
        <div class="animate-shimmer h-10 w-10 rounded-xl" style="background: rgba(255,255,255,0.05);"></div>
        <div class="flex-1 space-y-2">
          <div class="animate-shimmer h-4 w-1/3 rounded" style="background: rgba(255,255,255,0.05);"></div>
          <div class="animate-shimmer h-3 w-1/4 rounded" style="background: rgba(255,255,255,0.03);"></div>
        </div>
      </div>
    {/each}
  </div>
{:else if rows.length === 0}
  <div class="panel">
    {#if emptyIcon}
      <svelte:component this={import('./EmptyState.svelte').then(m => m.default)} icon={emptyIcon} title={emptyTitle} description={emptyDescription} />
    {:else}
      <div class="flex flex-col items-center justify-center py-12 text-center">
        <p class="text-sm" style="color: var(--text-quaternary);">{emptyTitle}</p>
      </div>
    {/if}
  </div>
{:else}
  <div class="panel overflow-hidden">
    <div class="overflow-x-auto scrollbar-none">
      <table class="data-table">
        <thead>
          <tr>
            {#each headers as h}
              <th class={h.hidden || ''}>{h.label}</th>
            {/each}
          </tr>
        </thead>
        <tbody>
          {#each rows as row, i (row[rowKey])}
            {@render children({ row, index: i })}
          {/each}
        </tbody>
      </table>
    </div>
  </div>
{/if}

// frontend/src/components/ui/DataTable.tsx
"use client";

import { ReactNode } from "react";

interface Column<T> {
  key: string;
  header: string;
  render?: (item: T) => ReactNode;
  className?: string;
}

interface DataTableProps<T> {
  columns: Column<T>[];
  data: T[];
  loading?: boolean;
  pagination?: {
    page: number;
    totalPages: number;
    onPageChange: (page: number) => void;
  };
  onRowClick?: (item: T) => void;
  emptyMessage?: string;
}

export default function DataTable<T extends Record<string, any>>({
  columns,
  data,
  loading = false,
  pagination,
  onRowClick,
  emptyMessage = "لا توجد بيانات",
}: DataTableProps<T>) {
  return (
    <div className="glass-panel rounded-2xl overflow-hidden">
      <div className="overflow-x-auto">
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b border-border/50">
              {columns.map((col) => (
                <th
                  key={col.key}
                  className={`text-right p-4 text-muted-foreground font-medium ${col.className || ""}`}
                >
                  {col.header}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {loading ? (
              <tr>
                <td colSpan={columns.length} className="text-center py-12">
                  <span className="spinner h-6 w-6 inline-block" />
                </td>
              </tr>
            ) : data.length === 0 ? (
              <tr>
                <td colSpan={columns.length} className="text-center py-12 text-muted-foreground">
                  {emptyMessage}
                </td>
              </tr>
            ) : (
              data.map((item, i) => (
                <tr
                  key={item.id || i}
                  className={`border-b border-border/20 hover:bg-muted/10 transition-all ${
                    onRowClick ? "cursor-pointer" : ""
                  }`}
                  onClick={() => onRowClick?.(item)}
                >
                  {columns.map((col) => (
                    <td key={col.key} className={`p-4 ${col.className || ""}`}>
                      {col.render
                        ? col.render(item)
                        : (item[col.key] as ReactNode) ?? "—"}
                    </td>
                  ))}
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      {pagination && pagination.totalPages > 1 && (
        <div className="flex items-center justify-between px-4 py-3 border-t border-border/30">
          <button
            onClick={() => pagination.onPageChange(pagination.page - 1)}
            disabled={pagination.page <= 1}
            className="btn-ghost text-xs disabled:opacity-30"
          >
            السابق
          </button>
          <div className="flex items-center gap-1">
            {Array.from({ length: Math.min(pagination.totalPages, 7) }, (_, i) => {
              let pageNum: number;
              if (pagination.totalPages <= 7) {
                pageNum = i + 1;
              } else if (pagination.page <= 4) {
                pageNum = i + 1;
              } else if (pagination.page >= pagination.totalPages - 3) {
                pageNum = pagination.totalPages - 6 + i;
              } else {
                pageNum = pagination.page - 3 + i;
              }
              return (
                <button
                  key={pageNum}
                  onClick={() => pagination.onPageChange(pageNum)}
                  className={`w-8 h-8 rounded-lg text-xs font-medium transition-all ${
                    pageNum === pagination.page
                      ? "bg-primary text-primary-foreground"
                      : "text-muted-foreground hover:bg-muted/30"
                  }`}
                >
                  {pageNum}
                </button>
              );
            })}
          </div>
          <button
            onClick={() => pagination.onPageChange(pagination.page + 1)}
            disabled={pagination.page >= pagination.totalPages}
            className="btn-ghost text-xs disabled:opacity-30"
          >
            التالي
          </button>
        </div>
      )}
    </div>
  );
}
