// admin/src/lib/components/EmptyState.svelte
<script lang="ts">
	let {
		icon: Icon,
		title,
		description
	}: {
		icon?: any;
		title: string;
		description?: string;
	} = $props();
</script>

<div class="flex flex-col items-center justify-center py-16 text-center">
	{#if Icon}
		<div class="w-16 h-16 rounded-2xl border border-white/8 bg-white/[0.02] flex items-center justify-center mb-4">
			<Icon size={28} class="text-ink-muted" />
		</div>
	{/if}
	<h3 class="text-lg font-bold text-ink-secondary mb-2">{title}</h3>
	{#if description}
		<p class="text-sm text-ink-muted max-w-sm">{description}</p>
	{/if}
</div>

// frontend/src/components/ui/EmptyState.tsx
"use client";

import { ReactNode } from "react";

interface EmptyStateProps {
  icon: ReactNode;
  title: string;
  description?: string;
  action?: ReactNode;
}

export default function EmptyState({ icon, title, description, action }: EmptyStateProps) {
  return (
    <div className="flex flex-col items-center justify-center py-16 px-4 text-center">
      <div className="h-16 w-16 text-muted-foreground/50 mb-4">{icon}</div>
      <h3 className="text-lg font-semibold text-foreground mb-2">{title}</h3>
      {description && (
        <p className="text-sm text-muted-foreground max-w-sm mb-4">{description}</p>
      )}
      {action && <div>{action}</div>}
    </div>
  );
}
