// frontend/src/components/ui/Modal.tsx
"use client";

import { ReactNode, useEffect } from "react";
import { X } from "lucide-react";

interface ModalProps {
  isOpen: boolean;
  onClose: () => void;
  title: string;
  children: ReactNode;
  footer?: ReactNode;
  maxWidth?: string;
}

export default function Modal({
  isOpen,
  onClose,
  title,
  children,
  footer,
  maxWidth = "max-w-lg",
}: ModalProps) {
  useEffect(() => {
    if (isOpen) {
      document.body.style.overflow = "hidden";
    } else {
      document.body.style.overflow = "";
    }
    return () => {
      document.body.style.overflow = "";
    };
  }, [isOpen]);

  if (!isOpen) return null;

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm"
      onClick={onClose}
    >
      <div
        className={`relative ${maxWidth} w-full mx-4 glass-panel-strong rounded-2xl shadow-2xl`}
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between p-5 border-b border-border/30">
          <h3 className="text-lg font-bold">{title}</h3>
          <button
            onClick={onClose}
            className="p-2 rounded-lg hover:bg-muted/20 transition-all"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Body */}
        <div className="p-5">{children}</div>

        {/* Footer */}
        {footer && (
          <div className="flex items-center justify-end gap-3 p-5 border-t border-border/30">
            {footer}
          </div>
        )}
      </div>
    </div>
  );
}

// admin/src/lib/components/Modal.svelte
<script lang="ts">
	import { X } from 'lucide-svelte';
	import type { Snippet } from 'svelte';

	interface Props {
		open: boolean;
		title: string;
		onclose: () => void;
		children: Snippet;
		footer?: Snippet;
	}

	let { open, title, onclose, children, footer }: Props = $props();
</script>

{#if open}
	<div class="fixed inset-0 z-[9000] flex items-center justify-center p-4" onclick={onclose}>
		<div class="absolute inset-0 bg-black/60 backdrop-blur-sm"></div>
		<div class="panel relative w-full max-w-lg p-6 z-10" onclick={(e) => e.stopPropagation()}>
			<div class="flex items-center justify-between mb-4">
				<h2 class="text-lg font-bold">{title}</h2>
				<button onclick={onclose} class="btn-ghost p-1">
					<X size={18} />
				</button>
			</div>
			{@render children()}
			{#if footer}
				<div class="flex gap-3 justify-end mt-6 pt-4 glass-divider">
					{@render footer()}
				</div>
			{/if}
		</div>
	</div>
{/if}
