// frontend/src/routes/login/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { goto } from '$app/navigation';
  import { page } from '$app/stores';
  import { auth } from '$lib/api/endpoints';
  import { parseApiResponse, forceLogout } from '$lib/api/client';
  import { authStore } from '$lib/stores/auth';
  import { toasts } from '$lib/stores/toast';
  import Button from '$lib/components/Button.svelte';
  import {
    Mail, Lock, Eye, EyeOff, ArrowLeft, ShieldCheck, Zap, TrendingUp,
    Loader2, Fingerprint, Sparkles, Crown, Activity, ChevronLeft
  } from 'lucide-svelte';
  import ParticleBackground from '$lib/components/ParticleBackground.svelte';

  let email = $state('');
  let password = $state('');
  let twoFaCode = $state('');
  let showPassword = $state(false);
  let loading = $state(false);
  let requires2FA = $state(false);
  let tempToken = $state('');
  let errors = $state<Record<string, string>>({});

  onMount(() => {
    if (authStore.isAuthenticated()) {
      goto('/dashboard');
    }
  });

  async function handleSubmit(e: Event) {
    e.preventDefault();
    errors = {};

    if (!email.trim()) {
      errors.email = 'البريد الإلكتروني مطلوب';
      return;
    }
    if (!password) {
      errors.password = 'كلمة المرور مطلوبة';
      return;
    }

    loading = true;
    try {
      if (requires2FA) {
        if (!twoFaCode.trim() || twoFaCode.length !== 6) {
          errors.twoFaCode = 'أدخل رمز 2FA المكوّن من 6 أرقام';
          loading = false;
          return;
        }
        const res = await auth.verify2FA(tempToken, twoFaCode);
        const data = await parseApiResponse<{
          token: string;
          refresh_token: string;
          user: any;
        }>(res);
        localStorage.setItem('token', data.token);
        localStorage.setItem('refresh_token', data.refresh_token);
        localStorage.setItem('user', JSON.stringify(data.user));
        authStore.setUser(data.user);
        toasts.success('مرحباً بعودتك!');
        await goto('/dashboard');
        return;
      }

      const res = await auth.login({ email: email.trim(), password });
      const data = await res.json();

      if (data.requires_2fa) {
        requires2FA = true;
        tempToken = data.temp_token;
        toasts.info('أدخل رمز المصادقة الثنائية');
        loading = false;
        return;
      }

      if (!res.ok) throw new Error(data.error || 'فشل تسجيل الدخول');

      localStorage.setItem('token', data.token || data.data?.token);
      localStorage.setItem('refresh_token', data.refresh_token || data.data?.refresh_token);
      localStorage.setItem('user', JSON.stringify(data.user || data.data?.user));
      authStore.setUser(data.user || data.data?.user);
      toasts.success('مرحباً بعودتك!');
      await goto('/dashboard');
    } catch (err: any) {
      toasts.error(err.message || 'فشل تسجيل الدخول. تحقق من بياناتك.');
    } finally {
      loading = false;
    }
  }

  const features = [
    { icon: Zap, label: 'تنفيذ فوري', sub: '< 10 مللي ثانية', color: 'mint' },
    { icon: ShieldCheck, label: 'أمان مصرفي', sub: '2FA + تشفير', color: 'azure' },
    { icon: TrendingUp, label: 'سيولة عالية', sub: '+200 زوج تداول', color: 'gold' }
  ];

  // Static class lookups (Tailwind JIT safe)
  const colorClasses: Record<string, { bg: string; border: string; text: string }> = {
    mint: { bg: 'bg-accent-mint/10', border: 'border-accent-mint/20', text: 'text-accent-mint' },
    azure: { bg: 'bg-accent-azure/10', border: 'border-accent-azure/20', text: 'text-accent-azure' },
    gold: { bg: 'bg-accent-gold/10', border: 'border-accent-gold/20', text: 'text-accent-gold' },
    violet: { bg: 'bg-accent-violet/10', border: 'border-accent-violet/20', text: 'text-accent-violet' },
    rose: { bg: 'bg-accent-rose/10', border: 'border-accent-rose/20', text: 'text-accent-rose' }
  };
</script>

<ParticleBackground />

<div class="min-h-screen flex items-center justify-center p-4 sm:p-6 relative">
  <!-- Top fixed gradient strip -->
  <div class="fixed top-0 inset-x-0 h-px pointer-events-none z-50" style="background: linear-gradient(90deg, transparent, rgba(245, 181, 68, 0.5), rgba(168, 85, 247, 0.4), transparent);"></div>

  <div class="w-full max-w-5xl grid lg:grid-cols-2 gap-0 panel-glow overflow-hidden relative" style="min-height: 620px;">
    <!-- Inner topbar gradient highlight -->
    <div class="absolute top-0 inset-x-0 h-px pointer-events-none z-10" style="background: linear-gradient(90deg, transparent 10%, rgba(245, 181, 68, 0.6) 50%, transparent 90%);"></div>

    <!-- Left side — brand showcase -->
    <div class="relative hidden lg:flex flex-col justify-between p-10 overflow-hidden">
      <div class="absolute inset-0 bg-gradient-to-br from-accent-violet/12 via-transparent to-accent-gold/12"></div>
      <div class="absolute top-0 right-0 w-72 h-72 bg-accent-gold/15 rounded-full blur-3xl -translate-y-1/2 translate-x-1/2 animate-float"></div>
      <div class="absolute bottom-0 left-0 w-72 h-72 bg-accent-violet/15 rounded-full blur-3xl translate-y-1/2 -translate-x-1/2 animate-float" style="animation-delay: 2s;"></div>
      <div class="absolute inset-0 grid-bg opacity-20"></div>

      <!-- Logo -->
      <div class="relative z-10">
        <a href="/" class="flex items-center gap-2.5 group">
          <div class="relative w-10 h-10 rounded-xl bg-gradient-to-br from-accent-gold via-accent-rose to-accent-violet flex items-center justify-center font-black text-ink-950 text-lg transition-transform group-hover:scale-105">
            <span class="absolute inset-0 rounded-xl opacity-50 blur-md bg-gradient-to-br from-accent-gold to-accent-violet"></span>
            <span class="relative">N</span>
          </div>
          <span class="text-xl font-bold text-white tracking-tight">NEXUS Exchange</span>
        </a>
      </div>

      <!-- Hero text -->
      <div class="relative z-10 space-y-6">
        <div class="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-accent-gold/10 border border-accent-gold/25 text-accent-gold text-[10px] font-bold tracking-wide">
          <span class="relative flex h-1.5 w-1.5">
            <span class="animate-ping absolute inline-flex h-full w-full rounded-full bg-accent-gold opacity-60"></span>
            <span class="relative inline-flex rounded-full h-1.5 w-1.5 bg-accent-gold"></span>
          </span>
          منصة التداول رقم 1 في الشرق الأوسط
        </div>

        <h1 class="text-4xl font-bold leading-tight text-balance tracking-tight">
          منصة التداول
          <span class="text-aurora block" style="text-shadow: 0 0 30px rgba(245, 181, 68, 0.25);">الأكثر احترافية</span>
        </h1>
        <p class="text-slate-300 text-lg leading-relaxed">
          تداول بثقة على منصة تجمع بين السرعة والأمان والسيولة العالية. انضم إلى آلاف المتداولين المحترفين.
        </p>

        <!-- Features list — premium style -->
        <div class="space-y-3 pt-2">
          {#each features as feat}
            {@const c = colorClasses[feat.color]}
            <div class="flex items-center gap-3 text-slate-200 group">
              <div class="w-10 h-10 rounded-xl {c.bg} {c.border} border flex items-center justify-center group-hover:scale-105 transition-transform">
                <feat.icon size={17} class={c.text} />
              </div>
              <div class="flex-1">
                <p class="text-sm font-semibold text-white">{feat.label}</p>
                <p class="text-[11px] text-slate-400">{feat.sub}</p>
              </div>
              <ChevronLeft size={14} class="text-slate-600 group-hover:text-slate-400 group-hover:-translate-x-1 transition-all" />
            </div>
          {/each}
        </div>
      </div>

      <!-- Footer -->
      <div class="relative z-10 flex items-center justify-between">
        <div class="text-xs text-slate-400">© 2026 NEXUS Exchange</div>
        <div class="flex items-center gap-1.5 text-[10px] text-slate-500">
          <Activity size={10} class="text-accent-mint" />
          <span>جميع الأنظمة تعمل</span>
        </div>
      </div>
    </div>

    <!-- Right side — login form -->
    <div class="p-8 sm:p-12 flex flex-col justify-center bg-ink-950/40 relative">
      <div class="absolute inset-0 pointer-events-none" style="background: radial-gradient(ellipse 100% 60% at 50% 0%, rgba(168, 85, 247, 0.05), transparent 60%);"></div>

      <!-- Mobile logo -->
      <div class="lg:hidden mb-8 flex items-center gap-2.5 relative">
        <div class="relative w-10 h-10 rounded-xl bg-gradient-to-br from-accent-gold via-accent-rose to-accent-violet flex items-center justify-center font-black text-ink-950 text-lg">
          <span class="absolute inset-0 rounded-xl opacity-50 blur-md bg-gradient-to-br from-accent-gold to-accent-violet"></span>
          <span class="relative">N</span>
        </div>
        <span class="text-xl font-bold text-white tracking-tight">NEXUS</span>
      </div>

      <div class="mb-8 relative">
        <div class="flex items-center gap-2 mb-2">
          {#if requires2FA}
            <div class="w-9 h-9 rounded-xl bg-accent-violet/10 border border-accent-violet/20 flex items-center justify-center">
              <Fingerprint size={18} class="text-accent-violet" />
            </div>
          {:else}
            <div class="w-9 h-9 rounded-xl bg-accent-gold/10 border border-accent-gold/20 flex items-center justify-center">
              <Lock size={18} class="text-accent-gold" />
            </div>
          {/if}
          <h2 class="text-2xl font-bold text-white tracking-tight">
            {requires2FA ? 'تحقق ثنائي' : 'تسجيل الدخول'}
          </h2>
        </div>
        <p class="text-slate-400 text-sm">
          {requires2FA
            ? 'أدخل رمز المصادقة من تطبيق المصادقة لديك'
            : 'أدخل بياناتك للوصول إلى حسابك'}
        </p>
      </div>

      <form onsubmit={handleSubmit} class="space-y-5">
        {#if requires2FA}
          <div>
            <label class="input-label" for="2fa">رمز التحقق</label>
            <input
              id="2fa"
              bind:value={twoFaCode}
              type="text"
              maxlength="6"
              inputmode="numeric"
              placeholder="000000"
              class="input text-center text-2xl tracking-[0.5em] font-mono"
            />
            {#if errors.twoFaCode}
              <p class="mt-1.5 text-xs text-accent-rose">{errors.twoFaCode}</p>
            {/if}
            <p class="mt-2 text-[11px] text-slate-500 flex items-center gap-1.5">
              <Fingerprint size={11} class="text-slate-600" />
              أدخل الرمز المكوّن من 6 أرقام من تطبيق المصادقة
            </p>
          </div>
        {:else}
          <div>
            <label class="input-label flex items-center gap-1.5" for="email">
              <Mail size={11} class="text-accent-gold" />
              البريد الإلكتروني
            </label>
            <div class="relative">
              <div class="absolute inset-y-0 right-0 flex items-center pr-3 text-slate-400 pointer-events-none">
                <Mail size={16} />
              </div>
              <input
                id="email"
                bind:value={email}
                type="email"
                autocomplete="email"
                placeholder="you@example.com"
                class="input pr-10 {errors.email ? 'border-accent-rose/60' : ''}"
              />
            </div>
            {#if errors.email}
              <p class="mt-1.5 text-xs text-accent-rose">{errors.email}</p>
            {/if}
          </div>

          <div>
            <div class="flex items-center justify-between mb-1.5">
              <label class="text-xs font-medium text-slate-400 flex items-center gap-1.5" for="password">
                <Lock size={11} class="text-accent-gold" />
                كلمة المرور
              </label>
              <a href="/forgot-password" class="text-xs text-accent-gold hover:underline flex items-center gap-1">
                نسيت كلمة المرور؟ <ChevronLeft size={11} />
              </a>
            </div>
            <div class="relative">
              <div class="absolute inset-y-0 right-0 flex items-center pr-3 text-slate-400 pointer-events-none">
                <Lock size={16} />
              </div>
              <input
                id="password"
                bind:value={password}
                type={showPassword ? 'text' : 'password'}
                autocomplete="current-password"
                placeholder="••••••••"
                class="input pr-10 pl-10 {errors.password ? 'border-accent-rose/60' : ''}"
              />
              <button
                type="button"
                class="absolute inset-y-0 left-0 flex items-center pl-3 text-slate-400 hover:text-white transition-colors"
                onclick={() => (showPassword = !showPassword)}
                aria-label="إظهار/إخفاء كلمة المرور"
              >
                {#if showPassword}<EyeOff size={16} />{:else}<Eye size={16} />{/if}
              </button>
            </div>
            {#if errors.password}
              <p class="mt-1.5 text-xs text-accent-rose">{errors.password}</p>
            {/if}
          </div>
        {/if}

        <Button type="submit" {loading} fullWidth size="lg">
          {#if !loading}
            {requires2FA ? 'تحقق' : 'تسجيل الدخول'}
            <ArrowLeft size={18} />
          {/if}
        </Button>
      </form>

      {#if !requires2FA}
        <!-- Divider -->
        <div class="my-6 flex items-center gap-3">
          <div class="flex-1 h-px bg-gradient-to-l from-white/10 to-transparent"></div>
          <span class="text-[10px] text-slate-500 uppercase tracking-wider">أو</span>
          <div class="flex-1 h-px bg-gradient-to-r from-white/10 to-transparent"></div>
        </div>

        <div class="text-center text-sm text-slate-400">
          ليس لديك حساب؟
          <a href="/register" class="text-accent-gold font-medium hover:underline mr-1 inline-flex items-center gap-1">
            أنشئ حساباً جديداً <ChevronLeft size={12} />
          </a>
        </div>
      {:else}
        <button
          class="mt-6 text-sm text-slate-400 hover:text-white transition-colors flex items-center gap-1.5"
          onclick={() => {
            requires2FA = false;
            twoFaCode = '';
            tempToken = '';
          }}
        >
          <ArrowLeft size={14} class="rotate-180" />
          العودة لتسجيل الدخول
        </button>
      {/if}
    </div>
  </div>
</div>

// admin/src/app/login/page.tsx
"use client";

import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import toast from "react-hot-toast";
import {
  Eye,
  EyeOff,
  LogIn,
  Mail,
  Lock,
  Zap,
  ShieldCheck,
  ArrowRight,
  Shield,
} from "lucide-react";

const API = process.env.NEXT_PUBLIC_API_URL || "http://localhost:3000";

export default function AdminLoginPage() {
  const router = useRouter();
  const [form, setForm] = useState({ email: "", password: "" });
  const [show, setShow] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [mounted, setMounted] = useState(false);

  // 2FA state
  const [show2FA, setShow2FA] = useState(false);
  const [tempToken, setTempToken] = useState("");
  const [twoFACode, setTwoFACode] = useState("");
  const [twoFALoading, setTwoFALoading] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError("");
    setLoading(true);
    try {
      const res = await fetch(`${API}/api/v1/auth/login`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(form),
      });
      const data = await res.json();

      // Check for 2FA required
      if (data.requires_2fa) {
        setTempToken(data.temp_token);
        setShow2FA(true);
        return;
      }

      if (!res.ok) {
        setError(data.error || "فشل تسجيل الدخول");
        return;
      }
      if (data.user.role !== "ADMIN") {
        setError("ليس لديك صلاحية الوصول للوحة الإدارة");
        return;
      }
      localStorage.setItem("token", data.token);
      localStorage.setItem("refresh_token", data.refresh_token || "");
      localStorage.setItem("user", JSON.stringify(data.user));
      toast.success("مرحباً بك في لوحة الإدارة");
      router.push("/dashboard");
    } catch {
      setError("حدث خطأ في الاتصال");
    } finally {
      setLoading(false);
    }
  };

  const handle2FAVerify = async (e: React.FormEvent) => {
    e.preventDefault();
    setTwoFALoading(true);
    try {
      const res = await fetch(`${API}/api/v1/auth/verify-2fa`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ temp_token: tempToken, code: twoFACode }),
      });
      const data = await res.json();
      if (!res.ok) {
        setError(data.error || "رمز المصادقة غير صحيح");
        return;
      }
      if (data.user.role !== "ADMIN") {
        setError("ليس لديك صلاحية الوصول للوحة الإدارة");
        return;
      }
      localStorage.setItem("token", data.token);
      localStorage.setItem("refresh_token", data.refresh_token || "");
      localStorage.setItem("user", JSON.stringify(data.user));
      toast.success("مرحباً بك في لوحة الإدارة");
      router.push("/dashboard");
    } catch {
      setError("حدث خطأ في الاتصال");
    } finally {
      setTwoFALoading(false);
    }
  };

  // ─── 2FA Verification Screen ───
  if (show2FA) {
    return (
      <div
        className="min-h-screen flex items-center justify-center p-4 bg-background relative overflow-hidden"
        dir="rtl"
      >
        {/* Animated Background Orbs */}
        <div className="absolute inset-0 overflow-hidden pointer-events-none">
          <div className="absolute top-1/4 right-1/4 w-[500px] h-[500px] bg-emerald-500/15 rounded-full blur-[120px] animate-pulse-glow" />
          <div className="absolute bottom-1/4 left-1/4 w-[400px] h-[400px] bg-teal-500/10 rounded-full blur-[100px] animate-pulse-glow delay-500" />
          <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-emerald-600/5 rounded-full blur-[150px]" />
          <div className="absolute inset-0 bg-grid-pattern opacity-40" />
        </div>

        {/* 2FA Card */}
        <div
          className={`relative w-full max-w-md ${
            mounted ? "animate-scale-in" : "opacity-0"
          }`}
        >
          <div className="glass-panel-strong rounded-3xl p-8 animated-border">
            {/* 2FA Icon */}
            <div className="text-center mb-8">
              <div className="relative inline-flex">
                <div className="w-20 h-20 rounded-2xl bg-emerald-500/10 border border-emerald-500/20 flex items-center justify-center glow-emerald">
                  <ShieldCheck className="h-10 w-10 text-emerald-500" />
                </div>
                <div className="absolute -top-1 -right-1 w-6 h-6 rounded-full bg-emerald-500 flex items-center justify-center">
                  <Zap className="h-3 w-3 text-white" />
                </div>
              </div>
              <h1 className="text-2xl font-bold mt-5 mb-2">المصادقة الثنائية</h1>
              <p className="text-sm text-muted-foreground leading-relaxed">
                أدخل رمز المصادقة من تطبيق المصادقة الخاص بك
              </p>
            </div>

            {/* Error */}
            {error && (
              <div className="p-3.5 rounded-2xl bg-red-500/10 border border-red-500/20 text-red-400 text-sm mb-6 flex items-center gap-2 animate-scale-in">
                <div className="w-2 h-2 rounded-full bg-red-500 flex-shrink-0" />
                {error}
              </div>
            )}

            {/* 2FA Form */}
            <form onSubmit={handle2FAVerify} className="space-y-6">
              <div>
                <label className="block text-sm font-medium mb-2">
                  رمز المصادقة
                </label>
                <div className="relative">
                  <input
                    type="text"
                    className="input-field text-center text-3xl tracking-[0.5em] font-mono py-4 h-16"
                    placeholder="000000"
                    value={twoFACode}
                    onChange={(e) =>
                      setTwoFACode(
                        e.target.value.replace(/\D/g, "").slice(0, 6)
                      )
                    }
                    maxLength={6}
                    required
                    autoFocus
                    dir="ltr"
                  />
                  <div className="absolute left-4 top-1/2 -translate-y-1/2">
                    <ShieldCheck className="h-5 w-5 text-muted-foreground/40" />
                  </div>
                </div>
                <p className="text-xs text-muted-foreground mt-2 text-center">
                  الرمز مكون من 6 أرقام
                </p>
              </div>
              <button
                type="submit"
                disabled={twoFALoading || twoFACode.length !== 6}
                className="btn-primary w-full gap-2 py-3 text-base"
              >
                {twoFALoading ? (
                  <span className="spinner h-5 w-5" />
                ) : (
                  <ShieldCheck className="h-5 w-5" />
                )}
                {twoFALoading ? "جاري التحقق..." : "تأكيد الرمز"}
              </button>
            </form>

            <button
              onClick={() => {
                setShow2FA(false);
                setTempToken("");
                setTwoFACode("");
                setError("");
              }}
              className="text-sm text-muted-foreground hover:text-foreground mt-6 block mx-auto transition-colors duration-200 flex items-center gap-1.5"
            >
              <ArrowRight className="h-3.5 w-3.5" />
              رجوع لتسجيل الدخول
            </button>
          </div>
        </div>
      </div>
    );
  }

  // ─── Main Login Screen ───
  return (
    <div
      className="min-h-screen flex items-center justify-center p-4 bg-background relative overflow-hidden"
      dir="rtl"
    >
      {/* Animated Background Orbs */}
      <div className="absolute inset-0 overflow-hidden pointer-events-none">
        <div className="absolute -top-32 -right-32 w-[500px] h-[500px] bg-emerald-500/15 rounded-full blur-[120px] animate-pulse-glow" />
        <div className="absolute -bottom-32 -left-32 w-[400px] h-[400px] bg-teal-500/10 rounded-full blur-[100px] animate-pulse-glow delay-500" />
        <div className="absolute top-1/3 left-1/3 w-[300px] h-[300px] bg-emerald-400/5 rounded-full blur-[80px] animate-float" />
        <div className="absolute bottom-1/3 right-1/3 w-[350px] h-[350px] bg-teal-400/8 rounded-full blur-[90px] animate-float delay-300" />
        <div className="absolute inset-0 bg-grid-pattern opacity-40" />
      </div>

      {/* Login Card */}
      <div
        className={`relative w-full max-w-md ${
          mounted ? "animate-slide-in-up" : "opacity-0"
        }`}
      >
        <div className="glass-panel-strong rounded-3xl p-8 animated-border">
          {/* Logo & Header */}
          <div className="text-center mb-8">
            <div className="inline-flex items-center gap-2.5 mb-4">
              <div className="relative">
                <div className="w-14 h-14 rounded-2xl bg-gradient-to-br from-emerald-500 to-teal-600 flex items-center justify-center shadow-lg shadow-emerald-500/25">
                  <Zap className="h-7 w-7 text-white" />
                </div>
                <div className="absolute -top-0.5 -right-0.5 w-3.5 h-3.5 rounded-full bg-emerald-400 animate-pulse-glow" />
              </div>
              <div className="text-right">
                <span className="text-3xl font-bold gradient-text">EgMoney</span>
              </div>
            </div>

            {/* Admin Badge */}
            <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-purple-500/10 border border-purple-500/20 mb-4">
              <Shield className="h-3.5 w-3.5 text-purple-400" />
              <span className="text-xs font-medium text-purple-400">
                لوحة الإدارة
              </span>
            </div>

            <h1 className="text-2xl font-bold mb-2">تسجيل دخول المشرفين</h1>
            <p className="text-sm text-muted-foreground leading-relaxed">
              أدخل بيانات حسابك للوصول إلى لوحة الإدارة
            </p>
          </div>

          {/* Error Message */}
          {error && (
            <div className="p-3.5 rounded-2xl bg-red-500/10 border border-red-500/20 text-red-400 text-sm mb-6 flex items-start gap-2.5 animate-scale-in">
              <div className="w-2 h-2 rounded-full bg-red-500 flex-shrink-0 mt-1.5" />
              <span>{error}</span>
            </div>
          )}

          {/* Login Form */}
          <form onSubmit={handleSubmit} className="space-y-5">
            {/* Email Field */}
            <div className="space-y-2">
              <label className="block text-sm font-medium">
                البريد الإلكتروني
              </label>
              <div className="relative">
                <div className="absolute right-3.5 top-1/2 -translate-y-1/2 text-muted-foreground/50 pointer-events-none">
                  <Mail className="h-4 w-4" />
                </div>
                <input
                  type="email"
                  className="input-field pr-11"
                  placeholder="admin@eg-money.com"
                  value={form.email}
                  onChange={(e) =>
                    setForm({ ...form, email: e.target.value })
                  }
                  required
                  dir="ltr"
                />
              </div>
            </div>

            {/* Password Field */}
            <div className="space-y-2">
              <label className="block text-sm font-medium">كلمة المرور</label>
              <div className="relative">
                <div className="absolute right-3.5 top-1/2 -translate-y-1/2 text-muted-foreground/50 pointer-events-none">
                  <Lock className="h-4 w-4" />
                </div>
                <input
                  type={show ? "text" : "password"}
                  className="input-field pr-11 pl-11"
                  placeholder="••••••••"
                  value={form.password}
                  onChange={(e) =>
                    setForm({ ...form, password: e.target.value })
                  }
                  required
                />
                <button
                  type="button"
                  onClick={() => setShow(!show)}
                  className="absolute left-3.5 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground transition-colors duration-200"
                >
                  {show ? (
                    <EyeOff className="h-4 w-4" />
                  ) : (
                    <Eye className="h-4 w-4" />
                  )}
                </button>
              </div>
            </div>

            {/* Submit Button */}
            <button
              type="submit"
              disabled={loading}
              className="btn-primary w-full gap-2.5 py-3 text-base relative overflow-hidden group"
            >
              {loading ? (
                <span className="spinner h-5 w-5" />
              ) : (
                <LogIn className="h-5 w-5 group-hover:translate-x-0.5 transition-transform duration-200" />
              )}
              {loading ? "جاري تسجيل الدخول..." : "تسجيل الدخول"}
            </button>
          </form>

          {/* Security Badge */}
          <div className="mt-8 pt-6 border-t border-border/30 text-center">
            <p className="text-xs text-muted-foreground/50 flex items-center justify-center gap-1.5">
              <ShieldCheck className="h-3 w-3" />
              اتصال مشفر وآمن 256-bit SSL
            </p>
          </div>
        </div>

        {/* Footer Note */}
        <div className="mt-4 text-center">
          <p className="text-xs text-muted-foreground/40">
            هذه الصفحة مخصصة لمديري النظام فقط
          </p>
        </div>
      </div>
    </div>
  );
}
