// admin/src/app/login/page.tsx
"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import toast from "react-hot-toast";
import { Eye, EyeOff, LogIn, Mail } from "lucide-react";

const API = process.env.NEXT_PUBLIC_API_URL || "http://localhost:3000";

export default function AdminLoginPage() {
  const router = useRouter();
  const [form, setForm] = useState({ email: "", password: "" });
  const [show, setShow] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  // 2FA state
  const [show2FA, setShow2FA] = useState(false);
  const [tempToken, setTempToken] = useState("");
  const [twoFACode, setTwoFACode] = useState("");
  const [twoFALoading, setTwoFALoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError("");
    setLoading(true);
    try {
      const res = await fetch(`${API}/api/v1/auth/login`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(form),
      });
      const data = await res.json();

      // Check for 2FA required
      if (data.requires_2fa) {
        setTempToken(data.temp_token);
        setShow2FA(true);
        return;
      }

      if (!res.ok) {
        setError(data.error || "فشل تسجيل الدخول");
        return;
      }
      if (data.user.role !== "ADMIN") {
        setError("ليس لديك صلاحية الوصول للوحة الإدارة");
        return;
      }
      localStorage.setItem("token", data.token);
      localStorage.setItem("refresh_token", data.refresh_token || "");
      localStorage.setItem("user", JSON.stringify(data.user));
      toast.success("مرحباً بك في لوحة الإدارة");
      router.push("/dashboard");
    } catch {
      setError("حدث خطأ في الاتصال");
    } finally {
      setLoading(false);
    }
  };

  const handle2FAVerify = async (e: React.FormEvent) => {
    e.preventDefault();
    setTwoFALoading(true);
    try {
      const res = await fetch(`${API}/api/v1/auth/verify-2fa`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ temp_token: tempToken, code: twoFACode }),
      });
      const data = await res.json();
      if (!res.ok) {
        setError(data.error || "رمز المصادقة غير صحيح");
        return;
      }
      if (data.user.role !== "ADMIN") {
        setError("ليس لديك صلاحية الوصول للوحة الإدارة");
        return;
      }
      localStorage.setItem("token", data.token);
      localStorage.setItem("refresh_token", data.refresh_token || "");
      localStorage.setItem("user", JSON.stringify(data.user));
      toast.success("مرحباً بك في لوحة الإدارة");
      router.push("/dashboard");
    } catch {
      setError("حدث خطأ في الاتصال");
    } finally {
      setTwoFALoading(false);
    }
  };

  // 2FA verification screen
  if (show2FA) {
    return (
      <div className="min-h-screen flex items-center justify-center p-4 bg-background">
        <div className="absolute inset-0 overflow-hidden pointer-events-none">
          <div className="absolute -top-40 -right-40 w-96 h-96 bg-emerald-500/20 rounded-full blur-3xl" />
          <div className="absolute -bottom-40 -left-40 w-96 h-96 bg-teal-500/10 rounded-full blur-3xl" />
        </div>
        <div className="relative w-full max-w-md">
          <div className="glass-panel-strong rounded-3xl p-8">
            <div className="text-center mb-8">
              <div className="w-16 h-16 mx-auto mb-4 rounded-full bg-blue-500/10 flex items-center justify-center">
                <Mail className="h-8 w-8 text-blue-500" />
              </div>
              <h1 className="text-2xl font-bold">المصادقة الثنائية</h1>
              <p className="text-sm text-muted-foreground mt-1">
                أدخل رمز المصادقة من تطبيقك
              </p>
            </div>
            {error && (
              <div className="p-3 rounded-xl bg-red-500/10 border border-red-500/20 text-red-500 text-sm mb-4">
                {error}
              </div>
            )}
            <form onSubmit={handle2FAVerify} className="space-y-4">
              <div>
                <label className="block text-sm font-medium mb-1.5">
                  رمز المصادقة
                </label>
                <input
                  type="text"
                  className="input-field text-center text-2xl tracking-[0.5em] font-mono"
                  placeholder="000000"
                  value={twoFACode}
                  onChange={(e) =>
                    setTwoFACode(e.target.value.replace(/\D/g, "").slice(0, 6))
                  }
                  maxLength={6}
                  required
                  autoFocus
                  dir="ltr"
                />
              </div>
              <button
                type="submit"
                disabled={twoFALoading || twoFACode.length !== 6}
                className="btn-primary w-full gap-2"
              >
                {twoFALoading ? (
                  <span className="spinner h-4 w-4" />
                ) : (
                  <LogIn className="h-4 w-4" />
                )}
                {twoFALoading ? "جاري التحقق..." : "تأكيد"}
              </button>
            </form>
            <button
              onClick={() => {
                setShow2FA(false);
                setTempToken("");
                setTwoFACode("");
                setError("");
              }}
              className="text-sm text-muted-foreground hover:text-foreground mt-4 block mx-auto"
            >
              رجوع
            </button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen flex items-center justify-center p-4 bg-background">
      <div className="absolute inset-0 overflow-hidden pointer-events-none">
        <div className="absolute -top-40 -right-40 w-96 h-96 bg-emerald-500/20 rounded-full blur-3xl" />
        <div className="absolute -bottom-40 -left-40 w-96 h-96 bg-teal-500/10 rounded-full blur-3xl" />
      </div>
      <div className="relative w-full max-w-md">
        <div className="glass-panel-strong rounded-3xl p-8">
          <div className="text-center mb-8">
            <div className="text-2xl font-bold gradient-text mb-2">EgMoney</div>
            <h1 className="text-2xl font-bold">لوحة الإدارة</h1>
            <p className="text-sm text-muted-foreground mt-1">
              تسجيل دخول المشرفين
            </p>
          </div>
          {error && (
            <div className="p-3 rounded-xl bg-red-500/10 border border-red-500/20 text-red-500 text-sm mb-4">
              {error}
            </div>
          )}
          <form onSubmit={handleSubmit} className="space-y-4">
            <div>
              <label className="block text-sm font-medium mb-1.5">
                البريد الإلكتروني
              </label>
              <input
                type="email"
                className="input-field"
                placeholder="admin@eg-money.com"
                value={form.email}
                onChange={(e) =>
                  setForm({ ...form, email: e.target.value })
                }
                required
              />
            </div>
            <div>
              <label className="block text-sm font-medium mb-1.5">
                كلمة المرور
              </label>
              <div className="relative">
                <input
                  type={show ? "text" : "password"}
                  className="input-field pl-10"
                  placeholder="••••••••"
                  value={form.password}
                  onChange={(e) =>
                    setForm({ ...form, password: e.target.value })
                  }
                  required
                />
                <button
                  type="button"
                  onClick={() => setShow(!show)}
                  className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground"
                >
                  {show ? (
                    <EyeOff className="h-4 w-4" />
                  ) : (
                    <Eye className="h-4 w-4" />
                  )}
                </button>
              </div>
            </div>
            <button
              type="submit"
              disabled={loading}
              className="btn-primary w-full gap-2"
            >
              {loading ? (
                <span className="spinner h-4 w-4" />
              ) : (
                <LogIn className="h-4 w-4" />
              )}
              {loading ? "جاري تسجيل الدخول..." : "تسجيل الدخول"}
            </button>
          </form>
        </div>
      </div>
    </div>
  );
}

// admin/src/routes/login/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { goto } from '$app/navigation';
	import { login, verify2FA, setTokens, setStoredUser } from '$lib/api/client';
	import { toast } from '$lib/stores/toast';
	import { ShieldCheck, Eye, EyeOff, Loader2 } from 'lucide-svelte';

	let email = $state('');
	let password = $state('');
	let showPassword = $state(false);
	let loading = $state(false);
	let error = $state('');
	let requires2FA = $state(false);
	let tempToken = $state('');
	let twoFACode = $state('');

	async function handleLogin() {
		error = '';
		loading = true;

		try {
			const res = await login(email, password);

			if (res.success && res.data) {
				if (res.data.requires_2fa) {
					requires2FA = true;
					tempToken = res.data.token;
				} else if (res.data.user?.role === 'ADMIN') {
					setTokens(res.data.token, res.data.refresh_token);
					setStoredUser(res.data.user);
					toast.success('تم تسجيل الدخول بنجاح');
					goto('/dashboard');
				} else {
					error = 'ليس لديك صلاحية الوصول';
				}
			} else {
				error = res.data?.message || 'بيانات الدخول غير صحيحة';
			}
		} catch {
			error = 'حدث خطأ في الاتصال';
		} finally {
			loading = false;
		}
	}

	async function handle2FA() {
		error = '';
		loading = true;

		try {
			const res = await verify2FA(twoFACode, tempToken);
			if (res.success && res.data?.user?.role === 'ADMIN') {
				setTokens(res.data.token, res.data.refresh_token);
				setStoredUser(res.data.user);
				toast.success('تم التحقق بنجاح');
				goto('/dashboard');
			} else {
				error = 'رمز التحقق غير صحيح';
			}
		} catch {
			error = 'حدث خطأ في الاتصال';
		} finally {
			loading = false;
		}
	}

	function handleKeydown(e: KeyboardEvent) {
		if (e.key === 'Enter' && !loading) {
			if (requires2FA) handle2FA();
			else handleLogin();
		}
	}
</script>

<svelte:window onkeydown={handleKeydown} />

<div class="min-h-screen flex items-center justify-center relative overflow-hidden">
	<!-- Aurora Background Blobs -->
	<div class="absolute inset-0 pointer-events-none overflow-hidden">
		<div class="absolute w-[500px] h-[400px] rounded-full blur-[120px] bg-accent-gold/[0.07] top-[10%] right-[10%] animate-aurora-1"></div>
		<div class="absolute w-[400px] h-[400px] rounded-full blur-[100px] bg-accent-violet/[0.06] bottom-[10%] left-[15%] animate-aurora-2"></div>
		<div class="absolute w-[300px] h-[300px] rounded-full blur-[80px] bg-accent-mint/[0.04] top-[50%] left-[50%] animate-aurora-3"></div>
		<div class="absolute w-[250px] h-[250px] rounded-full blur-[80px] bg-accent-azure/[0.05] top-[5%] left-[60%] animate-aurora-4"></div>
	</div>

	<!-- Login Card -->
	<div class="relative z-10 w-full max-w-md mx-4">
		<div class="panel p-8 panel-glow">
			<!-- Logo -->
			<div class="flex flex-col items-center mb-8">
				<div class="w-14 h-14 rounded-2xl bg-gradient-to-br from-accent-gold/30 to-accent-violet/20 border border-accent-gold/20 flex items-center justify-center mb-4 shadow-lg">
					<ShieldCheck size={28} class="text-accent-gold" />
				</div>
				<h1 class="text-2xl font-extrabold text-aurora">NEXUS</h1>
				<p class="text-sm text-ink-muted mt-1">لوحة الإدارة</p>
			</div>

			{#if error}
				<div class="panel panel-rose px-4 py-3 mb-5 text-sm text-accent-rose text-center">
					{error}
				</div>
			{/if}

			{#if !requires2FA}
				<!-- Login Form -->
				<form onsubmit={(e) => { e.preventDefault(); handleLogin(); }} class="flex flex-col gap-5">
					<div>
						<label for="loginEmail" class="block text-sm font-medium text-ink-secondary mb-2">البريد الإلكتروني</label>
						<input
								id="loginEmail"
							type="email"
							bind:value={email}
							placeholder="admin@example.com"
							class="input-field"
							required
							dir="ltr"
						/>
					</div>
					<div>
						<label for="loginPassword" class="block text-sm font-medium text-ink-secondary mb-2">كلمة المرور</label>
						<div class="relative">
							<input
								type={showPassword ? 'text' : 'password'}
								id="loginPassword"
								bind:value={password}
								placeholder="••••••••"
								class="input-field pl-10"
								required
								dir="ltr"
							/>
							<button
								type="button"
								class="absolute left-3 top-1/2 -translate-y-1/2 text-ink-muted hover:text-ink-primary transition-colors"
								onclick={() => (showPassword = !showPassword)}
							>
								{#if showPassword}<EyeOff size={16} />{:else}<Eye size={16} />{/if}
							</button>
						</div>
					</div>
					<button type="submit" class="btn-primary w-full py-3" disabled={loading}>
						{#if loading}
							<Loader2 size={18} class="animate-spin" />
						{/if}
						تسجيل الدخول
					</button>
				</form>
			{:else}
				<!-- 2FA Form -->
				<form onsubmit={(e) => { e.preventDefault(); handle2FA(); }} class="flex flex-col gap-5">
					<div class="text-center mb-2">
						<p class="text-sm text-ink-secondary">أدخل رمز التحقق الثنائي</p>
					</div>
					<div>
						<input
							type="text"
							bind:value={twoFACode}
							placeholder="000000"
							class="input-field text-center text-2xl tracking-[0.5em] font-mono"
							maxlength="6"
							dir="ltr"
							
						/>
					</div>
					<button type="submit" class="btn-primary w-full py-3" disabled={loading || twoFACode.length < 6}>
						{#if loading}
							<Loader2 size={18} class="animate-spin" />
						{/if}
						تحقق
					</button>
					<button type="button" class="btn-ghost w-full" onclick={() => { requires2FA = false; tempToken = ''; }}>
						رجوع
					</button>
				</form>
			{/if}
		</div>
	</div>
</div>
