// frontend/src/routes/register/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { goto } from '$app/navigation';
  import { auth } from '$lib/api/endpoints';
  import { toasts } from '$lib/stores/toast';
  import { authStore } from '$lib/stores/auth';
  import Button from '$lib/components/Button.svelte';
  import {
    Mail, Lock, User, Eye, EyeOff, ArrowLeft, Check, X,
    ShieldCheck, Zap, TrendingUp, Crown, Sparkles, ChevronLeft,
    Activity, Loader2
  } from 'lucide-svelte';
  import ParticleBackground from '$lib/components/ParticleBackground.svelte';

  let email = $state('');
  let username = $state('');
  let password = $state('');
  let confirmPassword = $state('');
  let showPassword = $state(false);
  let loading = $state(false);
  let errors = $state<Record<string, string>>({});
  let agreedToTerms = $state(false);

  onMount(() => {
    if (authStore.isAuthenticated()) goto('/dashboard');
  });

  // Password strength meter
  const passwordStrength = $derived.by(() => {
    const p = password;
    if (!p) return { score: 0, label: '', percent: 0, color: '#475569' };
    let score = 0;
    if (p.length >= 8) score++;
    if (p.length >= 12) score++;
    if (/[a-z]/.test(p) && /[A-Z]/.test(p)) score++;
    if (/\d/.test(p)) score++;
    if (/[^a-zA-Z0-9]/.test(p)) score++;
    const labels = ['', 'ضعيفة جداً', 'ضعيفة', 'متوسطة', 'قوية', 'قوية جداً'];
    const colors = ['#475569', '#f43f7a', '#f43f7a', '#f5b544', '#3b82f6', '#22d3a4'];
    return {
      score,
      label: labels[score],
      color: colors[score],
      percent: (score / 5) * 100
    };
  });

  // Password requirements checklist
  const requirements = $derived([
    { label: '8 أحرف على الأقل', met: password.length >= 8 },
    { label: 'حرف كبير وصغير', met: /[a-z]/.test(password) && /[A-Z]/.test(password) },
    { label: 'رقم واحد على الأقل', met: /\d/.test(password) },
    { label: 'رمز خاص', met: /[^a-zA-Z0-9]/.test(password) }
  ]);

  async function handleSubmit(e: Event) {
    e.preventDefault();
    errors = {};

    if (!email.trim()) {
      errors.email = 'البريد الإلكتروني مطلوب';
      return;
    }
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
      errors.email = 'صيغة البريد غير صحيحة';
      return;
    }
    if (!username.trim() || username.length < 3) {
      errors.username = 'اسم المستخدم يجب أن يكون 3 أحرف على الأقل';
      return;
    }
    if (password.length < 8) {
      errors.password = 'كلمة المرور يجب أن تكون 8 أحرف على الأقل';
      return;
    }
    if (password !== confirmPassword) {
      errors.confirmPassword = 'كلمتا المرور غير متطابقتين';
      return;
    }
    if (!agreedToTerms) {
      toasts.warning('يجب الموافقة على الشروط والأحكام');
      return;
    }

    loading = true;
    try {
      const res = await auth.register({
        email: email.trim(),
        username: username.trim(),
        password
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || 'فشل إنشاء الحساب');

      toasts.success('تم إنشاء الحساب بنجاح! تحقق من بريدك الإلكتروني.');
      await goto('/login');
    } catch (err: any) {
      toasts.error(err.message || 'فشل إنشاء الحساب');
    } finally {
      loading = false;
    }
  }

  const benefits = [
    { icon: Zap, label: 'تنفيذ فوري', sub: '< 10 مللي ثانية', color: 'mint' },
    { icon: ShieldCheck, label: 'أمان مصرفي', sub: '2FA + تشفير', color: 'azure' },
    { icon: TrendingUp, label: 'سيولة عالية', sub: '+200 زوج', color: 'gold' }
  ];

  const colorClasses: Record<string, { bg: string; border: string; text: string }> = {
    mint: { bg: 'bg-accent-mint/10', border: 'border-accent-mint/20', text: 'text-accent-mint' },
    azure: { bg: 'bg-accent-azure/10', border: 'border-accent-azure/20', text: 'text-accent-azure' },
    gold: { bg: 'bg-accent-gold/10', border: 'border-accent-gold/20', text: 'text-accent-gold' },
    violet: { bg: 'bg-accent-violet/10', border: 'border-accent-violet/20', text: 'text-accent-violet' },
    rose: { bg: 'bg-accent-rose/10', border: 'border-accent-rose/20', text: 'text-accent-rose' }
  };
</script>

<ParticleBackground />

<div class="min-h-screen flex items-center justify-center p-4 sm:p-6 relative">
  <!-- Top fixed gradient strip -->
  <div class="fixed top-0 inset-x-0 h-px pointer-events-none z-50" style="background: linear-gradient(90deg, transparent, rgba(168, 85, 247, 0.5), rgba(245, 181, 68, 0.4), transparent);"></div>

  <div class="w-full max-w-5xl grid lg:grid-cols-2 gap-0 panel-glow overflow-hidden relative" style="min-height: 620px;">
    <!-- Inner topbar gradient highlight -->
    <div class="absolute top-0 inset-x-0 h-px pointer-events-none z-10" style="background: linear-gradient(90deg, transparent 10%, rgba(168, 85, 247, 0.6) 50%, transparent 90%);"></div>

    <!-- Left — register form -->
    <div class="p-8 sm:p-10 flex flex-col justify-center bg-ink-950/40 order-2 lg:order-1 relative">
      <div class="absolute inset-0 pointer-events-none" style="background: radial-gradient(ellipse 100% 60% at 50% 0%, rgba(245, 181, 68, 0.05), transparent 60%);"></div>

      <!-- Mobile logo -->
      <div class="lg:hidden mb-6 flex items-center gap-2.5 relative">
        <div class="relative w-10 h-10 rounded-xl bg-gradient-to-br from-accent-gold via-accent-rose to-accent-violet flex items-center justify-center font-black text-ink-950 text-lg">
          <span class="absolute inset-0 rounded-xl opacity-50 blur-md bg-gradient-to-br from-accent-gold to-accent-violet"></span>
          <span class="relative">N</span>
        </div>
        <span class="text-xl font-bold text-white tracking-tight">NEXUS</span>
      </div>

      <div class="mb-6 relative">
        <div class="flex items-center gap-2 mb-2">
          <div class="w-9 h-9 rounded-xl bg-accent-violet/10 border border-accent-violet/20 flex items-center justify-center">
            <Sparkles size={18} class="text-accent-violet" />
          </div>
          <h2 class="text-2xl font-bold text-white tracking-tight">إنشاء حساب جديد</h2>
        </div>
        <p class="text-slate-400 text-sm">ابدأ رحلتك في التداول خلال دقيقة واحدة</p>
      </div>

      <form onsubmit={handleSubmit} class="space-y-4 relative">
        <div>
          <label class="input-label flex items-center gap-1.5" for="email">
            <Mail size={11} class="text-accent-gold" />
            البريد الإلكتروني
          </label>
          <div class="relative">
            <div class="absolute inset-y-0 right-0 flex items-center pr-3 text-slate-400 pointer-events-none">
              <Mail size={16} />
            </div>
            <input
              id="email"
              bind:value={email}
              type="email"
              autocomplete="email"
              placeholder="you@example.com"
              class="input pr-10 {errors.email ? 'border-accent-rose/60' : ''}"
            />
          </div>
          {#if errors.email}<p class="mt-1.5 text-xs text-accent-rose">{errors.email}</p>{/if}
        </div>

        <div>
          <label class="input-label flex items-center gap-1.5" for="username">
            <User size={11} class="text-accent-gold" />
            اسم المستخدم
          </label>
          <div class="relative">
            <div class="absolute inset-y-0 right-0 flex items-center pr-3 text-slate-400 pointer-events-none">
              <User size={16} />
            </div>
            <input
              id="username"
              bind:value={username}
              type="text"
              autocomplete="username"
              placeholder="username"
              class="input pr-10 {errors.username ? 'border-accent-rose/60' : ''}"
            />
          </div>
          {#if errors.username}<p class="mt-1.5 text-xs text-accent-rose">{errors.username}</p>{/if}
        </div>

        <div>
          <label class="input-label flex items-center gap-1.5" for="password">
            <Lock size={11} class="text-accent-gold" />
            كلمة المرور
          </label>
          <div class="relative">
            <div class="absolute inset-y-0 right-0 flex items-center pr-3 text-slate-400 pointer-events-none">
              <Lock size={16} />
            </div>
            <input
              id="password"
              bind:value={password}
              type={showPassword ? 'text' : 'password'}
              autocomplete="new-password"
              placeholder="••••••••"
              class="input pr-10 pl-10 {errors.password ? 'border-accent-rose/60' : ''}"
            />
            <button
              type="button"
              class="absolute inset-y-0 left-0 flex items-center pl-3 text-slate-400 hover:text-white transition-colors"
              onclick={() => (showPassword = !showPassword)}
              aria-label="إظهار/إخفاء كلمة المرور"
            >
              {#if showPassword}<EyeOff size={16} />{:else}<Eye size={16} />{/if}
            </button>
          </div>
          {#if password}
            <div class="mt-2 flex items-center gap-2">
              <div class="flex-1 h-1.5 bg-ink-800 rounded-full overflow-hidden">
                <div
                  class="h-full rounded-full transition-all duration-300"
                  style="width: {passwordStrength.percent}%; background: {passwordStrength.color};"
                ></div>
              </div>
              <span class="text-xs font-medium tabular-nums" style="color: {passwordStrength.color}">
                {passwordStrength.label}
              </span>
            </div>
            <!-- Requirements checklist -->
            <div class="mt-2 grid grid-cols-2 gap-1">
              {#each requirements as req}
                <div class="flex items-center gap-1.5 text-[10px]">
                  {#if req.met}
                    <Check size={10} class="text-accent-mint" />
                    <span class="text-accent-mint/80">{req.label}</span>
                  {:else}
                    <X size={10} class="text-slate-600" />
                    <span class="text-slate-500">{req.label}</span>
                  {/if}
                </div>
              {/each}
            </div>
          {/if}
          {#if errors.password}<p class="mt-1.5 text-xs text-accent-rose">{errors.password}</p>{/if}
        </div>

        <div>
          <label class="input-label flex items-center gap-1.5" for="confirmPassword">
            <Check size={11} class="text-accent-gold" />
            تأكيد كلمة المرور
          </label>
          <div class="relative">
            <div class="absolute inset-y-0 right-0 flex items-center pr-3 text-slate-400 pointer-events-none">
              <Lock size={16} />
            </div>
            <input
              id="confirmPassword"
              bind:value={confirmPassword}
              type={showPassword ? 'text' : 'password'}
              autocomplete="new-password"
              placeholder="••••••••"
              class="input pr-10 {errors.confirmPassword ? 'border-accent-rose/60' : ''}"
            />
            {#if confirmPassword}
              <div class="absolute inset-y-0 left-0 flex items-center pl-3">
                {#if password === confirmPassword}
                  <Check size={16} class="text-accent-mint" />
                {:else}
                  <X size={16} class="text-accent-rose" />
                {/if}
              </div>
            {/if}
          </div>
          {#if errors.confirmPassword}<p class="mt-1.5 text-xs text-accent-rose">{errors.confirmPassword}</p>{/if}
        </div>

        <label class="flex items-start gap-2.5 cursor-pointer group">
          <input
            type="checkbox"
            bind:checked={agreedToTerms}
            class="mt-1 w-4 h-4 rounded border-white/10 bg-ink-900 text-accent-gold focus:ring-accent-gold/50"
          />
          <span class="text-xs text-slate-400 leading-relaxed group-hover:text-slate-300">
            أوافق على
            <a href="/terms" class="text-accent-gold hover:underline">الشروط والأحكام</a>
            و
            <a href="/privacy" class="text-accent-gold hover:underline">سياسة الخصوصية</a>
          </span>
        </label>

        <Button type="submit" {loading} fullWidth size="lg">
          {#if !loading}
            إنشاء الحساب
            <ArrowLeft size={18} />
          {/if}
        </Button>
      </form>

      <!-- Divider -->
      <div class="my-5 flex items-center gap-3">
        <div class="flex-1 h-px bg-gradient-to-l from-white/10 to-transparent"></div>
        <span class="text-[10px] text-slate-500 uppercase tracking-wider">أو</span>
        <div class="flex-1 h-px bg-gradient-to-r from-white/10 to-transparent"></div>
      </div>

      <div class="text-center text-sm text-slate-400">
        لديك حساب بالفعل؟
        <a href="/login" class="text-accent-gold font-medium hover:underline mr-1 inline-flex items-center gap-1">
          سجل دخولك <ChevronLeft size={12} />
        </a>
      </div>
    </div>

    <!-- Right — brand showcase -->
    <div class="relative hidden lg:flex flex-col justify-between p-10 overflow-hidden order-1 lg:order-2">
      <div class="absolute inset-0 bg-gradient-to-bl from-accent-gold/10 via-transparent to-accent-violet/10"></div>
      <div class="absolute top-0 left-0 w-72 h-72 bg-accent-violet/15 rounded-full blur-3xl -translate-y-1/2 -translate-x-1/2 animate-float"></div>
      <div class="absolute bottom-0 right-0 w-72 h-72 bg-accent-gold/15 rounded-full blur-3xl translate-y-1/2 translate-x-1/2 animate-float" style="animation-delay: 2s;"></div>
      <div class="absolute inset-0 grid-bg opacity-20"></div>

      <!-- Logo -->
      <div class="relative z-10 flex justify-end">
        <a href="/" class="flex items-center gap-2.5 group">
          <span class="text-xl font-bold text-white tracking-tight">NEXUS Exchange</span>
          <div class="relative w-10 h-10 rounded-xl bg-gradient-to-br from-accent-gold via-accent-rose to-accent-violet flex items-center justify-center font-black text-ink-950 text-lg transition-transform group-hover:scale-105">
            <span class="absolute inset-0 rounded-xl opacity-50 blur-md bg-gradient-to-br from-accent-gold to-accent-violet"></span>
            <span class="relative">N</span>
          </div>
        </a>
      </div>

      <!-- Hero text -->
      <div class="relative z-10 space-y-6 text-right">
        <div class="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-accent-violet/10 border border-accent-violet/25 text-accent-violet text-[10px] font-bold tracking-wide">
          <Sparkles size={10} />
          انضم لأكثر من 2 مليون متداول
        </div>

        <h1 class="text-4xl font-bold leading-tight text-balance">
          ابدأ رحلتك في عالم
          <span class="text-aurora block" style="text-shadow: 0 0 30px rgba(168, 85, 247, 0.3);">العملات الرقمية</span>
        </h1>
        <p class="text-slate-300 text-lg leading-relaxed">
          منصة موثوقة تقدم لك أدوات احترافية وتجربة تداول سلسة وآمنة.
        </p>

        <!-- Benefits list — premium style -->
        <div class="space-y-3 pt-2">
          {#each benefits as b}
            {@const c = colorClasses[b.color]}
            <div class="flex items-center gap-3 text-slate-200 group">
              <div class="w-10 h-10 rounded-xl {c.bg} {c.border} border flex items-center justify-center group-hover:scale-105 transition-transform">
                <b.icon size={17} class={c.text} />
              </div>
              <div class="flex-1">
                <p class="text-sm font-semibold text-white">{b.label}</p>
                <p class="text-[11px] text-slate-400">{b.sub}</p>
              </div>
            </div>
          {/each}
        </div>

        <!-- Stats grid -->
        <div class="grid grid-cols-3 gap-3 pt-4">
          <div class="text-center p-3 rounded-xl bg-white/[0.02] border border-white/5">
            <div class="text-2xl font-bold text-gold-gradient tabular-nums">+2M</div>
            <div class="text-[10px] text-slate-400 mt-0.5">متداول نشط</div>
          </div>
          <div class="text-center p-3 rounded-xl bg-white/[0.02] border border-white/5">
            <div class="text-2xl font-bold text-gold-gradient tabular-nums">$50B</div>
            <div class="text-[10px] text-slate-400 mt-0.5">حجم يومي</div>
          </div>
          <div class="text-center p-3 rounded-xl bg-white/[0.02] border border-white/5">
            <div class="text-2xl font-bold text-gold-gradient tabular-nums">+200</div>
            <div class="text-[10px] text-slate-400 mt-0.5">عملة رقمية</div>
          </div>
        </div>
      </div>

      <!-- Footer -->
      <div class="relative z-10 flex items-center justify-between">
        <div class="flex items-center gap-1.5 text-[10px] text-slate-500">
          <Activity size={10} class="text-accent-mint" />
          <span>جميع الأنظمة تعمل</span>
        </div>
        <div class="text-xs text-slate-400">© 2026 NEXUS Exchange</div>
      </div>
    </div>
  </div>
</div>

// frontend/src/app/register/page.tsx
"use client";

import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import toast from "react-hot-toast";
import {
  Eye,
  EyeOff,
  UserPlus,
  ArrowLeft,
  Mail,
  RefreshCw,
  Zap,
  User,
  Lock,
  Globe,
  Phone,
  ShieldCheck,
  CheckCircle2,
  Sparkles,
  ArrowRight,
} from "lucide-react";

const API = process.env.NEXT_PUBLIC_API_URL || "http://localhost:3000";

export default function RegisterPage() {
  const router = useRouter();
  const [form, setForm] = useState({
    username: "",
    email: "",
    password: "",
    full_name: "",
    country: "",
    phone: "",
  });
  const [show, setShow] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [registered, setRegistered] = useState(false);
  const [registeredEmail, setRegisteredEmail] = useState("");
  const [resendLoading, setResendLoading] = useState(false);
  const [resendCooldown, setResendCooldown] = useState(0);
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  // Cooldown timer for resend
  useEffect(() => {
    if (resendCooldown <= 0) return;
    const timer = setTimeout(() => setResendCooldown((prev) => prev - 1), 1000);
    return () => clearTimeout(timer);
  }, [resendCooldown]);

  // Password strength indicator
  const getPasswordStrength = (password: string) => {
    const checks = {
      length: password.length >= 8,
      uppercase: /[A-Z]/.test(password),
      lowercase: /[a-z]/.test(password),
      number: /\d/.test(password),
      special: /[!@#$%^&*(),.?":{}|<>]/.test(password),
    };
    const passed = Object.values(checks).filter(Boolean).length;
    return { checks, passed, total: 5 };
  };

  const passwordStrength = getPasswordStrength(form.password);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError("");
    setLoading(true);
    try {
      const res = await fetch(`${API}/api/v1/auth/register`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(form),
      });
      const data = await res.json();
      if (!res.ok) {
        setError(data.error || "فشل إنشاء الحساب");
        return;
      }
      setRegisteredEmail(data.email || form.email);
      setRegistered(true);
      toast.success("تم إنشاء الحساب بنجاح");
    } catch {
      setError("حدث خطأ في الاتصال");
    } finally {
      setLoading(false);
    }
  };

  const handleResendVerification = async () => {
    if (resendCooldown > 0) return;
    setResendLoading(true);
    try {
      const res = await fetch(`${API}/api/v1/auth/resend-verification`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ email: registeredEmail }),
      });
      const data = await res.json();
      if (res.status === 429) {
        toast.error(data.error || "يرجى الانتظار قبل طلب رابط جديد");
        setResendCooldown(60);
        return;
      }
      toast.success(data.message || "تم إرسال رابط التحقق");
      setResendCooldown(60);
    } catch {
      toast.error("حدث خطأ في الاتصال");
    } finally {
      setResendLoading(false);
    }
  };

  // Registration success - show verification message
  if (registered) {
    return (
      <div
        className="min-h-screen flex items-center justify-center p-4 bg-background relative overflow-hidden"
        dir="rtl"
      >
        {/* Animated Background Orbs */}
        <div className="absolute inset-0 overflow-hidden pointer-events-none">
          <div className="absolute top-1/4 right-1/4 w-[500px] h-[500px] bg-emerald-500/15 rounded-full blur-[120px] animate-pulse-glow" />
          <div className="absolute bottom-1/4 left-1/4 w-[400px] h-[400px] bg-teal-500/10 rounded-full blur-[100px] animate-pulse-glow delay-500" />
          <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-emerald-600/5 rounded-full blur-[150px]" />
          <div className="absolute inset-0 bg-grid-pattern opacity-40" />
        </div>

        {/* Verification Success Card */}
        <div className={`relative w-full max-w-md ${mounted ? "animate-scale-in" : "opacity-0"}`}>
          <div className="glass-panel-strong rounded-3xl p-8 animated-border text-center">
            {/* Success Icon with Animation */}
            <div className="relative inline-flex mb-6">
              <div className="w-24 h-24 rounded-3xl bg-emerald-500/10 border border-emerald-500/20 flex items-center justify-center glow-emerald">
                <Mail className="h-12 w-12 text-emerald-500 animate-float" />
              </div>
              <div className="absolute -bottom-1 -left-1 w-8 h-8 rounded-full bg-emerald-500 flex items-center justify-center shadow-lg shadow-emerald-500/30">
                <CheckCircle2 className="h-5 w-5 text-white" />
              </div>
            </div>

            <h1 className="text-2xl font-bold mb-3">تحقق من بريدك الإلكتروني</h1>
            <p className="text-muted-foreground mb-2">تم إرسال رابط التأكيد إلى</p>
            <div className="inline-flex items-center gap-2 bg-emerald-500/10 border border-emerald-500/20 rounded-xl px-4 py-2 mb-4">
              <Mail className="h-4 w-4 text-emerald-400" />
              <p className="text-emerald-400 font-semibold text-base" dir="ltr">
                {registeredEmail}
              </p>
            </div>
            <p className="text-sm text-muted-foreground leading-relaxed mb-8">
              يرجى الضغط على رابط التأكيد في البريد الإلكتروني لتفعيل حسابك.
              <br />
              الرابط صالح لمدة 24 ساعة.
            </p>

            <div className="space-y-3">
              <button
                onClick={handleResendVerification}
                disabled={resendLoading || resendCooldown > 0}
                className="btn-ghost w-full gap-2 border border-border/50 hover:border-emerald-500/30 hover:bg-emerald-500/5"
              >
                {resendLoading ? (
                  <span className="spinner h-4 w-4" />
                ) : (
                  <RefreshCw className="h-4 w-4" />
                )}
                {resendCooldown > 0
                  ? `إعادة الإرسال بعد ${resendCooldown} ثانية`
                  : "إعادة إرسال رابط التأكيد"}
              </button>
              <Link
                href="/login"
                className="btn-primary w-full inline-flex items-center justify-center gap-2.5 py-3 text-base"
              >
                <ArrowRight className="h-4 w-4" />
                الانتقال لتسجيل الدخول
              </Link>
            </div>

            <div className="mt-6 pt-6 border-t border-border/30">
              <Link
                href="/"
                className="text-sm text-muted-foreground hover:text-foreground inline-flex items-center gap-1.5 transition-colors duration-200"
              >
                <ArrowLeft className="h-3.5 w-3.5" />
                العودة للرئيسية
              </Link>
            </div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div
      className="min-h-screen flex items-center justify-center p-4 bg-background relative overflow-hidden"
      dir="rtl"
    >
      {/* Animated Background Orbs */}
      <div className="absolute inset-0 overflow-hidden pointer-events-none">
        <div className="absolute -top-32 -right-32 w-[500px] h-[500px] bg-emerald-500/15 rounded-full blur-[120px] animate-pulse-glow" />
        <div className="absolute -bottom-32 -left-32 w-[400px] h-[400px] bg-teal-500/10 rounded-full blur-[100px] animate-pulse-glow delay-500" />
        <div className="absolute top-1/3 left-1/3 w-[300px] h-[300px] bg-emerald-400/5 rounded-full blur-[80px] animate-float" />
        <div className="absolute bottom-1/3 right-1/3 w-[350px] h-[350px] bg-teal-400/8 rounded-full blur-[90px] animate-float delay-300" />
        <div className="absolute inset-0 bg-grid-pattern opacity-40" />
      </div>

      {/* Register Card */}
      <div className={`relative w-full max-w-md ${mounted ? "animate-slide-in-up" : "opacity-0"}`}>
        <div className="glass-panel-strong rounded-3xl p-8 animated-border">
          {/* Logo & Header */}
          <div className="text-center mb-8">
            <Link href="/" className="inline-flex items-center gap-2 mb-4 group">
              <div className="relative">
                <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-emerald-500 to-teal-600 flex items-center justify-center shadow-lg shadow-emerald-500/20 group-hover:shadow-emerald-500/30 transition-shadow duration-300">
                  <Zap className="h-6 w-6 text-white" />
                </div>
                <div className="absolute -top-0.5 -right-0.5 w-3 h-3 rounded-full bg-emerald-400 animate-pulse-glow" />
              </div>
              <span className="text-3xl font-bold gradient-text">EgMoney</span>
            </Link>
            <h1 className="text-2xl font-bold mb-2">إنشاء حساب</h1>
            <p className="text-sm text-muted-foreground leading-relaxed">
              ابدأ رحلة التداول اليوم مع EgMoney
            </p>
          </div>

          {/* Error Message */}
          {error && (
            <div className="p-3.5 rounded-2xl bg-red-500/10 border border-red-500/20 text-red-400 text-sm mb-6 flex items-start gap-2.5 animate-scale-in">
              <div className="w-2 h-2 rounded-full bg-red-500 flex-shrink-0 mt-1.5" />
              {error}
            </div>
          )}

          {/* Register Form */}
          <form onSubmit={handleSubmit} className="space-y-4">
            {/* Username Field */}
            <div className="space-y-2">
              <label className="block text-sm font-medium">اسم المستخدم</label>
              <div className="relative">
                <div className="absolute right-3.5 top-1/2 -translate-y-1/2 text-muted-foreground/50 pointer-events-none">
                  <User className="h-4.5 w-4.5" />
                </div>
                <input
                  type="text"
                  className="input-field pr-11"
                  placeholder="ahmed"
                  value={form.username}
                  onChange={(e) => setForm({ ...form, username: e.target.value })}
                  required
                  dir="ltr"
                />
              </div>
            </div>

            {/* Email Field */}
            <div className="space-y-2">
              <label className="block text-sm font-medium">البريد الإلكتروني</label>
              <div className="relative">
                <div className="absolute right-3.5 top-1/2 -translate-y-1/2 text-muted-foreground/50 pointer-events-none">
                  <Mail className="h-4.5 w-4.5" />
                </div>
                <input
                  type="email"
                  className="input-field pr-11"
                  placeholder="ahmed@email.com"
                  value={form.email}
                  onChange={(e) => setForm({ ...form, email: e.target.value })}
                  required
                  dir="ltr"
                />
              </div>
            </div>

            {/* Full Name Field */}
            <div className="space-y-2">
              <label className="block text-sm font-medium">الاسم الكامل</label>
              <div className="relative">
                <div className="absolute right-3.5 top-1/2 -translate-y-1/2 text-muted-foreground/50 pointer-events-none">
                  <User className="h-4.5 w-4.5" />
                </div>
                <input
                  type="text"
                  className="input-field pr-11"
                  placeholder="محمد أحمد"
                  value={form.full_name}
                  onChange={(e) => setForm({ ...form, full_name: e.target.value })}
                />
              </div>
            </div>

            {/* Country & Phone */}
            <div className="grid grid-cols-2 gap-3">
              <div className="space-y-2">
                <label className="block text-sm font-medium">الدولة</label>
                <div className="relative">
                  <div className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground/50 pointer-events-none">
                    <Globe className="h-4 w-4" />
                  </div>
                  <input
                    type="text"
                    className="input-field pr-9"
                    placeholder="مصر"
                    value={form.country}
                    onChange={(e) => setForm({ ...form, country: e.target.value })}
                  />
                </div>
              </div>
              <div className="space-y-2">
                <label className="block text-sm font-medium">رقم الهاتف</label>
                <div className="relative">
                  <div className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground/50 pointer-events-none">
                    <Phone className="h-4 w-4" />
                  </div>
                  <input
                    type="tel"
                    className="input-field pr-9"
                    placeholder="+20 100 000 0000"
                    value={form.phone}
                    onChange={(e) => setForm({ ...form, phone: e.target.value })}
                    dir="ltr"
                  />
                </div>
              </div>
            </div>

            {/* Password Field */}
            <div className="space-y-2">
              <label className="block text-sm font-medium">كلمة المرور</label>
              <div className="relative">
                <div className="absolute right-3.5 top-1/2 -translate-y-1/2 text-muted-foreground/50 pointer-events-none">
                  <Lock className="h-4.5 w-4.5" />
                </div>
                <input
                  type={show ? "text" : "password"}
                  className="input-field pr-11 pl-11"
                  placeholder="••••••••"
                  value={form.password}
                  onChange={(e) => setForm({ ...form, password: e.target.value })}
                  required
                  minLength={8}
                />
                <button
                  type="button"
                  onClick={() => setShow(!show)}
                  className="absolute left-3.5 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground transition-colors duration-200"
                >
                  {show ? <EyeOff className="h-4.5 w-4.5" /> : <Eye className="h-4.5 w-4.5" />}
                </button>
              </div>

              {/* Password Strength Indicator */}
              {form.password && (
                <div className="mt-3 animate-fade-in">
                  <div className="flex gap-1.5 mb-2">
                    {Array.from({ length: 5 }).map((_, i) => (
                      <div
                        key={i}
                        className={`h-1.5 flex-1 rounded-full transition-all duration-300 ${
                          i < passwordStrength.passed
                            ? passwordStrength.passed <= 2
                              ? "bg-red-500"
                              : passwordStrength.passed <= 3
                              ? "bg-yellow-500"
                              : "bg-emerald-500"
                            : "bg-muted/30"
                        }`}
                      />
                    ))}
                  </div>
                  <div className="grid grid-cols-2 gap-x-3 gap-y-1">
                    {[
                      { label: "8 أحرف على الأقل", met: passwordStrength.checks.length },
                      { label: "حرف كبير", met: passwordStrength.checks.uppercase },
                      { label: "حرف صغير", met: passwordStrength.checks.lowercase },
                      { label: "رقم", met: passwordStrength.checks.number },
                      { label: "رمز خاص", met: passwordStrength.checks.special },
                    ].map((req, i) => (
                      <div
                        key={i}
                        className={`flex items-center gap-1.5 text-xs transition-colors duration-200 ${
                          req.met ? "text-emerald-400" : "text-muted-foreground/50"
                        }`}
                      >
                        <CheckCircle2 className={`h-3 w-3 ${req.met ? "opacity-100" : "opacity-30"}`} />
                        {req.label}
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>

            {/* Submit Button */}
            <button
              type="submit"
              disabled={loading}
              className="btn-primary w-full gap-2.5 py-3 text-base relative overflow-hidden group mt-2"
            >
              {loading ? (
                <span className="spinner h-5 w-5" />
              ) : (
                <UserPlus className="h-5 w-5 group-hover:scale-110 transition-transform duration-200" />
              )}
              {loading ? "جاري إنشاء الحساب..." : "إنشاء حساب"}
            </button>
          </form>

          {/* Email Verification Notice */}
          <div className="mt-4 p-3 rounded-xl bg-emerald-500/5 border border-emerald-500/10 flex items-start gap-2.5">
            <Mail className="h-4 w-4 text-emerald-500 flex-shrink-0 mt-0.5" />
            <p className="text-xs text-muted-foreground leading-relaxed">
              سيتم إرسال رابط تأكيد إلى بريدك الإلكتروني لتفعيل الحساب
            </p>
          </div>

          {/* Divider */}
          <div className="relative my-5">
            <div className="absolute inset-0 flex items-center">
              <div className="w-full border-t border-border/40" />
            </div>
            <div className="relative flex justify-center">
              <span className="bg-card/80 backdrop-blur-xl px-4 text-xs text-muted-foreground">
                <Sparkles className="h-3 w-3 inline-block ml-1" />
                أو
              </span>
            </div>
          </div>

          {/* Login Link */}
          <div className="text-center">
            <p className="text-sm text-muted-foreground">
              لديك حساب بالفعل؟{" "}
              <Link
                href="/login"
                className="text-emerald-400 hover:text-emerald-300 font-medium transition-colors duration-200"
              >
                تسجيل الدخول
              </Link>
            </p>
          </div>

          {/* Back to Home */}
          <div className="mt-5 pt-5 border-t border-border/30 text-center">
            <Link
              href="/"
              className="text-sm text-muted-foreground hover:text-foreground inline-flex items-center gap-1.5 transition-colors duration-200"
            >
              <ArrowLeft className="h-3.5 w-3.5" />
              العودة للرئيسية
            </Link>
          </div>
        </div>

        {/* Security Badge */}
        <div className="mt-4 text-center">
          <p className="text-xs text-muted-foreground/50 flex items-center justify-center gap-1.5">
            <ShieldCheck className="h-3 w-3" />
            اتصال مشفر وآمن 256-bit SSL
          </p>
        </div>
      </div>
    </div>
  );
}
